### ISSUE TITLE
Scans fail for PowerApps

### ISSUE THREAD

**Issue by dmp569** [microsoft/accessibility-insights-web#1039]
## Describe the bug
I am trying to scan a web page based on PowerApps (https://web.powerapps.com/webplayer/app?) web player. The FastPass fails to complete. Tried also in the Axe extension directly and that failed as well.

**To Reproduce**
I am not sure I can grant you access to this specific PowerApp but wondering if AI has ever been used for testing these types of pages?

## Expected behavior

Scan to complete.

## Extension (please complete the following information)

- OS: Windows
- Version [2.7.1]
- Browser Version [Chrome 75.0.3770.142 (Official Build) (64-bit)]
- Target Page [https://web.powerapps.com/webplayer/app?]

## Did you search for similar existing issues?
Yes.
<!-- Did you search for similar issues in our github issues or on [stackoverflow]
Yes

**Comment by flyingUnderTheRadar** [comment]
Hi @dmp569,

Thank you for the report. Yes the tool has been used to scan PowerApps successfully in the past.

**If not the actual instance is it possible to create a sample that we could use to reproduce the issue?**

Additionally if you can send us console logs we can try to guess what might be happening.

**On the target page (the powerapp page)** enable the developer tools for chrome (see below), clear the console and then start fast pass.
![image](https://user-images.githubusercontent.com/45673569/62651065-091b2c80-b90d-11e9-9047-c3bada860d18.png)

Wait for 30 seconds to 1 minute (if your page has a lot of content). Once you have some logs there you can save them by right clicking
![image](https://user-images.githubusercontent.com/45673569/62651117-23550a80-b90d-11e9-9afa-c990acb8a4fc.png)

Thanks !
