### ISSUE TITLE
Parsing test - change the test method to avoid false positives (text changes only)

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#1071]
## Describe the bug

The Parsing test instructs users to run the Nu HTML checker via a bookmarklet, rather than typing the target page into the URL field at https://validator.w3.org/nu/. The two methods produce different results. I filed a bug on the Nu HTML Checker and got this explanation:
>Typing the URL into the validator causes it to test the HTML at that URL.
> When you use the bookmarklet, you load the HTML into a browser which converts it into a DOM (which involves error recovery), then executes any JavaScript on the page (which could modify the DOM further), then you ask the browser to generate HTML from the DOM which you send to the validator.

The Parsing test should instruct users to type the target page URL into the validator because that method produces more reliable results.. The bookmarklet is more likely to generate false positives.

The keyboard instructions that accompany the Parsing test will also need to be updated.

Proposed text changes are [here](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Ft%2FDD_VSCS%2FCandC%2FKeros%2FEWCxxI_6KCREo69wc2lf_ZsBoxSPPuXEIR9YyenH3t_lHA%3Fe%3D7D8pH4&data=02%7C01%7Cv-lidav%40microsoft.com%7Ccd705abe60ba48ca43f908d720cf6edb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637013947592552122&sdata=AYDS3GDiBuHxlaCNuRyw80LpB71C0QsAUAjfJ2iyoQ0%3D&reserved=0).

**To Reproduce**

1. Go to the [Nu HTML Validator](https://validator.w3.org/nu/) and type in the URL for this target page: https://www.w3.org/WAI/demos/bad/before/home.html
2. Go to the same target page and run the "Check serialized DOM of current page" bookmarklet (available [here](https://validator.w3.org/nu/about.html)).
3. Compare the results:
   - The first method (typing in the URL) generates 10 errors and warnings.
   - The second methods (running the bookmarklet) generates 11 errors and warnings.

## Extension 

- OS: Windows
- Version: 2.8.0
- Browser: Chrome 76.0.3809.100 (Official Build) (64-bit)
- Target Page: https://www.w3.org/WAI/demos/bad/before/home.html

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
@LiLoDavis after long investigation I think we decided not to move forward with this change, agree?

**Comment by LiLoDavis** [comment]
Agree. Current POR is to modify the bookmarklet to show root failures so users can figure out what actually went wrong.
