### ISSUE TITLE
Investigate reasons and rectification for Canary release delays.

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-web#1078]
## Describe the bug

Sometimes, our canary take longer than expected time for chrome store release, because of two reasons (found by @karanbirsingh after primary investigation):

- the failure is silent because the grunt task doesn't fail: https://github.com/c301/grunt-webstore-upload/issues/
- our extension hits pending review occasionally which leads to a delay in release time

We need to investigate (to find root cause for this) and rectify those errors to make sure that:
- we get failures in release when the errors happened.
- we get those failures rectified for the future releases.

**Comment by ferBonnin** [comment]
@smoralesd is this resolved? can we close, please?
