### ISSUE TITLE
Overview in Assessment is misaligned

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1088]
## Describe the bug

The overview section in assessment is misaligned and the region with the list of tests is not all scrollable

**To Reproduce**

1. Go to assessment
2. Click on overview
3. Scroll down

## Expected behavior

List of tests details should be well aligned, user should be able to fully scroll the list of tests in the left nav

## Screenshots

![Screenshot overview section](https://user-images.githubusercontent.com/9062104/63286345-a3179900-c26c-11e9-82c1-d54de2d031f7.png)

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.8
- Browser Version [e.g Chrome 71.0] 76
- Target Page [e.g www.bing.com] any

**Comment by dbjorge** [comment]
#1096 and #1098 fix the issues mentioned here and are merged into master. Canary release with fixes is pending.

**Comment by dbjorge** [comment]
Fixes are available in [Insiders](https://chrome.google.com/webstore/detail/accessibility-insights-fo/nnmjfbmebeckhpejobgjjjnchlljiagp) v2.8.1 - @ferBonnin, can you double check the resolution? :)

**Comment by ferBonnin** [comment]
tested in high contrast mode, zoom 200% different sizes, looks good :)
