### ISSUE TITLE
In Chrome 76+ at small window sizes, assessment overview pane has malformed scroll bar behavior

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#1118]
## Describe the bug

Chromium 76 regressed the Overview page of the assessment UI; at small window sizes, you see an unexpected whole-page vertical scrollbar in addition to the expected 2 scrollbars (one each for the left nav and main content views), and when the whole-page scrollbar is scrolled down, the left nav UI gets clipped.

#1098 fixes this, but we reverted it because it simultaneously introduced a different issue, #1112. #1112 only occurs with #1098 in place **and** on Chromium < 77. Since Chromium 77 is due to hit stable in 3 weeks and this bug is less user-impactful than #1112, we've decided to leave this bug alone until Chromium 77 hits stable, and then re-apply #1098 at that time to fix it.

**To Reproduce**
1. Install Accessibility Insights prod or insiders v2.8.0 or v2.8.2 (but not v2.8.1, which contained #1098)
2. Open an assessment
3. Navigate to the Overview
4. Resize the window to be small (~1024x768 repros it)
5. Observe that there are 3 scrollbars instead of 2
6. Scroll down on the rightmost/outermost scroll bar
7. Observe that the left nav gets clipped

## Expected behavior

Should be only 2 scroll bars (one per pane, none at the whole-page level), and neither of them should cause the left nav to clip

## Screenshots

![image](https://user-images.githubusercontent.com/376284/63463656-7c936280-c412-11e9-93f9-d3daa4b90b19.png)

## Extension (please complete the following information)

- OS: Windows
- Version: v2.8.0 or v2.8.2
- Browser Version: Chromium 76, 77, 78 (but not 75)
- Target Page: any

## Are you willing to submit a PR?

Yes (#1098)

**Comment by dbjorge** [comment]
Our fix for this (#1098) is blocked on Chromium 77 reaching the Chrome Stable channel

**Comment by ferBonnin** [comment]
@dbjorge asigning to you per conversation with Peter. He recalls you already have the fix for this
