### ISSUE TITLE
Add in-page links to the exported report's headers

### ISSUE THREAD

**Issue by jechols** [microsoft/accessibility-insights-web#1156]
## Is your feature request related to a problem? Please describe.

When we go through the report as a team, we like to jump to a given section so we can all discuss what we failed and why, but scrolling around the document takes up a lot more time than we'd prefer.

## Describe the desired outcome

Having some kind of table of contents toward the top of the report would be excellent.  We'd also love to see some links like "next section", "back to top", etc. when we're in a particular heading.

## Describe alternatives you've considered

It wouldn't be ideal, but we might all look at a screen reader like NVDA, using it strictly to navigate by headings.  Or maybe a browser extension, though I'm not seeing any that look very promising.

**Comment by adrianaandreeva** [comment]
Hi @jechols!

Thank you for using Accessibility Insights and for leaving a feature request! We appreciate your input and look forward to more suggestions.
We are working on a change in the cards UI that will result in something similar to what you are suggesting. Please stay tuned for the official release and leave us a comment after! 

Thanks,
Your Accessibility Insights Team
