### ISSUE TITLE
failure instance details: create & link to new content page for "Learn more about CSS selectors" in UI​

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#1166]
The failure instance detail panel needs an initial "Learn more about adding failure instances" guidance page that opens in a new tab. The new guidance page should have text that explains:
- how to get the CSS selector of an element using dev-tools
- how to format selectors inside iframes

When we run the feature by users during testing, we will come back and improve the text if needed.

![screenshot of failure instance panel details mock](https://user-images.githubusercontent.com/7775527/63898477-019bf000-c9ae-11e9-99b3-f567db6d1d8e.png)

**Comment by ferBonnin** [comment]
this link is being flagged by the linter (anchor-is-valid) rule.

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets remove this link from the code until we actually complete this work

**Comment by ferBonnin** [comment]
verified in canary
