### ISSUE TITLE
failure instance details: move buttons to footer & css changes

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#1167]
There are some slight differences between the current failure instance details panel & our [mock](https://www.figma.com/file/T7bhNPvbpGYZTSSehCAIohz7/Web-Assessment-report-experience?node-id=91%3A1634):
- the 'add failure instance' buttons should be in the footer. PR #1085 intentionally undid this work in order to revert a separate regression. We should reintroduce them using `onRenderFooterContent` without affecting the feature-flag-off experience
- ~~the "Comment" textbox is missing a placeholder, unblocked by #1032~~ (completed in #1191)

**Comment by ferBonnin** [comment]
reviewed with Peter, old bug. closing
