### ISSUE TITLE
Autocomplete requirement has a couple text issues

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#1190]
## Describe the bug

1. "If a text field does serve an identified input purpose" - the word does should be italicized.
2. "or icons; and" the ';' or the 'and' should be removed. Together, I believe they are redundant. I would personally remove the ";" character.

- Version 2.9.0

**Comment by dbjorge** [comment]
I disagree with the second suggestion; I think omitting the ; makes it more confusing (the "and" becomes confusing in the context of the preceding conjunction), and I think that it reads less smoothly without the "and". I agree that the "; and" construction doesn't technically seem like proper grammar, though; if we wanted to fix that, I think switching the (1) and (2) clauses and then omitting the ; would be okay, but I also think it reads fine as-is.

**Comment by dbjorge** [comment]
Fixed by #1192
