### ISSUE TITLE
Contrast test: Modify "How to test" for requirement 1: UI components

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#1203]
## Describe the bug
Clarify step 2a by adding text.

Current:
> 1. In the target page, examine each highlighted element in each of the following states:
Normal
Focused
Mouseover
Selected (if applicable)
2. In each state, use Accessibility Insights for Windows (or if you are testing on a Mac, the Colour Contrast Analyser) to verify that the following visual presentations (if implemented) have a contrast ratio of at least 3:1 against the adjacent background:
Any visual effect that indicates state
Any visual boundary that indicates the component's clickable area

Proposed: 
>1.	In the target page, examine each highlighted element in its normal state (not disabled or selected, no mouseover or input focus).
2.	Use Accessibility Insights for Windows (or if you are testing on a Mac, the Colour Contrast Analyser) to verify that the following visual presentations (if implemented) have a contrast ratio of at least 3:1 against the adjacent background:
a.	Any visual boundary that indicates the component's clickable area
b.	Any visual effect that indicates the component is in its normal state

**To Reproduce**

1. Go to the **Contrast** test.
2. Select the first requirement.
3. See the "How to test" content

## Are you willing to submit a PR?

No.

## Did you search for similar existing issues?

Yes.

**Comment by ferBonnin** [comment]
per conversation with Lisa Louise, reviewing approach on this. Do not start working on this bug, please.
