### ISSUE TITLE
Contrast test: Edit requirement 2: State changes

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#1204]
## Describe the bug

Requirement 2 is based on an incorrect interpretation of 1.4.11 Non-text Contrast. A clarification in [Understanding Success Criterion 1.4.11 Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) includes this clarification:

> This Success Criterion does not require that changes in color that differentiate between states of an individual component meet the 3:1 contrast ratio when they do not appear next to each other. For example, there is not a new requirement that visited links contrast with the default color, or that mouse hover indicators contrast with the default state. However, the component must not lose contrast with the adjacent colors, and non-text indicators such as the check in a checkbox, or an arrow graphic indicating a menu is selected or open must have sufficient contrast to the adjacent colors.

We need to edit the instructions to reflect that the user only needs to test the contrast of the visual indicators of each state against its background

 **To Reproduce**

1. Go to the "Contrast" test.
2. Select the second requirement ("State changes")

### new text

2 **State changes.** Any visual effect that indicates a component's state must have sufficient contrast.

How to test
The visual helper for this requirement highlights links, native widgets, and custom widgets in the target page.
1.	In the target page, examine each highlighted element to determine whether it can adopt any of the following states:
a.	Focused
b.	Mouseover
c.	Selected
2.	Identify any visual (non-text) indicators that communicate:
a.	The boundary of the component's clickable area (such as a border or background color)
b.	The component's current state (such as a differente background color or a checkmark)
3.	Use Accessibility Insights for Windows (or if you are testing on a Mac, the Colour Contrast Analyser) to verify that the visual indicator has a contrast ratio of at least 3:1 against the adjacent background.
4.	Exception: A lower contrast ratio is allowed if either of the following is true:
a.	The component is inactive/disabled.
b.	The component's appearance is determined solely by the browser.
5.	Record your results:
a.	Select Fail for any instances that do not meet the requirement.
b.	Otherwise, select Pass. Or, after you have marked all failures, select Pass unmarked instances.

**Remove from Test Guidance**
Provide sufficient contrast for controls' state changes. (WCAG 1.4.11)
Good: Ensure colors used to indicate different states have a contrast ratio ≥ 3:1.
Better: Indicate state changes by changing both color and another visual characteristic, such as shape or size.

**Remove more info & examples for this requirement for now.** We will review it and add new content.

## Are you willing to submit a PR?

No.

## Did you search for similar existing issues?

Yes.

**Comment by ferBonnin** [comment]
This also requires to remove the following Test Guidance:

Provide sufficient contrast for controls' state changes. (WCAG 1.4.11)
Good: Ensure colors used to indicate different states have a contrast ratio ≥ 3:1.
Better: Indicate state changes by changing both color and another visual characteristic, such as shape or size.

@LiLoDavis can you confirm?

**Comment by LiLoDavis** [comment]
Yes, I think we can remove it.

**Comment by ferBonnin** [comment]
per conversation with Lisa Louise, reviewing approach on this. Do not start working on this bug, please.
