### ISSUE TITLE
Default extension scroll behavior can lead to inaccessible content for keyboard-only users

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#1278]
## Describe the bug

In #1269 we found that a guidance page in the extension with no interactive links fails the  [scrollable-region-focusable](https://dequeuniversity.com/rules/axe/3.3/scrollable-region-focusable) rule. Because `overflow` is not set on `insights-root`, it is possible for a scrollbar to appear only over the main landmark div _excluding_ the header. When a keyboard-only user tabs to the page, focusing on the body may not be sufficient to scroll the page with the arrow keys. However, if either:
- there are any interactive elements that receive tab focus, or
- the scrollable content is focusable
- the scrollable content is the entire body

scrolling is possible via the keyboard.

We should explore how to structure our default guidance page (and other pages in the extension as well) to ensure they are fully accessible.

**To Reproduce**

1. Go to any guidance page, such as the "How to test" pages in the launchpad
2. Remove any interactive links via code or devtools
3. Try to scroll the page with the keyboard only

## CodePen repro example

https://codepen.io/karansin/pen/VwZgaxR

## Expected behavior

The user should be able to scroll content with the arrow keys only.

## Extension (please complete the following information)

- OS: Windows
- Version 2.9.2

**Comment by ferBonnin** [comment]
@iamrafan any recommendations?

I would suggest making sure we have a skip link as a thing that can be focused so a user can scroll.

**Comment by iamrafan** [comment]
@ferBonnin I think making the ```body``` as scrollable content would be most appropriate if we feel there is no need to have links in the page.

I tested using ```skip link``` as you suggested but that doesn't seem to give the scroll control to the arrow keys. I think this idea would work only if we can find a reliable way to trigger scrolling using arrow keys after using ```skip link```

**Comment by ferBonnin** [comment]
Thanks @iamrafan, what would happen if we set body as scrollable but there is nothing to scroll?

**Comment by iamrafan** [comment]
@ferBonnin There would be no need for scrollbar if the content is not large enough for the view port and this rule would pass. 

Even the current failure occurs only when the view port is so small that a scrollbar is need to view all the content

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets go ahead and make the whole body scrollable for all content pages (whether they have links or not)

**Comment by ferBonnin** [comment]
validated in insider. looks good.
