### ISSUE TITLE
Add more testing (manual or automated) for data tables

### ISSUE THREAD

**Issue by jechols** [microsoft/accessibility-insights-web#1297]
## Is your feature request related to a problem? Please describe.

When doing testing I'm not seeing anything that validates or suggests validating table headers.  For a data table, if there are no headers, this is a major problem most of the time.  It's also probably good to explain what kinds of headers make sense.  Sometimes you only need column headers, but in a lot of cases tables need row headers so a user can browse from one row to the next and hear some context.

There's also nothing about making sure things like captions are effectively (I'd like guidance on just what makes a good table caption in the first place).

## Describe the desired outcome

I'd like to see more in-depth explanations of data tables.  I'd like pass/fail options for making sure data tables have headers and that those headers make sense.  If headers are given in an invisible way (e.g., via the `headers` attribute), the accessible header needs to have a pass/fail option.  Captions should have a pass/fail that they properly describe the table (in whatever way captions are meant to be used).  All of these things should have a section in AI that explains to us what we should be looking for and how to find it (probably via accessibility web tools?)

## Describe alternatives you've considered

For the moment I'm just checking headers myself and shimming fail notes in AI where they are at least tangentially related, but without good guidance it's easy to forget to check, or to check the wrong thing.

**Comment by ferBonnin** [comment]
Thanks for the feature request @jechols! have you take a look at the [assessment](https://accessibilityinsights.io/docs/en/web/getstarted/assessment) feature? We do have a requirement for Data tables in the Semantics test

**Comment by jechols** [comment]
@ferBonnin I don't see anything in there about table headers or captions, which is why I filed the ticket.  The assessment has very minimal testing for tables currently, and there's a lot of data-table-specific tests I am having to try to remember to do that isn't guided.

**Comment by ferBonnin** [comment]
@iamrafan can you please take a look at this?

There is an automated check rule for table headers in axe-core, but looks like its marked as experimental, thus we are not surfacing it:
[All non-empty <td> elements in a <table> larger than 3 by 3 must have an associated table header](https://dequeuniversity.com/rules/axe/3.0/td-has-header)
We do show other automated checks related to table and table headers. But I am not sure we are covering this case.

**Comment by ferBonnin** [comment]
Hi @jechols!

We have reviewed this feature request and the tables failures and released [Accessibility Insights for Web V2.1.18.2](https://github.com/microsoft/accessibility-insights-web/releases/tag/web%402.18.2) that has additional support for tables

**Comment by jechols** [comment]
I finally managed to get this installed and tested, it looks like a major improvement!  Thanks!
