### ISSUE TITLE
Allow re-scan on checks where instances are auto detected

### ISSUE THREAD

**Issue by joppekroon** [microsoft/accessibility-insights-web#1298]
## Is your feature request related to a problem? Please describe.
It is possible for a check with automated instance detection to scan the wrong page. For example, when the target page has been closed or the assessment is restarted before the target page has been opened. At this point, the instance detection will detect items from another page, and there is no option available to invalidate this list and trigger a new scan when the target page is back in place. The only recourse at that point is to restart the assessment, manually edit the report, or fiddle with the IndexedDB.

## Describe the desired outcome
A way to trigger a re-scan of the target page, to fix wrong instance detection.

## Describe alternatives you've considered
It could be made harder to scan the wrong page. However, this is not full-proof as targets may be fulfilled by completely different pages, e.g. localhost.

**Comment by ferBonnin** [comment]
Thanks for the feature request @joppekroon! There is a possibility to trigger an scan for just one test, instead of the whole assessment: [Start over a single test](https://accessibilityinsights.io/docs/en/web/getstarted/assessment#start-over-a-single-test)

Would this help your scenario?

**Comment by joppekroon** [comment]
Yep, that solves the immediate problem.

But let's be real, after completing 23 out of 24 checks, "Start over" is the absolute last button I'm going to be pressing ;-).

**Comment by lisli1** [comment]
Hi @joppekroon, each of the 24 checks can be restarted individually. For example, if you want to restart the Landmarks check, you can do so by clicking the  **Start over** menu at the top right corner, which will give you the options to **Start over Assessment** or **Start over Landmarks** (see screenshot below for reference). Here, you would want to select **Start over Landmarks** to re-scan just the landmarks on the desired target page. This way, you would not have to restart all 24 of the checks.

Note that restarting a certain check will restart all the requirements under that check.

![image](https://user-images.githubusercontent.com/48259897/65803093-6de74c00-e132-11e9-8aff-fb1c4620446d.png)

**Comment by ferBonnin** [comment]
Hi @joppekroon glad to hear that this solves the immediate problem!

We do understand that selecting the "start over" button is a bit of a scary thing to do when you have completed so many tests. I will file a bug to have the "start over" button as a drowpdown button, so its clearer that there is more than one option :)

**Comment by ferBonnin** [comment]
Closing this feature request since the problem has been solved and we filed a bug to improve discoverability of the feature.
