### ISSUE TITLE
Is not clear the Start Over button has two options

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1316]
## Describe the bug
In Assessment its not clear the Start Over button has an option to start over the whole assessment vs a test (check #1298 )

## Expected behavior

There is a clear indicator of the behaviour of the button

## Screenshots

![Start Over Button opened](https://user-images.githubusercontent.com/9062104/65805148-4e9fed00-e139-11e9-9a33-d3343f6a699f.png)

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.10.0

## Are you willing to submit a PR?
No

## Did you search for similar existing issues?

Yes
## Additional context
This comes as a result of a feature request

**Comment by ferBonnin** [comment]
@cheade thoughts for making clear the button has options? thanks!

**Comment by cheade** [comment]
Hi! Command buttons can have the down-chevron on the right, acting like a contextual menu button:
![image](https://user-images.githubusercontent.com/40274682/65805392-282e8180-e13a-11e9-8d98-9c5a546d6c23.png)


This should be an available component within Fabric 🙂

**Comment by dbjorge** [comment]
accidentally auto-closed with merged PR; leaving open as resolved until Fer can verify the fix.

**Comment by ferBonnin** [comment]
lgtm in canary :)
