### ISSUE TITLE
Add notes for automated checks

### ISSUE THREAD

**Issue by fstorr** [microsoft/accessibility-insights-web#1323]
## It would be useful to add notes to automated check results
Being able to add notes to the results of automated checks would be helpful. For example: sometimes SVGs, exported from design tools, contain the same `id` attribute but there's no impact on accessibility. Although duplicate `id`s fail WCAG 4.1.1 (Parsing) and should be remediated, it would be useful to add a note to the report to help a development team understand the impact and prioritize their work.

## Describe the desired outcome
The ability to add notes to the results of automated checks and those notes are present in the exported report.

## Describe alternatives you've considered
1. Creating a separate document to send with the exported report.
2. Manually editing the exported report to add notes.

**Comment by ferBonnin** [comment]
Thanks for your feedback @fstorr!
After reviewing this with the team, we have decided that automated checks is intended to be a fast process and having the ability to add note would slow than that process. Your alternatives sound like a good workaround, we are adding one more for you to consider: before exporting a report you have the ability to add a comment. You could add in the textbox the comment you mention.
