### ISSUE TITLE
Add a time out for scanning so reports can be manually entered if scanning fails

### ISSUE THREAD

**Issue by fstorr** [microsoft/accessibility-insights-web#1349]
## Is your feature request related to a problem? Please describe.
Sometimes scanning doesn't work and I'm left with the spinning "scanning" icon and message that doesn't seem to time out. Refreshing the app and/or target web page doesn't fix the issue. Until a scan is complete, it's not possible to enter a pass or fail score. In many instances I don't need the page scanned to enter a pass or failure because I've already inspected it.

## Describe the desired outcome
Add a time out to the scanning process so the app is still usable if scanning fails. I should be able to enter a pass or a fail (with accompanying failure notes) without having the page scanned first.

## Describe alternatives you've considered
There aren't any. I can't add any detail to a report if the application is stuck on "scanning".

**Comment by ferBonnin** [comment]
hi @fstorr could you give us an example of a website that is getting stuck?

**Comment by fstorr** [comment]
I can’t point you at anything publicly—the issue is happening to me and others on pages inside a firewall. Happy to take this offline to work on this if that helps.

**Comment by karanbirsingh** [comment]
Hi @fstorr - a few questions for you to start :slightly_smiling_face:
- do you see this hanging behavior in "Automated checks" scanning or in an assisted manual test like "Headings > Heading function?" 
- Does it prevent you from adding manual instances, or marking existing instances that are generated for you (like headings)?
- do you mind copy-pasting any logs from the dev console? (step 3 [here](https://developers.google.com/web/tools/chrome-devtools/console/log#setup))
- how consistently do you see this issue? (every time, only on certain sites, randomly without any perceived correlation to site, etc)
- do you see this same behavior when you run Automated checks from FastPass? (This is the non-assessment view)

If you do have a sample repro or codepen that is similar, that would help us greatly as well. Sorry you've been seeing issues!
