### ISSUE TITLE
Text legibility > High contrast mode is missing from reports

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#1357]
## Describe the bug

**Text legibility** > **High contrast mode** is missing from reports.

**To Reproduce**

1. Export results.
2. Scroll down to "Text legibility."
3. "High contrast mode" is missing.

## Expected behavior

"High contrast mode" should be the first requirement under "Text legibility."

## Screenshots

![image](https://user-images.githubusercontent.com/45569509/66155022-9b6d4300-e5d3-11e9-87d0-ee44c4dafba9.png)

## Extension (please complete the following information)

- OS: Windows
- Version: 10.0.18362
- Browser Version: Chrome 77.0.3865.90 (Official Build) 
- Target Page: N/A

## Are you willing to submit a PR?

No.

## Did you search for similar existing issues?

Yes.

**Comment by dbjorge** [comment]
@LiLoDavis I'm not able to reproduce this in the current production version of the extension (v2.10.0):

![screenshot of high contrast mode requirement appearing as expected](https://user-images.githubusercontent.com/376284/66238108-a0052a80-e6ab-11e9-9c31-c24aab723a4a.png)

Can you verify:
* The version of Accessibility Insights for Web you're using (you can find this in chrome://extensions/ )
* That the "High contrast mode" test doesn't show up under the "Passed tests" or "Failed tests" sections? (this would prevent it from showing up in the "Incomplete tests" section in your screenshot

**Comment by LiLoDavis** [comment]
Yes, it showed up in "Passed tests" - my mistake.
