### ISSUE TITLE
Clicks below group headers in automated checks report still collapse group

### ISSUE THREAD

**Issue by peterdur** [microsoft/accessibility-insights-web#1444]
## Describe the bug

In the automated checks results report, after expanding a group by clicking on the group header, clicking anywhere within the expanded area results in the group being collapsed - even clicking on links.

**To Reproduce**

1. Run FastPass > Automated Checks
1. Export report
1. Under failed instances, click on a rule to expand it
1. Click in the empty area around "Resources for this rule"
1. Observe: List of instances for rule collapses
1. Click on Passed Checks header to expand it
1. Click on a rule description
1. Observe: Passed Checks group collapses
1. Click on Passed Checks header to expand it
1. Click on a WCAG link
1. Link is opened in a new tab
1. Go back to report tab
1. Observe: Passed Checks group has collapsed

## Expected behavior

Groups should only collapse in the report when clicking the group header. This works correctly in the details view when the Universal Cards UI preview feature is enabled.

## Screenshots

![collapse](https://user-images.githubusercontent.com/1752950/66687656-40bd9200-ec38-11e9-9aa0-9a23192415f7.gif)

## Extension

- OS: Windows
- Version: commit bb5864304cacccf8c86b21bbe9de1a9cadf9a747
- Browser Version: Edge Dev 79.0.294.1, Chrome 77.0.3865.90
- Target Page: any

**Comment by dbjorge** [comment]
Reopening for peter to verify

**Comment by peterdur** [comment]
Verified in Canary 2019.10.16.1631
