### ISSUE TITLE
Cards UI in Report and automated checks doesn't work with High Contrast

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1449]
## Describe the bug

When turning on High contrast either via OS settings or the Settings in the tool, Cards UI in Report and automated checks dont look ok

**To Reproduce**

1. Run Automated checks in any page with automated checks issues, download report
2.  open the report in a browser that supports Windows High contrast
3. Turn on high contrast from the OS

OR
1. Run Automated checks in any page with automated checks issues
2. Turn on high contrast from the settings
3. See error

## Expected behavior
Cards UI is clear in High Contrast Mode

## Screenshots
![Cards UI in Automated checks with High Contrast ](https://user-images.githubusercontent.com/9062104/66690390-82ecd080-ec44-11e9-8714-ac93da8d46be.png)

**Comment by ferBonnin** [comment]
@cheade suggestions here, please?

**Comment by cheade** [comment]
Two different suggestions: 

1) Make the card background white and the text black, with a higher contrast dividing line for the bottom controls. 
OR
2) Outline the card with a 2-3px white border line.

**Comment by ferBonnin** [comment]
@cheade could you provide us with a Figma file that includes selected states, please?

**Comment by ferBonnin** [comment]
@waabid assigning to you since you are looking into this feature. We need to fix high contrast before releasing Cards UI

**Comment by dbjorge** [comment]
This was done as a part of earlier feature work, will release with v2.11.x
