### ISSUE TITLE
(Canary) Check circles in Assessment report are misaligned

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#1470]
## Describe the bug

The icon we use to describe how many tests have failed in the assessment report is mangled - the circle appears at the bottom of the number instead of horizontally centered. This doesn't seem to occur in the fastpass report.

![screenshot of misaligned circles](https://user-images.githubusercontent.com/7775527/66851818-72807280-ef30-11e9-9354-3c24f86004e0.png)

**To Reproduce**

1. Open an assessment against any web page
2. Export a report with any comment

## Expected behavior

The circle should be horizontally aligned with the rest of the icon (see fastpass report)

## Extension (please complete the following information)

- OS: Windows
- Version: 2019.10.15.115
- Browser Version: Version 77.0.3865.120 (Official Build) (64-bit)
- Target Page: bing

**Comment by DaveTryon** [comment]
We should fix this quickly

**Comment by ferBonnin** [comment]
We should fix this before the next release

**Comment by peterdur** [comment]
This is a recent break - was working Friday as of #1442

**Comment by karanbirsingh** [comment]
per Haonan / Dan, it looks like `!DOCTYPE html` causes this - will remove the DOCTYPE for now so we can unblock master while figuring out the details
