### ISSUE TITLE
Target page failure dialog: misalignments in bottom "back / failure count / next" bar

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#1500]
## Describe the bug

Failure details dialog seems to be not "tall" enough to acomodate all the content, making the "Next >" button appear to close to the border, like there is not enough padding/margin or the size of the dialog is not high enough.

**To Reproduce**

1. Go to [accessible university before](http://www.washington.edu/accesscomputing/AU/before.html)
2. Run automated checks
3. Open the failure details dialog for the bypass failure (top right corner "!" icon, as bypass affects html tag)
4. Observe the bottom of the dialog. The "Next >" button is "aligned" with the bottom of the dialog itself

## CodePen repro example

Not needed

## Expected behavior

Failure Details dialog should have proper layout

## Screenshots

![image](https://user-images.githubusercontent.com/2837582/67030793-03885280-f0c5-11e9-84ae-4a0d1df36693.png)

## Extension (please complete the following information)

- OS: Windows 10 Enterprise 10.0.18362 Build 18362
- Extension Version: insider 2.10.1 (on edge dev)
- Browser Version Microsoft Edge version 79.0.294.1
- Target Page http://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes.

## Did you search for similar existing issues?

No

## Additional context

This is already on production.

**Comment by ferBonnin** [comment]
@smoralesd does this repro in prod?

**Comment by dbjorge** [comment]
@ferBonnin Yes, it does

**Comment by smoralesd** [comment]
@dbjorge LGTM on master
