### ISSUE TITLE
FastPass Automated checks: checkboxes do not have accessible name

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#1505]
## Describe the bug

Failure instance checkboxes do not have an accessible name

**To Reproduce**

1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. Open the extension popup and click FastPass
3. On the resulting details view page, click on the arrow to expand the list of failures (ensure that "Enable universal cards UI" feature flag is **not** on)
4. Go to the browser console
5. Run `A11YSelfValidator.validate()`
6. Expand resulting array to see failure details and nodes `id: "aria-toggle-field-name", description: "Ensures every ARIA toggle field has an accessible name"`

## Expected behavior

Running `A11YSelfValidator.validate()` should return an empty array.

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 10.0.18362 Build 18362
- Browser Version [e.g Chrome 71.0] Chrome 77.0.3865.120 (Official Build) 
- Target Page [e.g www.bing.com] https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

This seems to be the rule that is failing: https://dequeuniversity.com/rules/axe/3.3/aria-toggle-field-label

**Comment by DaveTryon** [comment]
This occurs in the current production bits

**Comment by ferBonnin** [comment]
@iamrafan could you check if this issue, please?

**Comment by iamrafan** [comment]
@ferBonnin This is a valid issue, but currently has no user impact as the checkboxes in the instance list are not individually focusable. We need to fix this if we plan to have the same details list experience and if we plan to enable focus on each grid cell in the row.

**Comment by ferBonnin** [comment]
thanks @iamrafan, in that case, since there is no user impact this bug will disappear with Cards UI, removing from ready for work and grouping it with the feature.

**Comment by ferBonnin** [comment]
this is now fixed with new UI in Insider, @lisli1 can you take a look and close or comment?

**Comment by lisli1** [comment]
Closing this issue since the (new) universal cards UI feature flag is on by default, and this issue shows up only on the old UI.
