### ISSUE TITLE
Toast placement incorrect when page zoomed in

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#1508]
## Describe the bug

When the details view is zoomed in (using control + plus) and scrolled down to the bottom, clicking "copy failure details" can produce a Toast in the center of the page instead of the bottom of the page.

![toast](https://user-images.githubusercontent.com/7775527/67055379-cb9d0180-f0fc-11e9-88e1-c92c0106bbe8.gif)

**To Reproduce**

1. Run a fastpass
2. Go to the details view
3. Zoom in the page significantly
4. Scroll down to the bottom of the page
5. Click copy failure details

We expect the toast to be 20 pixels or so from the bottom (can be reproduced at 100% zoom).

## Extension (please complete the following information)

- OS: Windows
- Version: 2.10.0
- Browser Version: 77.0.3865.120
- Target Page: any

**Comment by dbjorge** [comment]
I am unable to repro this in either insiders (2.10.2) or a dev build from current master:

![screenshot with zoomed in toast showing up as expected](https://user-images.githubusercontent.com/376284/67131136-5f7fd380-f1b8-11e9-8ef6-971dcb7ff850.png)

@karanbirsingh, can you check whether this is still reproducing on your machine and investigate if so?

**Comment by karanbirsingh** [comment]
@dbjorge looks like I can repro on production, but not insiders. I'll close the bug
