### ISSUE TITLE
Text in electron-port-textbox acts as if 'insert' is on & deleting creates spaces

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#1543]
## Describe the bug

When entering a port in the android textbox, moving the cursor back and typing leads to two oddities:
- typing over an existing character replaces it
- deleting a character via backspace replaces it with a space

![gif of behavior](https://user-images.githubusercontent.com/7775527/67422069-92461500-f586-11e9-8741-699c392686be.gif)

**To Reproduce**

1. yarn start:electron
2. type in 12345 in the enter-a-port control
3. move cursor between 123 and 45
4. type a number or press backspace

## Expected behavior

Backspace should remove the character instead of showing a space. Adding a new character should not replace an existing character (although this may push the limit over 5 - @ferBonnin @cheade what is best?)

running on Windows at [this commit point](https://github.com/microsoft/accessibility-insights-web/tree/26df8c8f6d9e4693cc9c51ed48d29905d0feb771)

**Comment by ferBonnin** [comment]
Per conversation with Peter his guess is that we are enforcing only 5 numbers, which is expected but may have the side effect of been disconcerting for the user.
Recommendation is to review expected behaviour of numeric constrains in electron text boxes (did we enforce it or is it done by the Electron control?)
 Also, given that the port number is hard-coded, why don't we pre-populate the text box with that number?

**Comment by smoralesd** [comment]
We are using Office UI Fabric's `MaskedTextField` (one of the sub classes of the [TextField](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield) component). This seems to be the default behavior of this control.
You can check this [code pen](https://codepen.io/smoralesd/pen/OJJOJMq?&editable=true) to play with the control.
I do notice a little difference between our usage and the examples on Office UI Fabric website: on our  case the placeholder values dissapear when the users input the first number, while on Office UI Fabric example, the "mask" stays visible until the user override all the characters.
I think this behavior difference comes from a prop we are passing to the control: `maskChar=""`

**Comment by ferBonnin** [comment]
Per conversation with Peter and looking at Sebastian comments, this is by design
