### ISSUE TITLE
Contrast > State changes > How to test: Clarify requirement for redundant state indicators

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#1558]
**Describe the bug**
The test instructions need to clarify that when a UI component has multiple (redundant) non-text state indicators, only one of them needs sufficient contrast.

**Current text**
The visual helper for this requirement highlights links, native widgets, and custom widgets in the target page.

1. In the target page, examine each highlighted element to determine whether it can adopt any of the following states:
a. Focused
b. Mouseover
c. Selected
2. Identify any visual (non-text) indicators that communicate:
a. The boundary of the component's clickable area (such as a border or background color)
b. The component's current state (such as a different background color or a checkmark)
3. Use [Accessibility Insights for Windows](https://go.microsoft.com/fwlink/?linkid=2075365) (or if you are testing on a Mac, the [Colour Contrast Analyser](https://developer.paciellogroup.com/resources/contrastanalyser/)) to verify that the visual indicator has a contrast ratio of at least 3:1 against the adjacent background.
Exception: A lower contrast ratio is allowed if either of the following is true:
a. The component is inactive/disabled.
b. The component's appearance is determined solely by the browser.
4. Record your results:
a. Select **Fail** for any instances that do not meet the requirement.
b. Otherwise, select **Pass**. Or, after you have marked all failures, select **Pass unmarked instances**.

**Propsosed text**
The visual helper for this requirement highlights links, native widgets, and custom widgets in the target page.
1. In the target page, examine each highlighted element to determine whether it supports any of the following states:
a. Focused
b. Mouseover
c. Selected
2. In each supported state, use [Accessibility Insights for Windows](https://go.microsoft.com/fwlink/?linkid=2075365) (or the [Colour Contrast Analyser](https://developer.paciellogroup.com/resources/contrastanalyser/) if you are testing on a Mac) to verify that the following visual presentations (if implemented) have a contrast ratio of at least 3:1 against the adjacent background:
a. Any visual boundary that indicates the component's clickable area
b. Any visual effect that indicates the component's current state.
Note: If an element has redundant state indicators (such as a unique background color _and_ a unique text style), only one indicator is required to have sufficient contrast.
Exception: A lower contrast ratio is allowed if either of the following is true:
a. The component is inactive/disabled.
b. The component's appearance is determined solely by the browser.
4. Record your results:
a. Select **Fail** for any instances that do not meet the requirement.
b. Otherwise, select **Pass**. Or, after you have marked all failures, select **Pass unmarked instances**.

**Comment by ferBonnin** [comment]
This is a minor text change

**Comment by ferBonnin** [comment]
@smoralesd you validated this, can you please close?

**Comment by ferBonnin** [comment]
Closing this bug as resolved, verified in insider 2.11.0
