### ISSUE TITLE
Visual Helper toggle in Assessment > Automated Checks not toggling target page highlights

### ISSUE THREAD

**Issue by peterdur** [microsoft/accessibility-insights-web#1567]
## Describe the bug

When there are failures in an Assessment > Automated Checks scan, toggling the visual helper on should highlight the elements that fail the requirement. This is not working. Navigating to a different requirement and back does cause the highlights to be shown/hidden as determined by the state of the toggle.

**To Reproduce**

1. In the browser, go to [Accessible University](https://www.washington.edu/accesscomputing/AU/before.html) 
1. Click on AI-Web > Assessment
1. In dialog if shown, choose Start New
1. In left nav, click Automated Checks
1. Wait for scan to complete
1. In middle nav, click color-contrast
1. In right pane, toggle Visual Helper to On
1. Observe that in the target page, the tabs above the image are not highlighted.
1. In middle nav, click bypass
1. In middle nav, click color-contrast
1. Observe that in the target page, the tabs above the image are now highlighted.

## Expected behavior

Toggling the visual helper on/off should show/hide highlights on the elements that fail the requirement without requiring navigation to a different requirement and back.

## Screenshots

![helper](https://user-images.githubusercontent.com/1752950/67703935-7b7e3480-f971-11e9-99f7-a5da3b949cd6.gif)

## Extension (please complete the following information)

- OS: Windows 10 1909 18363.418
- Version: 2.10.3 (Insider), also reproduces in 2.10.2 (Production)
- Browser Version: Chrome 77.0.3865.120 or Chrome 78.0.3904.70
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html

**Comment by smoralesd** [comment]
I also check test **7 Links**.
**Link function** visualization seems to work just fine:
![02 - link function visualization](https://user-images.githubusercontent.com/2837582/67705684-b2097e80-f974-11e9-86fc-2491187677c9.gif)

But **Link purpose** behaves the same as the *Automated checks**
![01 - link purpose visualization](https://user-images.githubusercontent.com/2837582/67705711-c5b4e500-f974-11e9-930c-91bae59a0b90.gif)

**Comment by smoralesd** [comment]
This was introduce on #1376 when we remove the old `ClientViewController` and started using `ClientStoreListener`, `FocusChangeHandler`, `TargetPageVisualizaitonUpdater` and `VisualizationStateChangeHandler`. 
Associated commit is [d7eeca5fb5a7ea73a42b1790f8aff8dd06b83da5](https://github.com/microsoft/accessibility-insights-web/commit/d7eeca5fb5a7ea73a42b1790f8aff8dd06b83da5)

**Comment by smoralesd** [comment]
Workaround: 
1. Enable the visual helper you want to use
1. Navigate to a differente requirement
1. Navigate back to the requirement with the enabled visual helper
1. The visualization should be enabled and visible on the target page

**Comment by smoralesd** [comment]
This issue has been resolved on master (#1601) but it hasn't been deploy to production yet (blocked by #1591)

**Comment by ferBonnin** [comment]
I see this fixed in canary
