### ISSUE TITLE
[playground] FastPass will not run again if you navigate to a different target page 

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#1625]
## Describe the bug

For the Playground version of the extension: If you navigate to a new target page in the **same** tab after running FastPass, FastPass hangs if you try to run automated checks or tab stops on the new target page.

**To Reproduce**

1. Go to 'www.cnn.com'
2. Click on the extension and run FastPass; wait for results to populate in DetailsView
3. In the same tab, go to 'www.microsoft.com'. Check to make sure the target page is updated in DetailsView
4. Try to run automated checks. 
5. See that the scan is hanging and never completes

## Expected behavior

The automated checks scan should complete, and you should see that there are no errors on 'www.microsoft.com'

## Extension (please complete the following information)

- OS: Windows
- Version **Playground** 2019.11.5.1756
- Browser Version [e.g Chrome 71.0]
- Target Page www.microsoft.com

## Are you willing to submit a PR?
Yes, if asked.

## Did you search for similar existing issues?
Yes

Yes

**Comment by ferBonnin** [comment]
this is a side effect of the permissions change. Sebastian is already looking into this experience.

**Comment by smoralesd** [comment]
fix on playground  2019.11.26.2050
