### ISSUE TITLE
Images > Image Function Visual Helper not highlighting the first image

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#1626]
## Describe the bug

The visual helper does not place a highlight box around the first image on 'www.microsoft.com'; the image does show up in the instances list in the DetailsView page. 

**To Reproduce**

1. Go to 'www.microsoft.com'
2. Click on the extension and elect to start an Assessment
3. Go to 14 > Images > Image function and enable the Visual helper
4. See that the first image is not highlighted on the page, but is still listed in the instances list in Details View
5. Attempt to deselect the image so the alleged highlight box will disappear
![image](https://user-images.githubusercontent.com/19158512/68239786-7ac44e80-ffc0-11e9-9aa9-2f58b817377e.png)
Note: sometimes deselecting, then selecting the image results in the highlight box being drawn; sometimes, the highlight box continues to be hidden

## Expected behavior

]
That a highlight box will be drawn around all images listed in 'instances' on DetailsView. Additionally, expect that deselecting and then selecting again will hide the box and redraw the box, respectively. 

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.10.3 of the Accessibility Insights for Web extension
- Browser Version [e.g Chrome 71.0]
- Target Page [e.g www.bing.com] 'www.microsoft.com'

## Are you willing to submit a PR?
Yes, if asked. 

## Did you search for similar existing issues?
Yes and yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, this seems to be because the image is on a carousel. If this is the case, then this is a known issue and won't fix. If not, lets add more details on what is causing this

**Comment by JGibson2019** [comment]
The highlight box will only be drawn around the image that was present when the scan first occurred. More specifically, if there are two images, A and B, and A was visible when AI Web scans, the highlight box can be hidden and redrawn when A is visible. When B comes to the front of the carousel, the box can be hidden but cannot be redrawn. When A becomes visible again, the image must be deselected from the instance list then selected again; after this, the highlight box becomes visible again. I think this is the intended behavior? If so, I will close the bug!

**Comment by JGibson2019** [comment]
Confirmed with team behavior is performing as designed. Closing out issue now.
