### ISSUE TITLE
Update prettier config to change line width to 100

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-web#1713]
## Describe the feature

The idea is to have line width more compatible with the `GitHub` diff view and we feel that default `prettier line width of 80 is best suited for that.
So, using [Prettier Override](https://prettier.io/docs/en/configuration.html#configuration-overrides) as suggested by @dbjorge and @smoralesd .

Creating this issue to track all the PRs that are going to be part of this, since we want to incrementally change the whole code base.

**Comment by smoralesd** [comment]
Since this is an engineering task, I'm closing it myself.
