### ISSUE TITLE
export: provide hosted export targets

### ISSUE THREAD

**Issue by bnb** [microsoft/accessibility-insights-web#1739]
## Is your feature request related to a problem? Please describe.
Nope.

## Describe the desired outcome
Currently, if I export I just get a bare HTML file. If I want to share this with peers, I need to publish it myself.

While I personally know of and have access to a dozen ways to publish a single HTML file rapidly, this isn't true of everyone who may use Accessibility Insights.

I'd love to see something like "Export to..." built-in to this project - more specifically, it would be cool to see "Export to..." options for Glitch, CodePen, GitHub Pages (if authed and a repo is selected?), and possibly even enable the community to contribute additional targets.

## Describe alternatives you've considered
The status quo is one alternative - it doesn't add any complexity, but does make exporting and sharing results harder.

An additional option would be an interactive CLI published to npm that requires you have npm and Node.js installed. Running something like `npx insights-publish ./path/to/insights/export.html` could be another option. This seems like potentially a significantly larger amount of work would be needed, though if you wanted to build built-in plugin support you could add something like `npx insights-publish --to=glitch  ./path/to/insights/export.html` where the module resolves `--to=glitch` as an additional module with a prefix like `insights-plugin-glitch` that it will install and that can hook into an extension API and publish as the author of `insights-plugin-glitch` defines.

## Additional context
None.

**Comment by adarshrema** [comment]
Hello @bnb, thank you for using Accessibility Insights for Web and this feature request. Looks like this would support a workflow specific to your team/ project. We welcome any contributions from your team to make this happen.

We are interested in gauging how attractive this feature might be for the larger community. However, given our current priorities and information we have about this feature request so far, it is not likely that we will be able to pick this up anytime soon.

**Comment by juchampa** [comment]
Hi @bnb ,

We are happy to inform you this issue has been addressed through a public contribution to our open source repository [here](https://github.com/microsoft/accessibility-insights-web/pull/2252), by @ sean-beard. This feature is now under a public flag, so feel free to use this feature and contribute to it if you'd like.

**Comment by bnb** [comment]
Thought I had responded to this initially, but apparently not.

> Hello @bnb, thank you for using Accessibility Insights for Web and this feature request. Looks like this would support a workflow specific to your team/ project. We welcome any contributions from your team to make this happen.

This has nothing to do with my specific team. The context in which I was asking was open-source work in which I used Accessibility Insights to provide feedback on how extremely inaccessible the site being proposed was. I outlined the entire scope of why I was requesting this in my initial comment and am concerned that the context that was extracted there was that it’s something my team was requesting when that is categorically not true and I provided no such indicator.

> This feature is now under a public flag, so feel free to use this feature and contribute to it if you'd like.

Would you be open to PRs from maintainers of additional sites similar to CodePen PRing support for their sites?

**Comment by ferBonnin** [comment]
> This has nothing to do with my specific team. The context in which I was asking was open-source work in which I used Accessibility Insights to provide feedback on how extremely inaccessible the site being proposed was. I outlined the entire scope of why I was requesting this in my initial comment and am concerned that the context that was extracted there was that it’s something my team was requesting when that is categorically not true and I provided no such indicator.

Hi @bnb thanks for clarifying that and our apologies for the confusion!

> Would you be open to PRs from maintainers of additional sites similar to CodePen PRing support for their sites?

We are open to contributions like the existing CodePen one, however we would prioritize sites for where there is user demand and we might need a different UX experience if we were to have more than 2-3 options on where to export to.

**Comment by ferBonnin** [comment]
this has been resolved for a while after the codePen integration with no other users' comments. closing :)
