### ISSUE TITLE
Update description text on Microsoft Edge Insider addons page

### ISSUE THREAD

**Issue by adarshrema** [microsoft/accessibility-insights-web#1750]
Issue:
Update WCAG version from 2.0 to 2.1 and remove '100%' coverage language based on guidance from CELA

Resolution:
Update language on the [Microsoft Edge Insider Addons page](https://microsoftedge.microsoft.com/insider-addons/detail/ghbhpcookfemncgoinjblecnilppimih) for Accessibility Insights for Web. Update *Assessment* under *Description* section to the following to be consistent with text on the [overview documentation page](https://accessibilityinsights.io/docs/en/web/overview):

Assessment allows anyone with HTML skills to verify that a web app or web site is compliant with [Web Content Accessibility Guidelines (WCAG) 2.1 Level AA](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1&levels=aaa).

**Comment by ferBonnin** [comment]
This needs to wait for next release, assigning to Peter per conversation.

**Comment by peterdur** [comment]
The 100% text has been removed from the listings in the [classic Edge store](https://www.microsoft.com/en-us/p/accessibility-insights-for-web/9nf8624pqs3c?activetab=pivot:overviewtab) and the [Chromium Edge store](https://microsoftedge.microsoft.com/addons/detail/ghbhpcookfemncgoinjblecnilppimih).
