### ISSUE TITLE
Help section loses bottom margin when the windows is small

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#1753]
## Describe the bug

By setting the windows size to less than 1130px the **Help** section (under Assessment > Overview) gets re-flowed to the bottom of the page but it doesn't have a proper border/margin, so it gets align with the end of the page itself

**To Reproduce**

1. Go to any website
2. Start a new **Assessment**
3. Go to the **Overview** section
4. Change the size of the browser windows so it's less than 1130px
5. Observe: the help section moves to the bottom of the page

## CodePen repro example

**Does not apply**

## Expected behavior

The **Help** section should have proper styling even when re-flowed

## Screenshots

![image](https://user-images.githubusercontent.com/2837582/69683404-94a9fc00-1069-11ea-881a-7cbf28cd4c6c.png)

## Extension (please complete the following information)

- OS: Windows 10 
- AI-Web version 2.10.3
- Browser Version 78.0.3904.108 (Official Build) (64-bit)
- Target Page any

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
will take care of this one as part of the reflow features. @ferBonnin add to appropiate feature

**Comment by AhmedAbdoOrtiga** [comment]
resolved in [PR#2798](https://github.com/microsoft/accessibility-insights-web/pull/2798)

**Comment by AhmedAbdoOrtiga** [comment]
@ferBonnin  this issue was resolved in  [PR#2798](https://github.com/microsoft/accessibility-insights-web/pull/2798), should we close it or is there a reason to move it to actives?

**Comment by ferBonnin** [comment]
@AhmedAbdoOrtiga we keep issues in the Active column when they are _active_ or _resolved_. Someone needs to take a look, confirm the fix and close this issue for it to move to _closed_

**Comment by ferBonnin** [comment]
reviewed this with Peter, this is still active. Ideally we would keep a small padding of white background after the help box.

**Comment by ferBonnin** [comment]
Per conversation with Peter, small issue that should not impact usability. Will reactivate if we hear user feedback
