### ISSUE TITLE
No failures in automated checks should not show red icon

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#1756]
## Describe the bug
When there are no failures, we show the red icon instead of a green sign or not show the red icon.

![image](https://user-images.githubusercontent.com/29855291/69684918-4dbf0500-106f-11ea-88c9-109607137b32.png)

**To Reproduce**

1. Go to [https://www.microsoft.com](https://www.microsoft.com)
2. Open Playgound extension's popup & goto adhoc tools panel.
3. Click on 'List view & filtering' link under Automated checks toggle.
4. This opens the details view for automated checks without any errors, as shown in the screenshot above.

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] - Windows & Mac
- Version [e.g. 1.140.1] (Playground extension 2019.11.26.2050)
- Browser Version [e.g Chrome 71.0]  78.0.3904.108

**Comment by ferBonnin** [comment]
Per conversation with Peter, the icon with 0 failures is consistent with the UI with failures. If we get user feedback that this is confusing will look into this again.
