### ISSUE TITLE
Details view does not respect high contrast if initial state is "No content available"

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#1757]
## Describe the bug

If a Details View begins its lifecycle in the "No content available" state (as opposed to reaching it via the corresponding target tab closing), it doesn't respect high contrast mode and just always renders in normal mode. Repros in both Prod and Playground as of writing.

**To Reproduce**
1. Enable High Contrast mode
1. Open an Assessment against any target page
1. Close the corresponding target page
1. Observe the no content available page rendering in high contrast mode as expected
1. Reload the details view
1. Observe the no content available page rendering in normal contrast mode

## Expected behavior

Page should still respect high contrast mode

## Screenshots

![animation showing the repro steps](https://user-images.githubusercontent.com/376284/69685042-d178f180-106f-11ea-8fac-8f0bc16eda39.gif)

## Extension (please complete the following information)

- OS: Windows
- Version: Repros in both prod/2.10.3 and playground/2019.11.26.2050
- Browser Version: any (repros in both edge insider dev and chrome stable)
- Target Page: any

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, It would be nice to fix, but its not a since there isn't anything the user can do once they receive this message, so won't fix.
