### ISSUE TITLE
In details view, console exception is thrown for violating Content Security Policy directive

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#1758]
## Describe the bug

- Goto any web page & then Open Assessment in details view.
- Click on any test step.
- Open dev tools & goto console on the details view.

Exception thrown:
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://az416426.vo.msecnd.net". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] - Windows
- Version [e.g. 1.140.1] - This is happening in all our extensions. Not sure when this was introduced
- Browser Version [e.g Chrome 71.0] - 78.0.3904.108

**Comment by ferBonnin** [comment]
Per conversation with Peter, this needs dev investigation.

**Comment by karanbirsingh** [comment]
This is caused (and fixed) by OF here: https://github.com/OfficeDev/office-ui-fabric-react/issues/10201 (fix in `office-ui-fabric-react@v7.27.0`)

This issue is blocked on our upgrade PR here: https://github.com/microsoft/accessibility-insights-web/pull/1924

**Comment by ferBonnin** [comment]
@devaradhanm this should be fixed now. Can you confirm?

**Comment by smoralesd** [comment]
@devaradhanm I have validated the error does not shows up on insider 2.14.1 so I'm closing this issues as resolved.
