### ISSUE TITLE
Environment tab in github has deployment link that doesnt exist

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#1764]
## Describe the bug
Since we have a separate repo for docs, github pages docs deployment should be removed / fixed so that it doesn't point to dead link.

**To Reproduce**

1. Go to [https://github.com/microsoft/accessibility-insights-web/deployments](https://github.com/microsoft/accessibility-insights-web/deployments)
2. Click on any of the 'View deployment' links.

**Comment by dbjorge** [comment]
I've disabled the bogus github pages setting in the repo settings, but this isn't sufficient to remove the Environment tab. https://github.community/t5/GitHub-Pages/How-to-remove-the-environment-tab/td-p/20662 suggests that this isn't officially supported yet, but one of the later comments suggests that we might be able to do it by [invoking a beta github API](https://developer.github.com/v3/repos/deployments/#parameters-2) to set the deployment status to "inactive".

**Comment by dbjorge** [comment]
I've performed the necessary API calls to set all the deployment statuses as Inactive. This doesn't appear to have caused the Environment tab to be removed for my account when I'm logged in, but has removed it from the repo when I view it in an incognito window logged out. It appears that this is the best we're going to be able to do with GitHub's current support for this operation, so marking this as resolved.

![screenshot of accessibility-insights-web repo from incognito mode with environments tab
not visible](https://user-images.githubusercontent.com/376284/70097786-055b9600-15df-11ea-923b-8d9c88b087ab.png)
