### ISSUE TITLE
Automated checks report: CSS broken in insider for Passed and Non-applicable rules

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#1791]
## Describe the bug

The passed and non-applicable rules not stylized appropriately.

**To Reproduce**

1. Scan any page with passing/non-applicable rules.
2. Export the results.
3. Expand the passed/non-applicable section.

## Expected behavior

Styling should be the same as production.

## Screenshots

Insider:

![image](https://user-images.githubusercontent.com/32555133/70103731-d4845c80-15f0-11ea-9283-d5be66e9b85d.png)

Production:

![image](https://user-images.githubusercontent.com/32555133/70103789-ea921d00-15f0-11ea-899a-4cf34b446d46.png)

## Are you willing to submit a PR?

Yes

## Additional context

Seems to be a css-module issue.

**Comment by waabid** [comment]
Seems to be fixed by #1787

**Comment by ferBonnin** [comment]
this looks ok in Canary now  2019.12.12.1641
