### ISSUE TITLE
Cards UI state resets when opening links

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#1800]
## Describe the bug

Cards states resets when the user opens a links (e.g. the more information links for the rules) and then navigate back the tab where the fast pass view is.

**To Reproduce**

1. Go to [Accessible University](https://www.washington.edu/accesscomputing/AU/before.html)
2. Open fast pass, let the scan finish
3. Expand the **bypass** card
4. Activate the **More information about bypass** link, this will create a new tab
5. Navigate back to the tab where the fast pass view is.
6. Observer: all the cards are collapsed and the **Visual helper** toggle is off.

## CodePen repro example

N/A

## Expected behavior

Cards state should be persisted when the user navigates (by any means) to a different tab and comes back.

## Screenshots

![01 - cards state reset on navigate away](https://user-images.githubusercontent.com/2837582/70194517-8c7c3d00-16b7-11ea-9cc6-6885becd86ba.gif)

## Context (please complete the following information)

- OS Name & Version: Windows 10.0.18363 Build 18363
- AI-Web Version & Environment: 2.11.0 Insider-->
- Browser Version: Google Chrome 78.0.3904.108 (Official Build) (64-bit)
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

No

## Additional context

N/A

**Comment by ferBonnin** [comment]
@waabid did you fixed this already?

**Comment by ferBonnin** [comment]
@smoralesd this looks fixed in Canary

**Comment by smoralesd** [comment]
Verified fixed on insider 2.12.0
