### ISSUE TITLE
Cards UI and parsing

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1801]
## Describe the bug

Cards UI fails parsing requirement

**To Reproduce**

1. Run automated checks, fast pass in a website with issues
2. open inspect and run the following command in the console: 
```javascript
(function(){function c(a,b){var c=document.createElement("textarea");c.name=a;c.value=b;d.appendChild(c)}var e=function(a){for(var b="",a=a.firstChild;a;){switch(a.nodeType){case Node.ELEMENT_NODE:b+=a.outerHTML;break;case Node.TEXT_NODE:b+=a.nodeValue;break;case Node.CDATA_SECTION_NODE:b+="<![CDATA["+a.nodeValue+"]]\>";break;case Node.COMMENT_NODE:b+="<\!--"+a.nodeValue+"--\>";break;case Node.DOCUMENT_TYPE_NODE:b+="<!DOCTYPE "+a.name+">\n"}a=a.nextSibling}return b}(document),d=document.createElement("form");d.method="POST";d.action="https://validator.w3.org/nu/";d.enctype="multipart/form-data";d.target="_blank";d.acceptCharset="utf-8";c("showsource","yes");c("content",e);document.body.appendChild(d);d.submit()})();
```
3. "then run the [check for WCAG 2.1 parsing compliance bookmarklet](https://validator.w3.org/nu/about.html)
4. See errors
 * Error: Start tag seen without seeing a doctype first. Expected <!DOCTYPE html>. 
* Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.) 
* Error: Element div not allowed as child of element button in this context. (Suppressing further errors from this subtree.) 

## Expected behavior

No errors should appear

## Context (please complete the following information)

- OS Name & Version:  Windows 10
- AI-Web Version & Environment:  Insider 2.11.0
- Browser Version:  Google Chrome 78
- Target Page:  any

## Additional context

Found during validation

**Comment by dbjorge** [comment]
Checked parsing test again in current master. Most of the issues are false positives from the perspective of 4.1.1 compliance; in particular, we don't think the "missing <!DOCTYPE>" and "div has name attribute" cases are 4.1.1 violations.

The OF7 update has fixed the third of the 3 issues from the original report. The `<div class="button-flex-container" aria-hidden="true">` nested inside a `<span>` in the nav bar items (the second of the 3 issues from the original report) does appear to still be occuring; will investigate it further.
