### ISSUE TITLE
Insider: Iframes scanning and highlighting

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1814]
## Describe the bug

Highlights are not showing with insider build

**To Reproduce**

1. Go to https://codepen.io/FerBonnin/pen/GRgprmO
2. Run Automated checks (fastpass) with Insider 
3. you will get two type of failures:
* color-contrast failure is not detected (1st time you scan)
* highlighter for the color contrast doesnt work (2nd time you scan)

In both cases, in the console, there is an error: 
`cannot connect to  <iframe id=​"result" name=​"CodePen" src=​"https:​/​/​cdpn.io/​FerBonnin/​fullpage/​GRgprmO" sandbox=​"allow-forms allow-modals allow-pointer-lock allow-popups allow-presentation allow-same-origin allow-scripts" allow=​"geolocation;​ microphone;​ camera;​ midi;​ vr;​ accelerometer;​ gyroscope;​ payment;​ ambient-light-sensor;​ encrypted-media" scrolling=​"auto" allowtransparency=​"true" allowpaymentrequest=​"true" allowfullscreen=​"true" class=​"result-iframe ">​#document</iframe>​
`
## CodePen repro example

https://codepen.io/FerBonnin/pen/GRgprmO

## Expected behavior

Failure should be detected consistently and highlighter should work

## Context (please complete the following information)

- OS Name & Version:  Windows 10
- AI-Web Version & Environment:  Insider 2.11.0
- Browser Version:  Chrome 78

**Comment by ferBonnin** [comment]
@smoralesd @dbjorge assigning to you since you are already looking into this :)

**Comment by smoralesd** [comment]
Fixed as of 2.13.1
