### ISSUE TITLE
Automated checks is scanned in assessments view even when it is not selected

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#1816]
## Describe the bug

When a user starts an assessment and decides to select a test other than automated checks, automated checks are scanned regardless. This should not happen: only the requirement that is selected should be scanned.

**To Reproduce**

1. Go to overview in assessment view.
2. Select a test that is not automated checks (e.g. custom widgets).

Note: now automated checks will either have a checkmark or an "X" in the left nav meaning it was scanned.

Gif below of the behavior:

![automatedcheckscanbug](https://user-images.githubusercontent.com/32555133/70363598-dabb4880-183d-11ea-8ea4-b9ac5a8d85bc.gif)

## Expected behavior

Only the selected requirement should be scanned.

## Context (please complete the following information)

- Browser Version: Edge Chromium Version 80.0.345.0
- Target Page:  any

## Are you willing to submit a PR?

Yes

**Comment by ferBonnin** [comment]
@waabid I can't repro this anymore in production. Is this fixed? if not, can you please add new repro steps?

**Comment by smoralesd** [comment]
I tried to repro this again (prod 2.15.0 and insider 2.16.0) without success. Closing the issue base on 2 different people at separated times not being able to reprro.
