### ISSUE TITLE
Pop up for starting a new report in Assessment tool

### ISSUE THREAD

**Issue by brandonleyton** [microsoft/accessibility-insights-web#1858]
## Describe the desired outcome

In the assessment tool, when an assessment is complete and the user loads a new page to test, a pop up appears asking if they want to stay on the current assessment or load a new assessment.

At that point it would be helpful for workflow to offer a button option allowing the user to save the current assessment report and then start a new assessment. If this were offered a a single function it would speed up workflow for testers that are reviewing large amounts of pages.

## Describe alternatives you've considered

The current workflow would require the user to exit the pop up, save the report and then start a new assessment. This doesn't take much more time, but if the user is reviewing many pages at once, the small amount of extra time needed to go back, save the report and start a new assessment, will add up.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
