### ISSUE TITLE
Overview icons green and red color

### ISSUE THREAD

**Issue by mhulse** [microsoft/accessibility-insights-web#1877]
Would it be possible to make the pass or fail icons green or red respectively?

![](https://user-images.githubusercontent.com/218624/71019067-8cfcd680-20ae-11ea-9e98-166fda875c38.png)

**Comment by ferBonnin** [comment]
Hi @mhulse thanks for the feature request! 

It is a good idea and we also thought about this, but when we did the designs and tested them we found it was an overwhelming experience for some users and the UI looked too busy with all those colors (grey, white, blue, red and green) so we decided to keep them grey and use the icons only.
