### ISSUE TITLE
Issue details dialog how to fix description repeats

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#1933]
## Describe the bug

**To Reproduce**

1. Go to https://www.bing.com/
2. Open the extension and run FastPass
3. Scroll down to the bottom of the target page
4. Open the issue details dialog in the banner under "Experience beauty every day" (It should be a color contrast issue), by clicking on the exclamation mark box on the right side of the highlighted issue
![image](https://user-images.githubusercontent.com/48259897/71702339-b0e53b00-2d83-11ea-8c78-cc0ba00fe862.png)
5. See that the description under "Fix the following" is actually the same thing repeated (`Element has insufficient color contrast of 4.22 (foreground color: #666666, background color: #dddddd, font size: 9.8pt (13px), font weight: normal). Expected contrast ratio of 4.5:1` x2)
![image](https://user-images.githubusercontent.com/48259897/71702325-990db700-2d83-11ea-8fa1-a4263e904adb.png)

## Expected behavior

The how to fix description should show only once

## Context (please complete the following information)

- OS Name & Version:  Windows 10.0.18363 Build 18363
- AI-Web Version & Environment:  Insider Version 2.13.0
- Browser Version:  Microsoft Edge Version 79.0.309.56 (Official build) beta (64-bit)
- Target Page:  https://www.bing.com/

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

- Issue not present in prod version 2.10.3
- Couldn't find this issue on other issue details dialogs (seems to be only on color contrast issues)
- This shows up also in AI Web Insider on Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by peterdur** [comment]
The text is also duplicated in the card for this result:
![image](https://user-images.githubusercontent.com/1752950/71738213-d8331b00-2e0a-11ea-9d20-56fb623b0c8d.png)
(Screenshot showing color-contrast result with duplicate text in "How to fix" area)

**Comment by smoralesd** [comment]
fixed on 2.13.1
