### ISSUE TITLE
Incorrect Bug: ARIA attribute is not allowed: aria-orientation="horizontal"

### ISSUE THREAD

**Issue by SavannahBourgeois** [microsoft/accessibility-insights-web#1952]
## Describe the bug

We have gotten bugs filed on us because of the insights tool saying that aria-orientation is not an allowed attribute. It seems like aria-orientation is an allowed attribute [(link)](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-orientation_attribute) so we are confused as to why this is happening.

**To Reproduce**

Repro Steps:
Step 1: Open Onenote for the web using edge browser.
Step 2: Navigate to “Edit Notebook” button by using tab key.
Step 3: Navigate to “Edit Note in browser field” menu-item by using tab key and select it.
Step 4: Navigate to Home tab by using ctrl+F6 and select it.
Step 5: Navigate to Insert tab by using arrow key and activate it.
Step 6: Navigate to “Table” button by using tab key and expand it.”
Step 7: Select row and column and press enter key.
Step 8: Navigate to “Table” tab by using “ctrl+F6” and select it.
Step 9: Open Developer tool bar (F12)
Step 10: Verify whether Elements must only use allowed ARIA attributes.
 
Actual Result:
ARIA attribute is not allowed: aria-orientation="horizontal"
 
Expected Result:
Elements must only use allowed ARIA attributes.

## Expected behavior

No error around aria-orientation.

## Screenshots

![Table_Element must only use allowed ARIA attributes](https://user-images.githubusercontent.com/42548121/72004975-63445480-3201-11ea-972b-e16fba6ae19c.png)

![Code Snippet_Insert_Table](https://user-images.githubusercontent.com/42548121/72004972-617a9100-3201-11ea-8edb-99e2a431dc96.png)

![word_3841738](https://user-images.githubusercontent.com/42548121/72004978-65a6ae80-3201-11ea-88b3-293974372b17.PNG)

## Context (please complete the following information)

OS: Version 1903 (OS Build 19002. 1)
Application: OneNote web
Browser: Chrome (Version 79.0.3945.79)
Edge (Version 44.19002.1.0)
Tool Used: Accessibility Insights for Web (K4W)
K4W Version: 2.10.3

## Are you willing to submit a PR?

no

## Did you search for similar existing issues?

yes

**Comment by ferBonnin** [comment]
Hi @SavannahBourgeois aria-orientation is not a valid attribute for role="group". Adding a link to the W3C documentation: [Aria-orientation](https://www.w3.org/TR/wai-aria/#aria-orientation)

**Comment by SavannahBourgeois** [comment]
Thanks, I have updated our code instead!
