### ISSUE TITLE
scanning doesnt complete on some pages

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#1953]
## Describe the bug

This issue seems to be due to https://github.com/dequelabs/axe-core/issues/1754

**To Reproduce**

1. Go to https://www.microsoft.com/en-us/ignite
2. Run automated checks by clicking on "List view & filtering" from adhoc panels view

## Actual Behavior
Sscanning doesnt complete & the screen is stuck with Scanning spinner.
On looking at the dev tools console in target page, we see this error log:

![image](https://user-images.githubusercontent.com/29855291/72021569-2b4e0900-3223-11ea-8554-15bd60d4c1d8.png)

## Expected behavior

Accessibility issues should be displayed. 

## Context (please complete the following information)

- OS Name & Version: Windows 10 Version 1903
- AI-Web Version & Environment: Prod extension - 2.13.1
- Browser Version: Chrome 79.0.3945.88
- Target Page: https://www.microsoft.com/en-us/ignite

**Comment by ferBonnin** [comment]
@devaradhanm we have updated to axe-core 3.5.1, can you confirm this issue has been addressed?

**Comment by devaradhanm** [comment]
Validated. this is fixed now.
