### ISSUE TITLE
Focus ring when selecting instance cards with mouse

### ISSUE THREAD

**Issue by ichelsea** [microsoft/accessibility-insights-web#1961]
## Describe the bug

When selecting a card with the mouse in Automated checks, the user gets the selected box as well as the focus ring. The focus ring should only be present if the user is navigating with the keyboard. 

**To Reproduce**

1. Run Automated checks on a site with errors. 
2. Select any instance card.

## Expected behavior

When selecting the card with the mouse, users should just see the blue highlight box around the card. When using the keyboard, users should see the focus ring and if they select with enter or the spacebar, they will see the selection and focus ring until they navigate focus away. 

## Screenshots

![image](https://user-images.githubusercontent.com/40274682/72095689-d1eee400-32cd-11ea-9ada-16fb058f418b.png)

## Context (please complete the following information)

- OS Name & Version:  macOS Catalina 10.15.2
- AI-Web Version & Environment: AI-Web 2.10.3
- Browser Version: Edge (BETA) 79.0.309.58
- Target Page: www.yahoo.com

## Are you willing to submit a PR?

Potentially

## Did you search for similar existing issues?

No

## Additional context

I have a screen recording if needed!

**Comment by Shobhit1** [comment]
Taking this one @devaradhanm @ferBonnin

**Comment by dbjorge** [comment]
The current behavior is the browser's default; the "not showing the focus indicator for mouse clicks" behavior we see with other buttons is only the normal browser behavior for `<button>`s that don't override border/outline styles.

There is a W3C proposal for a [`:focus-visible` CSS selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) that we could use in place of `:focus` to get the behavior the bug description requests, here (only showing focus if the element is focused *and* the browser's heuristics think it should be visualized, similar to how button focus rings work by default); however `:focus-visible` isn't standardized yet, and though [Chromium does implement it, it is disabled by default unless users opt into a Chromium feature flag](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#Browser_compatibility).

A [polyfill for it does exist](https://github.com/WICG/focus-visible), but I don't recommend we use it:
* I'm not sure it's complete enough that it would be a good idea (in particular, its heuristics only show focus if tab/shift+tab/arrow keys change focus, which might not be sufficient for AT users)
* It feels pretty heavyweight to add a dependency for such a minor UI thing

My inclination would be to wontfix this bug until such time as `:focus-visible` is available by default in Chromium. @ferBonnin , thoughts?

**Comment by ferBonnin** [comment]
@dbjorge thanks for investigating this!
Yes, marking out of scope for now; we can revisit when `:focus-visible` is available by default if we receive user feedback on this.
