### ISSUE TITLE
Automated checks background color

### ISSUE THREAD

**Issue by cheade** [microsoft/accessibility-insights-web#1962]
## Describe the bug

Background should be #F8F8F8 (--neutral-2), is currently #FFFFFF 

**To Reproduce**

1. Run Automated checks

## Expected behavior

Background should be #F8F8F8 (--neutral-2)

## Screenshots

Current:
![image](https://user-images.githubusercontent.com/40274682/72096773-c3093100-32cf-11ea-8cbb-43d5bcbff13d.png)

Should be: 
![image](https://user-images.githubusercontent.com/40274682/72097330-01ebb680-32d1-11ea-8397-43d19e965e54.png)

## Context (please complete the following information)

- OS Name & Version: macOS 10.15.2
- AI-Web Version & Environment: V2.10.3
- Browser Version: <!--e.g. Edge (BETA)
- Target Page: n/a

## Are you willing to submit a PR?

Yep

## Did you search for similar existing issues?

No

**Comment by smoralesd** [comment]
@cheade should this change affect other "views": Fast Pass > Tab Stops; all of the Assessments?

**Comment by ferBonnin** [comment]
@smoralesd I think this is only for  the Cards UI in automated checks FastPass

**Comment by ferBonnin** [comment]
@cheade This fix should be now available in Canary. Could you please review?

**Comment by cheade** [comment]
Looks good, thanks guys!
