### ISSUE TITLE
Visualizations are drawn for nodes that are not within the screenshot

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#1966]
## Describe the bug

When running the electron application, errors that are not on the screenshot are still visualized.

**To Reproduce**

1. Connect the electron application on android emulator (personally using Pixel 2)
2. Go to Bing Search app.
3. Scan the app.

## Expected behavior

These visualizations should not exist.

## Screenshots

![image](https://user-images.githubusercontent.com/32555133/72116528-54dc6280-32ff-11ea-9a76-8545d00b4d82.png)

## Context (please complete the following information)

Using android 27 on Pixel 2.

## Are you willing to submit a PR?

Yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, at the very least we should not highlight things that are not in the screenshot. partial highlights are ok

**Comment by ferBonnin** [comment]
@waabid can you please validate and close this?
