### ISSUE TITLE
No confirmation dialog after installation

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1974]
## Describe the bug

With the Electron tool, there is no confirmation dialog after installation to let users know it completed and ask if they want to launch the app.

**To Reproduce**
 
1. Uninstall Electron app
2. Install again with the most recent installer

## Expected behavior

After installation, it should let the users know it succeeded and then (ideally) ask if they want to launch the app

## Additional context

related to  #1868

**Comment by ferBonnin** [comment]
@karanbirsingh which version can I use to confirm this has been resolved?

**Comment by karanbirsingh** [comment]
@ferBonnin Tried resolving this on the most recent official canary and don't see it - moving back t oactive

**Comment by karanbirsingh** [comment]
@ferBonnin the latest version should be updated now (2020.206.3)

**Comment by ferBonnin** [comment]
looks great!
