### ISSUE TITLE
Telemetry in Console: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1988]
## Describe the bug

In Web Canary, the telemetry is not being logged. When opening background and looking at the console I have the following error:
`sendMessageToTab(99) failed for message { isStoreUpdateMessage: true,
  storeId: 'AssessmentStore',
  messageType: 'STORE_CHANGED',
  storeType: 0,
  payload: <payload info here> with browser error message: Could not establish connection. Receiving end does not exist.`

**To Reproduce**

1. Go to Web Canary
2. In Chrome Extensions, select the extensions and open background.html
3. do any action with the extension

## Context (please complete the following information)

- OS Name & Version:  Windows 10
- AI-Web Version & Environment:  Canary 2020.1.15.2214
- Browser Version:  Chrome  79.0.3945.117 
- Target Page:  any

## Additional information

I also see this happening in production

**Comment by smoralesd** [comment]
Telemetry is being logged.
I think the issue we have is we are flooding the console with the `sendMessageToTab failed` errors, which is a problem as it just make noise.

![image](https://user-images.githubusercontent.com/2837582/72482015-1c320280-37b1-11ea-8e70-233e58093271.png)
