### ISSUE TITLE
Electron app text change - minimum touch size is 44dp (not 48dp)

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#1994]
## Describe the bug
The "How to fix" content for TouchSizeWcag says to "Set the element's **minWidth** and **minHeight** attributes to at least 48dp."
However, the rule actually checks for a minimum of 44dp. (See [Why WCAG_TARGET_SIZE = 48; #12](https://github.com/dequelabs/axe-android/issues/12))

## Expected behavior

The "How to fix" content should say, "Set the element's **minWidth** and **minHeight** attributes to at least 44dp."

**Comment by ferBonnin** [comment]
@Shobhit1 when/where can this be validated by @LiLoDavis?

**Comment by LiLoDavis** [comment]
I have validated.
