### ISSUE TITLE
Text changes in Electron app

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#2043]
## Describe the bug

Two text changes needed in Electron app:
- in port number screen, should be Android not android (uppercase A)
- in Congratulations message, when no automated checks errors are found. Need to add further clarification that more testing is required; suggestion:
"No failed automated checks were found.  Continue investigating your app's accessibility compliance through manual testing"

## Expected behavior
New text changes are added 

## Additional context
Uppercase A is required per branding guidelines.
Adding more clarification per user's feedback.

**Comment by ferBonnin** [comment]
Marking as ready for triage so we can review text suggestions before changing them

**Comment by ferBonnin** [comment]
per conversation. For web, similar text (note that the differences are bolded)
No failed automated checks were found. Continue investigating your **website's** accessibility compliance through manual testing **using Tab stops and Assessment**"

**Comment by karanbirsingh** [comment]
This text is still not done:

`No failed automated checks were found. Continue investigating your website's accessibility compliance through manual testing using Tab stops and Assessment` because it requires different electron & web behavior. Getting the other static parts in now

**Comment by ferBonnin** [comment]
Per conversation with Peter, let's timebox getting the two different texts for Web and Unified to a day.
Android: "No failed automated checks were found. Continue investigating your app's accessibility compliance through manual testing"

Web: "No failed automated checks were found. Continue investigating your website's accessibility compliance through manual testing using Tab stops and Assessment"

 If there is something too complex to do this, talk with @ferBonnin for a generic text for both

**Comment by smoralesd** [comment]
@ferBonnin this message also shows up on the automated checks report. Should we use the "web" version of this message on the report too?

**Comment by ferBonnin** [comment]
@smoralesd yes, please

**Comment by DaveTryon** [comment]
@ferBonnin, this has been merged into master and should soon be present in canary releases of both AIWeb and the unified client. Please regress at your convenience.

**Comment by ferBonnin** [comment]
validated in unified and web canary. looks good.
