### ISSUE TITLE
Electron app should have 6-digit placeholder

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2045]
## Describe the bug

Instead of 12345, show 123456

**Comment by dbjorge** [comment]
@LiLoDavis I'm assuming you mean in the device connection dialog's port number field, right? Can you help me understand why you would prefer to see 6 digits? In general, port numbers can only range from 0-65535, so I would expect that a 5 digit number is an appropriate choice of placeholder.
