### ISSUE TITLE
Electron app "Rescan" button --> "Start over"

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2052]
## Describe the bug

In electron app, change "Rescan" button to "Start over" (for better consistency with web tool terms).

**Comment by ferBonnin** [comment]
per conversation with Peter, sounds good to change.

**Comment by ferBonnin** [comment]
Hi @LiLoDavis this change should be in canary now, could you let us know if this is fixed for you?

**Comment by LiLoDavis** [comment]
Yes, it's fixed.
