### ISSUE TITLE
Access to the Info and Examples

### ISSUE THREAD

**Issue by kjmears** [microsoft/accessibility-insights-web#2057]
I find the info and examples really useful. Would it be possible to have them as a standalone reference site. I think it would be really useful to share with developers and others in our organisation who need to have the errors explained and learn about the next steps to solve them.

Thanks for an awesome tool btw.

**Comment by ferBonnin** [comment]
Hi @kjmears thanks for the feature request! 
We are glad you find the info & examples useful. 

Apart from making them available as a standalone reference, another feature request that has been mentioned before for sharing the info & examples is adding them to the downloaded report.


We will leave this feature request open to monitor for upvotes from the community.

**Comment by jenniaynlynn** [comment]
I agree with this 100%!  The test steps and info are so useful and easy to understand.  I'd love to have easy access to these as a comprehensive piece to share with people learning accessibility and growing in their practice.

**Comment by mhulse** [comment]
Just found this: https://accessibilityinsights.io/info-examples/

**Comment by mhulse** [comment]
Just to update this thread, it looks like https://accessibilityinsights.io/info-examples/ is different than the info found in the plugin. **I'd really love to share links to the most up-to-date info and examples from the plugin.**

**Comment by ferBonnin** [comment]
Hi @mhulse could you please tell us more about this? Where possible, the info-examples in Accessibility Insights for Web point to the link you added above:

<img width="958" alt="screenshot of Accessibility Insights automated checks, hovering over the more info about this rule link. the preview link shows it points to accessibilityinsights.io" src="https://user-images.githubusercontent.com/9062104/152428919-c07cf603-8656-41ef-bc53-f9c6e0f33eab.png">

**Comment by mhulse** [comment]
> Hi @mhulse could you please tell us more about this? Where possible, the info-examples in Accessibility Insights for Web point to the link you added above:

Hi @ferBonnin, thanks for the reply.

Sorry if this wasn't clear in my original/last reply. Accessibility Insights for Web plugin doesn't actually point to https://accessibilityinsights.io/info-examples/. Sorry if I caused any confusion.

When I first found the above website, at first glance, I thought it was a web-published version of the info and examples found in the Accessibility Insights for Web plugin:

https://accessibilityinsights.io/info-examples/web/

When I was looking at the above examples again today, I realized the headings are different and I was not able to find examples like "Keyboard Navigation":

<img width="1678" alt="Screen Shot 2022-02-03 at 2 05 03 PM" src="https://user-images.githubusercontent.com/218624/152437172-7add636e-52aa-44f0-b048-0e0a9dd11302.png">

Unless I'm mistaken, the content found at https://accessibilityinsights.io/info-examples/web/ is not the same exact content as found in the Accessibility Insights for Web plugin. :(

**Comment by ferBonnin** [comment]
Hi @mhulse got it! this is accurate. Right now, the information we have at [Info & Examples in the Accessibility Insights website](https://accessibilityinsights.io/info-examples/web/ ) is for automated checks only. The information in the requirements in assessment is only available in the product at the moment.

**Comment by mhulse** [comment]
Thanks for the update/reply/help @ferBonnin, I really appreciate it!

**Comment by DaveTryon** [comment]
Plan: Add an entry to the web FAQ that points to the info and examples on accessibility-insights.io

**Comment by DaveTryon** [comment]
This was released on 8/22
