### ISSUE TITLE
Pinned taskbar shortcuts for unified electron client are removed on Windows during updates

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#2059]
## Describe the bug

On Windows: If a user has pinned the unified product to their taskbar, the pin is removed when the unified product gets an update. This is a known issue in electron-builder: https://github.com/electron-userland/electron-builder/issues/2514

The linked issue includes potential workarounds:
- [this](https://github.com/electron-userland/electron-builder/issues/2514) workaround doesn't unpin the icon, but the icon is lost and becomes a white rectangle
- this [workaround](https://github.com/electron-userland/electron-builder/issues/2514#issuecomment-476660017) is intrusive (always pin)

**To Reproduce**

1. Install the application
2. Pin the app to the taskbar
3. Run a new installer
4. Notice the pinned icon is removed

## Context (please complete the following information)

- OS Name & Version: Windows 1909
- electron-builder version: 22.2.0

**Comment by pashvin** [comment]
Any update on this issue?

**Comment by ferBonnin** [comment]
@madalynrose could you please check if this bug is still reproing?

**Comment by DaveTryon** [comment]
We won't be fixing this
