### ISSUE TITLE
Unified: app icon is not set in linux AppImage

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2097]
The strategy we implemented last week for using separate insider/canary/production app icons (omitting `icon` from our `new BrowserWindow` options and instead allowing it to defer to the icons set in the `electron-builder` config) doesn't work as expected with the linux AppImage (see https://github.com/electron-userland/electron-builder/issues/3599, https://github.com/electron-userland/electron-builder/issues/2269, https://github.com/electron-userland/electron-builder/issues/748).

It looks like the only actionable suggestion in those threads for us it to add the `icon` option back and use a runtime config to set it to the channel-appropriate icon.

(found during 2020.204.2 release validation)

**Comment by karanbirsingh** [comment]
linked PR #2113
