### ISSUE TITLE
Can the HTML results reporter be imported as a library and used individually ?

### ISSUE THREAD

**Issue by mohanraj-r** [microsoft/accessibility-insights-web#2123]
I use axe-core. I really like the HTML results report produced by this extension. Would it be possible to import and use just the results formatter as a library separate from the extension along with axe-core?

**Comment by smoralesd** [comment]
Hi @mohanraj-r thanks for your feature request and your interest on **Accessibility Insights for Web**.

I'm not 100% sure what you mean by _...import and use just the **results formatter**..._ but we are publishing [accessibility-insights-report](https://www.npmjs.com/package/accessibility-insights-report), which allows you to: _"Publish axe-core accessibility scan results as self-contained HTML files in the same format as accessibility-insights-web."_

Is this what you have in mind?

**Comment by mohanraj-r** [comment]
Thanks @smoralesd 
Looks like accessibility-insights-report could be the answer to what I am looking for. 
Might be good to document this - because I wasn't aware that this was being published from this repo to npm. Guess this can be closed for now.

**Comment by adarshrema** [comment]
Hello @mohanraj-r, marking this as resolved. Please go ahead and close this. Thank you!
