### ISSUE TITLE
Electron app main window always opens full-screen

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2147]
## Describe the bug
The primary window always opens full screen, and the window's **Restore down** button always shrinks it to a small, fixed size. As a consequence, getting the app window to the preferred size is a two-step process.  

**To Reproduce**
1. Launch the app.
2. Start testing.
3. Use the **Restore down** button.

## Expected behavior
The primary window should open to its most recent size and position.

## Context (please complete the following information)
Accessibility Insights for XXXXXXX - Canary
2020.211.7
2/11/2020

## Are you willing to submit a PR?
No

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, let's take a look at this

**Comment by lisli1** [comment]
Started working on this here: https://github.com/microsoft/accessibility-insights-web/pull/2584

Need to update to use IpcRendererShim and also save the most recent position of the window, as mentioned in Dave's comment on the above PR.

**Comment by DaveTryon** [comment]
@LiLoDavis, This fix is now live in the Canary build. Please regress at your convenience. Thanks!

**Comment by LiLoDavis** [comment]
Looks great!
