### ISSUE TITLE
Update README to include information of unified tool

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#2207]
## Describe the bug

Bug to track the need to update the README file **after 3/10**

**Comment by peterdur** [comment]
Some notes:

I expect we’d shift to a smaller root README (probably moving the existing building/more info/testing sections into something like docs/building-for-web.md and creating a parallel docs/building-for-android.md).

We’d also want to update the “Working with the Electron app” in docs/workflow.md to reflect use of the AI for Android Service.

**Comment by ferBonnin** [comment]
looks great!
