### ISSUE TITLE
Unified: disabling visual helper toggle causes scroll bars to overflow off bottom of screen

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2243]
## Describe the bug

Disabling the visual helper toggle in unified somehow causes the automated checks view container to increase in height such you can't scroll to the very bottom of either of the two panels:

![animation showing scroll bar bottoms disappearing as you toggle visual helper off](https://user-images.githubusercontent.com/376284/75403351-54eaee80-58bc-11ea-9758-7b44ab2898b0.gif)

## Context (please complete the following information)

- OS Name & Version: Windows 10
- AI Version & Environment: Unified dev aab472c7f06f33dfeab6df93c5f730a087023c4c

**Comment by ferBonnin** [comment]
Per conversation with Peter, we should fix this. Is not a blocking bug.
