### ISSUE TITLE
Requirement 3.2 "Revealing content" should not apply to non-sequential content?

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2254]
## Describe the bug

Web requirement 3.2 currently reads:

> ### Revealing content
> #### How to test
> 1. Examine the target page to identify any "trigger" components that reveal hidden content, such as menus, dialogs, expandable tree views, etc.
> 1. Use the keyboard to activate each trigger component.
> 1. Verify that focus is moved into the revealed content. (It is acceptable to Tab once or use an arrow key to move focus into the revealed content.)

We think this might be a little too broad; [SC 2.4.3](https://www.w3.org/WAI/WCAG21/Understanding/focus-order) / [F85](https://www.w3.org/WAI/WCAG21/Techniques/failures/F85) that this requirement is based on only demand that focus be ordered in *some* reasonable sequential order, and specifically note that complex widgets may exist for which there is not a *single* sequential order that makes sense (expandable tree views, for example).

For example, consider an accordion design pattern with an expand/collapse all button above all section headings, where both the "expand/collapse all" button and the individual section heading buttons would reveal hidden content (eg, AI4Web's cards view). This requirement as-written would demand that focus order move directly from both the expand/collapse all button *and* the first section heading to the first section's expanded content, but this would probably be a *violation* of SC 2.4.3, since it would force a focus order that is non-sequential.

**Comment by ferBonnin** [comment]
@LiLoDavis could you please review this is issue and let us know what you think?

**Comment by LiLoDavis** [comment]
> For example, consider an accordion design pattern with an expand/collapse all button above all section headings, where both the "expand/collapse all" button and the individual section heading buttons would reveal hidden content (eg, AI4Web's cards view). This requirement as-written would demand that focus order move directly from both the expand/collapse all button _and_ the first section heading to the first section's expanded content, but this would probably be a _violation_ of SC 2.4.3, since it would force a focus order that is non-sequential.

I don't see how this would violate 2.4.3, because that S.C. doesn't require a sequential focus order. Rather, it requires that focus order preserve meaning and operability. 

However, in this case I think it would make sense to move focus into the first section heading; otherwise, an assistive technology user would miss important introductory content.

In the electron app, I see that activating **Expand all** does not move focus at all. You have to tab three times to get to the revealed content. A better experience would be to move focus automatically to the first heading and then tab once to the first card.

**Comment by ferBonnin** [comment]
per conversation with Lisa Louise, let's modify step one to:

1. Examine the target page to identify any "trigger" components (typically buttons or links) that reveal hidden menus or dialogs.

**Comment by ferBonnin** [comment]
per conversation with Peter, sounds good :)

**Comment by dbjorge** [comment]
Resolved in master, should hit canary in 10-15 minutes. @LiLoDavis or @ferBonnin , can you double check the text change and close?

**Comment by ferBonnin** [comment]
verified in Canary
