### ISSUE TITLE
Settings panel styling regression since 2.14.1

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2256]
## Describe the bug

It looks like some of the styling for the Settings panel has regressed since 2.14.1 (presumably as part of extracting the Settings panel for use with unified in feat(android-settings).

2.14.1 on left, canary on right:

![screenshot of prod/canary side by side](https://user-images.githubusercontent.com/376284/75594493-c605df80-5a3d-11ea-9431-d17acf0ccf5a.png)

On canary, note:
* The "close" button is larger
* The Settings header text has different margins/font size

**To Reproduce**

1. Build web from master
2. Install production web extension
3. Open the "settings" panel of each side-by-side
4. Compare visually

## Context (please complete the following information)

- OS Name & Version: Windows 10
- AI-Web Version & Environment: not present in 2.14.1 vs present in c82ed0c
- Browser Version: new Edge stable
- Target Page: any

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

yes

**Comment by smoralesd** [comment]
Info & Examples panel seems to have the same some of the same issues as the other panels, specifically, the position of the close button

![image](https://user-images.githubusercontent.com/2837582/76254904-762bd300-620a-11ea-9bce-05b4e42a0c49.png)

**Comment by ferBonnin** [comment]
* there is inconsistency in the different sizes for the panel. they should all be the same
* the new size of the settings panel per #2307  is too small / hard to read

**Comment by dbjorge** [comment]
@smoralesd The info and examples panel having its close "x" above the initial header isn't part of the same regression this bug tracks, but I agree it doesn't look very good; it would be nice for us to improve it, but I think it should be a separate bug. I'll go file one.

@ferBonnin 
* Do you mean "between the info & examples panels and the other panels"? That difference is intentional, since info & examples uses 2-column tables that won't fit in the smaller size. If you mean a different set of panels, can you be more specific about which ones?
* The new size of the settings panel is the office fabric default and was used at @ichelsea 's request. If you want to use something besides the office fabric default, please discuss/create a mockup with @ichelsea and pick a specific pixel width for the size.

(setting to "needs more info" pending those responses)

**Comment by ferBonnin** [comment]
@dbjorge 
- Yes, I meant the info & examples panel but per offline conversation I agree that the panel has sufficient distinct purpose and layout, plus the fact that it has columns that its ok to not have the same size of the other panels
- I'll review this with Jim. Per offline conversation, the text in the settings panel now looks cramped so might be good to explore ways to improve this.

**Comment by ferBonnin** [comment]
reviewed with @peterdur, closing since looks ok
