### ISSUE TITLE
Electron app > How to fix - Text should not break in the middle of a word.

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2265]
## Describe the bug

The **How to fix** content should break _between_ words, not _within_ words.

**To Reproduce**

1. Run automated checks
2. Expand results
3. Resize window

Text breaks in the middle of a word. For example, on my screen it currently looks like this:
> The image has no alternate text and is not identifi
> ed as decorative. If the image conveys meaningful 
> content, provide alternate text using the contentD
> escription attribute. If the image is decorative, giv
> e it an empty contentDescription, or set its isImp
> ortantForAccessibility attribute to false.

## Expected behavior

Should break between words, something like this:

> The image has no alternate text and is not identified 
> as decorative. If the image conveys meaningful 
> content, provide alternate text using the 
> contentDescription attribute. If the image is 
> decorative, give it an empty contentDescription, or 
> set its isImportantForAccessibility attribute to false.

**Comment by dbjorge** [comment]
This probably implies we're using `word-break: break-all;` in a place where we should instead be using `overflow-wrap: break-word;` (the latter will only break a word apart if strictly necessary to avoid overflowing the container)

**Comment by ferBonnin** [comment]
validated in canary. looks good
