### ISSUE TITLE
"High contrast mode" requirement has outdated "How to test" text

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2266]
## Describe the bug

The "How to test" section for Test 17 (Text legibility) Requirement 1 (High contrast mode) reads:

> Google Chrome and Microsoft Edge Insider do not support Windows' high contrast mode.
> 1. Open the target page in Microsoft Edge.
> 1. Use Windows Settings > Ease of Access > Color & high contrast to apply a high contrast theme.
> 1. Verify that the target page adopts the colors specified for the theme.
> 1. Record your results:
>     a. If you find any failures, select Fail, then add them as failure instances.
>     b. Otherwise, select Pass.

This text has a few inaccuracies:
* Still calls new Edge `Microsoft Edge Insider`
* It's no longer correct that new Edge doesn't support Windows HC mode (new Edge stable supports it now)
* The suggested path to get to the system HC settings is outdated (the updated menu path is `Settings > Ease of Access > High contrast`, Color was separated to a separate settings submenu)

## Context (please complete the following information)

- OS Name & Version: Windows 10 1903 (OS Build 18362.657)
- AI-Web Version & Environment: Version 2020.3.2.1713 Canary
- Browser Version: new Edge stable 80.0.361.62
- Target Page: any

**Comment by ferBonnin** [comment]
@LiLoDavis suggestion for the text change:

Google Chrome doesn't support Windows' high contrast mode. 
1. Open the target page in Microsoft Edge or the new Microsoft Edge.
2. Use **Windows Settings** > **Ease of Access** > **High contrast** to apply a high contrast theme.

(rest is the same).

Thoughts?

**Comment by LiLoDavis** [comment]
Appears to be accurate, but "Microsoft Edge or the new Microsoft Edge" is odd, sounds a bit like a typo. How about this: "Open the target page in the new Microsoft Edge or Microsoft Edge Legacy."
Here's a [reference](https://support.microsoft.com/en-us/help/4533505).

**Comment by dbjorge** [comment]
All set! @LiLoDavis / @ferBonnin can you verify the text changes (after waiting long enough for #2293 to hit canary)

**Comment by ferBonnin** [comment]
validated in canary  2020.3.5.1713 looks good :)
