### ISSUE TITLE
telemetry dialog has invalid aria attribute

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#2316]
## Describe the bug

The telemetry dialog renders with role='alertdialog' and an invalid aria-attribute. This leads to an accessibility error as well as non-ideal NVDA behavior. ~Refactoring the component to use the 'BlockingDialog' component [here](https://github.com/microsoft/accessibility-insights-web/blob/master/src/common/components/blocking-dialog.tsx) would remove the error and improve NVDA behavior (see [blocking dialog](https://github.com/microsoft/accessibility-insights-web/blob/master/src/common/components/blocking-dialog.tsx) for detailed comment).~ Looks like the comment states a previous attempt to use this in telemetry-permission-dialog led to focus issues.

We manually override the title attribute to ' telemetry-permission-title' - adding 'titleAriaId' to modalProps may resolve the invalid aria attribute error.

**To Reproduce**

1. Reinstall Accessibility Insights for Web or unified product
2. Open product to see telemetry dialog
3. Run accessibility check via self-validator

## Expected behavior

No issues

## Context (please complete the following information)

- OS Name & Version: Windows 1909
- AI-Web Version & Environment: 2.14.1
- Browser Version: Version 80.0.3987.132 (Official Build) (64-bit)
- Target Page: any

**Comment by ferBonnin** [comment]
Took a look at this issue, looks like the aria-labelledby attribute being used doesn't exist. recommend changing it to a valid id

**Comment by karanbirsingh** [comment]
The aria-attribute fix is now in canary for both products. I am closing the issue. I don't believe the alertdialog NVDA portion originally filed is relevant for the telemetry dialog since it's the first thing in the application, so NVDA provides additional context. I'll consider a separate issue or PR for the device disconnected dialog, where the alertdialog role leads to less helpful info from NVDA when the dialog is created. cc @ferBonnin
