### ISSUE TITLE
SettingsPanelOpen telemetry event missing in Unified

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#2320]
## Describe the bug

In the electron app, the last SettingsPanelOpen event before turning off telemetry is consistently not fired.

**To Reproduce**

1. Open Accessibility Insights for Android with telemetry enabled
2. Connect a device, enter the port number, and start scanning
3. Toggle the settings menu open and closed a few times
4. Open the settings menu and turn telemetry off
5. Observe the stream of telemetry events generated

## Expected behavior

After the ScanCompleted event, we should see a stream of alternating SettingsPanelOpen and SettingsPanelClosed events, ending with SettingsPanelOpen. Instead, the last SettingsPanelOpen event is not recorded.

## Context (please complete the following information)

- OS Name & Version: Windows 10 version 1909 Build 18363.657
- AI-Unified Version & Environment: Insider 2020.306.3

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, worth investigating but we recall a conversation where we agreed that if the user selects telemetry OFF we stop sending telemetry even if there is pending events.
If that is what is happening here, we agree with keeping that approach even if we miss this event.

**Comment by RobGallo** [comment]
I have confirmed the timing of the code in AI-Web which disables telemetry is working as expected -- if you force the code which writes telemetry to the console to obey the enabled/disabled setting, you will see the expected pattern of open/close settings panel messages as described above. And the console telemetry is handled with the same exact code as all other telemetry.
