### ISSUE TITLE
Info & Examples panel close button is misaligned

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#2380]
## Describe the bug

(split out from [this comment](https://github.com/microsoft/accessibility-insights-web/issues/2256#issuecomment-596767677) in #2256)

The "close" button in our Info & Examples panels renders up above the title for the panel, inconsistent with the standard fabric layout our other panels use. It should ideally be laid out more similarly to the other panels (vertically aligned with the panel header).

**To Reproduce**

1. Start an assessment in web
2. Select any test/requirement
3. Select "info & examples"
4. Observe panel layout:

![image](https://user-images.githubusercontent.com/376284/77356277-38977180-6d03-11ea-908e-fbf7d925db37.png)

## Expected behavior

Close button and panel title should be at same vertical alignment

## Context (please complete the following information)

- OS Name & Version: Windows 10 1903 18362.720
- AI-Web Version & Environment: Canary Version 2020.3.20.1613
- Browser Version: Edge stable Version 80.0.361.69
- Target Page: irrelevant

**Comment by ferBonnin** [comment]
per conversation with Peter, makes sense to pick up

**Comment by dbjorge** [comment]
Didn't end up completing this before next feature started, so moving back to ready for work. The bits of work I had in progress are at https://github.com/dbjorge/accessibility-insights-web/tree/content-panel-header

**Comment by jalkire** [comment]
Fix merged in PR #2572

**Comment by dbjorge** [comment]
Confirmed
