### ISSUE TITLE
Text change in Contrast > State changes > How to test

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2406]
## Describe the bug

Immediately after **How to test**, insert the following clarification:

_Note: Contrast requirements for text within a UI component or graphic are covered in **Automated checks** and **Text legibility**._

**Comment by smoralesd** [comment]
Hi @LiLoDavis is this the right place?
![image](https://user-images.githubusercontent.com/2837582/77804773-90a0e180-703d-11ea-9e31-c158b929aaf4.png)

**Comment by LiLoDavis** [comment]
Yes, perfect.

**Comment by dbjorge** [comment]
Text should be available to validate in Insiders build 2.16.0!

**Comment by LiLoDavis** [comment]
Looks good.
