### ISSUE TITLE
Automated checks automatically selected after start over assessment

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#2418]
## Describe the bug

After the user selects **start over assessment**, automated checks gets selected.

**To Reproduce**

1. navigate to any website
1. start a new assessment
1. select any test but automated checks (neither overview), e.g. Keyboard
1. use the start over assessment option
1. Observe: the selected test gets updated from what the user selected before and now the automated checks is selected

## CodePen repro example

N/A

## Expected behavior

Not sure what the expected behavior should be here but I do see a couple of options:
1. The selected test is left unchanged
1. The selection is update to **Overview**

## Screenshots

![01 - automated checks automatically selected after start over](https://user-images.githubusercontent.com/2837582/77967444-fd181c80-7299-11ea-9912-d7bde3f6cbec.gif)

## Context (please complete the following information)

- OS Name & Version: Windows Version 10.0.18363 Build 18363
- AI-Web Version & Environment: Prod 2.15.0 & Insider 2.16.0
- Browser Version: Google Chrome  80.0.3987.149 (Official Build) (64-bit)
- Target Page: N/A

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

N/A

**Comment by ferBonnin** [comment]
Per conversation with Peter, let's fix this

**Comment by ferBonnin** [comment]
Validated with Canary 2020.4.27.1939
