### ISSUE TITLE
Showing insights for non-existing views - React native screen

### ISSUE THREAD

**Issue by SwathyMothilal** [microsoft/accessibility-insights-web#2428]
The tool is displaying suggestions for "android.widget.Button" which are not existing in the react-native page.

When tapped on the suggestions, the visual helper highlights a portion near the bottom strip of the device. [home, back button]

<img width="450" alt="Screenshot 2020-04-01 at 4 05 40 PM" src="https://user-images.githubusercontent.com/20316658/78127965-bc9fd680-7432-11ea-81d8-f44c475443ee.png">

**Comment by ferBonnin** [comment]
Hey @SwathyMothilal can you give us a bit more detail to reproduce this bug?

**Comment by SwathyMothilal** [comment]
Hi @ferBonnin, we have designed a reach native screen in our hybrid-app[it has both native and react implementation]. And, when I was scanning the app with the insights tool, I was getting insights for the bottom strip as shown in the image above.[home, back button].

**Comment by ferBonnin** [comment]
@SwathyMothilal this might be related to #1966 
Please help us investigate if this is the same issue or a different one.

- Can you try to scroll down in the application, scan again and check if you get visualizations on the home button again?
- Can you share the failure instances (should have at least the _class name_ and the _how to fix information_ but might also include additional information like _text_) that are associated with that visualization?

Thanks!
