### ISSUE TITLE
Wait for injected scripts to load before start scanning

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#2505]
## Describe the bug
We identified this issue when scanning in teams page with iframes.
axe waits for 500 ms for iframe to respond back for axe.ping.
The injected.bundle.js script gets injected when the user scans first time after page load. (Subsequent injections would be no-op, since the file is already injected)
So, we may need to make sure that the injected script is loaded before calling axe.run on the root window.
Subsequent scans work fine since the script is already injected.

To test this theory, I was able to scan successfully when i added wait after injection in [injection-controller](https://github.com/microsoft/accessibility-insights-web/blob/3459929849613cd7403afd8b568594a99a950361/src/background/injector-controller.ts#L63).
```
 this.injector.injectScripts(tabId).then(() => {
                setTimeout(() => {
                    this.interpreter.interpret({
                        messageType: Messages.Visualizations.State.InjectionCompleted,
                        tabId: tabId,
                    });
                }, 1000);
            });
```
(Instead of wait, one other solution could be that, root window sets some store state after all iframes are able to communicate with a slightly longer timeout value & then we start scanning, or we need to make sure axe.ping &  our [ping message](https://github.com/microsoft/accessibility-insights-web/blob/3459929849613cd7403afd8b568594a99a950361/src/injected/frameCommunicators/frame-communicator.ts#L124) has a higher wait time)

When this issue happens, the user might see the below error message from axe:

```
injected.bundle.js:36 Uncaught Error: Expect axe._selectorData to be set up
    at rt (injected.bundle.js:36)
    at Object.e [as getSelector] (injected.bundle.js:36)
    at injected.bundle.js:36
    at injected.bundle.js:36
    at injected.bundle.js:36

```
since the iframe may respond after root window completes the scan & sets _selectorData = null on cleanup.

**To Reproduce**
I don't have a repro page for this to share since i was able to only repro this only on an internal extension for teams.

## Context (please complete the following information)

- OS Name & Version: Windows 10 Build 18362.778
- AI-Web Version & Environment:  2.16.0 Prod
- Browser Version:  Google Chrome Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets take a look at this.

**Comment by ferBonnin** [comment]
Per conversation with Peter, marking this as out of scope since there isn't any feedback around this issue and no-one has taken a look
