### ISSUE TITLE
AI Android: High Contrast hover state color not changing for certain components

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#2545]
## Describe the bug
For certain buttons, such as "Start Over" the color of the component is not changing to blue when the user hovers over. 

**To Reproduce**

1. Go to the Insider build of Accessibility Insights for Android desktop application
2. Connect to a port (either through an emulator or through using mock of the Android service)
3. Hover over the "Start over" icon at the top of the automated checks view

## Expected behavior

You expect for the "Start over" button to turn blue to adhere to UX standards for High Contrast hover behavior

Example: "Export result" appears blue in hover and white in the default state
![image](https://user-images.githubusercontent.com/19158512/80157312-bc4eb300-857a-11ea-96a3-d65f941567e6.png)

![image](https://user-images.githubusercontent.com/19158512/80157295-b22cb480-857a-11ea-849c-b444126d6d33.png)

## Screenshots

"Start over" appears white in all states
![image](https://user-images.githubusercontent.com/19158512/80157269-a4772f00-857a-11ea-9d65-00ebbaa9efec.png)

## Context (please complete the following information)

- OS Name & Version: 
- AI-Web Version & Environment:  Accessibility Insights for Android 2020.422.21
- Browser Version: 
- Target Page:

**Comment by ferBonnin** [comment]
Per conversation with Peter, let's fix this.
