### ISSUE TITLE
Android client has scrollbar on view when it shouldn't (and can scroll away from title bar)

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#2590]
## Describe the bug

There seems to be a scroll bar on the entire application when it is not necessary. It seems to occur when the window is re-sized manually and there is a scroll bar on the results portion.

**To Reproduce**

1. Scan an app with many errors (I used our mock app).
2. Expand all errors.
3. Re-size such that you need a scroll bar on the results/cards portion.
4. You should see a scroll bar on the far right that scrolls the entire app a bit; should not be there.

## Expected behavior

There should be no scrollbar in that scenario.

## Screenshots

Here's a gif:
![resizemacelectronbug](https://user-images.githubusercontent.com/32555133/80744956-5317f400-8ad4-11ea-9ebe-131baad87a7e.gif)

## Context (please complete the following information)

- OS Name & Version: macOS Catalina 10.15.2 (edit: also repros on Windows 10 1909)
- AI Android: master as of 89366eeb4af17c39ba73602659f680edf6169672

## Are you willing to submit a PR?

n/a

**Comment by dbjorge** [comment]
Not mac-specific, I repro on windows as well in current master:

![screenshot of same issue in windows](https://user-images.githubusercontent.com/376284/80767612-21675300-8afd-11ea-8867-aa92ff08c15e.png)

Updating title/description accordingly.

Seems feasible that the electron 8 update could have brought this with it; we've seen very similar issues in web before with chromium updates.

**Comment by karanbirsingh** [comment]
@waabid @ferBonnin this has been resolved :)

**Comment by ferBonnin** [comment]
@waabid can you please validate and close?
