### ISSUE TITLE
accessibility-insights-report: reporterFactory require singleton creation to eliminate Office Fabric warnings

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-web#2597]
### Source
https://github.com/microsoft/accessibility-insights-web/blob/4bf47d142ba07b83c8c727a64ad24abca70d9f39/src/reports/package/reporter-factory.ts#L89

### Issue
The officeFabric cannot be instantiated multiple times b/c it breaks Office Fabric logic. As result console will have the following messages multiple times:

`Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include:
add, back, calculatorAddition, cancel, cat, checkBox, checkMark, chevronDown, chevronDownMed, chevronRight (+ 190 more)`

**Note:** The source of the message is not obvious and confusing for the package consumer and require research before making a fix even it is a simple fix.

The option to suppress Office Fabric warnings does not help since it require submodule import and that result compile error:

`import { setIconOptions } from '@uifabric/styling/lib/utilities/icons';
setIconOptions({ disableWarnings: true });`

`../../node_modules/@uifabric/styling/lib/utilities/icons.d.ts:5:33 - error TS2503: Cannot find namespace 'JSX'.
5         [key: string]: string | JSX.Element;`

Hence the option left to the package consumer is to create singleton for reporterFactory.

### Fix
Either
1) Suppress Office Warning messages in a package or  
2) Create and expose singleton for reporterFactory
3) ...

**Comment by ferBonnin** [comment]
triagged with @peterdur, this has been open and not resolve for 2 years, closing
