### ISSUE TITLE
Rename "Text legibility" category

### ISSUE THREAD

**Issue by patrickhlauke** [microsoft/accessibility-insights-web#2655]
## Is your feature request related to a problem? Please describe.
The current category name of "Text legibility" does not sufficiently/accurately convey what some of the tests/SCs are about.

High Contrast Mode, Orientation, Reflow (see https://github.com/microsoft/accessibility-insights-web/pull/2654) and Hover / focus content are not solely about text, but content in general.

Having these grouped under "text legibility" may lead auditors to the false impression that any problems under those tests relating to non-text content are ok/not applicable.

## Describe the desired outcome
Ideally, find a more suitable category name (and generalise the high-level description). Perhaps something like "Page adaptability", "Content adaptability" or similar. However, this admittedly makes "Contrast" and "Hover / focus content" stand out again/doesn't quite make them fit.

The Contrast test could logically be moved into the "Contrast" category.

"Hover / focus content" could potentially be placed under "Custom widgets"

**Comment by ferBonnin** [comment]
Thanks for the suggestion @patrickhlauke!

@LiLoDavis thoughts for changing the title of the test?
Changing requirements from one test to another is not trivial work (specially considering what happens for users that have an assessment in progress) but we could change the test title to something that is more comprehensive

**Comment by patrickhlauke** [comment]
if they were all to still stay within the same category, maybe (though a bit ugly) renaming to a combined "Content adaptability / text legibility"? hover/focus would still feel like the odd one out though to an extent...

**Comment by LiLoDavis** [comment]
We'll need the test name to be short. At this time, the longest test name is **Automated checks**. 
How about **Viewable content**?

**Comment by patrickhlauke** [comment]
> Changing requirements from one test to another is not trivial work

Going forward though, I think that would be the preferred option...but understand that it's quite a breaking change.

> We'll need the test name to be short. At this time, the longest test name is Automated checks.
How about Viewable content?

Doesn't completely capture some of the nuance (e.g. could argue that for "orientation", stuff is still "viewable", just that you potentially are forced to tilt your head on your hard-mounted device to see it properly), but as I can't come up with anything more suitable (closest I had was "Adaptable / viewable" but that still doesn't fit the current layout/length), I guess I could live with that for the time being.

(it does still feel odd at a very high level that text contrast would not be under contrast though...but maybe the more fundamental reshuffling of categories is something that could be considered for a future version)

**Comment by ferBonnin** [comment]
Perfect, just to summarize, this requires to change the Test title from "Text Legibility" to "Viewable Content"

**Comment by LiLoDavis** [comment]
> Perfect, just to summarize, this requires to change the Test title from "Text Legibility" to "Viewable Content"

I believe that's correct.

**Comment by ferBonnin** [comment]
after reviewing this with the board, the suggestion was to use "Adaptable content".

**Comment by patrickhlauke** [comment]
guessing that moving text contrast to the contrast category would still be too big a change though, right?

**Comment by ferBonnin** [comment]
> guessing that moving text contrast to the contrast category would still be too big a change though, right?
yes; doing this correctly, to not break any users that have an in progress assessment, is something complex. It is in our radar but we need to weight this effort against other possible features.

**Comment by ferBonnin** [comment]
Hi @patrickhlauke this issue is now fixed in our [Canary ](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem) extension

**Comment by patrickhlauke** [comment]
Just tried the canary extension ... looking good! The "Getting started" explanation for 17 Adaptable content could probably do with a slight rewrite, but I'll suggest something in a separate issue/PR. And yes, still holding out hope that in the far future, 17.3 Contrast will be moved to 24 Contrast :)

Long story short: perfect, thank you.
