### ISSUE TITLE
Add a screenshot in the Web Automated checks report

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#2770]
## Is your feature request related to a problem? Please describe.
It will make easier to visualize the elements that have a failure if we had a screenshot of the app or page scanned with the failures highlighted

## Describe the desired outcome
Add a screenshot in the exported report of Automated check failures. 

## Describe alternatives you've considered

taking a screenshot and saving it along the report

## Additional context
This was feedback requested by users during user interviews.

**Comment by DaveTryon** [comment]
As called out at https://github.com/microsoft/accessibility-insights-web#notice, we will not be making further investments in the Android scanning solution. I've updated the title accordingly

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
