### ISSUE TITLE
Text change - Issue filing > labels for URLs 

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2784]
In Accessibility Insights for Android, modify two labels under **Settings** > **Issue filing**

1. Change **Enter desired GitHub issues link:** to **Enter your GitHub issues URL**
2. Change **Enter the desired Azure Boards project link:** to **Enter your Azure Boards project URL** 

No colon (:) is needed after the label.

**Comment by ferBonnin** [comment]
This issue is now resolved in our [Canary](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem) extension

**Comment by LiLoDavis** [comment]
I filed this issue against the **android** tool, which has not yet been updated. I see, however, that the **web** tool has been updated, which is good because it has the same wording.

Also, under **Azure Boards**, I recommend changing **File issue details in:** to **Select a field for issue details** (no colon). That way, both instructions under **Azure Boards** are addressed to the user. (Currently the first instruction says what the user should do, while the second says what the system should do.)

**Comment by LiLoDavis** [comment]
I see the fix is in for android now. I'll file a separate bug for changing the second field name under Azure Boards.
