### ISSUE TITLE
Error when switching off the "reflow-ui" flag in the getting-started page

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [microsoft/accessibility-insights-web#2837]
## Describe the bug
An exception is thrown when you switch off the "reflow-ui" feature flag while you are in the getting-started page.

**To Reproduce**

1. Go to any assessment.
2. enable the "reflow-ui" feature flag
3. got to the "Getting Started" page
4. Diable the "reflow-ui" feature flag.
5. App crash.

## Expected behavior
App shouldn't crash.

## Screenshots
![flag swithcing issue](https://user-images.githubusercontent.com/45858632/84220012-ae9bb100-aa86-11ea-8068-01e3c7edfeae.gif)

## Context (please complete the following information)
- AI-Web Version & Environment: Canary
- Browser Version: any
- Target Page: any

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
No

**Comment by AhmedAbdoOrtiga** [comment]
I think the issue is while rendering the "getting-started", we assume that a test step is selected and we still check if  that test step was already scanned before but that won't work in the new ui because there's no step info, it works fine without the flag enabled because the getting-started page is in the same view as the step.

**Comment by ferBonnin** [comment]
per conversation with Peter, there is no user impact to this and we will remove the feature flag in a couple of weeks; reading at the comments, we have investigated and we understand what is causing this, it should go away once we remove the feature flag so not need to invest this. (if we were to make this view a public feature flag, then we should fix this issue, but we don't have plans to do that)
