### ISSUE TITLE
["File Issue"] Taking me to DevOps with "Issue" as the work item type.  Maybe because I'm also signed into GitHub?

### ISSUE THREAD

**Issue by chadsowald** [microsoft/accessibility-insights-web#2920]
## Describe the bug

Hi.  I use both GitHub and DevOps for different projects, but am typically signed into both.  I recently started running FastPasses on one of my projects (the one in DevOps).  When it finds issues, I click the "File issue" button.  I've already configured the extension with my DevOps project.  The extension correctly takes me to DevOps with the work item description filled in correctly.  However, the work item type is Issue, not Bug!  

I suspect this is because I'm also signed into GitHub and the extension doesn't do enough (or the right) checks to determine it should use the "Bug" work item type since I'm landing in DevOps.

Per this page, DevOps should always result in a Bug and GitHub should always result in an Issue:
https://accessibilityinsights.io/docs/en/web/getstarted/issuefiling#file-an-issue
![image](https://user-images.githubusercontent.com/165767/85064411-63596080-b160-11ea-915e-c60a3e229915.png)

**To Reproduce**

1. Be signed into both GitHub and DevOps.
1. Install the extension (I'm using the latest Edge)
1. Configure it for DevOps
1. Use FastPast to find an Issue.
1. Click "File Issue"

## Expected behavior

DevOps opens with a new **Bug** work item filled in.

## Actual behavior

DevOps opens with a new **Issue** work item filled in.

## Screenshots

Here's what it looks like when it happens.  It's not horrible as I can change the work item type afterwards.  But it really slows the process down.
![image](https://user-images.githubusercontent.com/165767/85064879-11fda100-b161-11ea-9bad-2459c2ba1f7a.png)

## Context (please complete the following information)

- OS Name & Version: OS Name	Microsoft Windows 10 Enterprise  Version 10.0.18363 Build 18363
- AI-Web Version & Environment: 2.18.2
- Browser Version: Microsoft Edge.  Version 85.0.538.0 (Official build) dev (64-bit)
- Target Page: <Internal/Private>

## Are you willing to submit a PR?

Probably not, would be if it's not too cumbersome to test.

## Did you search for similar existing issues?

No, I tried to search here on your GH and couldn't find anything within 5 minutes.

**Comment by ferBonnin** [comment]
hey @chadsowald thanks for filing this bug! 

To have Accessibility Insights file bugs instead of issues, please follow this instructions:

1. go to _settings_ in Accessibility Insights for Web
1. In the _Issue Filing_ section, select _Azure boards_ and select the option to _File issue details in:_  **Repro steps**.

When the _File issue details in:_  option says **Description** Accessibility Insights creates an _Issue_. when it says **Repro steps**, it creates a _Bug_.

Please let us know if this solves your issue!

**Comment by chadsowald** [comment]
Oh, okay, thanks! Could you please update your documentation and maybe the extension settings to make that clear?  Really appreciate your quick turnaround.  Take care!

**Comment by ferBonnin** [comment]
Thanks for the suggestion! we will address this in the documentation.
