### ISSUE TITLE
Bypass Blocks - Info & examples - misspelled word "cotent" 

### ISSUE THREAD

**Issue by gatosocal** [microsoft/accessibility-insights-web#2921]
In the Info & examples section of the Bypass Blocks test, the word "content" is misspelled as "cotent" in this sentence:
"Otherwise, reaching the primary cotent could require dozens of keystrokes."

<img width="626" alt="Bypass Block misspelled word" src="https://user-images.githubusercontent.com/63076384/85070503-c05a1400-b16a-11ea-9a75-21f7141d68b3.PNG">

**Comment by ferBonnin** [comment]
thanks for issue @gatosocal, we will fix this!

**Comment by ferBonnin** [comment]
Hi @gatosocal! This issue is now resolved in [Canary](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem)

**Comment by gatosocal** [comment]
Verified on Canary.  Thank you!
