### ISSUE TITLE
Add a Color Picker to the FastPass

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#2926]
## Is your feature request related to a problem? Please describe.

Right now there is no way to find color contrast errors in:
- text in images
- videos
- CSS gradients
- image backgrounds behind text (or inside text)
- image icons

Level Access’s Accessible Color Picker might be the best alternative out there but it isn't open source and requires teams to install and monitor yet another browser extension.

Having these tools built into FastPass would make it easier for deployment. 

## Describe the desired outcome
Make it easier for everyone to identify more difficult color contrast problems. 

## Describe alternatives you've considered
Level Access’s Accessible Color Picker.

## Additional context
People want a central tool, and Accessibility Insights is pretty good for this.

**Comment by juchampa** [comment]
Hi @mgifford , thank you for submitting this feature request. We currently don’t have a color picker in Accessibility Insights for Web Extension however, we do have a color contrast analyzer in Accessibility Insights for Windows. This feature request does need more investigation and we will also be looking forward to see how widely requested this feature is through the upvotes.

**Comment by DaveTryon** [comment]
There are existing tools to get color contrast from an eyedropper. Accessibility Insights for Windows is one if you're on a Windows machine. Adding this to the web extension is out of scope given our current priorities.

Thanks for using Accessibility Insights!

**Comment by mgifford** [comment]
I'm using Edge, but not Windows. I suppose I have access to a virtual Windows box.   
  
Good to know it is out of scope for Mac/Linux. I guess folks can just use any of the open source tools available here https://accessibility.civicactions.com/guide/tools#color
