### ISSUE TITLE
Unified: new setup process UI

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#2988]
## Describe the bug

A few UI changes from the new setup dialogs:
1.	On the “choose which device to use” screen, the list of connected devices appears to be indented quite a bit. It would be nicer if the device list was flush-left like the other places where we show a device.

![Choose which device to use screen](https://user-images.githubusercontent.com/9062104/86054244-a8a64980-ba0e-11ea-930d-5bbb06a9b419.png)

1.	On the “choose which device to use” screen and the “connected and ready to go!” screen, there appears to be a bit more vertical space between the title element and the content than on the other screens.
**more spacing**
![choose which device and connected screens](https://user-images.githubusercontent.com/9062104/86054396-f0c56c00-ba0e-11ea-9506-36c4a2fa93ae.png)
**ideal**
![port forwarding and let us install screens](https://user-images.githubusercontent.com/9062104/86054442-02a70f00-ba0f-11ea-802d-81e91ddb37e4.png)

**Fix**
•	I’m not sure why there’s extra space on the “choose which device to use” screen. It should match the “Let us install the latest version” picture, since they have the same combination of {title without help link} + {content text}. 
•	For the “connected and ready to go” screen, there’s probably some extra spacing that’s being introduced because of the hit area of the device tile. I’ve seen different approaches to fixing this. If it’s only ever going to be a one-off case, we can just create an ad-hoc spacing fix. If there are other cases where the devices will show up without text between them and the title, we could create some logic around it so that whenever this combination appears, it’s properly spaced.
•	In either case, the ideal state is that, while in the rest state, the spacing appears visually to be the same as the comparison examples.

## Context (please complete the following information)

- OS Name & Version:  Windows 10
- AI-Web Version & Environment:  Unified Canary

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

## Additional context

Found by Nate

**Comment by AhmedAbdoOrtiga** [comment]
@ferBonnin The android setup feature is still open, do you think this issue should be addressed as a part of it so it'd be included in the release validation?
@DaveTryon what do you think?

**Comment by ferBonnin** [comment]
@AhmedAbdoOrtiga no, we talked about this and we will take this outside of the feature.

**Comment by dbjorge** [comment]
@ferBonnin The extra indent on the choose your device screen is because that empty space is where the checkbox renders when the device is selected. What do you want to do about the checkbox?

**Comment by ferBonnin** [comment]
@dbjorge thanks! I checked with Nate and he mentions that in the mocks we were assuming always one would be selected, once one of them is selected it doesn't look weird.

would it be possible to always have the first device selected by default?

**Comment by DaveTryon** [comment]
@ferBonnin, this is live in canary. Please regress as appropriate. Thanks!

**Comment by ferBonnin** [comment]
looks good!
