### ISSUE TITLE
unified telemetry dialog high contrast styling is off

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#3015]
## Describe the bug

As of 2020.702.4, the unified/android telemetry dialog looks like this in high contrast mode:

![image](https://user-images.githubusercontent.com/376284/86401549-44c68f80-bc5f-11ea-9728-c93ef6da1d88.png)

In the web extension, the dialog looks like this:

![image](https://user-images.githubusercontent.com/376284/86401500-2d87a200-bc5f-11ea-8da7-53389b15bb29.png)

The styling should be closer to how web's looks, but I'm not quite sure by how much. In particular, I suspect:

* The "you can change this choice" text should use a smaller font size
* the button and checkbox should use a higher contrast text/button distinction
* The dialog background should be black, not dark gray
* There should be a white border around the dialog in place of the usual shadow effect

**To Reproduce**

1. Uninstall and reinstall canary accessibility insights for android
2. Enable system high contrast mode
3. Open the app
4. Observe the telemetry dialog

## Context (please complete the following information)

- OS Name & Version: Windows 10 1909 08363.900
- AI-Web Version & Environment: unified@2020.702.4

**Comment by ferBonnin** [comment]
Per conversation with Peter and since there are no color-contrast issues, its ok to have the dialogs slightly different.
