### ISSUE TITLE
Android setup dialogs with loading spinners aren't consistent in vertical alignment

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#3017]
## Describe the bug

Some of the loading spinners are top-aligning (eg, "Scanning for devices..." after selecting "Detect my device" button), and some are center-aligning (eg, "Loading..." after selecting ADB path). The inconsistency mismatches the mock and is a bit visually jarring. They should be consistently center-aligned.

It seems like probably an issue with the `AndroidSetupStepSpinnerLayout` (the one that includes buttons at the bottom).

Top-aligned example (wrong):

![image](https://user-images.githubusercontent.com/376284/86403420-899ff580-bc62-11ea-871f-63d93cab6830.png)

Center-aligned example (probably also wrong, is centered without accounting for being consistent with the buttons on other spinner views)

![image](https://user-images.githubusercontent.com/376284/86403524-bbb15780-bc62-11ea-8ee9-343faf15b4c0.png)

**To Reproduce**

1. (from master) Run `yarn build:mock-adb` and `yarn mock-adb slow-single-device`
1. Start unified and tell it to look for mock-adb
1. Go through setup flow
1. Observe spinners

## Context (please complete the following information)

- OS Name & Version: Windows 10 1909 08363.900
- AI-Web Version & Environment: unified@2020.702.4

**Comment by karanbirsingh** [comment]
@ferBonnin do we want the spinner halfway between the footer and top (and stays there even if the screen has no footer)?

**Comment by DaveTryon** [comment]
Confirmed that the spinners align consistently throughout the setup dialogs
