### ISSUE TITLE
Insider reflow validation: Overview test details column lines overlap/misalign at certain zoom level/window width

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#3082]
## Describe the bug

At a certain zoom level or window width, the lines in the test details columns overlap or misalign.

**To Reproduce**

1. Go to [Accessible University](http://www.washington.edu/accesscomputing/AU/before.html)
2. Run an Assessment
3. Zoom or resize details view window, while keeping Test details in view
4. See overlapping/misaligned lines

![overview-test-details-bug](https://user-images.githubusercontent.com/48259897/87489298-8eb45b80-c5f7-11ea-99a9-2f28fa6ecc69.gif)

## Expected behavior

The lines should not overlap and should be aligned when there are two columns. 

## Screenshots

Screenshot of overlapping lines
![image](https://user-images.githubusercontent.com/48259897/87488536-83603080-c5f5-11ea-98c0-335521b31019.png)

Screenshot of misaligned lines
![image](https://user-images.githubusercontent.com/48259897/87488542-8824e480-c5f5-11ea-9b42-b115db235a01.png)

## Context (please complete the following information)

- OS Name & Version:  Windows Version 10.0.18363 Build 18363

- AI-Web Version & Environment:  Insider 2.19.0
- Browser Version:  Microsoft Edge Version 83.0.478.61 (Official build) (64-bit)
- Target Page:  http://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

no

**Comment by ferBonnin** [comment]
per conversation with Peter, marking as ready for work

**Comment by ferBonnin** [comment]
@lisli1 can you please verify the fix?

**Comment by lisli1** [comment]
LGTM in Canary 2020.8.11.1635
