### ISSUE TITLE
Insider reflow validation: Headers inside nav panel is a different height than the rest of assessment view

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#3089]
## Describe the bug
#2852 was supposed to make these heights equal, but currently the header in the nav panel is taller, as seen here:
![image](https://user-images.githubusercontent.com/19158512/87593020-a5ae8880-c69f-11ea-9215-e29f1b89b44c.png)

The fix employed in the previous PR could have possibly regressed. We were able to repro with Windows/Chrome, Windows/Edge, and Mac/Edge

**To Reproduce**

1. Go to Web Insider v 2.19.0 and navigate to the target page
2. Click on Assessment View
3. Shrink the size of the window until the hamburger menu appears at the top of the Nav panel

## Expected behavior
The heights should be equal, as pictured here:
![image](https://user-images.githubusercontent.com/19158512/87593133-d5f62700-c69f-11ea-9908-182061d35753.png)

## Context (please complete the following information)

- OS Name & Version: 
- AI-Web Version & Environment: 
- Browser Version: 
- Target Page: 

## Did you search for similar existing issues?
Yes, and there is not one.

**Comment by ferBonnin** [comment]
per conversation with Peter, marking as ready for work

**Comment by ferBonnin** [comment]
@JGibson2019 please validate

**Comment by JGibson2019** [comment]
Checked in Canary and the fix is there!
