### ISSUE TITLE
Text change in Settings > Issue filing > Azure Boards

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3186]
## Describe the bug

In **Accessibility Insights for Web** and **Accessibility Insights for Android**, under **Settings** > **Issue filing** > **Azure Boards**, I recommend changing **File issue details in:** to **Select a field for issue details** (no colon). That way, both instructions under Azure Boards are addressed to the user. (Currently the first instruction says what the _user_ should do, while the second says what the _system_ should do.)

**Comment by lisli1** [comment]
@LiLoDavis, the fix is now in Canary. Please close the issue if it looks good to you.

**Comment by LiLoDavis** [comment]
Looks good
