### ISSUE TITLE
"Use the Start over button" is unclear now that the button can be hidden behind a ... menu

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#3229]
## Describe the bug

When we implemented reflow behavior for the main details view navigation, we made it possible for the "Start over" and "Export report" buttons to end up hiding behind a "..." button on the command bar, where previously we were always displaying them as buttons.

There are a few points where we refer to these buttons in text, for example, in FastPass automated checks when there aren't any results yet (ie, the happy path I'd expect a new customer to be trying first). I'm concerned that it might be confusing for the text to refer to a "Start over button" that isn't present on the screen (and is really a menu item, not a button). Maybe less confusing would be to put a second "Start over" button where the text currently is?

**To Reproduce**

1. Open fastpass > automated checks against any page (do not start a scan)
2. Resize the fastpass UI to a low enough width that the "Start over" command bar button collapses under the "..." menu
3. Observe text

## Expected behavior

Instructions shouldn't refer to a hidden element without explaining the menu in between and shouldn't refer to a menu item as a button

## Screenshots

![screenshot showing FastPass > Automated checks with no results yet](https://user-images.githubusercontent.com/376284/89799443-7bfc4c00-dafb-11ea-9876-1de0ec764092.png)

## Context (please complete the following information)

- OS Name & Version: Windows 2004
- AI-Web Version & Environment: 2.20.0
- Browser Version: new Edge
- Target Page: any

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, would it be possible to make the text "start over" a selectable element users can use to scan?

**Comment by dbjorge** [comment]
@ferBonnin Yes, it is definitely feasible to make the inline text be a second start over button (my understanding is that it should look like a button, not a link, since it doesn't act like a link)

**Comment by ferBonnin** [comment]
> my understanding is that it should look like a button, not a link, since it doesn't act like a link
@dbjorge correct

**Comment by ferBonnin** [comment]
verified in Canary, looks good!
