### ISSUE TITLE
Automated checks different results in FastPass vs. Assessment

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3230]
## Describe the bug

Where Automated checks in FastPass finds failed instances, Assessment finds none.

**To Reproduce**
1. Go to one of the URLs below
2. Run Automated checks in FastPass
3. Run Automated checks in Assessment
4. Compare results

URL | FastPass | Assessment
-- | -- | --
https://www.washington.edu/accesscomputing/AU/before.html | 24 failed instances | Never completes
https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-controlpatternsoverview | 1 failed instance | 0 failed instances
https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf | 2 failed instances | 0 failed instances
https://www.w3.org/WAI/demos/bad/before/home.html | 44 failed instances | 0 failed instances
https://www.w3.org/WAI/demos/bad/before/home.html | 98 failed instances | Never completes
https://support.google.com/youtube/answer/2734796?hl=en | 25 failed instances | 0 failed instances

## Expected behavior

Same results in FastPass and Assessment

**Comment by LiLoDavis** [comment]
Version 2.20.0 | Powered by axe-core 3.5.1

**Comment by ferBonnin** [comment]
Talked offline with Lisa Louise, this doesn't repo
