### ISSUE TITLE
link-name rule is disabled with axe-core 4.0.1 integration

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#3270]
## Describe the bug

axe-core 4.0.1 introduces a false positive in the link-name rule (see https://github.com/dequelabs/axe-core/issues/2459), so we've temporarily disabled this rule. This creates a potential for regression, so we'll want to move to a newer version of axe-core quickly after this false positive is addressed. 

## Context (please complete the following information)

- OS Name & Version: Mac 10.15.6
- AI-Web Version & Environment: Canary 2020.8.20.1856
- Browser Version: Google Chrome 84.0.4147.125 (Official Build) (64-bit)

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

This was an intentional decision to reduce false positives

**Comment by ferBonnin** [comment]
marking as blocked until the false-positive in the rule is addressed

**Comment by ferBonnin** [comment]
verified in version 2.22
