### ISSUE TITLE
UI Element for not supporting chrome-error:// pages

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#3271]
## Describe the bug
Our extension normally does not support scanning browser internal pages. We have a popup that informs users of this when they try to scan "chrome://" pages, but users who try to scan "chrome-error://" pages are just left with a hanging scan. To prevent this from happening, we should show the popup for both "chrome-error://" and "chrome://" page scenarios

**To Reproduce**

1. Go to Edge
2. Navigate to 'https://nav.smartscreen.msft.net/phishingdemo.html'
3. Open the Production version of Accessibility Insights for Web and run "Automated Checks" from Launch Pad
4. See the scan never completes

## Expected behavior

Since our extension doesn't support scanning on "chrome-error://" pages, there should be a popup informing the user and they should not be allowed to start a never terminating scan. 

## Context (please complete the following information)

- OS Name & Version: 
- AI-Web Version & Environment: 
- Browser Version: 
- Target Page:

**Comment by JGibson2019** [comment]
Easiest workaround is to download a local copy of the site’s outer HTML and scanning that. You can do this by running “document.documentElement.outerHTML” in the console, copying the output, saving it to a local file, and then running the extension there.

**Comment by ferBonnin** [comment]
Per conversation with Peter, marking as out of scope until ew hear user feedback. Workaround is documented in this bug if needed.
