### ISSUE TITLE
AI-Web > Assessment > Adaptable content > Contrast isn't showing instances

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3301]
## Describe the bug

In two places, the tool is supposed to show instances of the color-contrast rule that need review:

- FastPass > Needs review > color-contrast
- Assessment > Adapable content > contrast

However, the following pages are showing inconsistent results in the two place:
1. https://www.w3.org/WAI/standards-guidelines/aria/
2. https://www.factzoo.com/mammals/types-of-monkeys.htm
3. https://www.monkeyhappy.com/

**To Reproduce**
1. Go to one of the above pages.
2. Compare instances generated in FastPass vs. Assessment (see paths above).
3. All three pages generate multiple instances in FastPass but 0 instances in Assessment

## Expected behavior

Instances should be identical in FastPass and Assessment.

## Context (please complete the following information)

- OS Name & Version: Microsoft Windows 10 Enterprise 10.0.18363
- AI-Web Version & Environment: 2.21.1 Production
- Browser Version: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Target Page: See above

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by pownkel** [comment]
This looks like it might have been caused by the recent upgrade to Axe 4.0

**Comment by ferBonnin** [comment]
> This looks like it might have been caused by the recent upgrade to Axe 4.0
Interesting, how so?

**Comment by pownkel** [comment]
We get the color contrast evaluate function directly and wrap it in another function, but in axe 4 they've changed how they store/access those functions, so our check is failing silently. We don't call the evaluate function directly for any other checks, so this shouldn't affect other rules.

**Comment by ferBonnin** [comment]
@LiLoDavis this is now fixed in Canary

**Comment by LiLoDavis** [comment]
Looks good to me.
