### ISSUE TITLE
"Getting Started" should be "Getting started" (sentence case)

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3310]
## Describe the bug
"Getting Started" is presented in title case (all words capitalized) but most navigation options and page titles are presented in sentence case (first word capitalized). For example, in the navigation pane, the **Keyboard** test includes the following options:

- Keyboard
  - Getting Started
  - Keyboard navigation
  - No keyboard traps
  - On focus
  - On input
  - No keystroke timings
  - Character key shortcuts

## Expected behavior
"Getting Started" should be presented as "Getting started" when it appears in the navigation menu and or as a page title.

## Are you willing to submit a PR?
No

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
thanks for the fix @CorgiDev! 
@LiLoDavis this is now in canary.

**Comment by LiLoDavis** [comment]
Looks good!
