### ISSUE TITLE
Adaptable content > Text spacing - New visual helper

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3322]
## Is your feature request related to a problem? Please describe.
For this requirement, users must apply certain styling properties to verify that text adopts them with no clipping or overlap. At present, users must apply the styling manually to any text in an iframe. 

## Describe the desired outcome

- Turning on the visual helper should apply the required style properties to the root html document and to any html documents embedded in iframes. 
- Turning off the visual helper should restore the original styling by deleting the <style> element we created.

Here's the required styling:

```
<style>
* { line-height: 1.5 !important; letter-spacing: 0.12em !important; word-spacing: 0.16em !important; } 
p { margin-bottom: 2em !important; } 
iframe { border: thick dashed blue !important; background-color: yellow !important; }');
</style>
```

Here's JavaScript that creates <style> element with the above properties in the selected JavaScript context:

`var style = document.createElement('style'), styleContent = document.createTextNode('* { line-height: 1.5 !important; letter-spacing: 0.12em !important; word-spacing: 0.16em !important; } p { margin-bottom: 2em !important; } iframe { border: thick dashed blue !important; background-color: yellow !important; }'); style.appendChild(styleContent ); document.getElementsByTagName('head')[0].appendChild(style);`

## Describe alternatives you've considered
We tried using bookmarklets, but they can't apply the styling to text in iframes.

## Additional context
This feature was created in response to bug #3096.

**Comment by joppekroon** [comment]
We unfortunately use a lot of nested iframes, so we are heavily impacted by Accessibility Insights referring to a bookmarklet that does not actually work for us.

Although it is possible to add this to [improve the code of the bookmarklet](https://github.com/joppekroon/bookmarklets/blob/master/text-adaptation.js), I believe using the same style injection system that Accessibility Insights already uses for visual helpers would be superior. 

P.S. I'm not sure there is a need for the border on the iframes as suggested on top.

**Comment by LiLoDavis** [comment]
Looks good on most pages, 
However, it won't work on this target page: [Microsoft License Terms](https://www.microsoft.com/en-us/useterms). Visual helper is disabled, and it says **No matching/failing instances were found**.  There's text on the page, so it shouldn't say no instances.

**Comment by ferBonnin** [comment]
@LiLoDavis I cannot repro this, for me it takes a second or so and then the toggle is made available. This also happens if you go to requirements in Headings or Landmarks

**Comment by madalynrose** [comment]
@LiLoDavis I noticed that for some pages the scan takes a long time (especially if there are a lot of iframes). Because our visual helper toggle doesn't have a loading state, it can be hard to tell if it's still scanning or if it's finished and truly found no instances. Perhaps worth adding a feature for a loading state?

**Comment by LiLoDavis** [comment]
@madalynrose I see that the scan completed quickly today. Not sure what the problem was yesterday, as the page has relatively little text. I can't reproduce it, so I'll go ahead and close.
