### ISSUE TITLE
Add a 'File Issue' option via the Assessment section to automatically create work items. 

### ISSUE THREAD

**Issue by FaustinoSolano** [microsoft/accessibility-insights-web#3326]
## Is your feature request related to a problem? Please describe.
I am unable to use the 'File Issue' functionality from within the Assessment section

## Describe the desired outcome
I would like to be able to file an issue (bug) via Azure DevOps when using the Assessment section.

## Describe alternatives you've considered
Currently we have to copy and paste the data from the assessment into a manually created bug.

## Additional context
The fact that the option is there in the Automated Checks but not Assessment sections seems odd, is there a particular reason for it being in one but not the other?

**Comment by RobGallo** [comment]
@FaustinoSolano , 
Would you be willing to fill in the rest of the information for the feature? i.e., 

- Is your feature request related to a problem? Please describe.
- Describe the desired outcome
- Describe alternatives you've considered
- Additional context

This will help us build the feature you want and prioritize the work.

**Comment by dbjorge** [comment]
Adding a :+1: by proxy; a person I was interviewing recently (who shall remain anonymous) had the same request/suggestion

**Comment by FaustinoSolano** [comment]
> @FaustinoSolano ,
> Would you be willing to fill in the rest of the information for the feature? i.e.,
> 
> * Is your feature request related to a problem? Please describe. 
> * Describe the desired outcome
> * Describe alternatives you've considered
> * Additional context
> 
> This will help us understand the feature you want and prioritize the work.

I am unable to use the 'File Issue' functionality from within the Assessment section. 

I would like to be able to file an issue (bug) via Azure DevOps when using the Assessment section.

Currently we have to copy and paste the data from the assessment into a manually created bug.

The fact that the option is there in the Automated Checks but not Assessment sections seems odd, is there a particular reason for it being in one but not the other?

**Comment by ferBonnin** [comment]
thanks for the feature request @FaustinoSolano 

We reviewed this with the team and there are some interesting questions on providing the option to file bugs in Assessment (e.g. at what level do we file the bug, requirement or instance? how does it look like for manual requirements where there isnt a path or code snippet).

We will leave this feature request open to allow the community to upvote and share their thoughts about this functionality.

**Comment by DaveTryon** [comment]
We're working on a feature of assessment improvements and will consider this as a candidate for that feature. 

Thanks for using Accessibility Insights!
