### ISSUE TITLE
Accessibility Insights false positive bug when dealing with Shadow Text and Blur

### ISSUE THREAD

**Issue by joelkseattle** [microsoft/accessibility-insights-web#3419]
## Describe the bug

When using CSS text shadow, seems like Accessibility Insights will falsely think the shadow blur is a background color and will show a color constrast defect.
**To Reproduce**

1. https://flow.microsoft.com/en-us/
2. Run Accessibility Insights
3. Scroll down to "Explore Power Automate templates" section
4. See error indicated on the "Featured tab"

## Context (please complete the following information)

- OS Name & Version: 
- AI-Web Version & Environment: 
- Browser Version: 
- Target Page:

**Comment by iamrafan** [comment]
@joelkseattle Thanks for filing the issue. I filed issue https://github.com/dequelabs/axe-core/issues/2541 with axe-core and we shall update you once we release the fix

**Comment by iamrafan** [comment]
@joelkseattle Fixed in Version 2.23.0
