### ISSUE TITLE
Support for French & other languages

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#3425]
## Is your feature request related to a problem? Please describe.
I believe that this software (like many accessibility tools) is only available in English. Many users of the web speak other languages.  How do we support more people being able to understand how to create accessible content. 

## Describe the desired outcome
I'd like to be able to add French strings into the interface and provide better support for other languages. I understand that there are upstream implications for axe too. 

## Additional context
For adoption in many government agencies, software has to support more than English. Accessibility Insights is a great tool for widespread adoption in government.

**Comment by ferBonnin** [comment]
Hi @mgifford! thanks for the feature request. 

Apart from the initial effort to translate the whole application, there are also other implication around compliance, maintainability, added load on translation for each release or text change and a considerable infrastructure investment to enable this.
After carefully reviewing with the team and weighting it against other possible efforts we can do for the tool, we have come to the conclusion that at this moment, we cannot work on this request.

**Comment by mgifford** [comment]
Thanks @ferBonnin - should some organization step up willing to maintain the translations for a second language, would that change the decision? 

This is a great open source tool. Surely some French, Spanish, Dutch or German speaking country might have a government who might be interested in having it in their language who might be able to front the cost and responsibility for this. 

It's a big task to take on, but would love to help bring along some resources to make it more doable.

**Comment by ferBonnin** [comment]
Thanks @mgifford! it is an interesting idea; someone willing to do the translation would help for the translation part. However, there are still other investments that need to be done to enable the infrastructure to add new languages and at this moment, we cannot take them.

**Comment by mgifford** [comment]
That's totally fair..  I know it's definitely not trivial. Had hoped it would be a standard practice to build for mulit-lingual products in MS.

**Comment by mgifford** [comment]
Thought it might be useful to compare with the translations available from Google Lighthouse - https://github.com/GoogleChrome/lighthouse/issues/12549 - another open source project with accessibility features.
