### ISSUE TITLE
[Feature Request] Add a failure description

### ISSUE THREAD

**Issue by FernandVO** [microsoft/accessibility-insights-web#3430]
Some assesments have a failure description option, but some don't.

**Steps to reproduce**
Example: Native Widgets > Instructions

- The assesment shows a list of all form fields it encounters

- In this example a Yes and  No radio button are not programmatically related to a question so I fail them:

![radiobuttons](https://user-images.githubusercontent.com/72253412/94910477-0bdbc800-04a5-11eb-80a6-abe8c68401a8.JPG)

**Result**
- I  can fail them, but I can't leave a comment on what the exact problem is and how to fix it, like: "Solution: wrap the radio buttons in a fieldset/legend"

**Expected result**
Below the assesment there is a option for a "failure description".

**Comment by ferBonnin** [comment]
Hi @FernandVO Thanks for your feature request! This looks like a duplicate for #485.
Could you please take a look and let us know if that feature request covers this one?
