### ISSUE TITLE
Accessibility Insights for Android bugs are filed with Web tags in ADO

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#3438]
## Describe the bug

Accessibility Insights for Android bugs are filed with Web tags in ADO

**To Reproduce**

1. Open Accessibility Insights for Android, scan an app
2. Select file a bug with Azure DevOps settings
3. The bug is filed but the tags added say "Accessibility Insights for Web"
![tags include Web instead of Android](https://user-images.githubusercontent.com/9062104/95156368-45356180-074b-11eb-9dc8-f6dc26e0aab1.png)

## Expected behavior
Tag should say Accessibility Insights for Android

## Context (please complete the following information)

- OS Name & Version:  Windows

## Are you willing to submit a PR?
No

## Did you search for similar existing issues?

Yes

## Additional context
Something additional to note, in the _context_ section for this bug template, we should consider adding elements that could be relevant for Accessibility Insights for Android instead of just Web

**Comment by dbjorge** [comment]
@ferBonnin Should this be based strictly on the product name, or should it match how our application filename works and include the environment name when the environment is non-prod? ie, prod AI4Android would say "Accessibility Insights for Android" in either case, but would you prefer that canary AI4Android use "Accessibility Insights for Android" or "Accessibility Insights for Android - Canary"?

**Comment by ferBonnin** [comment]
@dbjorge just the name of the product name ("Accessibility Insights for Web" "Accessibility Insights for Android") no need to add the environment.

**Comment by ferBonnin** [comment]
verified in canary
