### ISSUE TITLE
Background color when expanding a rule should stay grey

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#3446]
## Describe the bug

The Background color in FastPass is grey. When you expand a rule, the background color is white.

**To Reproduce**

1. run Automated checks (fastPass) in a page with issues
2. expand a rule
3. notice that the background color for the expanded cards is white instead of grey.

## Expected behavior

the background color should stay grey (#F8F8F8)

## Screenshots

![grey and white background](https://user-images.githubusercontent.com/9062104/95241805-296da200-07c3-11eb-91df-a5a487a9f50b.png)

## Context (please complete the following information)

- OS Name & Version:  Windows
- AI-Web Version & Environment:  Version 2.22.0
- Browser Version:  Chrome 85.0.4183.121 
- Target Page:  any

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?
 yes

**Comment by dbjorge** [comment]
Didn't mean for this to auto-close. Fix is in master, should be ready to validate (modulo waiting for a canary build)

**Comment by ferBonnin** [comment]
verfied in canary
