### ISSUE TITLE
Reports in Web and Android tools have links that can't be distinguished from surrounding text

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3448]
## Describe the bug

In the Web and Android reports, some links can't be visually distinguished from surrounding text.

In both Web and Android reports:
- For rules that pass or N/A, the links to WCAG success criteria

In Web reports:
- Links in the footer to http://aka.ms/AccessibilityInsights

## Expected behavior

Links must have a distinct visual style (e.g., bold, italics, underlined) or a contrast ratio of at least 3:1 when compared to non-link text.

## Screenshots

![link-in-text-block](https://user-images.githubusercontent.com/45569509/95362273-b592ce80-0882-11eb-8002-4d2a1b20fe36.jpg)

![link-in-text-block2](https://user-images.githubusercontent.com/45569509/95363283-1cfd4e00-0884-11eb-940b-d26f4a238f87.jpg)

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets fix this but we might need to change our blue color for links, since it doesnt pass with grey text (like the web footer or the how to check cards)

**Comment by ferBonnin** [comment]
@LiLoDavis could you please take a look at possible fixes here? Our blue color for links is not 3:1 against the grey text we use in some places (footer and cards in fastPass). Should we change that light grey or make the blue link slightly darker?

**Comment by LiLoDavis** [comment]
@ferBonnin I recommend making the grey darker. I wasn't able to find a darker blue that passes. Changing the gray (currently #4c4c4c) to #222222 looks good to me and has a contrast ratio of 3.027:1 compared to the links.

**Comment by pownkel** [comment]
@LiLoDavis The fix is in canary!
