### ISSUE TITLE
Tab stops visualization is broken on the PowerBI web page

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-web#3475]
## Describe the bug

Tab stops visualization is broken on the left pane in PowerBI web page

## Screenshots
![tabstops-viz-bug](https://user-images.githubusercontent.com/22068434/96196148-8d9b0f00-0f03-11eb-9c6d-b534d7f572c6.gif)

## Context

- OS Name & Version: Windows 10 Enterprise, Version: 20H2, Build 19042.508
- AI-Web Version & Environment: Production 2.22.0
- Browser Version: Google Chrome 86.0.4240.75
- Target Page: https://msit.powerbi.com/home

**Comment by karanbirsingh** [comment]
initial triage note - I can reproduce this. Our visualization is unable to find the element. 
```js
home:1 Error in event handler: TypeError: Cannot read property 'tagName' of null
    at CenterPositionCalculator.getElementCenterPosition (webpack-internal:///./src/injected/visualization/center-position-calculator.ts:13:31)
    at SVGDrawer.createFocusIndicator (webpack-internal:///./src/injected/visualization/svg-drawer.ts:100:66)
    at eval (webpack-internal:///./src/injected/visualization/svg-drawer.ts:162:51)
    at arrayEach (webpack-internal:///./node_modules/lodash/lodash.js:516:11)
    at Function.forEach (webpack-internal:///./node_modules/lodash/lodash.js:9368:14)
    at SVGDrawer.getHighlightElements (webpack-internal:///./src/injected/visualization/svg-drawer.ts:158:22)
    at SVGDrawer.addHighlightsToContainer (webpack-internal:///./src/injected/visualization/svg-drawer.ts:66:38)
    at SVGDrawer.draw (webpack-internal:///./src/injected/visualization/base-drawer.ts:36:18)
    at SVGDrawer.drawLayout (webpack-internal:///./src/injected/visualization/base-drawer.ts:24:18)
    at DrawingController.enableVisualizationInCurrentFrame (webpack-internal:///./src/injected/drawing-controller.ts:63:20)
```

outerHTML of element that breaks is:

```js
<button _ngcontent-dsu-c40="" aria-haspopup="true" class="expanderButton switcher ng-star-inserted" pbitooltipposition="after" aria-expanded="false" aria-label="Expand" pbi-focus-tracker-idx="70">
    <mat-icon _ngcontent-dsu-c40="" class="glyph-small horizontal mat-icon notranslate pbi-glyph-font-face pbi-glyph-chevronrightmedium mat-icon-no-color" fonticon="pbi-glyph-chevronrightmedium" role="img" aria-hidden="true">
    </mat-icon>
</button>
```

The selector `button[pbi-focus-tracker-idx="\37 0"]` doesn't produce an element when queried in `svg-drawer`. We should check why that is / whether the selector value is changing. The `\37 0` is also odd given the `70` in the HTML.

https://github.com/microsoft/accessibility-insights-web/blob/f7747a480c9fd0b01337356e73866bebfe2d7a57/src/injected/visualization/svg-drawer.ts#L88

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets time box the investigation to 4 hours max, if we cannot find anything after that time, lets discuss further

**Comment by peterdur** [comment]
@ferbonnin As @karanbirsingh suggested above, I looked into whether the attribute we're using in the selector is changing, and it appears that it is.

To see this in the example above, right-click and Inspect the chevron next to Favorites. Put focus back on the page and Tab and shift-tab around that chevron and you'll see that the value of the class and pbi-focus-tracker-idx attributes change as you move through the control. Since we're using an earlier value of the attribute in the selector to decide where to draw the visualization, when this happens we can't find the element since the attribute no longer matches.

**Comment by peterdur** [comment]
Manually adding stable id attributes to the chevrons in DevTools results in axe-core using those in the selector, which gives the expected behavior:
![image](https://user-images.githubusercontent.com/1752950/106687509-16a48780-6581-11eb-88f9-53748780e8ef.png)

**Comment by ferBonnin** [comment]
thanks @peterdur and @karanbirsingh for this investigation! 
@iamrafan can we get this information back to the team that reported it, please?

**Comment by iamrafan** [comment]
@ferBonnin Update the team via email with the information to manually add ID attributes to the chevrons to see the expected behavior
