### ISSUE TITLE
Can a list have children that are not listitem (or group)

### ISSUE THREAD

**Issue by Anschur** [microsoft/accessibility-insights-web#3486]
Hi!

If I have list (`ul`) and place a `button `directly inside it get an error that the list is not correctly structured: 
https://dequeuniversity.com/rules/axe/4.0/list?application=msftAI

But if I have a structure where I use roles instead of semantic elements:
\<div role="list">
  \<div role="listitem">...\</div>
  \<div role="listitem">...\</div>
  \<button>Click me\</button>
\</div>

Accessibility Insights is fine with it. 
Is this allowed or is it a bug/missed case in Accessibility Insights?

**Comment by DaveTryon** [comment]
Thanks, @Anschur! We're investigating this now and will update this issue once we have more information.

**Comment by DaveTryon** [comment]
@Anschur, this appears to be a shortcoming in axe-core (the engine that we use for scanning). We've opened dequelabs/axe-core#2576 to report it and will pick up the fix once it's available.

**Comment by ferBonnin** [comment]
@iamrafan could you please update?

**Comment by iamrafan** [comment]
@ferBonnin we have been told allowing this use case is not required by ARIA and issue w3c/aria#1033 has been filed to get more clarity about the guidance/definition for "required owned element"

**Comment by iamrafan** [comment]
@Anschur The description of 'Required owned elements' and 'Owned elements' in ARIA is somewhat problematic. The ARIA working group is working to clarify the definitions to help users interpret the guidance better (w3c/aria#1033).

Going by the discussion in the (w3c/aria#1033) thread, it looks like the example you mentioned need not be failed and hence this is not a missed case or a false negative case. I am closing this issue, please feel free to get back to us if you have any further questions.
