### ISSUE TITLE
web e2e flakiness: pageerror with message 'Object'

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#3529]
## Describe the bug

Recently, we've been seeing a high number of web E2E failures in an assortment of different test cases with errors of the form:

```
Received: "Playwright.Page 'chrome-extension://eheeiipehjcbehnicfejeidgbhffnikc/background/background.html' emitted 'pageerror' (console.error): [Error]{name: 'Error', message: 'Object', stack: ''}"
```

* [Example failure](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=15110&view=logs&j=952ed597-794a-5756-0328-a93bb2daa2a4&t=46864a42-71df-5c2d-c60f-5fec8d56499d&l=33)

@waabid and I made some attempts to track down a more useful error, but didn't get very far yet. This issue tracks finding and fixing the root cause; in the meantime, we'll be suppressing this specific form of error, since it doesn't seem to correspond to any true issue breaking the extension.

**To Reproduce**

1. Run an e2e-reliability build
2. Observe that at least one of the failures will probably be from this issue

## Expected behavior

Shouldn't have flaky test, and if we do, should figure out how to get a more useful error message

**Comment by ferBonnin** [comment]
per conversation with @peterdur keeping around to track the supression

**Comment by ferBonnin** [comment]
@dbjorge @waabid do we know if this issue is still reproing?
