### ISSUE TITLE
Add additional instructions in the 'Connect to your Android device' / 'Connect to Service' screens

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#3542]
## Describe the bug

* In the connect to your Android device, we don't provide any text on what this screen is or what to do. Provide more information similar to what we do in other screens
* In the grant permissions on your device, mention in the text that users need to select _try again_    
  * should _try again_ be _check again_?

## Context (please complete the following information)
 
- OS Name & Version:  Windows
- AI-Web Version & Environment:  Accessibility Insights for Android

## Additional context
From user's interviews

**Comment by ferBonnin** [comment]
@LiLoDavis any suggestions for the text on the first screen or thoughts on changing to "check again" vs "try again"?

**Comment by LiLoDavis** [comment]
I prefer "Try again" but it is pretty vague. Try what, exactly? Perhaps it would help to clarify in the preceding text.
> Be sure the Accessibility Insights for Android Service on your device is turned on and has permission to access your device and capture screenshots. Then try again to connect.

**Comment by ferBonnin** [comment]
I like the proposed text. Minor suggestion:

> Then try again to connect.

how about then select _try again_ to connect?

**Comment by LiLoDavis** [comment]
I like your edit, and I have my own minor suggestion:

> Then select _Try again_ to connect.

**Comment by ferBonnin** [comment]
@LiLoDavis any suggestions for the other screen text? (connect your Android device)?

**Comment by LiLoDavis** [comment]
How about this:

> Connect a hardware device to your computer via USB, or run a virtual device in Android Studio or the Android Virtual Device Manager.

**Comment by DaveTryon** [comment]
@ferBonnin, please validate/close at your convenience. Thanks!

**Comment by ferBonnin** [comment]
verified in canary, thanks!
