### ISSUE TITLE
plugin disables itself on activation (left-click)

### ISSUE THREAD

**Issue by stefan-kern** [Microsoft/accessibility-insights-web#357]
The plugin can be installed, however when trying to open the plugin actions by left-clicking the plugin icon, the plugin disables itself.

- OS: Linux / Ubuntu 16.04
- Chrome:
  - Version 74.0.3724.8 (Official Build) dev (64-bit)
  - Version 73.0.3683.75 (Official Build) (64-bit)
- Target Page: (any) example: google.com

Please let me know if i can provide more information.

**Comment by smoralesd** [comment]
Hi @stefan-kern 
Thanks for your interest on Accessibility Insights for Web.
We'll be doing some preliminary investigation on this issue. We'll reply back as soon as we can.

**Comment by pshrmn** [comment]
I ran into the same issue with Linux Mint 19.1 using Chrome 72.0.3626.121. The error occurred with both the Production and Canary extension builds.

**Comment by lucagentile** [comment]
Same happens to me. I'm running Chrome 72.0.3626.119 (Official Build) (64-bit) on Ubuntu 18.04.2

**Comment by smoralesd** [comment]
Hi @stefan-kern.
Thanks for your interest on Accessibility Insights for Web.
We'll be triaging this issues soon. Keep tuned for updates.

**Comment by smoralesd** [comment]
Hi everyone, this issues is not fixed on master branch. Stay tune for new releases of our extension to get this fixes.

![01 - extension is working on linux](https://user-images.githubusercontent.com/2837582/54395680-bf842980-466d-11e9-8cf6-75bda529a22e.gif)

**Comment by smoralesd** [comment]
@stefan-kern This issues should be fixed on release [v2.0.5](https://github.com/Microsoft/accessibility-insights-web/releases/tag/v2.0.5. Download the extension from [here](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni).

**Comment by stefan-kern** [comment]
thanks for the fix, works now!
