### ISSUE TITLE
Mac/Chrome Extension - Cannot Uncheck Telemetry Checkbox on Install

### ISSUE THREAD

**Issue by onehotprocessor** [Microsoft/accessibility-insights-web#358]
Issue:
Upon installation of the extension, and first attempt to use the plugin, a screen is displayed with telemetry opt-in/opt-out options. The end user is unable to uncheck the telemetry opt-in box, and does not have the ability to opt-out. 

Expected:
End user is able to opt-out of telemetry. 

Steps to Reproduce:
1. Using macOS v10.14.2 (18C54) and Chrome v72.0.3626.119 (Official Build) (64-bit), and without having it already added to browser, navigate to the extensions download page in Chrome Web Store: https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni
2. Click 'Add to Chrome' button.
3. Confirm successful installation of extension. 
4. Navigate to any URL (ex., https://google.com) and click on the extension within the extension bar. 
5. On the telemetry opt-in/out notification, click the checkbox to unselect the checkbox (opt-out). 
6. Observe: end user is unable to unselect the checkbox, and as a result, unable to opt-out of telemetry.

Documentation:
Please note .mov file for more information. 
[extension telemetry checkbox.mov.zip](https://github.com/Microsoft/accessibility-insights-web/files/2961968/extension.telemetry.checkbox.mov.zip)

Environment:
* macOS v10.14.2 (18C54) and Chrome v72.0.3626.119 (Official Build) (64-bit)
* Chrome extension v2.0.4
* URL: https://google.com

**Comment by onehotprocessor** [comment]
Please note: for evaluation purposes by my company (and potential adoption), we will need telemetry turned off during eval. Thank you.

**Comment by Shobhit1** [comment]
Hey @onehotprocessor,

Thanks for reporting this issue.
Looks like there is a bug (check it [here](https://bugs.chromium.org/p/chromium/issues/detail?id=659642)) on Chromium (for Windows 10 and MacOS) which makes the UI on chrome extensions behave unusually.
If you can just try using the extension on one screen, you will be able to opt out of the telemetry from the popup.

Please let us know if it worked and we can mark this issue as closed.

**Comment by Shobhit1** [comment]
Talked to @onehotprocessor. Issues seems to be because of the chromium bug described.
Closing this one here.

**Comment by onehotprocessor** [comment]
Confirmed - Chromium is the culprit! Thanks so much.
