### ISSUE TITLE
Missing stylesheet with Chromium on Linux

### ISSUE THREAD

**Issue by pshrmn** [Microsoft/accessibility-insights-web#362]
## Describe the bug

When I try to run the extension on Chromium, I am running into various styling issues. This has occurred with both the Production and Canary extensions.

In the console for the "fast pass" window, I see a `file not found` error for `/Styles/default/detailsview.css`.

#### Style Issues:

1. The popup (what is shown when you click the favicon) is too narrow. I have a feeling that there is another stylesheet that fails to load, but I do not see an error for it.
2. The details view (the screen that is opened when you click on the `FastPass` or `Assessment` options in the popup) fails to load the `detailsview` CSS file.

I found the extension source code on my local filesystem, and the `Styles/default/detailsview.css` file exists there, so I'm not sure why Chromium cannot load it.

## Screenshots

![popup](https://user-images.githubusercontent.com/1127037/54325590-17208780-45d1-11e9-9b9c-ab2e7fb75689.png)
![fast-pass](https://user-images.githubusercontent.com/1127037/54325595-1b4ca500-45d1-11e9-92e9-96bdf6f8c032.png)

## Extension

- OS: Linux Mint
- Version 19.1
- Chromium Version 72.0.3626.121
- Target Page: any page

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)? Yes

**Comment by smoralesd** [comment]
Hi @pshrmn 
Thanks for your interest on Accessibility Insights for Web.
You've mention you found "various styling issues", can you update the description of the issues, add the details of all the styling issues?
We'll triage once we get this information.

**Comment by smoralesd** [comment]
Hey @pshrmn, the styling issues are now fixed on master branch. Stay tune for extension updates to get this fixes.

![01 - extension is working on linux](https://user-images.githubusercontent.com/2837582/54395617-89df4080-466d-11e9-86e9-c71385475326.gif)

**Comment by pshrmn** [comment]
Aha, those darn Linux case sensitive paths! Thanks for the quick fix @smoralesd!

**Comment by smoralesd** [comment]
Hi @pshrmn This issues should be fixed on release [v2.0.5](https://github.com/Microsoft/accessibility-insights-web/releases/tag/v2.0.5. Download the extension from [here](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni).

**Comment by pshrmn** [comment]
Works like a charm now!
