### ISSUE TITLE
Assessment guidance to ensure required fields have a visible indication

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#3658]
## Is your feature request related to a problem? Please describe.
In the "How to test" section of the "Cues" section for Native Widgets and Custom Widgets , the tester is guided to interact with the highlighted widgets to determine whether it adopts any of these states: Disabled, Read-only, Required.

However, even though WCAG 2.1 SC 3.3.2 Labels or Instructions explicitly states that inputs have labels, including clear indication of required fields, the "How to test" section does not include verification that those Required fields have a visible indicator. It only directs the tester to "inspect its HTML to verify that the states are appropriately coded.

Thus, a required field could be one that exposes its required state to a screen reader but doesn't have a visible indicator that it's required.

Shouldn't AI for Web include a test for a visible indicator for fields that are required?

## Describe the desired outcome
AI Web assessment includes a test that required fields have a clear visual indicator that they are required.

## Additional context
This feature request originally came from [this stackoverflow post](https://stackoverflow.com/questions/64829175/accessibility-insights-doesnt-have-guidance-to-test-that-required-input-field).

**Comment by ferBonnin** [comment]
@LiLoDavis could you please take a look?

**Comment by LiLoDavis** [comment]
> However, even though WCAG 2.1 SC 3.3.2 Labels or Instructions explicitly states that inputs have labels, including clear indication of required fields

I'm not convinced failure to visibly indicate required fields is a violation of this (or any) SC.

Neither the 3.3.2 SC itself nor the **Intent** section of the **Understanding** document explicitly mentions it, nor is there a documented **Failure** example for it. (It does appear in the **Examples** and **Sufficient Techniques**, but those don't constitute requirements.)

I believe the need to communicate required fields is addressed by **Errors** > **Error identification**.

If we do want to add a requirement for visible indicators, I'm not sure exactly where it belongs. Currently, both the **Cues** and **Instructions** requirements are about making content that's visible available programmatically. We might need to add a new requirement, else it won't be clear exactly what problem was identified - missing visual info, or missing programmatic info?

**Comment by ferBonnin** [comment]
@LiLoDavis thanks for taking a look into this! 

> I'm not convinced failure to visibly indicate required fields is a violation of this (or any) SC.

if it is not a failure criteria, we shouldn't add a requirement for it.

**Comment by ferBonnin** [comment]
> I'm not convinced failure to visibly indicate required fields is a violation of this (or any) SC. Neither the 3.3.2 SC itself nor the Intent section of the Understanding document explicitly mentions it, nor is there a documented Failure example for it. (It does appear in the Examples and Sufficient Techniques, but those don't constitute requirements.) I believe the need to communicate required fields is addressed by Errors > Error identification.

@pownkel I think the reply above should be ok to update the user question. I am closing this issue but if there are additional points made by the user, please feel free to re-open
