### ISSUE TITLE
AI Android hamburger menu not closed by clicking outside

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#3692]
## Describe the bug

In web, the hamburger menu can be closed by clicking outside the menu. In the electron app, the mouse pointer appears clickable outside of the hamburger menu, but clicking does not close the menu as expected.

**To Reproduce**

1. Open Accessibility Insights for Android, connect a device, and scan for issues
2. Resize the window until the left nav disappears and the hamburger button appears
3. Open the hamburger menu
4. Click outside the menu. The mouse pointer becomes a clickable pointer, but nothing happens on click.

## Expected behavior

The menu closes when a user clicks outside it.

## Context (please complete the following information)

- OS Name & Version: Windows 10 build 19042.630
- AI-Web Version & Environment: 2020.1123.2 Insider

**Comment by dbjorge** [comment]
Escape key also does not dismiss the menu (#3693 fixes both)
