### ISSUE TITLE
[Bug] Combined report UI changes

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#3729]
## Describe the bug

A couple UI changes for the combined report:

- Add "Rules" next to the Failed, Not applicable, and Passed test
![](https://user-images.githubusercontent.com/9062104/101206024-5c95ab80-3623-11eb-9bfe-c127e56da6f9.png)
- Add additional information in the footer around us using a clean browser environment and the display size we use to test: "The scan was performed in a clean browser environment, using axe-core 4.0.2 and Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.0 Safari/537.36 with a display resolution of 1920x1080.
- [if not too complex] switch the order in the rules results: show Failed rules, then Passed rules and finally Not applicable rules 

## Additional context

From user feedback

**Comment by ferBonnin** [comment]
To make this changes available to users, this will require a release to the report package and the CLI tool

**Comment by pownkel** [comment]
This will be done once we release the service and CLI tool after the holiday change freeze

**Comment by ferBonnin** [comment]
verified in combined report
