### ISSUE TITLE
Platform Specific Insights

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#374]
## Is your feature request related to a problem? Please describe.
How do we collect framework specific accessibility bugs from the telemetry that you are collecting to contribute back to the projects that they are built with?  

## Describe the desired outcome
I would like to see a list of Drupal, WordPress, GatsbyJS, etc issues, Ideally aligned with modules or plugins that are used. Would be nice to start being able to identify where accessibility bugs are introduced upstream. 

## Describe alternatives you've considered
I have asked groups like Siteimpove & Tenon to implement things like this.

**Comment by ferBonnin** [comment]
Hi @mgifford thanks for the feature request! 
This request requires more discussion on our side, we will update here when we know more.

**Comment by mgifford** [comment]
It is a huge issue.  That said, it has some really potential benefits.  If you could identify that an accessibility problem arises on 90% of all Drupal 8 websites that use the Bootstrap 4 theme, but doesn't occur on any of the WordPress sites that use Bootstrap 4, it would be possible to highlight post an issue here https://www.drupal.org/project/issues/search/bootstrap that could potentially fix thousands of sites. 

Likewise, if it hit all Bootstrap 4 themes maybe you could find the issue here https://github.com/twbs/bootstrap/issues and provide a summary like:

Google Estimates that this accessibility issue affects 23 million people a month around the world. 200,000 people with disabilities face barriers every month because of this bug.

**Comment by ferBonnin** [comment]
We understand the value you present with this example. The main questions on our side are two:
•	Would Accessibility Insights users be ok with sharing this type of telemetry?
•	And, how do we detect this?

Related to your request, have you seen webAIM report of scanning a million websites? They have some data on the [Web Frameworks from the million home pages scanned](https://webaim.org/projects/million/#webframeworks) 

Thanks!

**Comment by mgifford** [comment]
I would assume you'd want to have some sort of checkbox that says something like "I approve of information being consolidated so that this product and the web in general can be made more accessible." You'd need to say how the information was going to be used and make the permission an opt-in.  That said, it really could be something that organizations are encouraged to do. 

There are lots of ways to detect the framework. Not always 100% but usually there are signs.  There are tools like https://builtwith.com/ that could be leveraged.  There are a few other options with https://www.ostraining.com/blog/drupal/5-ways-drupal/ & https://www.isitwp.com/

The WebAIM report is great. I haven't looked at the data, but amazing that they have it. I look forward to seeing how it compares with reviews done in 2020!

**Comment by adarshrema** [comment]
Hi @mgifford, thank you for your interest in Accessibility Insights and this feature request. We have discussed this as a team and concluded that it will not be possible to share this information as we take the privacy of our users very seriously.

As suggested in one of our earlier responses, please review the report from webAIM that analyzes accessibility issues in the top 1 million web pages. You can also scan individual pages in question using Accessibility Insights.

We value your feedback and thank you for being a user of Accessibility Insights!
