### ISSUE TITLE
Text changes in Native widgets & Custom widgets > Instructions

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3752]
## Describe the bug
The proposed changes are intended to better align the **Instructions** requirements in the **Native widgets** and **Custom widgets** tests with [SC 2.5.3 Label in Name](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1&currentsidebar=%23col_overview&levels=aaa#label-in-name).
See [Instructions in Native widgets and Custom widgets.docx](https://github.com/microsoft/accessibility-insights-web/files/5690314/Instructions.in.Native.widgets.and.Custom.widgets.docx)

**Comment by lisli1** [comment]
This seems to be related to #3736

**Comment by LiLoDavis** [comment]
> This seems to be related to #3736

Yes, both are intended to ensure we adequately cover WCAG 2.4.3 Label in Name.

**Comment by lisli1** [comment]
@LiLoDavis, the text changes are now in Canary. Please verify the changes and close out the issue at your earliest convenience.

**Comment by LiLoDavis** [comment]
Looks good to me.
