### ISSUE TITLE
Contrast > State Changes requirement is missing info & examples content

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#3778]
## Describe the bug

Assessment requirement 24.2 (Contrast > State changes) is missing its info and examples content (it has no "i" icon in its how to fix panel).

Not sure whether we missed ever getting this written or if it's written and we missed integrating it; @ferBonnin / @LiLoDavis , do either of you know if we have this content ready to go already?

**To Reproduce**

1. Start a web Assessment on any page
2. Navigate to 24.2 Contrast > State Changes
3. Observe that is has no "info" icon like all other requirements do

## Expected behavior

Should have info & examples content

## Screenshots

![screenshot of State changes header with blank spot where info button should be circled](https://user-images.githubusercontent.com/376284/103043033-80c11a00-4549-11eb-9a13-463548ad8fdb.png)

## Context (please complete the following information)

- OS Name & Version: Windows/edge stable
- AI-Web Version & Environment: Repros on production 2.22.0 and dev
- Browser Version: 
- Target Page: any

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

n/a

**Comment by LiLoDavis** [comment]
See the attached document for info & examples.
[Contrast__Guidance__NEW_FINAL.docx](https://github.com/microsoft/accessibility-insights-web/files/5766211/Contrast__Guidance__NEW_FINAL.docx)

**Comment by ferBonnin** [comment]
@dbjorge @LiLoDavis this has been addressed; could you please take a look?

**Comment by LiLoDavis** [comment]
> @dbjorge @LiLoDavis this has been addressed; could you please take a look?

Looks good to me.
