### ISSUE TITLE
Making a pass/checkmark and a fail/cross a bit more immediately distinguishable in left-hand panel

### ISSUE THREAD

**Issue by patrickhlauke** [microsoft/accessibility-insights-web#3783]
When trying to quickly skim over the pass/fails in the left-hand bar, the fact that the icons are all grey/monochromatic can (at least for me) make it really tough to spot/differentiate the checkmarks and crosses

![Example of the left-hand panel showing large number of automated test results - lots of checkmarks, one cross, but as they're all grey solid circles with the icon in white in the middle they all look very similar](https://user-images.githubusercontent.com/895831/103102858-07dbc400-4616-11eb-830a-f8eff2ce3d95.png)

I'm not necessarily saying these should use the bright green/red equivalents used elsewhere as that may make the sidebar look a bit too ... garish

![Green checkmark circle and red cross circle used elsewhere in AI](https://user-images.githubusercontent.com/895831/103102971-92242800-4616-11eb-8eb7-ae0218d9c6c2.png)

But perhaps, keeping to the monochromatic theme, something more subtle like making passes just outline grey circles, white interior, and a grey checkmark, while keeping crosses solid grey circles with a white cross (or vice-versa)? Just something that would allow for easier skimming/at a glance recognition.

**Comment by ferBonnin** [comment]
possible duplicate/ similar to #1877

**Comment by ferBonnin** [comment]
thanks for the suggestion @patrickhlauke! 

We are keeping this feature request open for upvotes from the community. 
Previous user testing showed that adding colors was overwhelming for some users and the UI did look too busy, but we could explore subtle changes as suggested. To implement this change, we would need to generate various designs and do user testing first.

**Comment by DaveTryon** [comment]
We're working on a feature of assessment improvements and will consider this as a candidate for that feature. 

Thanks for using Accessibility Insights!

**Comment by patrickhlauke** [comment]
crikey, a blast from the past. glad to hear 👍
