### ISSUE TITLE
Default Headings keyboard shortcut conflicts with macOS screenshot shortcut

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-web#3800]
## Describe the bug
On macOS, the default keyboard shortcut for Headings is Cmd + Shift + 3. This is the same as [the macOS screenshot shortcut](https://support.apple.com/en-us/HT201361).

**To Reproduce**

1. Install AI-Web on a Mac
2. Observe that the default Headings shortcut is Cmd + Shift + 3
3. Attempt to use that shortcut to activate Headings
4. A screenshot is taken

## Expected behavior
Headings is enabled

## Context (please complete the following information)

- OS Name & Version: macOS Catalina 10.15.7
- AI-Web Version & Environment: 2.23.0 Insider, 2.22.0 Prod
- Browser Version: Chrome 88.0.4324.50 Official beta x86_64
- Target Page: any

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
this one and #3801 should be tackled together. In general, we should consider how the different shortcuts affect different OS's and Browsers

**Comment by LiLoDavis** [comment]
@ferBonnin and @peterdur I propose fixing this bug and #3907 by modifying the keyboard shortcuts as follows:

Windows Key | macOS Key | Command
-- | -- | --
Ctrl+Shift+A (was Ctrl+Shift+K) | Option+Shift+A (was Shift+⌘+K) | Activate   the extension
Ctrl+Shift+1 | Option+Shift+1 (was Shift+⌘+1) | Show or hide Automated checks
Ctrl+Shift+2 | Option+Shift+2 (was Shift+⌘+2) | Show   or hide the visual helper for landmarks
Ctrl+Shift+3 | Option+Shift+3 (was Shift+⌘+3) | Show or hide the visual helper for headings

One advantage to using Option+Shift+[letter/number] combinations is that they're not used by MacOS, Edge, or Chrome. Users who follow our example could choose any letter or number without creating a conflict. 

This change is likely to cause some confusion for current users of keyboard shortcuts.

**Comment by LiLoDavis** [comment]
@ferBonnin and @peterdur - New proposal:
Use **Alt** instead of **Ctrl** (Windows) and **Option** instead of **Command** (Mac).

Windows Key | macOS Key | Command
-- | -- | --
Alt + Shift + K | Option + Shift + K | Activate the extension
Alt + Shift + 1 | Option + Shift + 1 | Show or hide Automated checks
Alt + Shift + 2 | Option + Shift + 2 | Show or hide the visual helper for landmarks
Alt + Shift + 3 | Option + Shift + 3 | Show or hide the visual helper for headings

No known/documented conflicts with Edge or Chrome browsers, Windows or Mac operating systems.

**Comment by LiLoDavis** [comment]
It would be super helpful if someone who uses Linux could test and verify that the Windows commands work in Linux without conflicts.

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets look into this. Peter will review Linux to ensure there are no issues. 

Once this bug gets pick up, please sync with PM team since documentation changes and communication to users will be required

**Comment by peterdur** [comment]
OK, a visual pass through Chrome and Edge Dev shows that they keep the same shortcuts across platforms. This is explicitly documented in [Chrome's keyboard shortcuts](https://support.google.com/chrome/answer/157179?co=GENIE.Platform=Desktop&hl=en#zippy=%2Ctab-and-window-shortcuts%2Cgoogle-chrome-feature-shortcuts%2Caddress-bar-shortcuts%2Cwebpage-shortcuts%2Cmouse-shortcuts) list in that a single list is used for Windows and Linux shortcuts.

There are two documented Alt+Shift shortcuts in Chrome: Shift+Alt+t to set focus on the first item in the Chrome toolbar, and Alt+Shift+i to open a feedback form. 

Beyond these, Alt+Shift+b (on both Windows and Linux) sets the focus to the Favorites bar.

There do not seem to be any [Ubuntu shortcuts](https://help.ubuntu.com/stable/ubuntu-help/shell-keyboard-shortcuts.html) that conflict with the Alt+Shift pattern (closest is Alt+Shift+Ctrl+r to start/stop screencast recording)

**Comment by DaveTryon** [comment]
@jalkire, this has bene fixed as described in the [Canary channel](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem). Please close it out at your convenience. Thanks!

**Comment by DaveTryon** [comment]
One note: Canary docs have been updated; production docs will be updated after the next release
