### ISSUE TITLE
Minor text changes in Contrast > UI components and Contrast > State changes

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#3806]
## Describe the problem

In **How to test**, both requirements mention the same exceptions:

> Exception: A lower contrast ratio is allowed if either of the following is true:
> a. The component is inactive/disabled.
> b. The component's appearance is determined solely by the browser.

However, this text could be interpreted as meaning that there's another, lower threshold for these components, when in fact there isn't.

**To Reproduce**

1. Go to **Contrast** > **UI components** or **Contrast** > **State changes**.
2. Look at the content immediately after step 2b.

## Proposed text

> Exception: No minimum contrast ratio is required if either of the following is true:
> a. The component is inactive/disabled.
> b. The component's appearance is determined solely by the browser.

Change the text 

## Are you willing to submit a PR?

No.

**Comment by dbjorge** [comment]
Resolved by @cutePanda123 in #3852 (thanks for the contribution!)

**Comment by ferBonnin** [comment]
@LiLoDavis could you please take a look and close? :)

**Comment by LiLoDavis** [comment]
@ferBonnin Fixed in **Contrast** > **UI Components**, but not yet in > **State changes**.

**Comment by ferBonnin** [comment]
thanks @LiLoDavis! marking this as ready for work to address in **State changes**

**Comment by peterdur** [comment]
@LiLoDavis the State Changes fix should now be in Canary.

**Comment by LiLoDavis** [comment]
Looks good
