### ISSUE TITLE
yarn package manager command has a conflict with hadoop yarn command

### ISSUE THREAD

**Issue by cutePanda123** [microsoft/accessibility-insights-web#3851]
## Describe the bug

yarn package manager command has a conflict with hadoop yarn command

**To Reproduce**
1. install hadoop yarn command first
2. then install yarn package manager command 
3. run the command from yarnpkg with abbreviation yarn install or yarn build
4. see error 
```
~/Codes/accessibility-insights-web$ yarn install
ERROR: install is not COMMAND nor fully qualified CLASSNAME.
Usage: yarn [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    yarn [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
```

## CodePen repro example
N/A

## Expected behavior
run yarn package manager command to install or build without facing any errors

## Screenshots

![image](https://user-images.githubusercontent.com/26092755/106388504-a8e73880-6393-11eb-9ce7-8cb8a22162d0.png)

![image](https://user-images.githubusercontent.com/26092755/106388529-c3b9ad00-6393-11eb-89d9-75e165e948f1.png)

## Context (please complete the following information)
- OS Name & Version: ubuntu 18.04
- AI-Web Version & Environment: 1.0.4
- Browser Version: N/A
- Target Page: N/A

## Are you willing to submit a PR?
Yes.

## Did you search for similar existing issues?
Yes, I did. This is a new issue.

## Additional context
I was following the [wiki ](https://github.com/microsoft/accessibility-insights-web/blob/master/docs/building-web.md)in the readme to set up my dev environment with yarn install and yarn build. However, I got an error as above.

After I investigated the error, I found the root cause is the yarnpkg command is conflicting with the pre-installed Hadoop Yarn command in the system. The same issue and proposed fix is described in this StackOverflow link. https://stackoverflow.com/questions/44739402/hadoop-yarn-vs-yarn-package-manager-command-conflict

I would propose the yarn command mentioned in the readme can be more specific to use yarnpkg which is the full name of the yarn package manager command and it avoids conflicts with Hadoop yarn. I have tried the 'yarnpkg install' and 'yarnpkg build' command locally in my machine and they worked well without conflict.

**Comment by pownkel** [comment]
As far as I can tell, the `yarnpkg` solution mentioned here seems like the usual solution for this problem. We should make a note of this in the build instructions and update any dev scripts that use the `yarn` command.

**Comment by ferBonnin** [comment]
Per conversation with Peter, we should document this.

**Comment by pownkel** [comment]
The docs changes have just been merged. @cutePanda123 can you take a look and close this bug if that fixes the problem?

**Comment by cutePanda123** [comment]
Just checked the note about yarn vs yarnpkg in the readme. It looks good to me. Closed the bug.
