### ISSUE TITLE
Info panel as a web permalink

### ISSUE THREAD

**Issue by mhulse** [microsoft/accessibility-insights-web#3853]
I would love to be able to have a web permalink, where I can link to the tips/docs found in the various info panels used throughout the sections of the plugin.

For example, I wanted to share this information with my coworker, and it would be nice to not have to say "open up the plugin and navigate to the section ....": 

![](https://user-images.githubusercontent.com/218624/106524050-e08ad900-6496-11eb-96fe-b4b8ff4b0db4.png)

The information found within the AIW plugin is very valuable. A web version of this information would be very helpful.

**Comment by peterdur** [comment]
Duplicate/upvote of #2057?

**Comment by mhulse** [comment]
> Duplicate/upvote of #2057?

Oh my gosh, you're right! I feel so silly that I didn't find that. Thank you for pointing me in the right direction!

**Comment by ferBonnin** [comment]
@mhulse thank you for the feature request and for upvoting #2057!

**Comment by mhulse** [comment]
https://accessibilityinsights.io/info-examples/
