### ISSUE TITLE
Landmark best practice rules should not be flagged as failures

### ISSUE THREAD

**Issue by ferBonnin** [Microsoft/accessibility-insights-web#390]
## Describe the bug
This four rules should be best practice and not flagged in automated checks

* unique-landmark
* landmark-complementary-is-top-level
* landmark-banner-is-top-level
* landmark-contentinfo-is-top-level
* landmark-main-is-top-level
* landmark-no-duplicate-banner
* landmark-no-duplicate-contentinfo

**To Reproduce**
1. run automated checks in this page: https://webaim.org/intro/
unique-landmark rule is marked as failed

## Expected behavior
unique-landmark rule does not fail

## Extension (please complete the following information)

- OS: Windows
- Version 2.0.5
- Chrome Version 72.0.3626.121
- Target Page https://webaim.org/intro/

## Are you willing to submit a PR?
No

If asked, will you be willing to submit a PR to fix this bug? 
No

## Did you search for similar existing issues?
Yes

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
Yes

## Additional context
Reported in Twitter: https://twitter.com/jared_w_smith/status/1107791754206441472

**Comment by dbjorge** [comment]
The fix to omit the rules as best practices is straightforward (add `BestPractice` to the corresponding link configurations in `rule-to-link-mappings.ts`), but doing so revealed an issue where old assessments in progress with state for rules that were removed cause DetailsView to crash on load, so that will need to also be resolved as part of this fix.

**Comment by dbjorge** [comment]
There are two more affected rules to fix, so re-opening/editting description

* landmark-no-duplicate-banner
* landmark-no-duplicate-contentinfo
