### ISSUE TITLE
Default shortcuts should NOT be the same as browser ones. Example: In Edge, Ctrl+Shift+K is "Duplicate tab" shortcut

### ISSUE THREAD

**Issue by guillermorueda** [microsoft/accessibility-insights-web#3907]
## Describe the bug

**To Reproduce**

1. In Edge, press Ctrl+Shift+K
2. Expect the current tab to be duplicated (default shortcut behavior)
3. Instead, [Accessibility Insights add-on has taken over the shortcut](https://accessibilityinsights.io/docs/en/web/reference/keyboard/), and just opens

## Expected behavior

All shortcuts should not override default Edge shortcuts. Pressing Ctrl+Shift+K should still duplicate the current tab, instead of opening this add-on.

## Screenshots

![image](https://user-images.githubusercontent.com/1143812/107714647-83efa100-6c82-11eb-8cbe-2ad74895e1af.png)
![image](https://user-images.githubusercontent.com/1143812/107714928-024c4300-6c83-11eb-855b-b5e37a0e3c6f.png)

**Comment by RobGallo** [comment]
Related to issue #3800 .

**Comment by ferBonnin** [comment]
As a workaround, Keyboard shortcuts can be customized by going to edge://extensions/shortcuts or by opening the extension and selecting Keyboard shortcuts in the pop-up menu ([detailed instructions to customize keyboard shortcuts](https://accessibilityinsights.io/docs/en/web/reference/keyboard/#custom-keyboard-shortcuts))

**Comment by LiLoDavis** [comment]
@ferBonnin and @peterdur I propose fixing this bug and #3800 by modifying the keyboard shortcuts as follows:

Windows Key | macOS Key | Command
-- | -- | --
Ctrl+Shift+A (was Ctrl+Shift+K) | Option+Shift+A (was Shift+⌘+K) | Activate   the extension
Ctrl+Shift+1 | Option+Shift+1 (was Shift+⌘+1) | Show or hide Automated checks
Ctrl+Shift+2 | Option+Shift+2 (was Shift+⌘+2) | Show   or hide the visual helper for landmarks
Ctrl+Shift+3 | Option+Shift+3 (was Shift+⌘+3) | Show or hide the visual helper for headings

One advantage to using Option+Shift+[letter/number] combinations is that they're not used by MacOS, Edge, or Chrome. Users who follow our example could choose any letter or number without creating a conflict. 

This change is likely to cause some confusion for current users of keyboard shortcuts.

**Comment by guillermorueda** [comment]
Ctrl+Shift+A (and other Ctrl+Shift+<Letter/Number>) are indeed used by Edge directly:
![image](https://user-images.githubusercontent.com/1143812/108546630-3be20700-729e-11eb-8c0d-fad47f0ff7ba.png)

If it's going to be impossible/too hard to find a shortcut that works consistently across OSs, some options to consider are:
1. Have different shortcuts based on OS/browser
2. Support shortcuts, and include the "suggested" default values, but **make the shortcut functionality optional (and disabled by default)**. If done this way, the issue isn't just transferred to users (i.e. "you can go to your settings and change the shortcut"), or for users that may sparingly/occasionally use this extension, they can have it without shortcuts instead of opting for uninstalling it to avoid having to deal/maintain shortcuts.

I use the extension no more than once a month, so I took the #2 route, as I can just install it again when I need it and then put it away until I need it again... I'm sure the team rather have the people not having shortcuts than removing the extension) :-)

**Comment by ferBonnin** [comment]
We don't see ctrl + shift + A in the [list of documented shortcuts ](https://support.microsoft.com/en-us/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad) (and a few weeks ago, ctrl + shift+ K was also not documented) is there more up to date documentation we should be looking at? it would be much easier to find a shortcut that works consistently if we had the complete docs :)

Shortcuts are a way to provide a more usable and accessible experience for some users and having them off by default would be detrimental for this use case; that is not an option we would like to explore

**Comment by ferBonnin** [comment]
marking this as blocked for continuing the investigation until we have a complete list of shortcuts

**Comment by LiLoDavis** [comment]
@guillermorueda you are correct. I made a mistake when I said Ctrl+Shift+[letter/number] wasn't used. It's only the numbers that aren't used. 

I don't see Ctrl+Shift+A in the list of [Keyboard Shortcuts for Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad). I don't have **New Application Guard window** in my Edge menu because I haven't enabled Application Guard. I'll investigate to see whether that shortcut is configurable.

Also, I wanted to be sure you know our shortcuts can be disabled. Go to edge://extensions/shortcuts and clear the shortcut by selecting the X next to it.

**Comment by guillermorueda** [comment]
@LiLoDavis, thanks for the quick response/turnaround. Regarding disabling shortcuts, it's not possible (I don't know if there's a way to mark them as optional). When I click on the X to remove it, it gets repopulated with the default when I move the cursor away, effectively not being able to remove it.

**Comment by LiLoDavis** [comment]
@guillermorueda I see you are correct again - I can't disable the shortcut for activating the extension. It *looks* like it's cleared, but it resets when I close the window. Other extensions behave the same way.

**Comment by LiLoDavis** [comment]
New proposal: 
Use **Alt** instead of **Ctrl** (Windows) and **Option** instead of **Command** (Mac).

Windows Key | macOS Key | Command
-- | -- | --
Alt + Shift   + K | Option +   Shift + K | Activate the extension
Alt + Shift + 1 | Option + Shift + 1 | Show or hide Automated checks
Alt + Shift   + 2 | Option +   Shift + 2 | Show or   hide the visual helper for landmarks
Alt + Shift + 3 | Option + Shift + 3 | Show or hide the visual helper for headings

No known/documented conflicts with Edge or Chrome browsers, Windows or Mac operating systems.

**Comment by DaveTryon** [comment]
@guillermorueda, this has bene fixed as described in the [Canary channel](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem). Please close it out at your convenience. Thanks!

**Comment by guillermorueda** [comment]
Thanks a lot Dave... Was the code changed but not the documentation? Or am I not understanding it? I thought the change was to use "Alt" key instead of "Ctrl" key:
![image](https://user-images.githubusercontent.com/1143812/119863232-349a4d00-bece-11eb-8e82-e43bf501d10c.png)

**Comment by ferBonnin** [comment]
@guillermorueda documentation changes are also in canary and will be push at the same time we release Accessibility Insights for Web to production
