### ISSUE TITLE
Android: No graceful recovery from "Disconnected device" scenario

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#3938]
## Describe the bug

If the user disconnects their Android device, we have a device disconnected dialog and associated recovery path that attempt to get the user back into a usable state. Due to port forwarding and ADB's behavior, though, the recovery doesn't work and the user's only viable option seems to be to exit the app and restart.

The root problem is that ADB knows when a device is disconnected and removes any port forwarding for that device.

**To Reproduce**
1. Open a command prompt where you can run adb
2. Before starting the unified client, run **adb forward --list** and you'll get back an empty string
3. Start the unified client and run an automated scan
4. From your command prompt, run **adb forward --list**. You'll get back the device ID, the local port, and the device port, something like `ce11182b4587381d0b7e tcp:62442 tcp:62442`
5. Disconnect the device. If you run **adb forward --list**, you'll get back an empty string because ADB automatically removes the port forwarding when the device is disconnected
6. Click "Start over". You'll get the device disconnected dialog. 
    1. If you choose the rescan option, you'll just get the same device disconnected dialog
    2. If you choose to connect a new device, you'll be taken back to the "Connected and ready to go!" dialog (independent of if you've actually connected the device or not, which is a related bug). Assuming you've attached the device, port forwarding is not configured, so you can't talk to the service.
    3. If you choose to go all the way back to the page where we scan for devices, you'll eventually reach a point where you receive the "Port forwarding failed" dialog, and you're stuck. I've confirmed that occurs on Mac and Windows, and am assuming that it will also happen on Linux.

## Expected behavior

We should be able to gracefully recover and get the user connected to the same or a different device. The flow should follow the same pattern as connecting a device when the app is first launched.

Some implementation ideas:
- Remove the "Rescan" button from the dialog if the port forwarding no longer exists (detect using `adb forward --list`).
- When the user clicks on "Reconnect device", start with the first setup step instead of the last, so the user always goes through all setup steps. Most of these will transition automatically if the service is already running on the device, so the user impact is negligible in the simple case.
- Explicitly clear the the forwarded port every time we enter the port forwarding step. If this seems too heavy-handed, we could choose to keep the port previously mapped to this device if `adb forward --list` shows that an appropriate port mapping already exists.

## Context (please complete the following information)

- OS Name & Version: Repro'ed on Windows and Mac, didn't check Linux
- AI-Web Version & Environment: Current unified builds

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

Looking back through the change history, the "device disconnected" scenario predates the changes that automated configuring the device for scanning, and the automated configuration feature didn't consider implications to the device disconnected scenario.

**Comment by ferBonnin** [comment]
per conversation with Peter, let's explore option #2: "When the user clicks on "Reconnect device", start with the first setup step instead of the last, so the user always goes through all setup steps. Most of these will transition automatically if the service is already running on the device, so the user impact is negligible in the simple case."

**Comment by DaveTryon** [comment]
Fixed
