### ISSUE TITLE
Date stamp of report is always 19700101

### ISSUE THREAD

**Issue by Bram-diederik** [microsoft/accessibility-insights-web#3995]
If you export a report it should have the date added to the file name. but with the current version: 2.23.0 
the date in the filename is always 19700101

**Comment by jalkire** [comment]
I am able to repro this with the following steps:
1. Navigate to a new page
2. Launch assessment directly from the launchpad
3. Click start new on the dialog
4. Export result

If I first launch fastpass and then navigate to assessment, the problem goes away until I follow those steps again.

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets fix this. The time we should show on the report should be either the time the user selects the " export result" button or the time when the user did their first requirement. The first option is probably the more straightforward one.

**Comment by ferBonnin** [comment]
Hi @Bram-diederik this has been addressed and its now available in our [Canary extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem) please let us know what you think!
