### ISSUE TITLE
Add colour contrast fix to the output

### ISSUE THREAD

**Issue by Badlapje** [microsoft/accessibility-insights-web#4013]
## Is your feature request related to a problem? Please describe.
When doing an audit and checking for colour contrast, I often want to implement a fix quickly.  Being a simple-minded developer I am not good with colours.  I have no idea how i can easily find a colour that does pass the contrast test.  Let alone one which is close to the original colour.  Left to fix it myself, everything would turn into black on white.  
As an accessibility auditor I have the same problem from another angle: I want to be able to advise clients what a possible fix could be.  But as mentioned above: I have zero feeling for colours & zero knowledge on how to find a possible passing colour.

## Describe the desired outcome
I would love it if each failure in contrast came with a suggestion for how to fix it for both 4.5:1 and 7:1.  As in the closest colour for both background and foreground which by itself would fix it.  Eg. foreground colour of #ffffff and background colour of #efefef have a contrast of 2, if you change the foreground colour to #xxxxxx it's 5:1, if you change the background colour to #zzzzzz it's 6:1.  To get a result of 7:1 use #wwwww as a foreground or #llllll as a background.

## Describe alternatives you've considered
I currently use [the tota11y plugin from Khan academy](https://khan.github.io/tota11y/), which gives a suggestion for how to fix contrast by specifying the option for the foreground.

## Additional context
current output
![failed-colour-contrast](https://user-images.githubusercontent.com/4058016/110602132-f5d5e000-8185-11eb-9cf7-63b97603b519.png)

Output of tota11y
![image](https://user-images.githubusercontent.com/4058016/110602469-55cc8680-8186-11eb-84a4-659c99a2b92e.png)

**Comment by ferBonnin** [comment]
thanks for the suggestion @Badlapje! We are taking a look at this request

**Comment by ferBonnin** [comment]
This feature has now been addressed and its available in Production
