### ISSUE TITLE
Allow for merging results from another page or single rule failures from other pages

### ISSUE THREAD

**Issue by Badlapje** [microsoft/accessibility-insights-web#4014]
## Is your feature request related to a problem? Please describe.
When creating a report using Accessibility Insights it's tedious to have to do it page/page on a website.  Certain rules are obviously going to evaluate the same because the template/colours are the same.  Whereas other rules only come in to play on specific pages (eg. only one page with embedded video).  Generating separate reports per page is possible, but presenting that to a developer means there are now several files, each of which can be overlooked.

## Describe the desired outcome
Add the possibility of adding the results of a single rule tested on another page to a main report for a site: pick one starting page where as many rules as possible are tested, then add results for other rules (or even the same ones) tested on other pages as necessary.
This may be related to #653 

## Describe alternatives you've considered
- Currently i copy/paste the html from multiple reports together.  Which is time-consuming.  
- I've tried using separate files, but that looks unprofessional and increases the likelihood something is overlooked.  
- Another option is to add a fail on the page being tested and then adding a failure note for another page to it, specifying which page and what element failed.  But that again looks less professional (though possible for internal reports) & is not possible for each rules as not each rule allows for adding failure notes.

**Comment by dbjorge** [comment]
Thanks for filing an issue! Could you help us understand the scenario a little more?

* Are you interested in this for Assessment results, FastPass results, or both? If both, is one higher priority than the other?
* Do you have an impression of whether "common between pages" vs "unique per page" issues are more common in your usage?
* When you stitch together multiple reports manually like you describe, what have you found is the most useful way to organize the combined report? Do you have a preference for organizing everything rule-first vs organizing by-group-of-pages vs something else? If you have an example handy of one of these hand-merged reports that you think would be an ideal example, that would be very helpful!
* When you're performing an assessment across multiple pages, do you have a preference between going test-by-test (ie, go through the "Landmarks" test for each page before moving on to "Headings") or page-by-page (ie, go through each test for one page before moving on to the next) or something else?

**Comment by Badlapje** [comment]
>     * Are you interested in this for Assessment results, FastPass results, or both? If both, is one higher priority than the other?

For Assessment only really.  Fastpass is nice as a quick checkup, but not really to create a report that i want to pass along.
 
>     * Do you have an impression of whether "common between pages" vs "unique per page" issues are more common in your usage?

Issues are more common between pages, as should be expected for any site where a design system or component library is used.  But every site has a couple of "unique per page" issues.  
 
>     * When you stitch together multiple reports manually like you describe, what have you found is the most useful way to organize the combined report? Do you have a preference for organizing everything rule-first vs organizing by-group-of-pages vs something else? If you have an example handy of one of these hand-merged reports that you think would be an ideal example, that would be very helpful!

I'll post an example after my next audit, which should be sometime this week.  I prefer to organize rule-first.  Mostly because it's easier to address one issue during development that way.

>     * When you're performing an assessment across multiple pages, do you have a preference between going test-by-test (ie, go through the "Landmarks" test for each page before moving on to "Headings") or page-by-page (ie, go through each test for one page before moving on to the next) or something else?

I prefer to go page-by-page.  I also won't retest everything on all pages.  Sometimes it's immediately clear that some tests will yield the same result.  Eg. it's a page with yet another blogpost where the difference is the presence of multimedia, or if it's the same header / footer with textual content.  It makes sense to retest headings for the changed content, but it doesn't make sense to retest contrast for the same colour.
