### ISSUE TITLE
Add possibility to add other possible issues that are found

### ISSUE THREAD

**Issue by Badlapje** [microsoft/accessibility-insights-web#4015]
## Is your feature request related to a problem? Please describe.
When evaluating a page not all possible issues are currently in the tests.  Sometimes there are issues on / suggestions for a page that are not covered by WCAG SC, but which are good to make a note of none the less.  That currently cannot be done using Accessibility Insights.

## Describe the desired outcome
Add the possibility of adding suggestions / additional feedback, under either a self-specified title, or under a general "other feedback" title.  Ideally, that'd also give the option of adding links with more information about the issue and/or links with information on how to fix the issue.

## Describe alternatives you've considered
Currently i simply adjust the html of the generated page, or i create a report in a word document allowing me to add whatever i want.

## Additional context
This may be related to #653 and #4014

**Comment by dbjorge** [comment]
Thanks for filing the issue!

Adding freeform feedback/suggestions is one of the intended uses of the freeform "result description" text field in the "export results" dialog box pictured below:

![screenshot of "export report" dialog box](https://user-images.githubusercontent.com/376284/110695646-23d41800-81b8-11eb-83da-3e467493c3b9.png)

I think I'm probably misunderstanding your feature request; it's not clear to me what you're asking for that this doesn't already provide (besides support for hyperlinks). Would adding hyperlink support to this description meet your request, or is there something more specific that you're looking for? If the former, would you be satisfied with something like "supporting some limited form of markdown in the box", or would you be looking for something with a more complex editor experience?

**Comment by Badlapje** [comment]
> Adding freeform feedback/suggestions is one of the intended uses of the freeform "result description" text field in the "export results" dialog box pictured below:
> I think I'm probably misunderstanding your feature request; it's not clear to me what you're asking for that this doesn't already provide (besides support for hyperlinks). Would adding hyperlink support to this description meet your request, or is there something more specific that you're looking for? If the former, would you be satisfied with something like "supporting some limited form of markdown in the box", or would you be looking for something with a more complex editor experience?

Adding hyperlink support or markdown support would be nice, but doesn't really address my problem.  

Currently not all WCAG SC are incorporated.  It would be nice to state that i want to run a AAA test so those get added.  Or to allow me for adding them.

In the same spirit it'd be nice to be able to add other tests, currently not in WCAG.  These would be manual (as would the missing ones from AAA).  But being able to add those in a way that yields the same format as the tests which are part of the tool would be nice.  That'd mean the tool is a very nice basis, but flexible enough to allow me to add other tests when they make sense.
