### ISSUE TITLE
Allow for marking all subtests as passed/fail

### ISSUE THREAD

**Issue by Badlapje** [microsoft/accessibility-insights-web#4019]
## Is your feature request related to a problem? Please describe.
When testing certain pages, some things like timed events are no issue because there is no content of that type.  Currently you have to open each sub-test and hit pass in order to go through that test.  I've had several times during an audit that i could already see all subtests were going to pass because they simply do not apply to that page.

## Describe the desired outcome
It would be nice to have a general toggle per test so that we can mark all subtests as passed/failed if needed.  For me personally only the passed is needed, but maybe others need failed as well.
Additionally, a button "pass unmarked instances" for the rest of the test would be cool to allow for one subtest that needs review when the others don't (eg. with the images test, only image function was useful during my last page test, the others were not applicable)
## Describe alternatives you've considered
Not mentioning results for the test, but my OCD kicks in at that point.

**Comment by dbjorge** [comment]
This is interesting to think about! I'm not sure it would make sense for us to do this for all tests (most of the tests don't have exactly the same criteria for all sub-tests), but I agree that there are a few cases where it might make sense to add something like this. For example, I can see it being reasonable to offer some way to skip all the Multimedia tests if the user attests that there is no pre-recorded multimedia content on the page.

We'd want to be cautious about whether adding something like this might accidentally encourage folks to skip sub-tests prematurely, especially for folks that are newer to using the extension and might not be as familiar with what individual sub-tests would be targeting.

**Comment by Badlapje** [comment]
I'm not sure what feedback is required here?

To alleviate the concern about newer folks, the ability to skip other sub-tests could be a setting you need to toggle?

**Comment by ferBonnin** [comment]
oops! reopening this! 

@juchampa can you please clarify what is the additional author feedback needed?

**Comment by DaveTryon** [comment]
We're working on a feature of assessment improvements and will consider this as a candidate for that feature. 

Thanks for using Accessibility Insights!
