### ISSUE TITLE
Run checks in both light mode & dark mode

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#4026]
## Is your feature request related to a problem? Please describe.
I'd like Accessibility Insights to scan the site and evaluate for both dark mode and light mode, rather than just the state that the browser (or OS) is currently configured for. Why doesn't axe just test for all options available in prefers-color-scheme?

## Describe the desired outcome
Often personalization is forgotten. If we can easily test for light/dark modes, then we can ensure that contrast issues are not overlooked in alternate user preferences. 

## Describe alternatives you've considered
Users could run it twice (but they won't).  It could be fixed in axe.

**Comment by juchampa** [comment]
Hi @mgifford! That is a good feature request, have you made any request to axe? The current solution is what you mentioned for user to test in both dark & light mode.
