### ISSUE TITLE
Semantics > Headers attribute: Visual helper needs styling changes to reduce size of labels

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#4027]
## Describe the bug

The labels in the new visual helper obscure the cells in tightly-spaced data tables. When that happens, the visual helper isn't helpful at all.

**To Reproduce**

1. Go to [WCAG Failure 90](https://www.w3.org/WAI/WCAG21/working-examples/failure-table-headers-incorrect-association/)
2. Open Accessibility Insights for Web (Canary) and select Assessment.
3. Start a new assessment.
4. Go to **Semantics** > **Headers attribute** and turn on the visual helper for the first instance.
5. See that the table cells are obscured by the labels drawn by the visual helper.

## Expected behavior

The labels drawn by the visual helper should not obscure the table cells.

Recommendation: Change the styling of the visual helper for this requirement.
1. Change the labels' font size to 0.5em*
2. Remove the padding*

*The label text will likely be much smaller than the text in the page, but users can make it more legible by using the browser zoom.

## Screenshots

Current styling:
![image](https://user-images.githubusercontent.com/45569509/110837072-a959d580-8255-11eb-94e6-6ed15ba860c0.png)

Proposed styling:
![image](https://user-images.githubusercontent.com/45569509/110837250-d8704700-8255-11eb-8240-2d8b53cbc51f.png)

## Context (please complete the following information)

- OS Name & Version: Microsoft Windows 10 Pro version 10.0.18362 Build 18362
- AI-Web Version & Environment: Version 2021.3.10.1837 Canary
- Browser Version: Microsoft Edge Version 89.0.774.45 (Official build) (64-bit)
- Target Page: https://www.w3.org/WAI/WCAG21/working-examples/failure-table-headers-incorrect-association/

## Are you willing to submit a PR?

No.

## Did you search for similar existing issues?

Yes.

## Additional context

None

**Comment by dbjorge** [comment]
I agree that we should do something to improve the UX here with small table cells, but I don't feel that .5em text is sufficiently accessible for a user that already needs to use high zoom levels with standard-sized text. Are there alternatives we could consider (eg, options for moving the text outside the highlight box, or omitting it if the box is too small)? Perhaps we could ask the design folks for more ideas?

**Comment by LiLoDavis** [comment]
> I agree that we should do something to improve the UX here with small table cells, but I don't feel that .5em text is sufficiently accessible for a user that already needs to use high zoom levels with standard-sized text. Are there alternatives we could consider (eg, options for moving the text outside the highlight box, or omitting it if the box is too small)? Perhaps we could ask the design folks for more ideas?

Exploring alternatives is a good idea.

**Comment by peterdur** [comment]
Brainstorming for your consideration....

If users were to look at one row's visual helper at a time, we could move the text outside the highlight box as Dan suggests above:
![image](https://user-images.githubusercontent.com/1752950/111233185-be15d080-85a9-11eb-8e69-070958316872.png)

Thinking about the one-row-at-a-time approach more, what we highlight shows the relationship between id and headers attributes, so they might be redundant, at least for the purpose of instruction 2c:
![image](https://user-images.githubusercontent.com/1752950/111232648-c28db980-85a8-11eb-80c2-e055697a1721.png)
With the reduced visual clutter, the incorrect reference to the header in the second row is more apparent.

To do 2a with this approach, turn all visual helpers on, and inspect any headers that are not highlighted (or we could add all headers to the instance list, not just ones with header attributes, and look at the element information). To do 2b, turn all visual helpers on, and look for any table cells that are not highlighted.

**Comment by LiLoDavis** [comment]
@peterdur I really like the reduction of clutter in your second alternative, And because we include a code snippet in the report (oops, twice!), sufficient information to identify the problem cells will be included automatically in the report.

**Comment by ferBonnin** [comment]
Per conversation with Peter, let's try option 2, we should also only include the code snippet in the report once if possible

**Comment by ferBonnin** [comment]
one more comment, when picking up this bug, please loop in @LiLoDavis for reviewing UI changes and its likely the instructions will need to change slightly too

**Comment by ferBonnin** [comment]
verified in Canary
