### ISSUE TITLE
Color-contrast produces false-positive on elements during transition/animation

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#4144]
## Describe the bug

Color-contrast produces a failure in automated checks on an element while the DOM may be animating/transitioning around it.

**To Reproduce**

Note: these failures are not real failures and only occur randomly and rarely.

1. Go to https://visualstudio.microsoft.com/
2. Scroll to the carousel.
3. Keep scanning until issues are seen (like screenshot below).

## Expected behavior

These should not be errors.

## Screenshots

![image](https://user-images.githubusercontent.com/32555133/115935605-69873000-a448-11eb-8d87-72103ab0011e.png)

## Context (please complete the following information)

- OS Name & Version: MacOS Big Sur
- AI-Web Version & Environment: Version 2.25.0
- Browser Version: Edge 90.0.818.46
- Target Page: https://visualstudio.microsoft.com/

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
per triage conversation, assigning to @waabid

**Comment by lisli1** [comment]
A similar issue was found when there is white text overlaying images with lazyload behavior. Before scrolling down to the images, AI Web would find the color contrast issues. The color contrast issues are not present when scrolling down the page far enough to load the images (no color contrast issues by the time the user can view the images/text). Additionally, the color contrast issues are not present when CSS is disabled for the page.

**Comment by waabid** [comment]
My idea was to add something like this:

![image](https://user-images.githubusercontent.com/32555133/123671361-08d2f580-d7f3-11eb-846a-1f38e9d5bcc5.png)

This extra text on the bottom would only show if permissions were not granted. I believe we could decide then what this should do: ask for permissions or point to the "learn more" page. The latter might be more appropriate if we feel like the text isn't sufficient and we want to add something longer (that might not fit as nicely and hence, maybe something short for the learn more page).

**Comment by dbjorge** [comment]
The service has a bit at `packages\scanner-global-library\src\page-navigation-hooks.ts` that injects some CSS that disables animations on target pages. I think we have similar in our own e2e tests of ourselves. We might consider applying something similar to target pages.

**Comment by DaveTryon** [comment]
After reviewing the full list of issues in our backlog, we have concluded that we will not be addressing this issue.
