### ISSUE TITLE
Stuck at Scanning 98% when displaying automated checks from an assessment scan done by 2.0.5

### ISSUE THREAD

**Issue by peterdur** [Microsoft/accessibility-insights-web#416]
## Describe the bug

Found during insider validation of 2.1.0

**To Reproduce**
Steps to reproduce the behavior in dev
(example-site = a site of your choice with automated checks failures)

1. Build master as of commit f442d154554325f989e5cab11c2efa20eb9bba83 (release 2.0.5)
1. Start Chrome, go to chrome://extensions/ and update the extension
1. Start Chrome, right-click the extension button and choose "Inspect popup"
1. In DevTools, go to Application tab, Application > Clear storage, and click "Clear site data"
1. Close Chrome
1. Restart Chrome
1. Go to example-site
1. Open the extension popup, respond to telemetry prompt, and choose "Assessment"
1. Go to "Automated checks"
1. **Observe:** spinner says Scanning and counts up; soon automated check results are displayed.
1. Close Chrome
1. Build master as of commit 5be51c7faa7a370ac321be370528784343cad37e (release 2.1.0)
1. Restart Chrome, go to chrome://extensions/ and update the extension
1. Go to example-site
1. Open the extension popup and choose "Assessment"
1. Click "Continue previous" at the prompt
1. Go to "Automated checks"
1. **Observe:** spinner says Scanning 98% and never completes

## Expected behavior

Saved automated check results should be displayed.

## Screenshots

<img width="637" alt="54788712-46e11800-4bed-11e9-922b-01a93159db3a" src="https://user-images.githubusercontent.com/1752950/54789907-709c3e00-4bf1-11e9-9938-b7da4bccb703.png">

## Extension (please complete the following information)

- OS: Windows
- Version 2.1.0
- Chrome Version 72.0.3626.121
- Target Page (example-site)

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Fix not yet identified.

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)? Yes

**Comment by ferBonnin** [comment]
@peterdur is this fixed?

**Comment by peterdur** [comment]
This is fixed and released. Closing.
