### ISSUE TITLE
web/chrome 91: first-time telemetry dialog is visually cut off

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#4178]
## Describe the bug

During 2.26.0 validation, we found an incompatibility between Chrome 91 (current Chrome Beta) and the extension's first-time telemetry prompt dialog. The dialog's contents aren't being given the full height of the dialog to render in, and get squashed down to a ~80px height with a scrollbar (see screenshot below)

Unfortunately, opening the F12 developer tools in the popup during the repo causes the issue to stop reproing, and I am not able to repro the same issue when viewing the popup.html page in a standalone window (like our E2E tests do), so it's going to be a guessing game with trying CSS changes to work around the issue.

I was unable to find an existing Chromium bug tracking the issue, but their bug tracker does have a big banner across the top right now about how their search feature is broken and not returning all the results it should, so it's definitely possible there is a bug tracking this that I'm not able to search for right now.

Repros on all combinations of Mac, Windows, 2.25.0, 2.26.0 in Chrome Beta (Chromium 91). Does not repro in Chrome Stable or Edge Stable (both Chromium 90).

**To Reproduce**

1. Install Chrome Beta
2. Do a clean uninstall/reinstall of Accessibility Insights (any channel)
3. Open the popup view on any supported page
4. Observe telemetry dialog

## CodePen repro example

n/a

## Expected behavior

Dialog contents should fill the entire dialog window, like in stable browsers

## Screenshots

![screenshot of isssue](https://user-images.githubusercontent.com/376284/116733991-d2c3f180-a9ba-11eb-9e0d-261fa78e49f1.png)

## Context (please complete the following information)

- OS Name & Version: Repros on both Windows 20H2 (OS Build 19042.928) and macOS 11.2 BuildVersion 20D64
- AI-Web Version & Environment: Repros on on both 2.25.0 (current prod) and 2.26.0 (current insider)
- Browser Version: Google Chrome Version 91.0.4472.27 (Official Build) beta (64-bit)
- Target Page: Any

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

n/a

**Comment by ferBonnin** [comment]
@dbjorge do we know when does Chrome 91 will be in prod?

**Comment by dbjorge** [comment]
@ferBonnin May 25 (https://www.chromestatus.com/features/schedule)

**Comment by peterdur** [comment]
Also reproduces on Edge Version 91.0.864.15 (Official build) beta (64-bit)
(including resolving when dev tools are opened)

**Comment by ferBonnin** [comment]
Per conversation with Peter, marking this as high priority since the release is May 25th and its the first thing users interact with (plus its the telemetry permissions)

**Comment by dbjorge** [comment]
The issue doesn't seem to repro under Chromium 92, either (only 91).

I am able to get a repro under dev tools by:

1. Performing the original repro steps
2. Opening F12 dev tools (this loses the repro)
3. From the dev tools console, invoke `window.location.reload()`
4. This reproduces the error state while keeping a dev tools instance open

@waabid helped with some experimentation (on his mac, he didn't need to apply the workaround; for some reason, opening F12 didn't lose the repro for him). Fundamentally, the issue seems to be the Chromium isn't performing a CSS layout/reflow after all of our react components are rendered; making noop modifications to CSS in the F12 tools to force a reflow seems to cause the problem to resolve itself (presumably this is related to the "opening F12 loses the repro" behavior.

The options for working around this are probably to pick one of:
1. Force a reflow after our initial render (for example, by programmatically adding/removing styles from some elements in a `setTimeout`).
2. Use css workarounds that allow for reasonable looking behavior despite the lack of a final layout operation.

Both options are fragile. I think I lean towards option 2 if possible since it's less likely to cause flickering behavior.

The most promising looking place to start seems to be the `max-height: 100vh` office fabric applies to the element at selector `.telemetry-permission-dialog > ms-Modal-scrollableContent`; forcing a `max-height: unset` on that selector works around the issue, but isn't ideal because it creates a scroll bar where there shouldn't be one:

![screenshot showing telemetry dialog with unnecessary scrollbar](https://user-images.githubusercontent.com/376284/117198748-66306480-adb7-11eb-84fc-6a10a2f280e3.png)

This scrollbar only appears in Chromium 91; using the `max-height: unset` fix has no visual impact in Chrome Dev (92) or Edge Stable (90). This is probably good enough to ship (@ferBonnin to confirm) if necessary; I'll play around a little more looking for options to avoid the scrollbar, but I'm probably only going to give that a small timebox.

**Comment by ferBonnin** [comment]
@dbjorge thanks for the detailed investigation. Since the scrollbar only appears in Chromium 91 and this helps address the issue, I am ok with us shipping fix option #2

**Comment by dbjorge** [comment]
Verified as fixed in 2.26.1
