### ISSUE TITLE
Ensures ARIA attributes are allowed for an element's role : aria-labelledby is flagged as invalid on <span> element 

### ISSUE THREAD

**Issue by MohammedAjaz** [microsoft/accessibility-insights-web#4217]
In one of our applications Fast Pass has flagged the below issue and we assume this is incorrect as per ARIA roles & properties recommendation

Repro Steps
1. Open any sample webpage or any .HTML page
2. Add <span> element with aria-labelledby="id_value"
3. Run FastPass feature of Accessibility Insights (axe core 4.2.0)
4. See error - Ensures ARIA attributes are allowed for an element's role

As per ARIA <span> is allowed to have any aria* attribute with no role.
<snip>
span | No corresponding role | Any roleGlobal aria-* attributes and any aria-* attributes applicable to the allowed roles.
</snip>

![AI_FastPass_Failure](https://user-images.githubusercontent.com/70727392/118022890-bce6f280-b311-11eb-9792-83ce456ed081.png)

**Comment by iamrafan** [comment]
@MohammedAjaz thanks for filing the issue. Looks like this should be a needs review instead of a failure. I filed issue https://github.com/dequelabs/axe-core/issues/2933 with axe-core and we shall update you once we fix it

**Comment by ferBonnin** [comment]
@MohammedAjaz we have updated Accessibility Insights for Web to axe-core 4.3.2. Please let us know if the issue has been addressed!
