### ISSUE TITLE
Non-English Interface Support

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#4264]
## Is your feature request related to a problem? Please describe.
Would be great to see Accessibility Insight available in languages other than English. Most of the world doesn't speak English and most non-English speaking sites are getting worse https://webaim.org/projects/million/#languages

## Describe the desired outcome
Accessibility Insights to be used in default browser language. Incorporate French, Dutch, Spanish, etc. support. 

## Additional context
I'm collecting sparse resources https://github.com/accessibility/multilingual

**Comment by ferBonnin** [comment]
duplicate of #3425?

**Comment by mgifford** [comment]
Yes. Sorry.

**Comment by ferBonnin** [comment]
no worries, thanks @mgifford!
