### ISSUE TITLE
Flaky web e2e: timeouts on non-linux agents

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#4271]
## Describe the bug

During 2.26.1 release validation, we found inconsistent timeout issues affecting ~20% of runs.

Builds:
* [20210521.2](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=21116&view=results)
* [20240524.1](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=21117&view=results)

In Mac agents, we most typically saw individual tests timing out (generally hitting 5000ms timeouts).

In Windows agents, we don't see individual tests timing out, but instead see the e2e pipeline step's 15m timeout being hit. 

Investigating/optimizing test performance would help both issues. Migrating from Jest to the playwright runner might also help by adding retries per-test. If those is not possible (or in the meantime until that can be prioritized), easier workarounds might include:

* For Mac: Assign a longer timeout in mac agents (probably via an environment variable set by the pipeline definition to add a multiplier to the e2e timeouts)
* For Windows: Increase the pipeline step timeout

## Expected behavior

E2Es should be reliable

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: windows & linux azure pipelines hosted agents
- AI-Web Version & Environment: 2.26.1
- Browser Version: Puppeteer chromium
- Target Page: varied/local test cases

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

n/a

**Comment by ferBonnin** [comment]
@dbjorge is this bug addressed?
