### ISSUE TITLE
Cancel button is invisible in most Windows HC themes

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#4281]
## Describe the bug

The SVG for the cancel button always uses the default color of black. As a result, it disappears if a Windows user is using any of the black-based High Contrast themes

**To Reproduce**

1. On your Windows machine, enable either HC1, HC2, or HC Black high contrast themes
2. Go to a page (I used https://www.washington.edu/accesscomputing/AU/before.html)
3. Run automated checks
4. Click on any of the exclamation points
5. Look at the top right corner of the popup dialog. The Cancel button exists but it's not visible

## Expected behavior

Cancel button should be visible in all HC modes

## Screenshots

Popup with HC disabled:
![image](https://user-images.githubusercontent.com/45672944/119558611-7607ec80-bd56-11eb-91e6-0c11fd0a3ef0.png)

Popup with HC enabled (using HC 1)
![image](https://user-images.githubusercontent.com/45672944/119558519-55d82d80-bd56-11eb-9c40-de15452b69f9.png)

## Context (please complete the following information)

- OS Name & Version: Windows 10 21H1
- AI-Web Version & Environment: 2.26.1 Production
- Browser Version: Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html

**Comment by ferBonnin** [comment]
reviewed with @peterdur
