### ISSUE TITLE
e2e tests: flaky behavior in cross-origin-iframe.test.ts, wrong number of ruleDetails found

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#4321]
## Describe the bug

`cross-origin-iframe.test.ts` has been flaky on mac. See the [logs of this test run](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_build/results?buildId=21577&view=logs&j=35f60db1-8dd3-569f-bd5d-96748e2bf3e6&t=2fc41186-90ea-5b51-d168-32fb57609ff2&l=45) for test "scanning › with localhost permissions only › does not get results from inside cross-origin iframes"

## Expected behavior

`cross-origin-iframe.test.ts` should pass regularly on mac

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: windows & linux azure pipelines hosted agents
- AI-Web Version & Environment: 2.27.0
- Browser Version: Puppeteer chromium
- Target Page: varied/local test cases

**Comment by karanbirsingh** [comment]
I asked Kelsey for more details and we changed this issue to focus on `cross-origin-iframe.test.ts` because `scanning › with localhost permissions only › does not get results from inside cross-origin iframes` fails with a new signature. It seems like some of the other 5000ms timeout issues are very similar to #4271 and should be investigated together there.

**Comment by karanbirsingh** [comment]
Dan suggests exploring side-effects of the post-message test that timed out beforehand: 

> It sets an 'all-origins' manifest permission that would cause that symptom if it were leaked to the later test

> The original manifest without the override only gets restored on browser close, and the earlier test failed during beforeEach, which would mean that the afterEach (which closes the browser) wouldn't get called. An improvement for that case would be for the ManifestOverride machinery to somehow guarantee that it was starting from a clean copy of the manifest each time, rather than trusting that the content of the manifest at the time a new browser is being spun up to be a clean copy.
