### ISSUE TITLE
Your Docs just cover Setup & Fastpass - I want more! 

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#4322]
## Is your feature request related to a problem? Please describe.
Assessment & Ad hoc tools should be included.  Even if it is just a short blurb and a link to your great videos https://www.youtube.com/watch?v=m1l7ghxOKF0&t=159s&ab_channel=AccessibilityInsights

FastPass is great, but Accessibility is terrific because it doesn't stop with the automated tools.  Highlight what makes you different. 

## Describe the desired outcome

Add sections after "FastPass" & before "Issue filing" that highlight all of the other great stuff your tool can do
https://accessibilityinsights.io/docs/en/android/getstarted/fastpass/

## Additional context

An image for consideration:

![Screen Shot of Accessibility Insights Doc page with Accessibility Insights tool overtop of it](https://user-images.githubusercontent.com/116832/120377963-cf8a9100-c2eb-11eb-8354-e0bcd2a344ea.png)

**Comment by ferBonnin** [comment]
Hi @mgifford thanks for the feature request! 
From the screenshot, I see you are in the Android section, have you checked out the [_for Web_ Section](https://accessibilityinsights.io/docs/en/web/overview/)?

**Comment by ferBonnin** [comment]
@mgifford thanks for the additional feedback and suggestions. We will be looking into adding adhoc documentation and having our General section go before the tools section; after a conversation with the team, we have decided to keep the tools listed in alphabetical order.

**Comment by DaveTryon** [comment]
@nang4ally, assigning to you

**Comment by DaveTryon** [comment]
We have an internal feature that will add AdHoc testing to the https://accessibilityinsights.io, so we're closing this one.

Thanks for using Accessibility Insights!
