### ISSUE TITLE
Improve ad-hoc visualizations on cross-origin iframes

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#4357]
## Is your feature request related to a problem? Please describe.

Some websites reference cross-origin iframes. Our extension requires additional permissions to run scripts on such pages.

If a user runs an ad-hoc visualization without granting these permissions, the extension silently ignores results in these iframes. My example is headings, but other visualizations like tab stops are similar.

missing headings in an iframe ([demo page](https://karanbirsingh.github.io/temp-snippets/microsoft/accessibility-insights-web/iframes/diff-origin.html)) 

![heading inside iframe not highlighted](https://user-images.githubusercontent.com/7775527/121599855-8081e180-c9f8-11eb-8658-bb1459ad745b.png)

However, the user is not presented with a permissions banner in the ad-hoc panel. They need to open the details view and run a scan.

after granting permissions:

![heading inside iframe is highlighted](https://user-images.githubusercontent.com/7775527/121599962-a60eeb00-c9f8-11eb-9ce2-1cc41cb0c4e7.png)

## Describe the desired outcome

A user reached out to us internally asking why the tool wasn't finding their iframe's heading. It would be good if we can reuse the banner UX, or consider an FAQ / setup question to address it.

## Describe alternatives you've considered

We have UX for this for automated checks - when a user attempts either flow, we show a banner:

![a banner asking users to give the extension permissions](https://user-images.githubusercontent.com/7775527/121599116-78757200-c9f7-11eb-9dae-a90e9d01955f.png)

We could consider something similar.

We have a [section in our FAQ](https://accessibilityinsights.io/docs/en/web/reference/faq/#why-does-accessibility-insights-for-web-ask-for-additional-permissions-when-it-detects-iframes) that talks about cross-origin iframes, but it assumes the user has seen the banner.

**Comment by ferBonnin** [comment]
as discussed with the team, we will wait until we hear more from users on this edge case scenario. @waabid mentioned he has some ideas on how to tackle this

**Comment by waabid** [comment]
My idea was to add something like this:

![image](https://user-images.githubusercontent.com/32555133/123671361-08d2f580-d7f3-11eb-846a-1f38e9d5bcc5.png)

This extra text on the bottom would only show if permissions were not granted. I believe we could decide then what this should do: ask for permissions or point to the "learn more" page. The latter might be more appropriate if we feel like the text isn't sufficient and we want to add something longer (that might not fit as nicely and hence, maybe something short for the learn more page).

**Comment by ferBonnin** [comment]
Per conversation with Peter, moving to await community interest to check if this is an issue

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!

**Comment by rickynyairo** [comment]
Hi @DaveTryon I experienced this same issue recently. If you have resolution on how to fix it, e.g as suggested by @waabid , I'd be happy to take it up and raise a PR.
