### ISSUE TITLE
Plans for WCAG 2.2 support

### ISSUE THREAD

**Issue by thibaudcolas** [microsoft/accessibility-insights-web#4369]
👋  thank you for your work on Accessibility Insights! This has been my go-to testing extension since it came out, and from release to release it’s great to see it continuously getting better. I keep on recommending it to everyone who asks where to start when testing accessibility.

## Is your feature request related to a problem? Please describe.

I’m wondering whether you already have any plans for [WCAG 2.2](https://www.w3.org/TR/WCAG22/) support in the extension. I appreciate it’s still in draft and won’t become a recommendation until around the end of 2021 as far as I know, but personally I already think even as drafts the WCAG 2.2 success criteria are very useful things to consider.

## Describe the desired outcome

- Having WCAG 2.2 success criteria available in the Asssessments.
- Having any Axe checks for WCAG 2.2 available in the automated testing (see [issues tagged WCAG 2.2 on axe-core](https://github.com/dequelabs/axe-core/labels/wcag%202.2).
- Perhaps having a way to configure this somewhere, as I imagine WCAG 2.2 won’t be relevant to all users.

## Describe alternatives you've considered

The alternative would be to run Axe separately with experimental WCAG 2.2 checks as they come out, and audit WCAG 2.2 separately to the Assessment wizard.

## Additional context

[What's New in WCAG 2.2 Working Draft](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/)

**Comment by ferBonnin** [comment]
thanks for the feature request @thibaudcolas! We are glad you enjoy using Accessibility Insights.

We do have plans for WCAG 2.2 to be added into Assessment as well as any axe-core automated checks; we will be waiting until WCAG 2.2 is an official recommendation. 
We are also considering doing something similar to how we did with WCAG 2.1 adding a tag that says "_New for WCAG 2.2_" in the new requirements.

**Comment by DaveTryon** [comment]
We have an internal feature to do this once WCAG 2.2 is finalized. Please stay tuned, but we're closing this issue for now.

Thanks for using Accessibility Insights!
