### ISSUE TITLE
documentation issue, missing a check at "Connect to your Android device" 

### ISSUE THREAD

**Issue by Bram-diederik** [microsoft/accessibility-insights-web#4387]
https://accessibilityinsights.io/docs/en/android/getstarted/setup/ gives a good read how to use the tool. and its referred from the software.

But it does not state at the "Connect to your Android device" check that you need to have developer settings enabled on your phone.
I'm sure this is already set for developers. but still i think it would be good if this check is added.

**Comment by JGibson2019** [comment]
Hi @Bram-diederik! Thanks for the feedback! On the setup page section titled "Prepare your test environment", the second point serves as a check/reminder for users to do this; it mentions "If you're testing on a hardware device, you'll need to enable developer options and debugging on your device."

**Comment by Bram-diederik** [comment]
O yes. there its written.  But that section of the page is not shown by the installation process.
The process clearly guides you to https://accessibilityinsights.io/docs/en/android/getstarted/setup/#connect-to-your-android-device. 
and there its missing. 

The process is quite clear. you go to https://accessibilityinsights.io. you end up with a download. There are help in the installation pointing you to sections of a document. 

The process get stuck because the right information is hidden at the requested time. 

Still a documentation bug. Or you need to change the flow of the process by stating you need to read the documentation before installation. which makes it still a documentation bug.

**Comment by JGibson2019** [comment]
Got it! We've added a to do item to update our documentation and make this clearer. Thanks!

**Comment by ferBonnin** [comment]
The Getting started section now states: "If you're testing on a hardware device, you'll need to enable developer options and debugging on your device."
