### ISSUE TITLE
Android: Need to unmaximize window if we redetect the device

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#4491]
## Describe the bug

When we redetect a device after disconnect, the code tries to restore back to the 600x400 size used for the device connection experience. This works when the window is not maximized, but if the window is maximized (or presumably full screen on Mac), the window resize gets ignored.

**To Reproduce**

1. Start the client & scan an app
2. Get to the Automated checks view
3. Maximize the window
4. If you're using a physical device, unplug it. If you're using an emulator, shut down the emulator
5. Click the Start over button
6. When prompted, choose Re-detect device
7. Notice how the connection dialog is still maximized.

## Expected behavior

The connection dialog should be the same size on redetection as it was on the initial detection.

## Screenshots

What the connection dialog is supposed to look like (this is on Windows):
![image](https://user-images.githubusercontent.com/45672944/125865886-1a612b9a-095b-4253-a79b-7c1cd656f5dc.png)

What the connection dialog actually looks like (it's maximized--this is on Windows):
![image](https://user-images.githubusercontent.com/45672944/125866000-dc2ba04a-77c9-4c21-9d91-97f28af1c387.png)

## Context (please complete the following information)

- OS Name & Version: Windows 1- 21H1
- AI-Web Version & Environment: 2021.714.15 Production

**Comment by ferBonnin** [comment]
per conversation with Peter, marking this as won't fix. We agree that this is unexpected behaviour but its not broken as things seem to work fine in this state. Will reactivate if we get user feedback on this.
