### ISSUE TITLE
Android: export dialog disappears if window is resized

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#4492]
## Describe the bug

The export result dialog will disappear if the window is resized to where the export button moves to the "..." menu.

**To Reproduce**

1. Use the export result button.
2. The dialog will show up.
3. Resize window such that the export result dialog moves from the vertical "..." menu to outside of it or vice versa.

## Expected behavior

It should still show the dialog

## Context (please complete the following information)

- OS Name & Version: n/a
- AI-Web Version & Environment: Android

## Are you willing to submit a PR?

Yes

**Comment by ferBonnin** [comment]
reviewed with @peterdur. we should address this
