### ISSUE TITLE
[bug]: Spinner movement is almost imperceptible in system HC modes

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#4513]
## Describe the bug

The movement of the spinner that we display in either Web or unified is almost imperceptible in system HC modes

**To Reproduce**

1. Enable any Windows HC mode
2. Scan a page--especially a complex one that takes some time
3. Watch for movement of the spinner

## Expected behavior

The spinner movement should be clearer

## Screenshots

HC Mode | GIF
--- | ---
HC 1 | ![spinner-hc1](https://user-images.githubusercontent.com/45672944/126560734-6a760d7a-b1dd-42c0-ba70-ba7e254c0169.gif)
HC 2 | ![spinner-hc2](https://user-images.githubusercontent.com/45672944/126560755-66388d07-082b-44e5-b5cb-3e8cfbe562cc.gif)
HC Black | ![spinner-hc-black](https://user-images.githubusercontent.com/45672944/126560776-66a231e7-cf50-4cea-9684-c8124ac2b276.gif)
HC While | ![spinner-hc-white](https://user-images.githubusercontent.com/45672944/126560791-d3254d32-1519-4d34-a1e5-057eb1d7bed5.gif)

## Context (please complete the following information)

- OS Name & Version: Windows 10 21H1
- AI-Web Version & Environment: 2.27.0 Production
- Browser Version:  Google Chrome 92.0.4515.107 (Official Build) (64-bit)
- Target Page: any

**Comment by ferBonnin** [comment]
per conversation with Peter, we should check if this is Office Fabric spinner (and let them know). Regardless, we should fix this

**Comment by ferBonnin** [comment]
per conversation with Peter, closing since its low priority and nice to have. We will revisit if we hear user feedback
