### ISSUE TITLE
HitSlop not taken into account when determining button size

### ISSUE THREAD

**Issue by adrianskogvold** [microsoft/accessibility-insights-web#4595]
## Describe the bug

When testing touch size area of a button the hitslop of the button is not taken into account causing a false positive when testing for a large enough press area.

**To Reproduce**

Create a touchable that is a bit to small to pass WCAG 2.5.5 and then expand it using [hitSlop](https://reactnative.dev/docs/touchablewithoutfeedback#hitslop) to increase the touchable area of the button.
Run an automated check and it will fail on TouchSizeWcag.

## Expected behavior

Expected Accessibility insights to take the hitSlop into account when determining the size of the click area.

## Screenshots
<img width="468" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/18528076/130049280-cc497c69-8f62-42ee-827a-ced76e92808e.png">
Here you can see the yellow area being the button size, while the green area is the buttons touchable area extended by adding a hitSlop.

![AccessibilityFastPassExample](https://user-images.githubusercontent.com/18528076/130050217-fdbb9fbb-0e50-4f4d-8db2-a347d6dbd5c1.png)
Here you can see Accessibility Insights ignoring the hitSlop when determining the touchables size.

## Context (please complete the following information)

- OS Name & Version: macOS Big Sur 11,4  
- AI-Web Version & Environment: AI-Android: 2021.714.15
- Browser Version: N/A
- Target Page: N/A 

## Are you willing to submit a PR?
Yes, but I am unfamiliar with the repo and do not know where or how to fix the issue.

## Did you search for similar existing issues?
Yes, I did not find any other mentions of this issue in this repo, but found someone having the same type of issue with the accessibility inspector on iOS. https://medium.com/reactbrasil/introducing-react-native-accessibility-engine-fcf78f2a3805

**Comment by dbjorge** [comment]
Thanks for reporting the issue, @adrianskogvold !

I've investigated this and found that, while `hitSlop` does impact the pressable target area of the button for non-screen-reader users, it does *not* appear to impact the pressable target area for users of the platform's standard screen reader (Talkback). To test this, I created a simple React Native app that used a `TouchableOpacity` control with `hitSlop` defined, and attempted to single-tap just to the side of the button with Talkback disabled and then with Talkback enabled. The press was registered as expected with Talkback disabled, but with Talkback enabled, only presses within the visible bounds of the control would cause Talkback to recognize and announce the control.

Before we explore considering the `hitSlop` area as part of the target size for accessibility purposes, React Native would need to update its behavior to make sure `hitSlop` gets treated as part of the target size in *all* of the platform-standard input modalities.

**Comment by dbjorge** [comment]
I've marked the issue as resolved because we think Accessibility Insights' current behavior is correct, but please let us know if I've made a mistake in my testing or if the React Native behavior were to change and we'd be happy to take another look!
