### ISSUE TITLE
Automated checks crash target page with out of memory error

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-web#4600]
## Describe the bug
For some users, Accessibility Insights crashes during automated checks on a certain page. It is unclear what difference in environment causes the crash to occur for some but not others.

**To Reproduce**

1. Go to https://amdesigner.azurewebsites.net/
2. Select blank card
3. Run fastpass> automated checks
4. The page crashes after a few seconds with an error code: out of memory

## Expected behavior

The page does not crash

## Context (please complete the following information)

- OS: Windows
- Browser: Chrome Version 92.0.4515.131 (Official Build) (32-bit)
- Extension version 2.27
- Target Page: https://amdesigner.azurewebsites.net/

## Did you search for similar existing issues?

This appears to be similar to #4436. However, the crash still occurs when running axe-core 4.3.0 from console:
```js
await fetch("https://cdnjs.cloudflare.com/ajax/libs/axe-core/4.3.0/axe.min.js").then(r => r.text()).then(src => eval(src));
const results = await axe.run();
console.log(results);
```
## Additional context
@ferBonnin is able to repro this locally. @jalkire is not.

**Comment by ferBonnin** [comment]
marking this as fix since with the latest canary build (that has the latest axe-core version) this is not crashing. Unsure why it was crashing when running with console.
