### ISSUE TITLE
Accessibility insides omits some headings 

### ISSUE THREAD

**Issue by negi4abg** [microsoft/accessibility-insights-web#4707]
## Describe the bug

In guided assessment mode a heading of level 1 is not highlighted if all items of the site menu are closed.

**To Reproduce**

1. Go to https://www.tpgi.com/free-accessibility-testing-tools/#site-substance.
2. Run Accessibility Insides.
3. Start assessment mode.
4. Open "Headings" node and clik on the first test.
5. There is no heading at level 1 highlighted in the grid.
6. Go to the opened webpage and expand the first item from the main navigation - "ARC Platform".
7. Go back to the Accessibility insides window and re-run the headings test.
8. Now the heading one level "Free Website Accessibility Testing Tools" is highlighted in the grid, following these from the expanded area.

## CodePen repro example

No

## Expected behavior

The heading from the level 1 is outside the navigation landmark and should be highlighted no matter if a menu item is opened or closed.

## Screenshots

![image](https://user-images.githubusercontent.com/35510323/134140983-c9a9afc4-0483-4054-aeef-cee3b23e5ea3.png)

![image](https://user-images.githubusercontent.com/35510323/134140695-226e0ba4-ddb0-4cbc-b584-0fbffbd9ddc3.png)

## Context (please complete the following information)

- OS Name & Version: Windows 10 Version 21H1 (OS Build 19043.1237)
- Browser Version: Google Chrome Version 93.0.4577.82 (64-bit)--
- Extension version: 2.28.0
- Target Page: https://www.tpgi.com/free-accessibility-testing-tools/#site-substance

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

No

**Comment by lisli1** [comment]
Hi @negi4abg, thank you for using Accessibility Insights. 

Please help me understand this issue better -- are you asking that there should be a visual indicator for the heading 1 on the target page (the website you are scanning)? I see the H1 shown in the Assessment's lists of instances in both screenshots.
