### ISSUE TITLE
Android: client_OS values in telemetry are not ideal

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#4735]
## Describe the bug

In the Insider telemetry pipeline, the client_OS values in the telemetry are _always_ one of the three values, which map as follows:

OS | client_OS value
--- | ---
Windows | Windows 10
MacOS | Mac OS X 10.15
Linux | Android

In the prod telemetry pipeline, we lose the OS completely, instead reporting the released version. Here's the list of versions I get from the same query against the prod telemetry:

Android 2020.1124
Android 2021.407
Android 2021.414
Android 2021.518
Android 2021.714
Android 2021.826

**To Reproduce**

1. Open the telemetry portal
2. Enter the following query:
```
customEvents
| where timestamp > ago(30d)
| where customDimensions.applicationName == "Accessibility Insights for Android"
| summarize count() by client_OS
```
3. Look at the reported values

## Expected behavior

In an ideal world we would be able to use the `client_OS` field to determine the environment in which the product is being run. In practice, we get what is essentially a repeat of the `customDimensions.applicationVersion` field.

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
We are using the _properties.os_ to get the OS value in the prod db. This returns Windows or Mac (Darwin).

**Comment by DaveTryon** [comment]
Confirming what @ferBonnin added above, the query to get the platforms is as follows:
```
customEvents
| where timestamp > ago(30d)
| where customDimensions.applicationName == "Accessibility Insights for Android"
| where name == "AppInitialized"
| extend os = tostring(customDimensions.os)
| summarize count() by os
```

If we really wanted to, we could undoubtedly add code to set the client_OS version on every event, but since that's not necessary at this time, I'll just close this out.
