### ISSUE TITLE
TabStore onTabUpdate gives an exception

### ISSUE THREAD

**Issue by Shobhit1** [Microsoft/accessibility-insights-web#474]
## Describe the bug

**To Reproduce**

1. Go to `Chrome`. Open a new tab.
2. Open `background.html` devtools console.
3. Type `google.com` (website url doesn't matter here). Type any url.
3. Check `console` to get the below mentioned error

## Expected behavior

There should not be a console error before I even start to use my accessibility Insights extension.

## GIF

![tab-id-undefined](https://user-images.githubusercontent.com/4496335/55196635-30970700-516d-11e9-9995-66d47e5d94f1.gif)

## Extension (please complete the following information)

- OS: Windows 10
- Version:1.0.4
- Powered by axe-core 3.2.1
- Chrome Version: Version 74.0.3729.40 (Official Build) beta (64-bit)
- Target Page: N/A

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
@haonliu is this resolved?

**Comment by haonliu** [comment]
> @haonliu is this resolved?

Yes. Should the person who opened this issue close it or I should?

**Comment by ferBonnin** [comment]
great!
the person who open it. @Shobhit1 could you please verify?

**Comment by Shobhit1** [comment]
Fixed. I dont see the console error anymore. Closing the issue.
