### ISSUE TITLE
Ability to add optional comments to automated checks in assessment.

### ISSUE THREAD

**Issue by ssawczyn** [microsoft/accessibility-insights-web#4741]
## Is your feature request related to a problem? Please describe.
When performing an assessment, it would sometimes be handy to be able to add additional comments for context or other reasons.  For example, I recently marked a bunch of links as failed for link purpose and it would have been great to optionally have the ability to add comments for each failure in order to provide alternative (more descriptive) link text, or additional context about why I failed it.  I'm envisioning this working similarly to how I can manually add an issue to non-automated tests, e.g. an add button or comment field could be present for each failed instance.  

## Describe the desired outcome
I'd like to be able to add optional comments to failed automated checks in order to provide additional guidance or context.  Ideally, this could be an additional column in the instances table, or an add button could be placed in the table which triggers a dialog similar to adding an issue in non-automated checks.

## Describe alternatives you've considered
The only alternative I can think of is to copy the exported final report into some other template and then add my comments, but this is a real pain, not to mention very messy.

**Comment by ferBonnin** [comment]
Hi @ssawczyn thanks for your feature request! this looks like a duplicate of #485. Could you please take a look and let us know if that feature request covers this one?

**Comment by ssawczyn** [comment]
@ferBonnin  yes, unfortunately, this is a duplicate, my apologies -- I somehow missed the other.

**Comment by ferBonnin** [comment]
> @ferBonnin yes, unfortunately, this is a duplicate, my apologies -- I somehow missed the other.

No worries, thanks for the request @ssawczyn! Please feel free to upvote #485 if you'd like 🙂
