### ISSUE TITLE
Extension crashes and needs to be repaired when opened Inspector

### ISSUE THREAD

**Issue by Giorat** [Microsoft/accessibility-insights-web#486]
## Describe the bug

The extension crashes and needs to be repaired when I open the Inspector with Chrome on a Mac.

**To Reproduce**

1. Install the extension(stable or beta versions)
2. Enable the extension and activate it on a web page
3. While the application is running open the Inspector
4. The extension will disappear and you will have to Repair it in the chrome extension tab.

## Expected behavior

When using Inspector the app should be paused to prevent a crash.

## Screenshots

![image](https://user-images.githubusercontent.com/4527364/55341743-74f51080-54a7-11e9-977d-db2ff10dffe6.png)

## Extension (please complete the following information)

- OS: Mac
- Version [e.g. 1.140.1]
- Chrome Version 73.0.3683.86 
- Target Page https://www.hdblog.it/

**Comment by peterdur** [comment]
Hi @Giorat! Thanks for taking the time to file this issue. We're obviously very concerned about crashes. I've taken some time today to reproduce this on a Mac, with this specific version of Chrome, on the site https://www.hdblog.it/. So far I haven't had any luck. I'm wondering if there's something I'm doing differently. Could you describe the steps that cause the crash with more detail, to help me do exactly what you're doing that results in the crash? Thanks!

**Comment by Giorat** [comment]
It happens on every website.
In the exact moment I open the inspector while Insight is active this crash and it "needs to repaired".

![inspector_bug](https://user-images.githubusercontent.com/4527364/55387726-407a6680-5532-11e9-8eef-b5440c8d8882.gif)

**Comment by Giorat** [comment]
I tried the same steps without any problem on Chrome for Windows. 

But with Mac it happens every time, I also used Chrome Canary where I reproduced the same error.

**Comment by peterdur** [comment]
@Giorat The screen capture above was very helpful! I'm still trying to get this to reproduce on our Mac, even following the steps you show, even with the same set of extensions you have installed (and disabled). I'll let you know if I have more questions.

**Comment by Giorat** [comment]
Were you able to reproduce this bug @peterdur ?

**Comment by peterdur** [comment]
@Giorat, we've tried to reproduce on some more Macs last week and haven't had any success. We want to fix the issue but it's obviously difficult to do so without being able to get the crash to happen.
Here are some more questions that might help the investigation…
- Which version of macOS are you using?
- Do you have access to another Mac where you could try the extension to see if it happens there too? 
- Try turning on Developer Mode (Modalita sviluppatore) in chrome://extensions and see if any errors are reported there after the crash.
- If Developer Mode doesn't provide more information, try collecting logs by starting Chrome from a Terminal with verbose logging enabled:
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging --v=1&`
and then send us the log from
`~/Library/Application\ Support/Google/Chrome/chrome_debug.log`
(As noted at https://www.chromium.org/for-testers/enable-logging, the log may contain some personal information, so you will want to review the contents before sending. I'll email you with information about how to submit the log.)
