### ISSUE TITLE
Display useful state information about what controls are currently focused - Android

### ISSUE THREAD

**Issue by PureWeen** [microsoft/accessibility-insights-web#4890]
## Is your feature request related to a problem? Please describe.
When trying to debug focus issues (keyboard and screen reader) I'll frequently open up my app inside android studio and use the inspector so I can debug the issue. For example, recently our app was sending keyboard focus to nonvisible elements while I was using the TabIndex features of Application Insights on Android. I've hit similar issues with screen reader focus. If I hit issues like this then I'll use Inspector inside Android Studio to figure out what element has "accessibilityFocused" set to true or "focused" to true.

## Describe the desired outcome
It'd be helpful if I could see a "current state" of things inside Application Insights. If it could show/tell me what element currently has accessibilityFocus/keyboard focus. 

## Describe alternatives you've considered
Using Appium or Android Studio to inspect my elements

**Comment by peterdur** [comment]
Per async conversation with Fer, holding for additional community feedback.

**Comment by DaveTryon** [comment]
As called out at https://github.com/microsoft/accessibility-insights-web#notice, we will not be making further investments in the Android scanning solution. As such, we're closing this out.

Thanks for your interest in Accessibility Insights!
