### ISSUE TITLE
issue details dialog button is upside down

### ISSUE THREAD

**Issue by ferBonnin** [Microsoft/accessibility-insights-web#490]
## Describe the bug
buttons are not usable in the issue details on target page

**To Reproduce**

1. Go to https://uifabric-prod.azurewebsites.net/?example=jhkjhkj#/components/toggle
2. run automated checks
3. Click one failure to open issue details

## Expected behavior
buttons should look the same as in any other page

## Screenshots

![a screenshot of the issue details dialog](https://user-images.githubusercontent.com/9062104/55365165-4885c800-5498-11e9-8d66-184f4419cef6.png)

## Extension (please complete the following information)

- OS: Windows 
- Version: 2.1.2
- Chrome Version : 73.0.3683.86

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
Yes

**Comment by peterdur** [comment]
DRI triage: Bug has sufficient information, not a DRI issue.

**Comment by peterdur** [comment]
Assigning to PM (bot did not pick this up)

**Comment by ferBonnin** [comment]
@lisli1 looks like this got fixed with your PR, can you confirm?

**Comment by lisli1** [comment]
I can't repro this bug anymore, so I will mark it as resolved.
