### ISSUE TITLE
Red failure color in overlays vs. FastPass, Assessments, reports UI

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#4911]
## Describe the bug

The red that’s used in the FastPass Automated Checks website overlays is different than the red used within the Accessibility Insights UI and reports for both FastPass and Assessments.
Current red in overlays: rgb(204, 0, 0)

## Expected behavior
we use the same red color everywhere. Per design team, recommendation is to update the red in the overlays to match the red used elsewhere.

Recommended: rgb(232, 17, 35) 
(maps to var(--negative-outcome); used in FastPass, Assessments, and reports)

**Comment by peterdur** [comment]
Per async conversation with Fer, marking ready for work.
