### ISSUE TITLE
Extension not recoginzing dl element on the page

### ISSUE THREAD

**Issue by TimothyKrajewski** [Microsoft/accessibility-insights-web#492]
## Describe the bug
When running the scan I got 20 errors back saying "\<dt\> and \<dd\> elements must be contained by a \<dl\>" but in the DOM all the instances that the extension points out are wrapped in \<dl\> elements

**To Reproduce**
1. Go to a site https://jsfiddle.net/noj8ztfw/
2. Run the scan see the issue  "\<dt\> and \<dd\> elements must be contained by a \<dl\>" despite the tag being contained in a \<dl\> 

## CodePen repro example
* Goto https://codepen.io/ for a starting codepen
* Create a simple example of the page that you have issues with and Export that codepen or give us a link to that codepen.
https://jsfiddle.net/noj8ztfw/
https://codepen.io/anon/pen/gypNRW

## Expected behavior

This should be able to detect the parent element when the parent element is present

## Screenshots

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/9063297/55431227-032bce00-555e-11e9-8caa-8c93565a45e6.png">

## Extension (please complete the following information)

- OS: Mac
- Version 10.14.4
- Chrome Version Version 73.0.3683.86 (Official Build) (64-bit)

## Are you willing to submit a PR?

Yes 

## Did you search for similar existing issues?

Yes

**Comment by peterdur** [comment]
@TimothyKrajewski  Taking a look at the jsfiddle and running the scan, I agree that the error message is confusing here. As you observe, the error says the `<dt>` needs to be in a `<dl>`, which is clearly the case. More accurately, the rule is actually checking that the `<dt>` is in a `<dl>` which still has the default role of `list`. The `<dl>` in the jsfiddle has its role overridden to `listitem` which means its role as a valid container for a `<dt>` has been overridden.

**Comment by TimothyKrajewski** [comment]
So even removing that role on the I still get the error here is an update fiddle https://jsfiddle.net/noj8ztfw/ and I have also update the link in the initial filing

**Comment by peterdur** [comment]
Hmm - when I go to that jsfiddle I'm not seeing a dlitem failure reported. I'm using the latest release of the extension, version 2.1.2. Could you export your results from the automated checks (click the "Export result" button in the automated checks header) and attach? I've attached an example report from my run. (Note that I renamed it from x.html to x.html.txt so it could be attached to the issue.)

[AutomatedChecksReport_20190403_EditfiddleJSFiddle.html.txt](https://github.com/Microsoft/accessibility-insights-web/files/3039726/AutomatedChecksReport_20190403_EditfiddleJSFiddle.html.txt)
