### ISSUE TITLE
[CI/CD] Is there current support or workaround for CI integration?

### ISSUE THREAD

**Issue by lavmot-ms** [microsoft/accessibility-insights-web#4997]
**We encourage tool related questions to be asked on stackoverflow.com and tagged with `accessibility-insights`.**

## Your question here

Is there current support or workaround for CI integration?

**Comment by lisli1** [comment]
Please take a look at [axe-pipelines-samples](https://github.com/microsoft/axe-pipelines-samples), which contains examples on how to add automated accessibility tests to your CI builds.
