### ISSUE TITLE
Divs with role=heading should be replaced with native heading elements

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-web#5120]
## Describe the bug
In a few places in our codebase, we use div elements with role=heading instead of actual heading elements. According to [our guidance](https://github.com/microsoft/accessibility-insights-web/blob/5deba6151546207ecb802540184a0c7e46947827/src/content/adhoc/headings/guidance.tsx) and [other best practices](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role#best_practices), we should use native heading elements when possible. This bug tracks the work to refactor those. 

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
Yes

**Comment by majaokholm** [comment]
@jalkire I would like to give this one a go, if not already taken? It would be my first contribution here but looks pretty straight forward.

**Comment by jalkire** [comment]
> @jalkire I would like to give this one a go, if not already taken? It would be my first contribution here but looks pretty straight forward.

@majaokholm Sure thing, thank you for checking! One hint is to take a look at how we're using [`HeadingElementForLevel`](https://github.com/microsoft/accessibility-insights-web/blob/main/src/common/components/heading-element-for-level.tsx) right now as a starting point 🙂

**Comment by ferBonnin** [comment]
@majaokholm thanks! I have assigned this issue to you 😄

**Comment by majaokholm** [comment]
@jalkire sorry for the delay, got fir by sick kids. Nevertheless, I made a few changes but excluding e2e tests and unit tests I only found the div element with role=heading being used three places. I have refactored these three instances but am wondering if I might be overlooking something? I have created a draft pull request for my changes

**Comment by jalkire** [comment]
> @jalkire sorry for the delay, got fir by sick kids. Nevertheless, I made a few changes but excluding e2e tests and unit tests I only found the div element with role=heading being used three places. I have refactored these three instances but am wondering if I might be overlooking something? I have created a draft pull request for my changes

No problem at all, thank you for opening the PR! You found all the right div elements. I left a few pieces of feedback on the PR

**Comment by ferBonnin** [comment]
@jalkire can this be closed now?
