### ISSUE TITLE
Web Component Headings Not Being Detected by Headings test in Ad Hoc Tools

### ISSUE THREAD

**Issue by break-stuff** [microsoft/accessibility-insights-web#5126]
## Describe the bug

Headings within web components are not visible to the "Headings" test in the "Ad Hoc Tools" section of the browser extension.

**To Reproduce**

1. Go to the provided [code sandbox](https://codesandbox.io/s/web-component-header-test-mncbn?file=/index.html)
2. Click on 'Open in new window' (upper-right corner of the rendered content)
3. In the new browser window click the "Accessibility Insights for Web" browser extension icon
4. Click "Ad hoc tools"
5. Toggle the headings option to that it is "on"
6. Observe that the `h2` is identified (since it is not in a web component) and the `h1` that is in a web component is not identified.

## Code Sandbox repro example

https://codesandbox.io/s/web-component-header-test-mncbn?file=/index.html

## Expected behavior

Headings within web components should be identified by the headings identification tool.

## Context (please complete the following information)

- OS Name & Version: Windows 11 Enterprise 22000.438
- AI-Web Version & Environment:
- Browser Version: MS Edge Version 97.0.1072.69 (Official build) (64-bit)
- Target Page:

## Are you willing to submit a PR?

I am not familiar enough with the tool to submit a PR.

## Did you search for similar existing issues?

Yes, I was unable to find relevant information on the issue.

**Comment by ferBonnin** [comment]
reviewed with Peter. This needs investigation. Relevant notes:
* we are detecting the H1 element (in Assessment, the H1 appears in the list of Headings) but we are not able to draw the visualization
* the H1 is in an open shadow DOM

**Comment by ferBonnin** [comment]
@break-stuff thanks for reporting this issue! This has now been fixed and the fix is available to be reviewed in our [canary extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem).
