### ISSUE TITLE
SC number in pop up

### ISSUE THREAD

**Issue by MarjonBakker** [microsoft/accessibility-insights-web#519]
## Is your feature request related to a problem? Please describe.

When doing a fastpass on a website, red outlines with exclamation points are shown that I can click to see what the failure is. I then get a popup that has a 'rule name' for example 'image-alt' that's a link to an explanation on dequeuniversity.com. When I want to know the number of the WCAG 2.1 success criterion the failure falls under, I always have to click the link. Since I'm familiar with the SC's, I often need only the number (1.1.1 in the case of my example). The Axe extension does this and it's super handy.

## Describe the desired outcome

I'd love to have the number of the SC right in the popup, for example right after the rule name. That would save me quite a lot of clicks.

**Comment by Shobhit1** [comment]
Hi @MarjonBakker,

Thank you for filing this issue. We will triage it in our weekly review and update the issue. Thank you for contributing to Accessibility Insights!

**Comment by Shobhit1** [comment]
Hi @MarjonBakker,

Till the time we triage this issue and give you an answer on this feature request.
As a workaround, you can always check `WCAG` information in the fast pass assessment page. 
Just click `FastPass` from the popup menu and the extension will start the process.

![image](https://user-images.githubusercontent.com/4496335/55899264-3af7ce80-5b79-11e9-9828-34f411932ee8.png)

![image](https://user-images.githubusercontent.com/4496335/55899346-6c709a00-5b79-11e9-8597-d4d4e3e4b6aa.png)

**Comment by ferBonnin** [comment]
@cheade What are your thoughts on this?
My concern is that it might make the target page look to busy

**Comment by cheade** [comment]
This is interesting. If users are more inclined to view the WCAG rather than the deque rule description, then we should have it available on the target page pop-up. Key information should be in both places (target page and Accessibility Insights page) if both are widely used. 

At most I've only seen up to three WCAG rules for a single deque failure. I think we can find a place for the WCAG rules on this pop-up. As it stands right now, the pop-up is quite busy, I agree. If we can find some time to put a UI re-styling on the backlog (not a deep UX fix), then I think we can alleviate the busy concern.

**Comment by ferBonnin** [comment]
@cheade what do you mean by UI re-styling? 

this is a quick test on how it would look like with 3 WCAG:
![Tooltip with three WCAG](https://user-images.githubusercontent.com/9062104/55916379-0f88da00-5ba1-11e9-925f-40b0e5885878.png)

**Comment by cheade** [comment]
I thought MarjonBakker was referring to the pop-up once you click on it, and not the tooltip that appears on hover, as they mention clicking the link of the rule name.

**Comment by ferBonnin** [comment]
I think you are right, my bad. In that case I get what you mean on UI re-styling.
could we explore adding it next to the title? do we want to add links too?

**Comment by cheade** [comment]
Here's a simple suggestion for the pop-up (without UI cleanup): 

![image](https://user-images.githubusercontent.com/40274682/55917183-67284500-5ba3-11e9-95c4-a0c9289348eb.png)

**Comment by ferBonnin** [comment]
@MarjonBakker what are your thoughts on what Chelsea suggests?

**Comment by MarjonBakker** [comment]
@ferBonnin @cheade Yes, that is exactly what I mean and it would be very useful for me. I get that it clutters the page and would understand if you decide against it. On the other hand, w3.org is my go-to reference where I can also find 'understanding', 'how to meet', techniques and failures for all SC's. So a link directly to w3.org would be good.

**Comment by ferBonnin** [comment]
@MarjonBakker great! We will put it in our backlog.
Lets use Success Criteria and Success Criterion instead of W3C guidelines.

**Comment by dbjorge** [comment]
Implemented the basics, talking offline with @cheade to confirm the exact font/positioning we want before sending a PR.

![image](https://user-images.githubusercontent.com/376284/56702128-425dc280-66b7-11e9-8efc-b0834db9a81a.png)

**Comment by dbjorge** [comment]
@MarjonBakker This feature is now available in our [Canary extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem) (version 2019.4.29.2023). Feel free to give it a try and let us know if you find any issues with it!

**Comment by MarjonBakker** [comment]
Checked it out, and it's just what I need. Thanks all!
