### ISSUE TITLE
Tab stops not working

### ISSUE THREAD

**Issue by sandyio** [microsoft/accessibility-insights-web#5191]
## Describe the bug

**To Reproduce**

1. Go to 'Accessibility Insights for Web'
2. Click on 'tab stops'
3. it doesn't load - the blue circle just keeps spinning
4. help please!

**Comment by ThanyaLeif** [comment]
We were unable to reproduce the error.
Can you provide us with images of the issue or any other information about the problem?

**Comment by sandyio** [comment]
it seems to depend on the page.  I'll send along the next time I find one that spins out. thanks!
