### ISSUE TITLE
When headers are used, no automated checks detect if there aren't exactly 1 h1 element.

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-web#520]
## Describe the bug
According to the Headers test guidance in Assessment, "If the page uses headings, an automated check will fail if the page does not have exactly one top-level heading."

However, a page that doesn't have exactly 1 top-level heading when it uses headings isn't failing a corresponding automated check.

**To Reproduce**
1. Go to https://codepen.io/anon/pen/eovjqJ (another site example: https://bbc.com)
1. Run FastPass.

## CodePen repro example

Please provide a reproduction of the bug in a codepen, if possible. Here’s how

* Goto https://codepen.io/ for a starting codepen
* Create a simple example of the page that you have issues with and Export that codepen or give us a link to that codepen.

https://codepen.io/anon/pen/eovjqJ 

## Expected behavior

One of two:
- Headings guidance doesn't mention that automated check fails under these conditions.
or
- An automated check fails.

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.1.2
- Chrome Version [e.g 71.0] 73.0.3683.103
- Target Page [e.g www.bing.com] www.bbc.com

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights) Yes

**Comment by ferBonnin** [comment]
to fix: need to remove the note in headings test guidance. the rule mentioned is best practice.

**Comment by Shobhit1** [comment]
Fixed.

**Comment by risanaka** [comment]
Thanks, @Shobhit1!

**Comment by gatosocal** [comment]
The sentence, "If the page uses headings, an automated check will fail if the page does not have exactly one top-level heading.", is no longer in the Assessment section for Headings.

But, this sentence, "Use exactly one top-level heading. (WCAG 1.3.1)" is still on the "Guidance for Headings" page.  Shouldn't the "WCAG 1.3.1" in parentheses be replaced with "best practice"?

Accessibility Insights for Web
Version 2.16.0 | Powered by axe-core 3.5.1

**Comment by ferBonnin** [comment]
hi @gatosocal great point! we have filed a bug #2444 to track this change.
