### ISSUE TITLE
Accessible Description shows No Value

### ISSUE THREAD

**Issue by hunnynegi424** [microsoft/accessibility-insights-web#5220]
Below is my code for a logo button:
`<Button
    style={{ padding: 0, margin: 10 }}
    role='button'
    aria-label='Logo'
    aria-describedby='logoIcon'
    onClick={() => { window.location.href = '/PostLoginAnnouncements' }}
    onKeyDown={(e) => {
      if(e.key === 'Enter') { window.location.href = '/PostLoginAnnouncements' }
    }}
  >
    <div id='logoIcon' style={{ display: 'none' }}>Logo Icon Button</div>
    <CompanyLogo />
  </Button>`

yet, the accessibility tool shows Accessible Description has no value.

**Comment by shanisebarona** [comment]
Hi @hunnynegi424, looks the like the `aria-describedby='logoIcon'` is pointing to an element with a style of `display: none`, which removes the element completely from the DOM tree, will not be accessible to any user, and provides Accessible Description with no value. 

We suggest hiding content visually, if you are trying to hide content from sighted users. An example on hiding content visually can be found here: [Inclusively Hidden - Scott O'Hara.](https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html)

**Comment by hunnynegi424** [comment]
I tried that, it didn't work. I even removed all styling properties from the div, it still show no value for Accessible Description.

**Comment by shanisebarona** [comment]
Can you share a minimal repro (in something like Codepen) so that we can take a further look?

**Comment by hunnynegi424** [comment]
So my issue is, the accessible name shows the aria-label, but the accessible description says no value, even after defining the aria-describedby for the my div.

<div role='button' aria-label='action-button' aria-describedby='info-div'>Click Me</div>
<div id='info-div'>I am a button</div> 

does this make any sense? what exactly goes into Accessible Description under Custom Widgets > Instructions

**Comment by madalynrose** [comment]
Hello! I pasted the code above into codepen and Accessibility Insights successfully detected the accessible description for the Instructions requirement. I am unable to repro the issue you are seeing. Could you link to a page or a repo where you are seeing the issue?

![accessible description listed matching contents of info-div above](https://user-images.githubusercontent.com/3230904/157325981-08c4b9fe-9800-46d2-8253-a640e8a4ea2f.png)
