### ISSUE TITLE
Assessment instructions need to be updated for windows 11/current browser settings flows

### ISSUE THREAD

**Issue by sfoslund** [microsoft/accessibility-insights-web#5251]
## Describe the bug

Some assessment `How to test` instructions need to be updated for windows 11 and current browser settings. 

**To Reproduce**

1. Begin an assessment
2. Go to `Adaptable Content, High Contrast Mode` (can also be seen on `Adaptable Content, Resize Text` and possibly others)
3. See step 2 of `How to test` instructions, which says `Use Windows Settings > Ease of Access > High contrast to apply a high contrast theme.`. Settings differ with windows 11 and these instructions are no longer applicable with that version. 

## Expected behavior

Instructions should be updated to reflect the correct settings in:

* The latest version of Windows
* The latest version of Chrome and Microsoft Edge

This should include updating references to "Windows 10", "the new Microsoft Edge", and "Microsoft Edge Insider" to the current values

**Comment by DaveTryon** [comment]
Nandita to drive this and get updated text

**Comment by DaveTryon** [comment]
@nang4ally, tagging you after adding the "needs PM input" tag

**Comment by DaveTryon** [comment]
This has been released to prod
