### ISSUE TITLE
AI Web: telemetry source is incorrect when auto-generated instances to tab stops are added

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#5258]
## Describe the bug

Source is always DetailsView.

**To Reproduce**

1. Enable Tab Stops Automation.
2. Enable logging telemetry to console.
3. Run Tab Stops and create an error (e.g. tabbing back and forth quickly will create one).
4. In background.html, should see telemetry source for instances created is DetailsView.

## Expected behavior

Source should be TargetPage.

## Are you willing to submit a PR?

Yes

**Comment by ferBonnin** [comment]
@waabid can we close this issue?

**Comment by waabid** [comment]
Yep!
