### ISSUE TITLE
Inspector shows warnings on target pages with restrictive CSPs

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#529]
## Describe the bug

Inspector console shows the warning "Refused to load the font '<URL>' because it violates the following Content Security Policy directive" on certain target pages.

**To Reproduce**

1. Go to https://github.com
2. Run automated checks
3. Right click anywhere on the target page and select "Inspect"
4. Click the Console tab
5. See warning messages

## Expected behavior

Inspector console should not output the warnings.

## Screenshots

![image](https://user-images.githubusercontent.com/48259897/55976980-8b872e80-5c42-11e9-9944-dbc90bb25375.png)

## Extension (please complete the following information)

- OS: Windows
- Version 10.0.17134
- Chrome Version 73.0.3683.103
- Target Page https://github.com

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights) Yes

**Comment by ferBonnin** [comment]
@devaradhanm can you please investigate?

**Comment by devaradhanm** [comment]
@ferBonnin, this error might be hard to remove since this is happening due to a font added by the fabric css we inject.
We could solve this by having our visualization under iframe, which would be a feature request. (with this approach you won't see this error message & the ui experience will not be affected) We may need an investigation for this.

**Comment by dbjorge** [comment]
I don't think we'd need to go as far as having our own visualization. [Office Fabric supports configuring fonts to load from alternative sources](https://github.com/OfficeDev/office-ui-fabric-react/wiki/using-icons#alternative-cdn-options); I would expect we could package the necessary font package with our extension and use that functionality to load the fonts from a chrome://our_ext_id/ URL to work around the CSP issue, similarly to how our CSS bundles work.

**Comment by devaradhanm** [comment]
Looks like this is happening since we are importing fabric.scss in our scss file. I think we can remove this dependency, as i don't see any style changes when we remove it. i will send a PR for this change.tried removing this dependency,
