### ISSUE TITLE
Scan broken in master

### ISSUE THREAD

**Issue by haonliu** [Microsoft/accessibility-insights-web#533]
## Describe the bug

scan is broken

**To Reproduce**

1. Go to any page
2.  toggle adhoc tools -> automated checks,
3. spinner spinning forever

## Expected behavior

Scan should be able to complete

## Extension (please complete the following information)

- OS: Windows 10
- Version: Canary 2019.4.12.23
- Chrome Version: 73
- Target Page: any

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

no

**Comment by Shobhit1** [comment]
This was fixed with #534

**Comment by ferBonnin** [comment]
Hi @risanaka this issue has been fixed. You can verify the fix in our canary extension or we can let you know when its available in production. Thanks!

**Comment by ferBonnin** [comment]
Hi @haonliu, 
This issue has been resolved, could you verify?

**Comment by haonliu** [comment]
> Hi @haonliu,
> This issue has been resolved, could you verify?

Yep! I think we can close it.
