### ISSUE TITLE
Regression: unexpected extra spacing between card groups

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#5349]
## Describe the bug

In recent canary builds there is about 16px of undesirable extra spacing between groups of cards in card-based UI views (eg, web's FastPass Automated Checks). In the screenshot below, note the extra spacing in a recent dev build on the left vs the "normal" spacing in production on the right:

![screenshot demonstrating issue](https://user-images.githubusercontent.com/376284/162808233-7efa03f6-569d-4d7c-8551-6c1b5c4d4b3b.png)

It looks like the extra margin is coming from the default styling on the new `<h3>` elements just inside the card group headers introduced by #5189 - we probably need a style clear for those to avoid the new spacing.

**To Reproduce**

1. Use Accessibility Insights for Web Canary 2022.4.11.1622
2. Start a FastPass against any page with a variety of errors (eg, [the CityLights test page](https://www.w3.org/WAI/demos/bad/before/home.html))
3. Observe the spacing between the card groups

## CodePen repro example

n/a

## Expected behavior

Spacing should match production

## Screenshots

See above

## Context (please complete the following information)

- OS Name & Version: Windows 11 21H1 22000.556
- AI-Web Version & Environment: Canary 2022.4.11.1622
- Browser Version: Microsoft Edge Version 100.0.1185.36 (Official build) (64-bit)
- Target Page: any page with a variety of errors (eg, [the CityLights test page](https://www.w3.org/WAI/demos/bad/before/home.html))

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

#5189, #5120

**Comment by waabid** [comment]
Should have a PR out for this soon.

**Comment by peterdur** [comment]
@waabid @dbjorge has this been fixed by #5355?

**Comment by dbjorge** [comment]
Yes. Verified the fix in main.
