### ISSUE TITLE
Inspect HTML button should not be disabled

### ISSUE THREAD

**Issue by haonliu** [microsoft/accessibility-insights-web#547]
## Describe the bug

The Inspect HTML button in the details dialog on target page should not be disabled, for accessibility concerns.

**To Reproduce**
Open
Run automated checks.

1. Go to any web page with a11y issue.
2. Run automated checks.
3. Click the '!' icon in the target page.
4. See Inspect HTML button is disabled.

## Expected behavior

Inspect HTML button should not be disabled. User should be able to interact with it.

## Screenshots

![image](https://user-images.githubusercontent.com/15974344/56166473-91ef1080-5f8a-11e9-86f8-8ed62690ea74.png)

## Extension (please complete the following information)

- OS: Windows
- Version: staging 2.1.2
- Chrome Version [e.g 71.0]
- Target Page: any

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?
yes

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
yes

**Comment by Shobhit1** [comment]
@haonliu Isn't the `Inspect HTML` button supposed to be disabled till the time user manually opens the dev tools (`F12`) ? Can you please provide more context on this issue?

**Comment by ferBonnin** [comment]
@Shobhit1 behaviour should be similar to the file bug button, the message and alert that you need to open dev tools appears after you interact with the button

**Comment by Shobhit1** [comment]
> @Shobhit1 behaviour should be similar to the file bug button, the message and alert that you need to open dev tools appears after you interact with the button

Thanks @ferBonnin . I will take a look if I can take this one up today. 😺

**Comment by Shobhit1** [comment]
Taking this one.

**Comment by Shobhit1** [comment]
Created PR #859 for it.

**Comment by Shobhit1** [comment]
@ferBonnin / @haonliu Can you please verify this and close the bug if its fixed?

**Comment by ferBonnin** [comment]
Looks good to me :)
