### ISSUE TITLE
Back and next button in target page details dialog should be removed when there is only one instance

### ISSUE THREAD

**Issue by haonliu** [microsoft/accessibility-insights-web#549]
## Describe the bug

Back and next button in target page details dialog should be removed when there is only one instance.

**To Reproduce**

1. Go to any page with a11y issues.
2. run automated checks.
3. Scroll down to a failure, and open the details dialog by clicking '!'
4. See Back and next button in target page details dialog appear even when there is only 1 failure.

## Extension (please complete the following information)

- OS: Windows
- Version 2.1.2
- Target Page any

## Are you willing to submit a PR?
yes

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
yes

**Comment by ferBonnin** [comment]
@smoralesd is this resolved?

**Comment by smoralesd** [comment]
> @smoralesd is this resolved?

@ferBonnin Not yet, still working on it (The "Closed" badge you see on the related PR means the PR was not merge to master, just closed -like in abandoned)

**Comment by ferBonnin** [comment]
@haonliu this issue was marked as resolved, could you verify and close?

**Comment by karanbirsingh** [comment]
@haonliu ping
