### ISSUE TITLE
Support web scanning against separate processes (Electron applications, other browser extensions)

### ISSUE THREAD

**Issue by abettadapur** [microsoft/accessibility-insights-web#558]
I think this tool is great for quickly validating accessibility on websites. I would also like to use it to perform audits on Electron applications, which are also built on web technologies. 

I can install **devtools** extensions with this package (https://github.com/MarshallOfSound/electron-devtools-installer), but I cannot use this extension in my Electron application because it is not surface in the DevTools. It would be really great if a devtools tab could be added that surfaces the same UI the standard extension does

**Comment by adrianaandreeva** [comment]
Hi @abettadapur, thank you for your feedback! Glad you are finding Accessibility Insights helpful! This is a great suggestion, we will look into the timelines and effort for making this available and follow up.

-- Your Accessibility Insights Team

**Comment by nschonni** [comment]
Maybe Deque will share their build setup, since that extension installs as a DevTool extension (and in Firefox)

**Comment by abettadapur** [comment]
Any news on a timeline/priority for this issue?

**Comment by ferBonnin** [comment]
Hi @abettadapur thanks for reaching out! No new updates on our side for this yet. We will update this feature request when we have updates.

**Comment by imbushuo** [comment]
+1 for this one, which will also be helpful for testing browser extension pages.

cc @Jack-Works

**Comment by dbjorge** [comment]
Generalized the issue title slightly - we aren't sure if "support for Electron" applications would necessarily use a DevTools experience, vs a standalone tool that can connect to a separate process (similar to the standalone version of React DevTools). We'd ideally like an option that can support a variety of different out-of-process options (eg, Electron apps, other browser extensions, Tauri apps...), but we haven't committed to a specific technical strategy yet.

**Comment by kevin-findigs** [comment]
Any update on other browser extensions?

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
