### ISSUE TITLE
[Usability] Reflow buttons in failure cards

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#5609]
## Describe the bug

currently the failure cards in the automated checks and needs review instances have a "..." button by default. When this UI was first implemented, we determined reflowing the buttons to file bugs and copy failure details was not feasible. This bug is to revisit this after we updated the fluent UI version used 

**To Reproduce**

1. [Go to accessible university demo site](https://www.washington.edu/accesscomputing/AU/before.html)
2. Run FastPass > automated checks
3. notice how the failure cards always have the "..." button

## Expected behavior

the two buttons inside that menu appear / disappear as reflow allows 

## Context (please complete the following information)

- OS Name & Version:  N/A
- AI-Web Version & Environment:  Prod 2.32

## Are you willing to submit a PR?
No

## Did you search for similar existing issues?
Yes

## Additional context
Usability. Exploratory bug; if we determine this is now feasible let's chat with PM

**Comment by pownkel** [comment]
@ferBonnin I don't have much context for why this was originally infeasible, but I have a working version on [my own branch](https://github.com/microsoft/accessibility-insights-web/compare/main...pownkel:accessibility-insights-web:reflow-cards?expand=1) that reflows those buttons similarly to how it's done in the command bar and handles focus when the issue filing dialog closes
![gif showing the Automated Checks screen being expanded and the kebab button on cards expanding to show the "file issue" and "copy failure details" buttons](https://user-images.githubusercontent.com/55459788/178595961-d0135e0e-b275-4e09-9ef6-4f9ffe88c0f8.gif)
![gif showing the issue filing settings dialog being opened and closed at different widths. When the dialog is closed, focus returns to either the kebab button or the "file issue" button, depending on what is visible](https://user-images.githubusercontent.com/55459788/178596758-b0a5e5d3-5d81-459c-ac68-c3c310079af9.gif)

**Comment by ferBonnin** [comment]
This is awesome, thanks @pownkel! We should do this change, please!

**Comment by pownkel** [comment]
@ferBonnin this is complete and the change is in canary!

**Comment by ferBonnin** [comment]
thanks @pownkel, looks great!
