### ISSUE TITLE
[Usability] Explore making failure instance highlight more visible

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#5610]
## Describe the bug
In assessment, we highlight elements to review with a thin red line. In certain cases, it can be hard to understand what elements have been highlighted

**To Reproduce**

1. Go to Accessible university
2. Open Assessment > Images > 14.1
3. Turn on visual helper

## Expected behavior

Explore making the visual highlight clearer in different background colors. Design team suggested trying multiple border colors with red in the center and white surrounding this.
Another option to explore would be making the red border slightly thicker and giving a bit of padding between the element and the line 

The major concern is adding too many colors and lines might cover other elements thus why we are filing this bug to explore these two suggestions and discuss.

## Screenshots

example of multiple border colors with a orange background and red and white borders
<img width="102" alt="image" src="https://user-images.githubusercontent.com/9062104/172951999-4061b700-ecc1-4b00-8524-1a89b9bc1d42.png">

## Context (please complete the following information)

- OS Name & Version:  N/A
- AI-Web Version & Environment:  Prod 2.32
- Browser Version:  N/A
- Target Page:  N/A 

## Are you willing to submit a PR?
No
## Did you search for similar existing issues?
Yes
## Additional context

usability. Bug to explore alternatives

**Comment by ferBonnin** [comment]
if picking this issue, talk with @peterdur that has a prototype working.
If possible, lets just do this change for automated checks, needs review and assessment highlights

**Comment by Pranav-yadav** [comment]
@ferBonnin I can help with this one; if not already assigned to anyone :)

PS: PRs for already picked issues are ready to review & merge.

**Comment by Pranav-yadav** [comment]
> if picking this issue, talk with @peterdur that has a prototype working.
If possible, lets just do this change for automated checks, needs review and assessment highlights

@peterdur any status, sir?

**Comment by peterdur** [comment]
@Pranav-yadav I started working on a prototype of what would be required from the HTML/CSS perspective to make double-line outlines work at https://github.com/microsoft/accessibility-insights-web/compare/main...peterdur:accessibility-insights-web:double-highlight; haven't yet had the opportunity to clean/parameterize the code to production quality, update tests, etc.; also meant to explore whether there was a cleaner CSS way to do this.

**Comment by Pranav-yadav** [comment]
Thanks! Will check it out..

**Comment by segamiken** [comment]
@peterdur 
As a user of accessibility-insights-web, I wanted to fix this issue. Therefore, I created my own PR. https://github.com/microsoft/accessibility-insights-web/pull/6164

**Comment by Pranav-yadav** [comment]
Nice!
