### ISSUE TITLE
Undo button appears on all rows of issue list

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#5676]
## Describe the bug

In the Canary web extension (2022.6.24.1419), every row of the instances list shows the undo button, regardless of whether pass or fail has been checked:

![screenshot of instance details list with undo button on each row](https://user-images.githubusercontent.com/55459788/176039292-50f1d023-27e0-4086-bb54-d933107da681.png)

This is a regression from the current production version (2.32.0), which only shows the undo button on rows where either pass or fail has been checked:

![screenshot of instance details list with "pass" selected on only the first row, and an undo button on only the first row](https://user-images.githubusercontent.com/55459788/176039506-37dc92b5-ee6f-445e-a155-3a3f0c0d846e.png)

This is confusing for several reasons, first because those buttons do nothing until one of the radio buttons is checked, and second because NVDA now reads "undo" at the end of every instance row and it isn't clear what will be undone.

**To Reproduce**

1. Start an assessment in the canary web extension
2. In the left nav, go to Headings > Heading function
3. Once the scan completes and the instance details list populates, note that every row has an undo button even when nothing is checked

## Expected behavior

The undo button should only show on rows where either pass or fail has been checked.

## Screenshots

See above

## Context (please complete the following information)

- OS Name & Version: Windows 11 build 22000.739
- AI-Web Version & Environment: Canary 2022.6.24.1419
- Browser Version: Google Chrome 102.0.5005.115 (Official Build) (32-bit)
- Target Page: https://bing.com

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by pownkel** [comment]
I noticed after filing this that in both Canary and Prod, the undo button always appears beside pass/fail radio buttons on Assessment steps with no instances list:
![Screenshot of "No missing headings" Assessment step, with neither pass or fail selected and the undo button beside the radio buttons](https://user-images.githubusercontent.com/55459788/176047848-ce007ad5-7b5f-4406-8805-ea165b2e0897.png)

And in Fastpass > tab stops, the undo button appears when expected in both canary and prod:
![Screenshot of tab stops requirements, with "pass" selected on only the first requirement, and an undo button beside only the first row](https://user-images.githubusercontent.com/55459788/176048609-e190ebc2-38e2-4f4a-8243-8c96315a9829.png)

As part of fixing this bug, we should also make sure behavior is consistent wherever we have pass/fail radio buttons.

**Comment by ferBonnin** [comment]
triaged with Peter; we should fix this. In all cases, the undo button should only appear when there is something to undo
