### ISSUE TITLE
Settings menu buttons have no hover state with high contrast theme set

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#5678]
## Describe the bug

In the current Canary (2022.6.24.1419), when the "night sky" theme enabled in Windows, the settings menu buttons no longer have a visible hover state. This is a regression from the current production build. Other buttons in the extension still change color when hovered.

**To Reproduce**

1. In the Windows settings app, go to Accessibility > Contrast themes and enable the "Night sky" theme
2. In Chrome, start an assessment or fastpass run with the Canary extension
3. Select the gear in the upper right corner to open the settings menu
4. Hover the cursor over the buttons in the menu

## Expected behavior

The buttons should change visibly when hovered

## Screenshots

In the current Canary build (2022.6.24.1419) with the "Settings" button hovered
![settings menu no hover state](https://user-images.githubusercontent.com/55459788/176062846-af8b2cf6-cc71-4812-b47f-3bf48ccc67d8.png)

In the Production build (2.32.0) with the "Settings button hovered
![settings menu bar prod hover state](https://user-images.githubusercontent.com/55459788/176062941-e49f384c-83b7-4d9a-a09e-32f7722ddf4a.png)

## Context (please complete the following information)

- OS Name & Version: Windows 11 build 22000.739
- AI-Web Version & Environment: Canary 2022.6.24.1419
- Browser Version: Google Chrome 102.0.5005.115 (Official Build) (32-bit)
- Target Page: any

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by pownkel** [comment]
Edit: _Most_ other buttons still change color when hovered. I've found similar issues in a few other popup menus. The first screenshot in each pair is from Canary, the second is from Prod.

1. The Assessment "Start over" menu
<img width="207" alt="Start over menu with no hover color" src="https://user-images.githubusercontent.com/55459788/176299993-201c2aeb-b5b7-4543-b5f9-a71c8e4e9130.png">
<img width="210" alt="Start over menu with hover color" src="https://user-images.githubusercontent.com/55459788/176300097-3732103d-0ba2-4939-a309-5a3617928426.png">

2. The "export" split button in the Assessment "Export report" dialog
<img width="162" alt="Export button with no hover color" src="https://user-images.githubusercontent.com/55459788/176303710-b7b32c53-5429-4602-b635-22559c3e733a.png">
<img width="157" alt="Export button with hover color" src="https://user-images.githubusercontent.com/55459788/176303747-45e61e0a-bdf7-4518-9a03-3c42baffaa8f.png">

3. The top-left meatballs menu when the screen is shrunk to reflow size, *only* in Fastpass and *only* with the "start over" button (The "Export report" button changes text color to purple when hovered in both canary and prod)
<img width="112" alt="reflow menu with no hover color on start over" src="https://user-images.githubusercontent.com/55459788/176305734-6b98b594-c3c8-4dcc-afa1-3324d4d5f6aa.png">
<img width="109" alt="reflow menu with hover color on start over" src="https://user-images.githubusercontent.com/55459788/176305746-8bc7a7e9-0c3f-4ab8-9671-3173ecdacebd.png">

Interestingly, the buttons in the fastpass cards kebab menu do change color when hovered, although the styling is slightly different between Canary and Prod:
<img width="151" alt="Screenshot 2022-06-28 143333" src="https://user-images.githubusercontent.com/55459788/176306295-7f5d036d-2564-4d3a-b75c-722be4890bb5.png">
<img width="155" alt="Screenshot 2022-06-28 143446" src="https://user-images.githubusercontent.com/55459788/176306324-f9a4da4a-cb10-4f15-86ae-82dc44c86971.png">

And the Assessment reflow menu has identical hover states in both Canary and Prod ("Export report" is hovered in this screenshot, "Save Assessment" is always dark purple for some reason unless it's hovered):
<img width="135" alt="assessment reflow menu with hover state" src="https://user-images.githubusercontent.com/55459788/176306604-eb6b428b-1b9d-4e5f-b7b1-e385465df6be.png">

**Comment by peterdur** [comment]
This may be a Fluent UI issue. The same behavior can be seen in the contextual menu samples at https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu (FluentUI v 8.94.3)
![image](https://user-images.githubusercontent.com/1752950/189403402-672a2bda-f83b-4bf9-9939-24a8e0a31f6c.png)
(image showing no hover indication when mouse hovering over Rename item)

**Comment by peterdur** [comment]
Rolling fluentui/react back to 8.49.6 (the version used in the previous release) seems to restore the hover behavior.
