### ISSUE TITLE
Switcher Dropdown list to change between Assessment and FastPass doesn't announce changes

### ISSUE THREAD

**Issue by ferBonnin** [Microsoft/accessibility-insights-web#570]
## Describe the bug

**To Reproduce**
0.- turn on NVDA
1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. Click on Assessment, select start new (if there is an assessment in progress)
3. Using Keyboard, navigate to the switcher drop down list that allows you to go to FastPass
4.- open the list using space bar, up arrow to select FastPass,  space to select the option
5. Using Keyboard, navigate to the switcher drop down list that allows you to go to Assessment 
6.- Open the list using space bar, down arrow to select Assessment, Space to select the option

Screen reader reads: "select workflow list collapsed FastPass" on change from FastPass to Assessment

Note: can't repro this consistently

## Expected behavior
it should announce that the page changed to Assessment view

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows 
- Version [e.g. 1.140.1] 2.1.2 
- Chrome Version [e.g 71.0] 73.0.3683.103 
- Target Page https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug?No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
Yes

**Comment by haonliu** [comment]
@ferBonnin checked on https://developer.microsoft.com/en-us/fabric#/components/dropdown using NVDA, it is not happening on their side. So this might be an issue from our side, or they've fixed the issue.

**Comment by ferBonnin** [comment]
@haonliu how can we check if its fixed for us too?

**Comment by haonliu** [comment]
> @haonliu how can we check if its fixed for us too?

we can update office fabric and see if the issue is still there.

**Comment by ferBonnin** [comment]
@markreay thoughts?

**Comment by haonliu** [comment]
Just an update: so I tried to updated OF to 6.174.0, this issue is not fixed, and a bunch of a11y issue is found in e2e tests.

**Comment by haonliu** [comment]
Investigated a bit more on this issue, I think the cause is: the 'selected option' of the switcher does not change immediately after user input, It goes through our flux loop before updating the UI. This makes NVDA anoucing the option change incorrectly.

**Comment by haonliu** [comment]
Who should close this issue?

**Comment by ferBonnin** [comment]
@haonliu the person who open it, in this case me.

**Comment by ferBonnin** [comment]
verified in Canary version 2019.5.1.12208 with NVDA
