### ISSUE TITLE
Unified client is not clearing the local store when uninstalled from Mac or Linux

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#5711]
## Describe the bug

When deleting the unified client on Mac or Linux, the local storage is not cleared. As a result, the telemetry dialog doesn't display on re-install

**To Reproduce**

1. Install unified client on Mac or Linux
2. Start the app normally and get past the telemetry dialog (doesn't matter if you accept or decline telemetry)
3. Exit the app
4. Move the app to the trash
5. Reinstall the unified client on the same machine, same user
6. Start the app

Result: No telemetry dialog is displayed. If you open the dev tools, you'll see that the app no longer thinks it's on first boot.

## Expected behavior

The telemetry dialog should display on the reinstall (I've confirmed that this occurs on Windows uninstall)

## Context (please complete the following information)

- OS Name & Version: MacOS Monterey 12.4, Ubuntu 22.04
- AI-Android Insider 2022.706.1

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
@DaveTryon is this happening in insider only or in prod too?

**Comment by ThanyaLeif** [comment]
Following uninstall instructions and performing a fresh install appears to work for me, telemetry dialog is displayed again:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/32908302/177835651-736c80d4-cdf8-4f1a-8c39-f9cd62b09a93.png">
(Image showing telemetry dialog)

**Comment by DaveTryon** [comment]
@ferBonnin, this happens for all versions. The uninstall instructions work correctly if you modify them for the Insider or Canary channel. In this case, I think the gap was that the validation template assumes a clean system without explicitly saying so. I've updated the validation template to explicitly call this out and point to the uninstall instructions you referenced.

I think we can close this out now. Worst case, we have an issue that people can find and get a link to the instructions.
