### ISSUE TITLE
Visualizations fail for targets with semicolon character

### ISSUE THREAD

**Issue by sfoslund** [microsoft/accessibility-insights-web#5735]
## Describe the bug

Automated checks visualizations fail on web pages that include the character `;`. 

**To Reproduce**

1. Go to code pen: https://codepen.io/dbjorge/pen/OJvXaVg
2. Run fast pass automated checks
4. See message `unable to find frame to highlight button[data-attr="with ` in target page and no visualization. 

## Expected behavior

Visualization should be shown on pages with `;` character in targets.

## Context (please complete the following information)

- OS Name & Version: Windows 11
- AI-Web Version & Environment: 2.32.0 prod
- Browser Version: Chrome 103.0.5060.114
- Target Page: https://codepen.io/dbjorge/pen/OJvXaVg

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
I can't see the error message, however, the button in the codepen is not failing the Button-name rule also, changing the attr of the button to something without a semicolon makes it such that the frame-title rule fails whether as with the semicolon, no failures are found.

**Comment by sfoslund** [comment]
> the button in the codepen is not failing the Button-name rule

@ferBonnin what build/ version are you reproing that with? I'm seeing the button failing the button-name rule as expected in the current prod.

> changing the attr of the button to something without a semicolon makes it such that the frame-title rule fails whether as with the semicolon, no failures are found.

I think this behavior is related to updating the codepen, not to changing the content of the code pen in this specific case. I'm seeing those frame-title failures regardless of how I change the code pen content both in this example and with other code pens.

**Comment by ferBonnin** [comment]
investigated this with @sfoslund. We found it was an issue with the codepen and couldn't repro when testing html directly.
