### ISSUE TITLE
Error in sample code (re: aria-required-parent

### ISSUE THREAD

**Issue by teresawong-msft** [microsoft/accessibility-insights-web#5741]
## Describe the bug

There is an error with Pass example on this page:
https://accessibilityinsights.io/info-examples/web/aria-required-parent/

![image](https://user-images.githubusercontent.com/109237416/178790548-5392422a-6425-4993-86bd-77adf3b39f7c.png)

## Expected behavior

Should read:

![image](https://user-images.githubusercontent.com/109237416/178791039-a6babc05-4ca4-4246-b8d0-6e2ef08e9233.png)

**Comment by JGibson2019** [comment]
@teresawong-msft thank you for bringing this to our attention; we will work on getting the documentation updated!

**Comment by JGibson2019** [comment]
The updated documentation is live on [https://accessibilityinsights.io/info-examples/web/aria-required-parent/](https://accessibilityinsights.io/info-examples/web/aria-required-parent/)
