### ISSUE TITLE
Add color box to the hex codes

### ISSUE THREAD

**Issue by mgifford** [microsoft/accessibility-insights-web#579]
## Is your feature request related to a problem? Please describe.

It should be easier to verify you've got the right colors and know how to act on it. 

Make it easier to see/understand color contrast problems. Sometimes what the color contrast tool is testing isn't what appears on the page.  It would be good to clearly show a box with the background/foreground color in the message. 

Might be also useful to remind folks that there may be additional testing required if there are gradients or background images. 

## Describe the desired outcome

There is a good description but most of haven't internalized the hex codes to know what foreground color: #00836d & background color: #fbf5ee look like. 

You could also possibly suggest colors like would meet the requirements like http://contrast-finder.tanaguru.com/

## Additional context

<img width="549" alt="Screen Shot 2019-04-22 at 2 57 58 PM" src="https://user-images.githubusercontent.com/116832/56519540-50251380-6510-11e9-8afb-873508f8a70d.png">

**Comment by ferBonnin** [comment]
Thanks for the Suggestion @mgifford we will keep this feature request in our backlog.

**Comment by smoralesd** [comment]
@ferBonnin @mgifford This is on [canary](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem) now.

**Comment by ferBonnin** [comment]
awesome! 
@mgifford please let us know what you think!

**Comment by mgifford** [comment]
That looks great now, Thanks! 
<img width="501" alt="screenshot with colors by the hex" src="https://user-images.githubusercontent.com/116832/58764927-3e855180-853b-11e9-9b0b-35a111e48b8f.png">
