### ISSUE TITLE
Issue filling fails with "Query String too long" error

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-web#588]
## Describe the bug

When I tried to use "File Issue" feature on the Issue dialog popup, the process fails with following errors:

1. Azure boards: "Query string too long"
2. Github: 2FA fails with 500 error.

**To Reproduce**
Prerequisite: You should **not** be logged in Azure devops or github before this

1. Go to "any target page'
2. Click on Accessibility Insights popup windows and press settings to configure Issue filling.

Part 1:

3. Choose Github as the option and put in a url for your repo.
4. Fast Pass the target page
5. Turn on the visualizations for accessibility issues found
6. Click on the red exclamation mark to open Issue dialog
7. Click on the File Issue button and try to login

Part 2:

3. Choose Azure board as the option and put in a url for your repo.
4. Fast Pass the target page
5. Turn on the visualizations for accessibility issues found
6. Click on the red exclamation mark to open Issue dialog
7. Click on the File Issue button and try to login

## Expected behavior

It should successfully file an issue or create an issue after logging you in for the specific service provider (github or azure boards)

## Extension (please complete the following information)

- OS: Windows 10
- Version: 10.0.17763 Build 17763
- Chrome Version: 74.0.3729.108 (Official Build) beta (64-bit)

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights) 

Yes

**Comment by karanbirsingh** [comment]
I have reached out to GitHub support to get their thoughts on the GitHub length. For me a URL of 1938 characters leads to the 500 server error if the user is logged out. This [link ](https://github.com/microsoft/accessibility-insights-windows/issues/new?body=jnkbxjkkolvifefgtsawrhemblthejpykcxqlalpoosvsvjtobejtrqqmhjyctgdxpurpixpllojczqgsjepjkkqthjgpxkbuqdpldcxfmitewpooeeislxsqmakovvedmwvsumnpizmhttpvygqfyqlbmwdgzssddoenfoughbwjnfbkwcpnleqeahnefnfnolhrsagchwwfiykjjhodocolwveiyyusfvcuszhvrpwrnjpefgbynozdssnlojdopqtbzdntoknsvwhmqaazbndznjhbgrwijewtgivhlvtybkcmldgvwpbomctodbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrnkdxigiohoappkxtoztrbhfrmwvujplboqyqiqviyabjunmkszbkvzvgkwemkhaezzbfwlbqezzzjnkbxjkkolvifefgtsawrhemblthejpykcxqlalpoosvsvjtobejtrqqmhjyctgdxpurpixpllojczqgsjepjkkqthjgpxkbuqdpldcxfmitewpooeeislxsqmakovvedmwvsumnpizmhttpvygqfyqlbmwdgzssddoenfoughbwjnfbkwcpnleqeahnefnfnolhrsagchwwfiykjjhodocolwveiyyusfvcuszhvrpwrnjpefgbynozdssnlojdopqtbzdntoknsvwhmqaazbndznjhbgrwijewtgivhlvtybkcmldgvwpbomctodbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrnkdxigiohoappkxtoztrbhfrmwvujplboqyqiqviyabjunmkszbkvzvgkwemkhaezzbfwlbqezzzjnkbxjkkolvifefgtsawrhemblthejpykcxqlalpoosvsvjtobejbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrnkdxigiohoappkxtoztrbhfrmwvujplboqyqiqviyabjunmkszbkvzvgkwemkhaezzbfwlbqezzzjnkbxjkkolvifefgtsawrhembltjdopqtbzdntoknsvwhmqaazbndznjhbgrwijewtgivhlvtybkcmldgvwpbomctodbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrnkdxigiohoappkxtoztrbhfrmwvujplboqyqiqviyabjunmkszbkvzvgkwemkhaezzbfwlbqezzzjnkbxjkkolvifefgtsawrhemblthejpykcxqlalpoosvsvjtobejbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrhmqaazbndznjhbgrwijewtgivhlvtybkcmldgvwpbomctodbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrnkdxigiohoappkxtoztrbhfrmwvujplboqyqiqviyabjunmkszbkvzvgkwemkhaezzbfwlbqezzzjnkbxjkkolvifefgtsawrhemblthejpykcxqlalpoosvsvjtobejbpfjlltbztnfzlvtzycnkugkcpjenyuxnthvhsqjmmfvfymaenuvvepjepdexjwsdcrvcljrnkdxigiohoappkxdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsd) is an example. When the user is logged in, we can add many more characters.

**Comment by karanbirsingh** [comment]
I got a response - the team has acknowledged the issue and will follow up with me when they have more info. No ETA.
