### ISSUE TITLE
Edge compat: "file url disallowed" text refers to "Chrome" settings

### ISSUE THREAD

**Issue by dbjorge** [Microsoft/accessibility-insights-web#589]
## Describe the bug

The popup.html content when trying to run the extension on a file:// url when this is not enabled in extension settings references "Chrome" even from Edge in the message `Your Chrome settings don't allow Accessibility Insights for Web to run on file URLs.`

**To Reproduce**

1. Ensure the extension settings do *not* have "Enable for file:// urls" checked
2. Navigate to any file:// URL
3. Click on the extension icon
4. Observe the message from above

## CodePen repro example

n/a

## Expected behavior

Message should be updated to something browser-agnostic ("extension settings"?

## Screenshots

![image](https://user-images.githubusercontent.com/376284/56615697-7a3e0a80-65d0-11e9-93ec-9fe6c7a9258e.png)

## Extension (please complete the following information)

- OS: Windows
- Version 2.2.0
- Edge Version 75.0.131.0 (Official build) dev (64-bit)
- Target Page: any file:// page (I used `file:///Q:/repos/accessibility-insights-web/src/tests/end-to-end/test-resources/native-widgets/input-type-radio.html`)

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

We should audit the codebase for other strings containing the term "Chrome" as part of the fix here

**Comment by peterdur** [comment]
Fixed by PR #608. Verified in Canary 2019.4.26.1829.
