### ISSUE TITLE
need architectural docs to better understand this project

### ISSUE THREAD

**Issue by LUTLJS** [microsoft/accessibility-insights-web#5905]
I have spoken to the early team member [Sebastian Morales](https://github.com/smoralesd) about providing any software engineering documentation like Requirement Specifications, User Interface Design, etc. This would help new contributors better understand how this project is implemented and make new contributions more easily.

**Comment by ferBonnin** [comment]
Thanks for the feature request, @LUTLJS, as we work on different features, we will look for opportunities to add architectural docs. Adding this to our backlog

**Comment by sfoslund** [comment]
As part of the MV3 work we recently added this architecture doc, which seems to cover at least part of this request: https://github.com/microsoft/accessibility-insights-web/blob/main/docs/mv3-architecture.md

**Comment by DaveTryon** [comment]
Plan is to add future architecture documents to the repo, but we aren't going to try to do this retroactively.
