### ISSUE TITLE
URL change dialog doesn't show up for change in file urls

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-web#591]
## Describe the bug

URL change dialog box doesn't show up when we go from one file url to another.

**To Reproduce**

1. Open a HTML file in chrome to test for accessibility issues
2. Run assessment by clicking on Assessment from extension's popup page.
3. Verify some assessments so that it makes an entry in indexed DB
4. Change the file url to another url by opening another HTML file.

## Expected behavior

The change in files should trigger the URL change dialog box to show up as it does when we change target page urls.

## GIF

![persistence-no-dialog](https://user-images.githubusercontent.com/4496335/56616816-2680f080-65d3-11e9-8552-d1d55ae94154.gif)

## Extension (please complete the following information)

OS: Windows 10
Version: 10.0.17763 Build 17763
Chrome Version: 74.0.3729.108 (Official Build) beta (64-bit)

## Are you willing to submit a PR?

Yes/No

## Did you search for similar existing issues?

Yes

**Comment by Shobhit1** [comment]
Taking this one.

**Comment by ferBonnin** [comment]
for webpage urls, we only compare the hostname, for filenames, if we do that then we end up in this scenario. Ideal scenario would be that if we have filenames, then we compare the full filename, but unsure if that can be detected and complexity around it

**Comment by Shobhit1** [comment]
Created a PR for this in draft stage. We should discuss this when you are back @ferBonnin

**Comment by Shobhit1** [comment]
Marking this issue as resolved and closing it.
