### ISSUE TITLE
How to Test content still refers to "Visual Helpers" after rename

### ISSUE THREAD

**Issue by peterdur** [Microsoft/accessibility-insights-web#592]
## Describe the bug

#521 renamed the "Visual Helper" toggles to "Highlight instances on target page" but several How to Test instructions still refer to visual helpers. For example, Assessment > Landmarks > Landmark roles says "The visual helper for this requirement highlights all landmarks in the target page."

**To Reproduce**

1. Go to Assessment > Landmarks > Landmark roles
2. Observe that the toggle is called "Highlight instances on target page" but the instructions talk about the "visual helper" (see screenshot below)

## Expected behavior

Language should be consistent between instructions and UX.

## Screenshots

![image](https://user-images.githubusercontent.com/1752950/56617967-19193580-65d6-11e9-8dad-1fe64a5663fc.png)

## Extension (please complete the following information)

- OS: Windows
- Version: Insider 2.2.0
- Edge Insider version: Version 75.0.131.0 (Official build) dev (64-bit)
- Target Page: www.bing.com

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

**Comment by ferBonnin** [comment]
@peterdur given that we reverted that, I don't think this is a valid bug anymore, do you agree?

**Comment by peterdur** [comment]
Agreed. Closing. When we reimplement the text change, we'll remember to update the content.
