### ISSUE TITLE
"Highlight instances on target page” doesn't make sense for some old visual helper toggles

### ISSUE THREAD

**Issue by peterdur** [Microsoft/accessibility-insights-web#593]
## Describe the bug

#521 renamed the "Visual Helper" toggles to "Highlight instances on target page" but this doesn't make sense in some cases:
- The toggle for “color as meaning” page makes the whole page go grey (see screenshot below for context)
- The toggles for “keyboard navigation” and “visible focus” record elements that get the keyboard focus

**To Reproduce**

1. Go to Assessment > Sensory > Color as meaning
2. Observe that toggle is labeled "Highlight instances on target page”
3. Click toggle and note that it does not highlight instances; it turns the whole page greyscale.

## Expected behavior

Toggle should be labeled consistently with its behavior.

## Screenshots

![image](https://user-images.githubusercontent.com/1752950/56618476-98f3cf80-65d7-11e9-88fb-9ba7260b78a1.png)

## Extension (please complete the following information)

- OS: Windows
- Version: Insider 2.2.0
- Edge Insider version: Version 75.0.131.0 (Official build) dev (64-bit)
- Target Page: www.bing.com

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

**Comment by Shobhit1** [comment]
Hi @ferBonnin,
So I reverted the changes that we made for this using PR #597 . Do we want to track this here for more information/discussion. Please let me know.

**Comment by ferBonnin** [comment]
thanks @Shobhit1 I think we can close this issue as resolved. For now, seems like a more generic text for all toggles makes more sense.

**Comment by Shobhit1** [comment]
Closing this in favor of having a more detailed discussion later.
