### ISSUE TITLE
Fastpass scans are delayed when tab stops is incomplete

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#6002]
## Describe the bug

If the user starts the tab stops visualizer in fastpass, then changes to a different tab in details view before tabbing through the entire page, automated checks and fastpass scans take significantly longer to complete. This seems to be somewhat page-dependent, since so far I've only seen it reproduce on github pages.

**To Reproduce**

1. Open https://github.com/microsoft/accessibility-insights-web
2. Open the chrome extension and select "fastpass"
3. Wait for the automated checks scan to complete. This should only take a few seconds.
4. Navigate to "Tab stops" and toggle the visualizer on. Focus will change to the target page.
5. Go back to the details view and navigate to Automated checks again (it makes no difference whether the tab stops visualizer toggle is still on, or whether the user has partially tabbed through the page). Select "Start over."
6. Note that the scan takes much longer to run this time.

## CodePen repro example

n/a

## Expected behavior

Scans should not be delayed by incomplete tab stops

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: Windows 11 build 22000.856
- AI-Web Version & Environment: Production 2.23.0
- Browser Version: Google Chrome 104.0.5112.102 (Official Build) (32-bit)
- Target Page: [
](https://github.com/microsoft/accessibility-insights-web)

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

Possibly related to the bug fixed by #6001. I suspect something is blocking execution in the target page script until the tab stops analyzer times out, regardless of whether the visualizer toggle is enabled or the user is in the tab stops tab.

**Comment by ferBonnin** [comment]
per triaging conversation, given that this seems to be page specific, leaving this as await community interest to wait for customer reports.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
