### ISSUE TITLE
Bug: Needs Review counter overflows with 3 or more digits

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#6003]
## Describe the bug

The OutcomeChip control in __Needs review__ results only works properly if the count is 2 or fewer digits. Once it hits 3 digits, the text wraps and some of it display _outside_ the visible control. The attached screenshot shows 3 `OutcomeChip` objects. The overall count is 110 and the counter renders correctly. The second and third `OutcomeChip` objects show counts of 10 and 100, respectively. The `OutcomeChip` with a count of 100 renders the final '0' on a separate line, which is confusing.

**To Reproduce**

1. Go to a page with lots of items (I happened to use a popular selling site that shall remain nameless in the report but feel free to ask me offline)
2. Run automated checks
3. Go to the __Needs review__ tab
4. Look at the `OutcomeChip` with a count >= 100

## Expected behavior

The count should be completely within the visible OutcomeChip. This may have the side effect of misaligning the columns of the displayed results.

## Screenshots

<img width="770" alt="image" src="https://user-images.githubusercontent.com/45672944/188931639-1c11eaad-2351-49ca-b5db-92dcbbe6c44f.png">

## Context (please complete the following information)

- OS Name & Version: Ubuntu 22.04
- AI-Web Version & Environment: 2.34.1 Insider
- Browser Version: Chrome 105.0.5195.102

## Did you search for similar existing issues?

Yes

**Comment by shanisebarona** [comment]
I am not able to repro this when running the extension on a site with a lot of errors and when manually adding digits to the outcome chip.
