### ISSUE TITLE
BUG: Ad hoc visualization toggle does not reset after extension is toggled off and on

### ISSUE THREAD

**Issue by madalynrose** [microsoft/accessibility-insights-web#6004]
## Describe the bug

When the extension is toggled off and then on again in edge://extensions the visualization toggle does not get set to off even though the visualization is in the off state.

**To Reproduce**

1. Open the ad hoc tools view in the extension on any target page
2. Toggle on an ad hoc visualization (e.g. automated checks)
3. Navigate to the extensions details page (edge://extensions) and toggle the extension off and then back on
4. Return to the target page and open the launch pad
5. See that the visualization toggle is still set to on

## Expected behavior

Visualization toggle is set to off after extension is toggled off and back on

## Screenshots

<img width="401" alt="ad hoc tools showing automated checks in the on state" src="https://user-images.githubusercontent.com/3230904/188936549-787a0c00-9d96-4251-890a-e31b584d461b.png">

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

Found during Insider validation for 2.34.1

**Comment by ferBonnin** [comment]
per triage conversation, won't fix. Leaving this issue for a documented workaround and will revisit if we get considerable customer feedback.
