### ISSUE TITLE
Assessment Overview help box links are using wrong color

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#601]
## Describe the bug

The overview page's help box should be using links of color "communication-primary" per design, but are instead using "communication-shade-10" via the `.insights-link` class. Need to verify with design whether it's the insights-link style that's wrong (ie, whether all of our links should be "communication-primary" by default) or if it's just these specific links that should be changed.

**To Reproduce**

1. Start an Assessment on any page
2. Click on the Overview assessment
3. right click/inspect on any of the links
4. observe that the color is `rgb(16, 110, 190)` (via .insights-link using --link color with `!important`)

## Expected behavior

Links should be colored as communication-primary `rgb(0, 120, 212)`

## Screenshots

![image](https://user-images.githubusercontent.com/376284/56623088-98fbcb80-65e7-11e9-8c1f-9041833c8679.png)

## Extension (please complete the following information)

- OS: Windows
- Version 2.2.0
- Microsoft Edge Version 75.0.131.0 (Official build) dev (64-bit)
- Target Page irrelevant

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

**Comment by cheade** [comment]
Adding in design input for this one - I think the reason why $communication/shade-10 was used here is because on the card background of #F8F8F8, the normal $communication-primary fails color contrast. 

I'm wondering if we should move our primary link color to communication/shade-10 in order to just cover all links, or just use it when we have links on a gray, #F8F8F8 background.

**Comment by dbjorge** [comment]
@cheade I have a slight preference for the former option (ie, making primary link color just be communication/shade-10) but am okay with either. I think the final decision on that is yours.

**Comment by cheade** [comment]
@dbjorge let's go with making the primary link color communication/shade-10.

**Comment by ferBonnin** [comment]
@dbjorge lets just check all color contrast in the tool with and without high contrast with this change.

**Comment by cheade** [comment]
This change shouldn't affect high contrast mode - high contrast mode uses a bright yellow for link colors.

**Comment by cheade** [comment]
I'll tackle this one :)
