### ISSUE TITLE
Left nav item text shifts slightly when a test switches from "in progress" to "pass/fail" status

### ISSUE THREAD

**Issue by dbjorge** [Microsoft/accessibility-insights-web#602]
## Describe the bug

The text alignment of the Test names in the left nav bar shifts slightly when the icon changes from a number to a pass/fail indicator:

![shifting-text-repro](https://user-images.githubusercontent.com/376284/56623313-95b50f80-65e8-11e9-90e0-798a52db5fec.gif)

It appears that either the numerical circles or the pass/fail icons are not quite centered with one another. In the mock there is an equal 8px of top and bottom padding, with a 24px by 24px size. 

**To Reproduce**

1. Start an Assessment on any page
2. Click on any Test with manual pass/fail requirements (eg, "Errors")
3. Mark all the Requirements as "Pass"
4. From any requirement, toggle between setting it as "Pass" and resetting its status
5. As you toggle, observe that the text alignment of the "Errors" item in the left nav bar changes slightly

## Expected behavior

This toggling should not shift the text in the nav bar

## Extension (please complete the following information)

- OS: Windows
- Version 2.2.0
- Microsoft Edge Version 75.0.131.0 (Official build) dev (64-bit)
- Target Page irrelevant

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

**Comment by ferBonnin** [comment]
@dbjorge per conversation with Mark, won't fix.
