### ISSUE TITLE
Submit to Edge Insider Addons store

### ISSUE THREAD

**Issue by cglong** [microsoft/accessibility-insights-web#606]
## Is your feature request related to a problem? Please describe.
It's difficult to install Accessibility Insights for Web onto [Edge Insider](https://www.microsoftedgeinsider.com/).

## Describe the desired outcome
I'd like to be able to install the extension without changing settings in my browser.

## Describe alternatives you've considered
I can enable installation of extensions from other sources (i.e. the Chrome Web Store) and navigate to the extension URL directly to install it.

**Comment by peterdur** [comment]
Work in progress.

**Comment by peterdur** [comment]
We are now in the Edge Insider Addons store - you can find the extension [here](https://microsoftedge.microsoft.com/insider-addons/detail/ghbhpcookfemncgoinjblecnilppimih).
