### ISSUE TITLE
False positive #2? 

### ISSUE THREAD

**Issue by geoffrk00** [microsoft/accessibility-insights-web#6101]
https://webcompliance.trafficmanager.net/ScanResultsApi/GetAccessibilityScanConsolidatedReport?siteId=8172d1b3-b36c-e711-80c2-0004ffc0fa4b

https://learn.microsoft.com/en-us/ is showing an error for

aria-allowed-role: Ensures role attribute has an appropriate value for the element

<aside role="navigation" class="assessments-side-nav is-vertically-scrollable" style="height: 673px;">

role of navigation is allowed on this element
Running AI4W does not flag this as an error

**Comment by jlperkins** [comment]
Hi Geoff, it looks like this instance is a legitimate failure, and it shows up in the Assessment's first automated checks step. If you expand the failure in question in the report you linked to, you can see that the URL it is reporting the failure on is actually [https://learn.microsoft.com/en-us/assessments/?mode=pre-assessment&id=azure-architecture-review&session=local](https://learn.microsoft.com/en-us/assessments/?mode=pre-assessment&id=azure-architecture-review&session=local), and not [https://learn.microsoft.com/en-us/](https://learn.microsoft.com/en-us/).  This is fine; it just means that this is a subpage of your link, which was also scanned during the report generation. Your report states that in total, 100 URLs were scanned, and this was one of them.  

When I run Automated Checks in the Accessibility Insights for Web extension, (whether that's via FastPass or the first step of an Assessment), on [https://learn.microsoft.com/en-us/assessments/?mode=pre-assessment&id=azure-architecture-review&session=local](https://learn.microsoft.com/en-us/assessments/?mode=pre-assessment&id=azure-architecture-review&session=local), I do see the same aria-allowed-role failure. 

Let me know if you are also able to reproduce this.

**Comment by geoffrk00** [comment]
Thanks for the info from mozilla. That is what I was looking for.

We have updated the element to a nav. 

This issue can be closed
