### ISSUE TITLE
Links to Design Pattern in Assessment take you to main ARIA APG page

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#6116]
## Describe the bug
The design pattern links no longer take you to the design pattern page

**To Reproduce**
Got to Assessment > Custom widgets > Design pattern on a page with custom widgets, note that the links we have in the list of instances no longer take you to the design pattern page. Instead they take you to the landing page with all design patterns

## Context (please complete the following information)

- OS Name & Version:  Windows 
- AI-Web Version & Environment:  Insider MV3  2.35.0
- Browser Version:  Chrome
- Target Page:  any

## Did you search for similar existing issues?
yes

## Additional context

There is a new site for WAI ARIA practices that is redirecting the old link to this.

**Comment by ferBonnin** [comment]
we should change the links in all requirements that point to design patterns

**Comment by Pranav-yadav** [comment]
@ferBonnin I can help with this one; if not already assigned to anyone :)

PS: PR for: Parsing Instructions rephrase: `#6130` is opened already & is ready to review & merge.

**Comment by ferBonnin** [comment]
Thanks @Pranav-yadav assigning this to you!
This is the [landing page link](https://www.w3.org/WAI/ARIA/apg/patterns), we would need to point to the right subpage for each pattern. For example for _combobox_  the current link is: [https://www.w3.org/TR/wai-aria-practices-1.1/**#combobox** ](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox) the new link should be: [https://www.w3.org/WAI/ARIA/apg/patterns/**combobox**/](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)


Thanks for the parsing instructions rephase, our team will review and merge!
