### ISSUE TITLE
User is not told if AI-Web skips unresponsive iframe

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#6128]
## Describe the bug

Our extension makes a best-effort attempt to scan child iframes - we send messages to the child frame and wait for a small timeout. If the child frame does not respond by our timeout, we skip the child iframe.

The user should be notified when we skip an iframe. `axe-core` exposes a rule `frame-tested` that we can use to detect when an iframe was skipped.

**To Reproduce**

1. Go to [this demo page](https://karanbirsingh.github.io/temp-snippets/microsoft/accessibility-insights-web/message-capturing-iframes/same-origin.html)
2. Select either checkbox so that child window message events are disrupted
3. Try scanning the page and granting iframe permissions if needed
4. Notice that no issues are found in the child iframe (even though the empty input is unnamed)
5. Notice there is no indication to the user that the frame was skipped

## Expected behavior

`axe-core` has a rule called [`frame-tested`](https://github.com/dequelabs/axe-core/blob/master/doc/frame-messenger.md#error-handling--timeouts) that we can enable in our scans. By default, results will show up in "needs review" and we can add content to flesh it out.

If we prefer to surface the results elsewhere (a dialog box, a notice banner, etc)  that works too.

## Context (please complete the following information)

- AI-Web Version & Environment: Version 2.35.0 
- Target Page: https://karanbirsingh.github.io/temp-snippets/microsoft/accessibility-insights-web/message-capturing-iframes/same-origin.html

This is a demo target page. We have seen websites in our support channel exhibiting this behavior.

**Comment by karanbirsingh** [comment]
@ferBonnin By default, this rule would have shown up in needs review. With the banner, would we like to omit `frame-tested` from needs-review, or is the banner in addition?

Should the banner follow similar design & behavior as the existing banners (screenshot below)?

![banners in ai-web](https://user-images.githubusercontent.com/7775527/198089696-5bdc408b-f459-40d7-84ab-6b36c065fb67.png)

The existing banners have a call to action for the user. In this case, the user probably can't do much because we aren't giving them any configuration options. They should probably file an issue on our GitHub. Maybe there's a default issue template link we can populate for them and suggest in the banner link?

**Comment by ferBonnin** [comment]
@karanbirsingh since we cannot assume the user will step into needs review, we would like to omit the rule and instead add the banner. Yes, the banner should follow similar design & behaviour as the existing banners.

**Comment by sfoslund** [comment]
This was addressed in #6330
