### ISSUE TITLE
Our default iframe ping timeouts may be too low

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#6129]
## Describe the bug

When scanning child iframes, our extension has to wait for a response from each frame. We have to balance two possibilities:
- Analysis or messaging inside the child frame may be slow, so we need to wait long enough for a response. Giving up too early means we lose results.
- The child frame may be entirely unresponsive; perhaps messaging is disabled altogether. Waiting too long means our users get confused because the spinning circle goes forever.

We need to pick the right timeout values so that we can scan as many websites as possible without waiting so long that users get annoyed when child frames are unresponsive.

There are two places where we currently wait for a response:
- we use axe-core's default [`pingWaitTime`](https://github.com/dequelabs/axe-core/blob/master/doc/frame-messenger.md#pingwaittime) value of 500ms
- we have a [custom messenger timeout](https://github.com/microsoft/accessibility-insights-web/blob/main/src/injected/frameCommunicators/all-frames-messenger.ts#L39) of 500ms for tab-stops, visualizations, etc (anything that isn't automated checks)

We have encountered a website on our support channel that requires a higher timeout. No matter what, we should notify the user that their iframe wasn't scanned (tracked separately in #6128).

But this issue tracks whether we should also change our default timeouts.

**To Reproduce**

1. Go to this [demo page](https://karanbirsingh.github.io/temp-snippets/microsoft/accessibility-insights-web/message-capturing-iframes/same-origin.html)
2. Check the "delay propagation" checkbox
3. Scan the website with AI-Web
4. Notice we find no issues in the child iframe (we should, the input is empty)

## Expected behavior

We have a few options:
- Accept a higher ping timeout. In local testing on my computer, increasing the timeouts to 1000ms allows us to scan this website. However, different environments will have different performance - it's possible that even 1000ms is too low for some setups.
- Allow the end-user to configure the ping timeout from their extension. It could be a developer setting.
- Leave things as they are

## Context (please complete the following information)

- AI-Web Version & Environment: 2.35 prod

**Comment by ferBonnin** [comment]
triaged with Peter, let's add telemetry to detect instances of this and baseline.

after, lets open another tracking bug to increase the timeout based on the telemetry. We should also confirm increasing the timeout doesn't impact scanning pages without slow iframes.

**Comment by karanbirsingh** [comment]
@ferBonnin Can you elaborate on the telemetry requirements? What in particular should we capture?

If axe-core is unable to contact the frame because of a low `pingWaitTime`, I am not sure if we can detect this beyond the results of `frame-tested` described in #6128 . Maybe @dbjorge knows more? Here is our [axe-frame-messenger](https://github.com/microsoft/accessibility-insights-web/blob/main/src/injected/frameCommunicators/axe-frame-messenger.ts) and [here are the axe-core docs](https://github.com/dequelabs/axe-core/blob/master/doc/frame-messenger.md#error-handling--timeouts) about frame messaging in general.

For the custom frame-messenger timeouts used in non-axe-core parts of the application, we log the error message & therefore can already query in telemetry:
```
customEvents 
| where name contains "error" 
| where customDimensions.message contains "Some iframes"
| project timestamp, customDimensions.installationId, session_Id, customDimensions.message
| limit 100
```

I think in general any such events will tell us "a timeout happened", but the timeout value will never differ from our configured maximum of 500ms.

**Comment by ferBonnin** [comment]
@karanbirsingh we were not aware that we already had telemetry for this, our plan was to analyze how often it happened for a baseline before changing the maximum. Let's re-triage this with the new information

**Comment by ferBonnin** [comment]
@shanisebarona assigning to you per draft PR 🙂

**Comment by dbjorge** [comment]
Updated the timeout from 500ms to 1000ms in #6176.
