### ISSUE TITLE
Parsing instructions can be confusing

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#6130]
## Describe the bug

The parsing instructions say: "Run the first bookmarklet in the browser tab containing your target page"
Users might not know how to run the bookmarklet in their page. 

**To Reproduce**

Go to assessment > Parsing > Parsing

## Expected behavior

Instead, I propose we have: "Run the first bookmarklet in the browser tab containing your target page by selecting the bookmarklet in the browser window with your target page" 

This is a bit wordy so suggestions are appreciated.

## Context (please complete the following information)

- OS Name & Version:  Windows
- AI-Web Version & Environment:  2.35.0 MV3 Insider
- Browser Version:  Chrome
- Target Page:  any

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

Observed while talking with a user

**Comment by peterdur** [comment]
Suggestion: maybe "Go to the browser tab containing your target page and, in that browser window, select the first bookmarklet"?

**Comment by Pranav-yadav** [comment]
@ferBonnin I can help with this one; if not already assigned to anyone :)

**Comment by ferBonnin** [comment]
thanks @Pranav-yadav! Assigning this to you 🙂
