### ISSUE TITLE
Assessment 9.1 (Design patterns) is a little confusing about what multiple listed patterns per instance means

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#6178]
## Describe the bug

We had a user write to us today that felt confused by Assessment Requirement 9.1 (Design patterns). They were not familiar with the notion of patterns vs roles and were confused by the way the instances list presents more than one "Design pattern" per instance for roles which can map to more than one possible design pattern - they weren't sure if we were indicating that the instance was somehow simultaneously mapping to multiple design patterns or what.

We could probably help future users avoid this confusion if we clarified the "Design patterns:" label in the instances list and/or the requirements text to clarify that an instance should be marked passed if design pattern which best describes the instance is listed at all among the multiple listed patterns, and *not* that it needs to somehow meet *all* of the listed design pattern descriptions simultaneously.

Maybe something like changing "Design patterns" to "Allowed design patterns" or "Allowed design patterns for role" or similar, and changing step 3 in the "How to test instructions" from the current:

> 3. In the **Instances** list below, verify that the custom widget has the right role for its design pattern.

...to something more like...

> 3. In the **Instances** list below, verify that the design pattern which best describes the custom widget is one of the listed allowed design patterns for that widget's role.

**To Reproduce**

1. Go to https://www.w3.org/WAI/demos/bad/before/home.html (or any other test page that triggers 9.1)
2. Start an assessment
3. Navigate to requirement 9.1
4. Observe current text/instance list labeling

## CodePen repro example

n/a

## Expected behavior

Users unfamiliar with ARIA design patterns/roles should be able to understand how to pass/fail widgets in the requirement

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: n/a
- AI-Web Version & Environment: 2.35.0 Prod
- Browser Version: n/a
- Target Page: n/a

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

#6116 is a recent issue that should help somewhat with the same requirement, but it doesn't seem like it was the root cause of this specific user's problem - the user was able to find the design patterns even without the improved link, they just didn't understand how to apply it to the pass/fail requirement.

**Comment by ferBonnin** [comment]
Thanks for this issue! I agree bringing some more clarity into why multiple patterns are listed would be helpful. The proposed text  is assuming that the user has the right role to start with. Ideally that would be the case but not necessarily (in the info an examples we use the difference between dialog and alert that would use two different roles).

I would suggest brainstorming a different text that stills ensures the user confirms that the widget has the right role for the design pattern they want to use
