### ISSUE TITLE
Make Assessment 11.4 (Status messages) assisted

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#6179]
## Is your feature request related to a problem? Please describe.

This issue is based on a customer support request where they were confused by 11.4's "How to test" instruction to

> 3. Inspect the page's HTML to identify an empty container with one of the following attributes:

The user was confused about exactly how they should be looking for such elements.

## Describe the desired outcome

I think this is a good candidate for creating a (partially) assisted requirement - it is much easier for us to query for containers matching one of those attributes than it is for the user to do so (`document.querySelectorAll('[role="alert"],[role="log"],[role="progressbar"],[aria-live="assertive"]')` is close but doesn't handle iframes/open shadow DOM). I think an instance list that presents containers matching that pattern and includes a note about the container's current text content would make it easier for a user to test this requirement, especially a user that isn't super familiar with browser dev tools (like the motivating case).

## Describe alternatives you've considered

I'm not sure there's a great option for keeping it manual and improving the "How to fix" text - the only thing that comes to mind is literally suggesting the `document.querySelectorAll` approach, but it's questionable when we know there are edge cases that will miss.

## Additional context

n/a

**Comment by DaveTryon** [comment]
We're working on a feature of assessment improvements and will consider this as a candidate for that feature. 

Thanks for using Accessibility Insights!
