### ISSUE TITLE
available with command line so it can be incorporated in CI/CD Pipeline

### ISSUE THREAD

**Issue by kamal2222ahmed** [microsoft/accessibility-insights-web#6191]
## Is your feature request related to a problem? Please describe.

As part of 508/Trusted Tester ,I want to be able to run this as part of a CI/CD Pipeline and results posted as part of a build.
## Describe the desired outcome

$aib fastpass result.json
$aib assessment result.json
etc
and results be also available as HTML pages ( local ) 
the result.json is available for later integration with other reporting tools
## Describe alternatives you've considered

I have tried axe-code and cypress-axe but the issue its that they do not align with Trusted Tester or 508 
## Additional context

it would be helpful to highlight the WebElement failing the WCAG Criteria and a suggestion on how to fix and test it.

**Comment by shanisebarona** [comment]
Hi @kamal2222ahmed, thank you for your submission! 

We do offer a command line solution! It crawls an entire site and performs our automated checks against each page. It is published as the [accessibility-insights-scan NPM package](https://www.npmjs.com/package/accessibility-insights-scan).

We also maintain an [Accessibility Insights Action](https://github.com/microsoft/accessibility-insights-action/blob/main/docs/gh-action-usage.md) for GitHub Actions.

We also maintain a set of [sample code](https://github.com/microsoft/axe-pipelines-samples) which has example of how to integrate the accessibility scanning engine we use ([axe-core](https://github.com/dequelabs/axe-core)) into test suites that use a few popular browser automation tools like [Playwright](https://playwright.dev/) and [Selenium](https://www.selenium.dev/). This will cover common accessibility issues, and while we are constantly thinking about how to automate more types of checks, unfortunately there are many types that cannot be detected by automation.

**Comment by katydecorah** [comment]
Hi @lee0c, you're right, we did deprecate the GitHub Action within the last few weeks. In addition to the recommendations that Shanise made, we do have an [Azure DevOps extension](https://github.com/microsoft/accessibility-insights-action/blob/main/docs/ado-extension-usage.md) which is available to internal Microsoft teams. Feel free to reach out to us if you have any questions about getting started with the extension.

**Comment by lee0c** [comment]
@katydecorah Thanks for getting back to me so quickly! I'm looking at GH specifically, not AzDO unfortunately, but I expect I can still make progress with the NPM package linked above. Thanks again!
