### ISSUE TITLE
[Bug] Test page contents are not rendering properly after running automated checks

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#6212]
## Describe the bug

We have a web site where running AIWeb causes the content of the nav pane to disappear. It exists in HTML, but does not render as expected.

**To Reproduce**

1. Go to https://tdc.azure.net/welcome (requires MSFT login). Notice that the Home button is displayed
<img width="375" alt="image" src="https://user-images.githubusercontent.com/45672944/204363622-d20ff1dc-e608-454a-9920-691590a14ce7.png">

2. Run FastPass. Notice that the Home button is _not_ displayed
<img width="374" alt="image" src="https://user-images.githubusercontent.com/45672944/204363792-32338b6c-6362-47f4-8a3a-105557b8cfce.png">

3. Inspecting the page when the button is not displaying confirms that it's still there in the HTML, but something is interfering with the rendering.

Additional observation: I positioned the FastPass results and the original page so they were both visible, then refreshed the original page multiple times. 2 consistent patterns emerged:
1. On the first refresh, the Home button flashed momentarily then disappeared. It consistently appeared on the second refresh.
2. Pressing "Start Over" from the automated checks page caused the home button to disappear again.

## Context (please complete the following information)

- OS Name & Version: Win11 22H2 (also happens on MacOS Ventura 13.0.1)
- AI-Web Version & Environment: 2.35.0 Production
- Browser Version: Google Chrome 107.0.5304 (Official Build)
- Target Page: https://tdc.azure.net/welcome

**Comment by ferBonnin** [comment]
triaged with @peterdur we should investigate. Ideally let's create a minimal repro that doesn't depend on this page. We should check if it has anything to do with both sites using Fluent UI

**Comment by dbjorge** [comment]
Resolved by #6294
