### ISSUE TITLE
investigation for "ResizeObserver loop limit exceeded" unhandled error

### ISSUE THREAD

**Issue by shanisebarona** [microsoft/accessibility-insights-web#6215]
This issue is to track the engineering task of further investigation into the "[ResizeObserver ](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)loop limit exceeded" unhandled error. 

Based on initial investigation as part of 1994211, this error might be related to our use of [`react-resize-detector`](https://github.com/maslianok/react-resize-detector). It's possible all the listeners that need to be notified, might not be, thus throwing the error.

Task: A follow up investigation on how we can add better logging of react's update timings. 
- Is it possible to get the timing of react updating? 
- If so, does react do that?
- Are there points in the application where react takes a long time to update?
- Can use/add telemetry to log the components involved?

**Comment by DaveTryon** [comment]
After reviewing the list of issues in our backlog, we have concluded that we will not be address this issue.
