### ISSUE TITLE
Update usages of assessments provider to be from deps instead of props

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#6238]
## Describe the bug

AssessmentsProvider is something we use through deps but in a few cases it is coming through props. This is further conflated by the filtered assessment provider which **should** be used through props. Reducing the times where use it through props when we shouldn't should help clear up some of the verbose component usages.

An example PR for this: #6235

**Comment by DaveTryon** [comment]
Closed prematurely

**Comment by DaveTryon** [comment]
After reviewing the full list of issues in our backlog, we have concluded that we will not be addressing this issue.
