### ISSUE TITLE
"List view and filtering" incorrectly tagging iframe elements for Needs Review

### ISSUE THREAD

**Issue by JGibson2019** [microsoft/accessibility-insights-web#6254]
## Describe the bug
Clicking "List view and filtering" after toggling Needs Review from the Ad Hoc panel is incorrectly tagging some elements within an iframe as Needs Review

**To Reproduce**

1. Go to /accessibility-insights-web/src/tests/end-to-end/test-resources/all.html (from the Web repo)
2. Click on the Accessibility Insights extension
3. Click "Ad hoc tools"
4. Toggle "Needs review" on
5. Click "List view and filtering"
6. See multiple color contrast issues (at this point 24) listed in Details View
7. Click "Start over" in Details View
8. See 0 instances to review

## Expected behavior
Consistently finding the same number of instances to review

## Context (please complete the following information)

- OS Name & Version: Windows 11 Enterprise Version 10.0.22621 Build 22621
- AI-Web Version & Environment: Production 2.35.0
- Browser Version: Google Chrome Version 108.0.5359.95
- Target Page: /accessibility-insights-web/src/tests/end-to-end/test-resources/all.html (from the Web repo)

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
triaged with @peterdur, we should investigate

**Comment by nang4ally** [comment]
Adjusted priority, discussed with @peterdur

**Comment by JGibson2019** [comment]
Closing because no longer repros
