### ISSUE TITLE
Inspect Element doesnt work if the same element is inspected again

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#627]
## Describe the bug

**To Reproduce**

1. Go to any page with a11y issues
2. Run automated checks
3. click on one of the issues in the target page to open issue details dialog
4. Open devtools
5. Click on Inspect element
6. Select some other element in the devtools.
7. Inspect the same issue again.

## Screenshots
![issue](https://user-images.githubusercontent.com/29855291/56930070-6858dd80-6a90-11e9-8c38-8d5fac8f063e.gif)

**Expected**
The issue element should be highlighted in dev tools

**Actual**
The current selection in dev tools is not changed

**Comment by ferBonnin** [comment]
@devaradhanm what happens if you do not "Collapse body html element in the dev tools"? or you close the inspect?
We feel like this is a weird edge case.

**Comment by ferBonnin** [comment]
From conversation with Peter: this is kind of an edge case (we havent heard of a user having it) but we understand it can be confusing. temporary workaround, if this happens, inspect another element and then come back.
@devaradhanm do we know if this is happening because we are filtering a duplicate request to inspect the element or is it on the devtools side?

**Comment by iamrafan** [comment]
@ferBonnin I too faced this issue many times when investigating user issues. It was tough for me to go back and inspect the same element after making changes in the DOM in other places (Especially in custom widgets).

**Comment by devaradhanm** [comment]
@ferBonnin , this is happening because of the way we handle store message changes in [StoreProxy](https://github.com/microsoft/accessibility-insights-web/blob/d467cb0ae5cd3ed64a988f4cce6f4715e25e6a4d/src/common/store-proxy.ts#L32). (We don't fire change event when there is no state change)
including @waabid & @smoralesd on their inputs if we can fix this easily without breaking other functionality.

**Comment by devaradhanm** [comment]
@ferBonnin , I dont think we need to do any investigation here. we can go ahead with the implementation i suggested based on priority.

**Comment by smoralesd** [comment]
@devaradhanm is this too hacky a fix? https://github.com/microsoft/accessibility-insights-web/pull/713
