### ISSUE TITLE
Tool Incorrectly Reports button-name rule failure when "for" is used for programmatic mapping of accessible name

### ISSUE THREAD

**Issue by cabillin** [microsoft/accessibility-insights-web#6275]
## Describe the bug

Tool Incorrectly Reports button-name rule failure when "for" is used for programmatic mapping of accessible name

**To Reproduce**

1. Go to page that uses "for" for programmatic mapping of accessible name (e.g. 
2. Click on Accessibility Insights for Web plugin

If repro'ing on CodePen
4. Click on FastPass and grant it permission to the iframe
5. Click on button-name under "Failed instance"

If repo'ing on normal site
4. Click on Ad hoc tools, then Automated checks
7. Click on red box/! that show up around button & observe that rule = button-name

## CodePen repro example

https://codepen.io/KnetTravlr/full/zYLOzLO

## Expected behavior

No issues found by Accessibility Insights for Web plugin on this component

## Screenshots

![image](https://user-images.githubusercontent.com/71525014/208218335-c500b134-d21c-4e9c-8c16-d7103a83f166.png)

## Context (please complete the following information)

- OS Name & Version: Windows 11 Pro Insider Preview Build 25267.1000
- AI-Web Version & Environment:  2.35.0
- Browser Version: Microsoft Edge Version 108.0.1462.46 (Official build) (64-bit)
- Target Page: internal Microsoft site

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes, on github issues

## Additional context

None

**Comment by katydecorah** [comment]
Thanks for writing in and sharing the test case, @cabillin.

I reviewed your test case this morning, and I believe that this is a true positive. For form controls like `input`, you can use the pattern of `htmlFor` and `id` to associate a label with the input. However, the `button` element does not observe the same pattern and requires an accessible name to be set as a `title`, `aria-label`, or `aria-labelledby` attribute, or provide inner text. You can read [more about how to fix `button-name`](https://accessibilityinsights.io/info-examples/web/button-name/).

In case you haven't seen it, the FluentUI `Toggle` component does offer a `label` prop to define an accessible label. The [FluentUI documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle#usage) also offers a "Toggles with custom labels" example to show you can create an accessible custom label.

I hope this information helps. Please let us know if you have any questions.

**Comment by cabillin** [comment]
I apologize for the delay; I was on vacation. I would like to reopen this issue.

Per the mozilla docs, using for (htmlFor) with button is valid:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
![image](https://user-images.githubusercontent.com/71525014/210679857-82e08cf4-7dc0-43bf-a22d-5043d119d139.png)

https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#labelable
![image](https://user-images.githubusercontent.com/71525014/210679920-9d0922d4-28da-4a96-851f-279a67847bfa.png)

Please point me to any other documentation that indicates that for/htmlFor with a button is invalid.

Thank you, yes, I saw those options in the Fluent component, but we have a specific use case that we are using this for.

**Comment by katydecorah** [comment]
Thanks for following up, @cabillin! 

I looked into this a bit more this morning and found the following resources from Web Content Accessibility Guidelines (WCAG), which this automated check is based on for its success criteria:

- From [Using label elements to associate text labels with form controls](https://www.w3.org/WAI/WCAG21/Techniques/html/H44#description) under the Description section, it states: "The label element is not used for the following elements: button (the label is provided by the content)&hellip;"

- From [Test cases, Button has non-empty accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/97a4e1/#test-cases), none of the passed examples show usage with `label` element.

- From [Button, ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/button/#wai-aria-roles-states-and-properties-3), the section does not mention using `label` element.

- From [Labeling Buttons, Labeling Controls](https://www.w3.org/WAI/tutorials/forms/labels/#labeling-buttons), the section does not mention using `label` element.


I believe the MDN reference where it states the `label` element can be associated with `button` element [comes from the HTML standard](https://html.spec.whatwg.org/multipage/forms.html#category-label). I think this a case where the HTML markup is correct according to the HTML spec but is not an accessible practice as described by the WCAG success criteria.

I hope this information helps. Please let us know if you have any questions.

**Comment by cabillin** [comment]
It's true that [Using label elements to associate text labels with form controls](https://www.w3.org/WAI/WCAG21/Techniques/html/H44#description) states: "The label element is not used for the following elements: button (the label is provided by the content)…", but it also doesn't have any examples where the label is outside of the button and it doesn't have examples where the label is not provided by the content. We know that using aria-labelledby is valid because this page mentions aria-labelledby in the bibliography & [Button, ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/button/#wai-aria-roles-states-and-properties-3) explicitly state that aria-labelledby can be used. But if aria-labelledby is being used, shouldn't the element be a label (which essentially invalidates the original statement of "The label element is not used for ... button")?

Looking at [their suggested implementation of the switch](https://www.w3.org/WAI/ARIA/apg/example-index/switch/switch-button) (the generic pattern for Fluent's toggle), they still have their visible label inside the button, which is not something I've seen in any live implementation of a switch in production code. 🤷‍♀️But [ARIA Authoring Practices Guide (APG): Switch](https://www.w3.org/WAI/ARIA/apg/patterns/switch/) does explicitly state that aria-labelledby is a valid way to programmatically map the name (still no example) but does not mention for/htmlFor.

Especially given the general preference to use native HTML rather than aria, I find the recommendation to use aria-labelledby rather than for/htmlFor inconsistent with general best practices. I plan to reach out to public-aria-practices@w3.org to ask for more explicit guidance in their docs, but I will conform in the meantime.

Thank you for your time.
