### ISSUE TITLE
Ad hoc tools headings overlap with guidance text when text is too long

### ISSUE THREAD

**Issue by ThanyaLeif** [microsoft/accessibility-insights-web#6293]
## Describe the bug

When link text is too long or the browser's font size is set as large, it is possible to enter a state where "Ad-hoc tools" headings and the guidance link get drawn over each other.

![2f74365b-c31e-492c-a918-36da433a9360](https://user-images.githubusercontent.com/32908302/209226963-bc618501-fee7-49b5-a311-1e05717661c2.jpg)

**To Reproduce**

1. Go to your browser `settings > Appearance` and change font size to large
2. Open AI4Web (production)
3. Go to "Ad hoc tools"
4. See how the spacing between "Accessible names" and the guidance link is narrower than the rest of the links.

(If you edit the link's text to make them longer you will notice how to headings and links starts to overlap)

## CodePen repro example

n/a

## Expected behavior

Text shouldn't overlap.

## Screenshots

See above

## Context (please complete the following information)

- OS Name & Version: Windows 11 Enterprise Build 22621.963
- AI-Web Version & Environment: Accessibility Insights for Web 2.35.0
- Browser Version:  Edge Version 108.0.1462.46 (Official build) (64-bit)
- Target Page: n/a

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context
n/a

**Comment by ferBonnin** [comment]
suggesting to timebox to 4 hours and regroup if needed
