### ISSUE TITLE
Color contrast error with Bootstrap 4 themes

### ISSUE THREAD

**Issue by Yuvan111** [microsoft/accessibility-insights-web#6299]
## Describe the bug

We are experiencing an issue with the color contrast in our sample when using the Bootstrap 4 themes. We are referencing the official Bootstrap 4 script for the button component, as seen in the sample link provided: 

https://stackblitz.com/edit/wgumyr?file=index.html.

We have also used the Accessibility Insights web tool to check for any potential issues, and we are seeing a color contrast error on the Bootstrap 4 official page itself.

**To Reproduce**

1. Run the stack blitz sample(https://stackblitz.com/edit/wgumyr?file=index.html).
2. Check the accessibility issue using the google chrome extension of accessibility insights web tool.
3. And see the accessibility error(color-contrast) in button tag.

## Expected behavior

Please check the color-contrast issue based on bootstrap4 official standard guidelines, to avoid this type error.

## Screenshots

![image](https://user-images.githubusercontent.com/89587491/209676397-6508abf9-8658-4151-825c-2876ca5062ea.png)
![image](https://user-images.githubusercontent.com/89587491/209676435-b46f4326-645b-40a2-821a-6c92a00cda7b.png)

**Comment by ferBonnin** [comment]
Hi @Yuvan111 thanks for reaching out and using Accessibility Insights! 
These color-contrast issues look legitimate to me; did you mean to file this bug on the Bootstrap GitHub instead of the Accessibility Insights repo?
