### ISSUE TITLE
Kaspersky detected a file as HEUR:Trojan.Script.Generic

### ISSUE THREAD

**Issue by ArnaldoDM** [microsoft/accessibility-insights-web#6307]
I don't know if this information is interesting to share here.
My antivirus Kaspersky detected a trojan horse on my chrome extension "Accessibility insights for web"

Event: Object was not processed
User: *******
User Type: Active User
Module: Virus Scan
Result: Untreated
Description Result: Unprocessed
Type: Trojan Horse
Name: HEUR:Trojan.Script.Generic
Accuracy: Heuristic analysis
Threat Level: High
Object Type: File
Object Name: detailsView.bundle.js
Object Path: C:\Users\*******\AppData\Local\Google\Chrome\User Data\Profile1\Extensions\pbjjkligggfmakdaogkfomddhfmpjeni\2.36.1_0\bundle
SHA256: DA5F63BA8E7B5BA8D21339A1A4494819D39EBB7F3AEBB4394B73E401B4D1CD29
MD5: 5A26C15BA091ACDB16E6258FF9E23E4E
Reason: Ignored

![trojan](https://user-images.githubusercontent.com/56535180/210367363-5c61fc9f-d2f2-4172-b0a9-d1283cf1daf5.png)

**Comment by MarkSky** [comment]
I have the same problem!
`
事件: 偵測到惡意物件
使用者類型: 目前使用者
元件: 智慧查殺
結果: 偵測到
結果描述: 偵測到
類型: 木馬程式
名稱: HEUR:Trojan.Script.Generic
精確度: 啟發式分析
威脅等級: 高
物件類型: 檔案
物件名稱: detailsView.bundle.js
物件路徑: C:\Users\pte75\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\ghbhpcookfemncgoinjblecnilppimih\2.36.1_0\bundle
MD5: 5A26C15BA091ACDB16E6258FF9E23E4E
原因: 專家分析
資料庫發佈日期: 今天，2023-01-05 11:19:00
`

**Comment by pownkel** [comment]
After some more investigation, I see that Kaspersky is showing a false positive on production and insider builds of our extension, including a build of the most recent main branch. Our canary and dev builds are not affected, so I suspect that Kaspersky is thrown off by something in the minified version of detailsView.bundle.js. Our internal antivirus software does not detect any threats in our extension, and the hashes of the file scanned are identical to the hashes shared here. I've submitted a request for reanalysis to [opentip.kaspersky.com](https://opentip.kaspersky.com/), and suggest that anyone experiencing this issue does the same to help bring this to their attention.

@ArnaldoDM @MarkSky In the short term, if you're not comfortable creating an exception in your antivirus software, the [Canary version](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem) of our extension does not trigger the false positive from Kaspersky.
