### ISSUE TITLE
[Usability] Make failure instance highlight more visible for Android

### ISSUE THREAD

**Issue by katydecorah** [microsoft/accessibility-insights-web#6341]
## Describe the bug

In https://github.com/microsoft/accessibility-insights-web/issues/5610, and resolved in https://github.com/microsoft/accessibility-insights-web/pull/6164, the injected highlight style was updated to improve its visibility. Android could also benefit from updating the style in Android's "Automated check" panel.

**To Reproduce**

1. Open an app using Accessibility Insights for Android
2. Visit Automated checks
3. See the highlighted elements in the "Target app screenshot"

## CodePen repro example

n/a

## Expected behavior

The highlighted elements in Android use the new style introduced in https://github.com/microsoft/accessibility-insights-web/pull/6164, which displays a red and white border.

## Screenshots

The screenshot below shows the current highlight style which is a flat red border with an adjacent white-colored exclamation point inside a red square.

![](https://user-images.githubusercontent.com/2180540/211906720-03501bcf-35b4-4193-9d77-5b8be0fd36c5.png)

## Context (please complete the following information)

- OS Name & Version: 
- AI-Web Version & Environment: Accessibility Insights for Android 2023.109.3 Insider
- Browser Version: 
- Target Page: 

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

The current styles for the Android highlight box live in [`highlight-box.scss`](https://github.com/microsoft/accessibility-insights-web/blob/176f5567deef9df88a028070f24c2e56584a3744/src/electron/views/screenshot/highlight-box.scss#L0-L1) and are applied to [`highlight-box.tsx`](https://github.com/microsoft/accessibility-insights-web/blob/176f5567deef9df88a028070f24c2e56584a3744/src/electron/views/screenshot/highlight-box.tsx). Ideally, we would share the styles for the highlight box defined in [`injected.scss`](https://github.com/microsoft/accessibility-insights-web/blob/176f5567deef9df88a028070f24c2e56584a3744/src/injected/styles/injected.scss#L258-L322).

**Comment by DaveTryon** [comment]
We won't be fixing this
