### ISSUE TITLE
Color-contrast issue on Detailsview automated checks page.

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-web#643]
## Describe the bug

Color contrast issue on Automated checks page. 

**To Reproduce**

1. Run automated checks from Ai4w extension on any page.
2. Open developer tools (F12) and open console
3. Run `A11YSelfValidator.validate()`
4. See 1 color-contrast issue found.

## Expected behavior

There should not be any error in console.

## Screenshots

![image](https://user-images.githubusercontent.com/4496335/57043500-8f441a80-6c1c-11e9-82f6-52b7d677b09c.png)

![image](https://user-images.githubusercontent.com/4496335/57043579-de8a4b00-6c1c-11e9-9cea-688894fa9728.png)

## Extension (please complete the following information)

- OS: Windows 10
- Version: Insider 2.3.0
- Browser Version: Edge Insiders
- Target Page: Doesn't matter

## Are you willing to submit a PR?

Yes

**Comment by ferBonnin** [comment]
@Shobhit1 could you fix this, please?

**Comment by Shobhit1** [comment]
Fixed.
