### ISSUE TITLE
Color contrast suggestions may require update for axe-core#3928

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#6469]
## Description

`axe-core` is considering a future update to the way they format `color-contrast` messages in https://github.com/dequelabs/axe-core/issues/3928 which would be likely to require a corresponding update to our machinery that injects suggested colors into those messages.

This doesn't require any action on our end right now, but filing an engineering/tech debt issue to track the likely future work and to link the two issues for notification purposes.

**Comment by DaveTryon** [comment]
When we first discussed this, we thought we had a unit test that would catch it. That isn't the case, since the unit tests convert our data into a snapshot. We would need a unit test that converts live data from axe-core into a snapshot to detect this.
