### ISSUE TITLE
Card selection stores logic should be consolidated

### ISSUE THREAD

**Issue by sfoslund** [microsoft/accessibility-insights-web#6489]
We have 3 separate card selection stores which are all used for different purposes but share much of their logic. See for example the `onNavigateToNewCardsView` function for each:

- https://github.com/microsoft/accessibility-insights-web/blob/main/src/background/stores/needs-review-card-selection-store.ts#L202
- https://github.com/microsoft/accessibility-insights-web/blob/main/src/background/stores/assessment-card-selection-store.ts#L208
- https://github.com/microsoft/accessibility-insights-web/blob/main/src/background/stores/card-selection-store.ts#L192

Ideally we should find a way to consolidate this logic into one place, instead of keeping it duplicated across 3 separate files. 

See https://github.com/microsoft/accessibility-insights-web/pull/6457#discussion_r1132794819 for context

**Comment by DaveTryon** [comment]
After reviewing the full list of issues in our backlog, we have concluded that we will not be addressing this issue.
