### ISSUE TITLE
Assessment > Headings - Heading highlighted on page is missing from list

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#651]
## Describe the bug

There is a mismatch between headings (1) highlighted in the target page and (2) displayed in the Instances list. 

**To Reproduce**

1. Go to https://www.uwb.edu/brand/website/accessibility/examples/inaccessible-page.
2. Launch an assessment.
3. Go to the Headings test (requirement 1).
4. Compare the headings that are highlighted in the target page vs. those in the list of instances. A heading in the upper left corner of the target page is highlighted, but doesn't appear in the list.

## Expected behavior

The headings highlighted should exactly match the headings listed.

### Highlighted headings

![image](https://user-images.githubusercontent.com/45569509/57245512-e288e500-6fef-11e9-9b9d-96a7bc926caa.png)

### Headings in the Instances list

![image](https://user-images.githubusercontent.com/45569509/57245581-12d08380-6ff0-11e9-823e-fbe87c0f2b20.png)

## Extension (please complete the following information)

- OS: Windows
- Version: 2.3.0
- Browser Version: Version 74.0.3729.131 (Official Build) (64-bit)
- Target Page: https://www.uwb.edu/brand/website/accessibility/examples/inaccessible-page

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by waabid** [comment]
This seems to be happening because the element in question is not hidden using traditional means (i.e. display none) but rather, using absolute positioning (positioned off screen). As a result, we do not ignore this heading and try to draw on it.

This box seemingly appearing randomly is likely happening because we do not calculate whether an element is able to be drawn on at a later time.

**Comment by ferBonnin** [comment]
@waabid the element does appear in the list for me and I see it in the screenshot Lisa Louise attached (is _site information_) the number of highlighted elements in the page matches with the number of elements listed.

**Comment by LiLoDavis** [comment]
@ferBonnin You're right - I didn't match it to the element in the list because of its odd placement in the DOM. I'll close this bug as by design.
