### ISSUE TITLE
Launching web extension sometimes gets stuck in loading spinner

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#6524]
## Describe the bug

A few users have reported scenarios where they aren't able to successfully launch the extension (ie, click the browser action icon to load the extension popup). We aren't sure exactly what conditions lead to this case yet. In most cases, the issue appears to get resolved by reloading the extension; however, we have had at least [one report from a user that sees the issue reliably even after uninstalling and reinstalling the extension](https://stackoverflow.com/q/75751002/2825668).

We are suspicious that one possible explanation could be users with invalid stored application state which causes the extension to error while loading. However, this wouldn't explain cases that persist across uninstall/reinstall. It's possible that there may be multiple issues causing similar symptoms.

@nang4ally, @lisli1, and myself have all seen this symptom at least once before, but don't have a current repro or working repro steps. Our next steps would be some combination of:

* Reach out to user(s) with consistent error state and request console error logs + a dump of application state.
* Spend some time attempting to reproduce the issue locally (maybe with some attempts at uninstalling/reinstalling)
* Add some sort of self-healing mechanism to detect this class of issue and offer to clear some/all application state to try to work around it

**To Reproduce**

Not yet known

## CodePen repro example

n/a

## Expected behavior

Application should be able to load successfully, even if stored state is somehow invalid

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: Dan has reproed on Windows 11, unsure if other platforms have reproed
- AI-Web Version & Environment: 2.37.3 Production (but also sometimes on dev builds)
- Browser Version: Unknown
- Target Page: Unknown if this is a factor

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

* [Related public StackOverflow question](https://stackoverflow.com/q/75751002/2825668)

**Comment by dbjorge** [comment]
If anyone does encounter this issue, it would be very helpful if you could provide a dump of the application state of Accessibility Insights. To gather this data:

1. **WARNING**: This debugging data may contain information identifying the pages open in your browser as well as any in-progress work in Accessibility Insights, which may include HTML snippets from page(s) being tested. Do not share this debugging data unless you are comfortable with this! You will have the opportunity to review the data (in step 5) before sharing it (in step 6).
2. Activate Accessibility Insights by clicking its icon in the browser toolbar (or equivalent keyboard shortcut)
3. Right click on the popup with the loading spinner and select "Inspect"
4. In the resulting Developer Tools window's "Console" interface, run the following snippet, which should result in a prompt to save a JSON file named `accessibility-insights-indexeddb.json`:
```js
var dbOpenRequest = indexedDB.open("default-db", 1);
dbOpenRequest.onerror = () => {
  console.log("Error opening IndexedDB. Make sure you're running this script from the DevTools console of an Accessibility Insights window, not a page being tested.");
};
dbOpenRequest.onsuccess = () => {
  console.log("Successfully opened IndexedDB, attempting to query stored data");
  const db = dbOpenRequest.result;
  const transaction = db.transaction(["default-store"]);
  const objectStore = transaction.objectStore("default-store");
  const getAllRequest = objectStore.getAll();

  getAllRequest.onerror = () => {
      console.log("Error querying IndexedDB. Make sure you're running this script from the DevTools console of an Accessibility Insights window, not a page being tested.");
  }
  getAllRequest.onsuccess = () => {
    console.log("Successfully queried IndexedDB data, attempting to export contents");
    const appState = getAllRequest.result;
    console.log(appState);

    console.log("WARNING: This debugging data may contain information identifying the pages open in your browser as well as any in-progress work in Accessibility Insights, which may include HTML snippets from page(s) being tested. Do not share this debugging data unless you are comfortable with this!")

    const contentBlob = new Blob([JSON.stringify(appState)], { type: "text/plain" });
    const linkElement = document.createElement("a");
    linkElement.download = "accessibility-insights-indexeddb.json";
    linkElement.href = window.URL.createObjectURL(contentBlob);
    linkElement.click();
  };
};
```
5. Feel free to review the contents of the file before sharing it
6. Share the resulting JSON file (for example, by uploading it as a [GitHub gist](https://gist.github.com/) and commenting here in this issue with a link)

**Comment by DaveTryon** [comment]
There's nothing we can do on this without a consistent repro. If you have a consistent repro of this, please follow [these instructions](https://github.com/microsoft/accessibility-insights-web/issues/6524#issuecomment-1480358977) and upvote the issue. Thanks!

**Comment by JGibson2019** [comment]
No upvotes for this issue so closing due to inconsistent repro
