### ISSUE TITLE
Provide users with ability to import/export an assessment as data (e.g. json)?

### ISSUE THREAD

**Issue by mmafe** [microsoft/accessibility-insights-web#653]
Currently I can only work on a single assessment at a time. If I want to start a new assessment, I'm forced to lose my previous work. I am also unable to edit a previously exported assessment once I've started a new one.

# My Request
In addition, I would love to be able to:
- export an assessment as data (e.g. json file)
- re-import the data of that assessment

This would allow me to:
- simultaneously work on multiple assessments
- edit a previously exported assessment without having to redo the whole thing from scratch

**Comment by nschonni** [comment]
This may be applicable if you start to look at output formats https://w3c.github.io/wcag-act/act-rules-format.html#appendix-data-example

**Comment by scottsb** [comment]
Here is a more detailed explanation of the same approach @nschonni mentions. It would be amazing if this tool could generate interchangeable data files with the W3C's own (sadly poorly maintained) tool:
https://github.com/w3c/wcag-em-report-tool/blob/master/docs/EARL+JSON-LD.md

**Comment by ferBonnin** [comment]
Hey @mmafe, thanks for your interest in Accessibility Insights for Web!

This is a request that requires more discussion and investigation on our side, we will update here when we know more and we will keep checking for upvotes/reactions from the community on this request

**Comment by adbajaj** [comment]
This would be very helpful for my team as well! Would be interested to know ball park timings on when this is coming.
Thanks,
Aditya

**Comment by mgifford** [comment]
Just wanting to check in on the status of this. Love the idea of being able to take this data and just plug it into W3C's WCAG-EM Report Tool /c @scottsb @nschonni

**Comment by nitedog** [comment]
@ferBonnin I'd be happy to engage in such a discussion on interchangeable formats.

**Comment by mgifford** [comment]
@WilcoFiers let me know that you should be able to do this in axe with https://github.com/dequelabs/axe-reporter-earl

In which case, it should be possible with Accessibility Insights.

**Comment by ferBonnin** [comment]
Hi Everyone, thanks for the additional inputs on this feature request! This last comments seem to be focused around the ability to export the assessment as data.

To help us understand better the requirements, can you share a little bit about:
-  the scenarios where having the assessment as data would be helpful / how would you use this data? 
- tell us a bit more about what formats would be helpful and why?

**Comment by mmafe** [comment]
@ferBonnin Thanks for looking into this!

I'd find an export of the assessment as data helpful if I need to:
- update the report (e.g. if I find a new issue)
- have someone else review or edit the report before we finalize it
- do multiple accessibility audits at the same time

I'm comfortable with JSON, however I think (for me) any format would work as long as I can import or export it specifically from accessibility insights. For others, it might be a different case.

**Comment by adbajaj** [comment]
+1 mmcafe's comments

**Comment by scottsb** [comment]
For me having the output as data would be ideal for transfer to other tools for generation of a final report that includes manual testing as well. For this purpose ACT/EARL would be the ideal format, ideally in the JSON-LD serialization, as suggested by others above.

**Comment by ferBonnin** [comment]
We are looking into this, exploring some options and we have to open questions around EARL, if someone can help with the answer we will appreciate it!
- Does EARL has a way to add additional custom fields?
- Does EARL has a validator we could use to test the formatting is correct?

**Comment by hmig** [comment]
@ferBonnin  

- the scenarios where having the assessment as data would be helpful / how would you use this data?
1. Import the results back in Accessibility Insights and complete/revise an assessment 
2. Import the results into another tool in order to compile the results for an entire website to produce a VPAT

- tell us a bit more about what formats would be helpful and why?
- 1. JSON and csv because those are easy standards to work with

Has there been any movement on this feature? Is there any likelihood it will be implemented?

**Comment by ferBonnin** [comment]
Marking this as active since we are working on the Save / load (Import/Export) part of this feature request. 
The export to a JSON format will not be covered in this first part of the feature.

**Comment by ferBonnin** [comment]
Thank you all for the insights on this feature request!
The Save and Load functionality is now available in Accessibility Insights for Web V2.27.0 ([release notes](https://github.com/microsoft/accessibility-insights-web/releases/tag/web%402.27.0)) Please take a look and **let us know what you think!**

![Command bar now has two additional buttons: Save assessment & Load Assessment](https://user-images.githubusercontent.com/9062104/120547147-8dbe2100-c3a5-11eb-8b14-30a5e1c3db00.png)

**Comment by mgifford** [comment]
Ok, that's really exciting. 

[What I see for Edge is still](https://microsoftedge.microsoft.com/addons/detail/accessibility-insights-fo/ghbhpcookfemncgoinjblecnilppimih) Version 2.26.1 - Updated 24 May 2021

On Brave though, after I deleted the extension & re-loaded it it worked fine. Is there no auto-update process?

Anyways, wow. So this now saves a JSON formatted file like SavedAssessment_20210602_HomeCivicActionsAcce.a11ywebassessment

With a title that would allow someone to pretty easily find it.  Does your .a11ywebassessment format follow the EARL structure? It's all based on WCAG Accessibility Conformance Testing (ACT) & Evaluation and Report Language (EARL).  

If so this would make it much easier to import into something that just leads nicely to a VPAT. I'm assuming that's part of the goal.

**Comment by ferBonnin** [comment]
Hey @mgifford glad you like it! 

> Is there no auto-update process?

We just released a few hours ago, both Edge and Chrome should auto-update after a few hours.

> Does your .a11ywebassessment format follow the EARL structure? 

No, we divided this feature request into two parts:
1) allow users to save & load an assessment so you can do things like import the results back in Accessibility Insights, update the assessment if you find something later (or if you fix something), do multiple assessments at the same time and have someone else review/ complete an assessment.
2) the second part would be a JSON file format to enable scenarios like uploading to a VPAT.

**Comment by adbajaj** [comment]
> Thank you all for the insights on this feature request!
> The Save and Load functionality is now available in Accessibility Insights for Web V2.27.0 ([release notes](https://github.com/microsoft/accessibility-insights-web/releases/tag/web%402.27.0)) Please take a look and **let us know what you think!**
> 
> ![Command bar now has two additional buttons: Save assessment & Load Assessment](https://user-images.githubusercontent.com/9062104/120547147-8dbe2100-c3a5-11eb-8b14-30a5e1c3db00.png)

I am doing the happy dance right now. Thank you and very excited! Here's efficiency! =)

**Comment by mgifford** [comment]
@ferBonnin I'm especially interested in hearing about the 2nd part. Very interested in efforts to aggregate findings into VPAT documents.

**Comment by mgifford** [comment]
In looking at the original request, it looks like with V2.27.0  we can close this.

I am wondering about setting up a new issue though to focus on having a more standardized EARL report that could be part of a broader VPAT or WCAG-EM process.

**Comment by ferBonnin** [comment]
Keeping this open for the second part of this feature request

**Comment by mra11yx** [comment]
Created a new feature request to specifically address the second part: https://github.com/microsoft/accessibility-insights-web/issues/4398

**Comment by ferBonnin** [comment]
closing this issue since there are two feature request for the second part:
#4398  and #4331
