### ISSUE TITLE
[Windows 11 HC] Quick Assess Automated checks text in navigation bar does not match other tests

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#6547]
## Describe the bug

The color for the Automated checks text in the left navigation bar in Quick Assess does not match the color of the other items in the nav bar in all Windows 11 high contrast themes (aquatic, desert, dusk, night sky).

**To Reproduce**

1. Enable a Windows contrast theme from Settings
2. Enable Quick Assess from Preview features
3. Go to https://www.washington.edu/accesscomputing/AU/before.html
4. Open Quick Assess from the launchpad
5. See the color of Automated checks text in the nav bar is different from that of the other tests

## Expected behavior

Text color should match the color of the other tests in the nav bar

## Screenshots

(Screenshot of Quick Assess in Aquatic theme, opened to Overview, with different Automated checks text color than other tests)
<img width="431" alt="Screenshot 2023-03-29 104853" src="https://user-images.githubusercontent.com/48259897/228633720-7e4e3731-a926-4940-914c-297e40dd010b.png">

(Screenshot of Quick Assess in Desert theme, opened to Overview, with different Automated checks text color than other tests)
<img width="385" alt="Screenshot 2023-03-29 104953" src="https://user-images.githubusercontent.com/48259897/228633750-11be3e5d-3241-4aa1-9817-62b6729155be.png">

(Screenshot of Quick Assess in Dusk theme, opened to Overview, with different Automated checks text color than other tests)
<img width="402" alt="Screenshot 2023-03-29 105129" src="https://user-images.githubusercontent.com/48259897/228633786-403d4024-86aa-4672-90ce-8d12961f320c.png">

(Screenshot of Quick Assess in Night sky theme, opened to Overview, with different Automated checks text color than other tests)
<img width="387" alt="Screenshot 2023-03-29 105144" src="https://user-images.githubusercontent.com/48259897/228633814-3cadedd8-6ced-4db9-8eeb-54472c2d5a43.png">

## Context (please complete the following information)

- OS Name & Version: Windows Version 10.0.22621 Build 22621
- AI-Web Version & Environment: Production 2.37.3
- Browser Version: Microsoft Edge Version 111.0.1661.44
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html

## Did you search for similar existing issues?

yes

**Comment by JGibson2019** [comment]
Closed as this is being addressed in the upcoming QuickAssess feature
