### ISSUE TITLE
[BUG] MV3 Canary extension is still listed in the store

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#6556]
## Describe the bug

The MV3 Canary extension is still listed in the chrome web store, which seems wrong

**To Reproduce**

1. Open https://chrome.google.com/webstore/search/accessibility%20insights in your favorite browser
2. Notice that the returned results include Accessibility Insights for Web - Canary (M3), which has not been updated since December 2022.

## Expected behavior

Given that this version is no longer supported, it should probably be at least unlisted, potentially completely removed.

**Comment by DaveTryon** [comment]
Triage decision is to remove this from the store.

**Comment by peterdur** [comment]
Changed visibility in store to "Unlisted" and submitted today.

**Comment by peterdur** [comment]
Canary M3 version no longer appears in search results.

**Comment by DaveTryon** [comment]
Confirmed
