### ISSUE TITLE
Assessment written in the form of clear test cases

### ISSUE THREAD

**Issue by jxlz** [microsoft/accessibility-insights-web#6583]
## Is your feature request related to a problem? Please describe.
Write the web assessment more explicitly like test cases. This would clarify desired outcomes instead of implying what failure looks like.

## Describe the desired outcome
Today the first keyboard test looks like:

1. Use the keyboard to navigate through all the interactive interface components in the target page.
a. Use Tab and Shift+Tab to navigate between widgets both forwards and backwards.

An improvement could look like some variation of:
Test Case #1: Tab and Shift + Tab
Test steps and details
Failure conditions

**Comment by jxlz** [comment]
You may be able to leverage and influence https://ictbaseline.access-board.gov/ which has done work in this area.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
