### ISSUE TITLE
Details view switcher is not updated when view changed from popup view

### ISSUE THREAD

**Issue by waabid** [microsoft/accessibility-insights-web#659]
## Describe the bug

The details view switcher does not update when you click on fast pass or assessments in the popup view.

**To Reproduce**

1. Open popup view.
2. Click FastPass.
3. Open popup view again.
4. Click Assessment.

Note how the switcher is not updated and still says fast pass.

## Expected behavior

The switcher should state assessment when switched.

## Screenshots

![switchernotupdated](https://user-images.githubusercontent.com/32555133/57340667-a9ce3600-70eb-11e9-90e2-63243933a161.gif)

## Extension (please complete the following information)

- OS: Windows
- Version 2.3.0
## Are you willing to submit a PR?

Yes

**Comment by smoralesd** [comment]
It sounds to me that this is a side effect of a previous bugfix (trying to fix the switcher state to be properly announced by the SR). In the bug fix, we move the state to the component instead of getting it through the props from the background.

**Comment by ferBonnin** [comment]
@Shobhit1 ping to follow up :)
