### ISSUE TITLE
Incorrect string "model" instead of "modal"

### ISSUE THREAD

**Issue by JoshuaLamusga** [microsoft/accessibility-insights-web#672]
## Describe the bug
I hope this image will explain the bug:
![image](https://user-images.githubusercontent.com/30244654/57638268-4a947980-7562-11e9-8c7a-1ec4d58dd042.png)

Just a typo, where the word model is used when modal should be used. Highlighted with a red circle.

**Comment by Shobhit1** [comment]
PR welcome 😄
