### ISSUE TITLE
Broken download links for Android version

### ISSUE THREAD

**Issue by spbriggs** [microsoft/accessibility-insights-web#6764]
The download links for Android version on https://accessibilityinsights.io/downloads/ are all broken. Getting a ResourceNotFound error for all three of them

**Comment by spbriggs** [comment]
Just noticed https://github.com/microsoft/accessibility-insights-web/issues/6744

Website needs updating to reflect it

**Comment by DaveTryon** [comment]
@spbriggs, our website will be updated in the next few days. Sorry for the confusion. We'll keep this open as a reference issue until the docs update is complete.

**Comment by DaveTryon** [comment]
The docs release will go out very soon, which will remove the download links. We can close this once the docs release is completed.

**Comment by DaveTryon** [comment]
@spbriggs, we updated the docs site today. Closing this issue
