### ISSUE TITLE
Switcher accessible name is confusing

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#680]
## Describe the bug

The dropdown that changes between Assessment and FastPass reads "select workflow".  For a new user, the message is confusing and does not convey what a workflow is.

**To Reproduce**

1. turn on JAWS
2. Launch accessibility Insights in any page
3. get focus to the switcher

## Expected behavior

A better description of what the control is and what it does:
"Select Assessment or FastPass workflow"

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.3.0
- Target Page [e.g www.bing.com] any

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)

Yes
## Additional context
This was feedback from a user using JAWS

**Comment by RobGallo** [comment]
"Select type of test to run"?
"Select test mode"?

**Comment by ferBonnin** [comment]
@RobGallo one is assessment and the other is fastPass, not sure if they count as _tests_ (given that assessment has a list of 22 tests).

Would this be too long: "Select Assessment or FastPass workflow"?

**Comment by ferBonnin** [comment]
note: if we change this, it would be good to check documentation: "The tool supports two primary scenarios:"

**Comment by ferBonnin** [comment]
per conversation with Rob: "Select Activity". 
workflow is vague, adding assessment, fastpass, is redundant and can be too long if we add more options
