### ISSUE TITLE
When visual helper is disabled, its confusing for AT users

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#682]
## Describe the bug

**To Reproduce**

1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. turn on NVDA or Jaws
3. go to Headings test, requirement 1
4. there are no headings on the page, so the visual helper will be disabled. Visually, that is conveyed immediately, but for a user using a screen reader, you need to press down arrow key 3 times to get to the message that explains why the visual helper is unavailable. Screen reader reads:

- Visual helper
- toggle button unavailable not pressed visual helper
- off
- No matching/failing instances where found

## Expected behavior
would expect that the first down arrow key explains why its unavailable

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.3.0
- Browser Version [e.g Chrome 71.0] 74.0.3729.131
- Target Page [e.g www.bing.com] https://www.washington.edu/accesscomputing/AU/before.html

**Comment by RobGallo** [comment]
The thing that jumps out at me is that some headings tests require headings to exist and some don't. If there are tests which require a certain type of element to exist, and none do, why don't we mark those tests as not applicable in a way that all kinds of users can tell why? To solve this bug minimally, we could add the element count as part of the heading.

**Comment by ferBonnin** [comment]
@RobGallo each requirement is checking for different things. In the case of requirement 2: no missing headings, if the visual helper didn't found headings it can mean they aren't implement them correctly or that they are not using them.

Since the requirement requires the user to determine whether is pass or fail, we cannot automatically mark it as not applicable (and we do not use _not applicable_ in Assessment, we learned that having 4 possible states, and in particular, the _not applicable_, was very confusing for users)

this is not the only requirement where if the visual helper didn't found any instances it is not marked as pass automatically, so a better message for screen reader would be great.

**Comment by RobGallo** [comment]
@ferBonnin 
I think having tests automatically pass is just as confusing as "not applicable". It's like they should be disabled, or separated, or something. But I think at least having the count of instances in the heading would alieviate the problem.

**Comment by ferBonnin** [comment]
Per conversation with Rob, would be good to read the message in one go instead of having to tab 4 times to get the status. Another option could be that given that the toggle is not available, we dont show it at all and just say no instances found

**Comment by Shobhit1** [comment]
> Per conversation with Rob, would be good to read the message in one go instead of having to tab 4 times to get the status. Another option could be that given that the toggle is not available, we dont show it at all and just say no instances found

Just a quick question on the option 2, does it not take us away from having a consistent UX? Without looking at the code for this; i am assuming that hiding visual helper for `No matching instances` should be straight forward; so the only question is about consistency for all  users.
Please let me know what you think @ferBonnin .

**Comment by Shobhit1** [comment]
After discussion with @ferBonnin ; the want from this issue is that whenever the visual helper is disabled; AT should not be reading the state of it. 
It should just say for example: 
```
Visual Helper
No matching/failing instances were found
```

**Comment by ferBonnin** [comment]
validated with Canary and NVDA
