### ISSUE TITLE
Implement a scanning sound when scanning automated checks/list of instances

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#685]
## Is your feature request related to a problem? Please describe.
Yes, if I am using a screen reader there are some cases (the internet connection is slow, the page is big, etc) where I don't know what Accessibility insights is doing: is it still scanning?

## Describe the desired outcome
apart from the spinning wheel, I would like a scanning sound that notifies me that its still scanning.

## Describe alternatives you've considered
Other options could be notifying % of scanning every certain time or using a sound that changes volume/pitch with correlation of the % scanned.

## Additional context
Feedback from user.
Accessibility Insights for Windows has a scanning sound

**Comment by AhmedAbdoOrtiga** [comment]
Just FYI: we have this feature already in AIWin, and it's configurable by the user (on/off)
![image](https://user-images.githubusercontent.com/45858632/57961103-98421680-78c1-11e9-895f-2d926326997d.png)

**Comment by ferBonnin** [comment]
Quick Note: using sound only to notify users will not work for braille displays to communicate state of the scanning.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
