### ISSUE TITLE
Information related to the heading level requirement does not clarify the need for proper heading level order.

### ISSUE THREAD

**Issue by orunsewe** [microsoft/accessibility-insights-web#691]
When using the information given as guidance for checking the heading level requirement, I noticed that the steps indicate the need for heading levels to visually match the programmatic level. However, it is not clear if this test requires heading levels to be in a logical order, that is, not skipping heading levels or using the wrong heading level.

As a user, I would like some clarification in the information panel indicating the need for proper heading level order so that all heading requirements are met without confusion.

**Comment by ferBonnin** [comment]
@LiLoDavis thoughts on this?

**Comment by LiLoDavis** [comment]
@ferBonnin Properly structured headings is considered a best practice, not a WCAG AA requirement. If we decide to include best practices in our tool, there's an axe rule that looks for incorrect heading hierarchy.

**Comment by ferBonnin** [comment]
@LiLoDavis agree.

@orunsewe  thanks for the feature request and your interest in the tool. We have a question to understand better the request. You mention: _"However, it is not clear if this test requires heading levels to be in a logical order, that is, not skipping heading levels or using the wrong heading level."_  
In the Guidance page for Headings (information icon next to the Headings test title), we have: _"Structure multiple headings on a page hierarchically. (best practice)_". 
Is this helpful to clarify what you mention?

**Comment by orunsewe** [comment]
Yes it is helpful. Thank you.

**Comment by ferBonnin** [comment]
@orunsewe Awesome! 
Do you think this is enough for the feature request or is there something else you would like to have for this?
