### ISSUE TITLE
Result description (after selecting Export result) does not support line breaks

### ISSUE THREAD

**Issue by mmafe** [microsoft/accessibility-insights-web#698]
## Is your feature request related to a problem? Please describe.
The result description (created after selecting Export result) does not support line-breaks.

I attempted to export:

```
Must fix:
- first issue
- second issue
- third issue

Should fix:
- first issue
- second issue
```

This was exported as follows:
```Must fix: - first issue - second issue - third issue Should fix: - first issue - second issue```

## Describe the desired outcome
I'd love it if the result description supported line-breaks (or even maybe Markdown)?

**Comment by ferBonnin** [comment]
Hi @mmafe thanks for your interest in Accessibility Insights for Web.
This is a great suggestion, we will we will look into the timelines and effort for making this available and follow up.

**Comment by annikakouhia** [comment]
@ferBonnin Feature is up and running in Canary! Right now line breaks are working. Screenshots available here as well #741

**Comment by ferBonnin** [comment]
Awesome! Thanks Annika.
@mmafe as Annika mentions the fix is now available in [Canary](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem). Please let us know what you think! :)

**Comment by mmafe** [comment]
Thank you! Looks good to me. Feel free to close the issue. 👍
