### ISSUE TITLE
Result description should maintain its content

### ISSUE THREAD

**Issue by mmafe** [microsoft/accessibility-insights-web#699]
## Is your feature request related to a problem? Please describe.
If I fill in the result description (after selecting Export result), and I accidentally close the window (either by clicking outside the window or selecting the close button), the content I typed in disappears.

Going forward, I've been keeping track of my summary findings in a separate document and then pasting that into the Results Description window when I'm ready to export. However, new users would not know to do this and could easily lose their work.

## Describe the desired outcome
It would be wonderful if the content in the Result Description was maintained even if you close it. I would be able to come back to my report and the Result Description would still be there. 

Even better would be to move the Result Description into the Overview page, so you can continually edit it while working on the report. Then once you click Export result, it would generate your report.

**Comment by ferBonnin** [comment]
Hi @mmafe thanks for your suggestion and the interest to Accessibility Insights for Web.

Per conversation with @juliestuart-ms makes sense to keep the information if possible since the user can always clear the information entered. We will we will look into the timelines and effort for making this available and follow up.

**Comment by ferBonnin** [comment]
Hi @mmafe this feature request has now been completed and should be available in [Canary ](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem) now :)
Please let us know what you think!
