### ISSUE TITLE
No links to needs-review doc pages?

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-web#7007]
## Describe the bug

None of the needs-review document pages are referenced anywhere inside the web extension. Some of the rules that show up in the __Needs review__ tab link to their counterparts of  __Automated checks__ document pages.

Specifically:
- https://accessibilityinsights.io/info-examples/web/needs-review/aria-input-field-name/ is never referenced
- https://accessibilityinsights.io/info-examples/web/needs-review/color-contrast/ is never referenced. If a `color-contrast` is detected, the "More information about color contrast" opens https://accessibilityinsights.io/info-examples/web/color-contrast/, which is a different page
- https://accessibilityinsights.io/info-examples/web/needs-review/link-in-text-block/ is never referenced. If you create the scenario described on that page, it appears in Automated Checks, not Needs Review, and the "More information about link-in-text-block" link goes to a page owned by deque
- https://accessibilityinsights.io/info-examples/web/needs-review/p-as-heading/ is never referenced
- https://accessibilityinsights.io/info-examples/web/needs-review/th-has-data-cells/ is never referenced

## Expected behavior

Since these pages exist to add more detail on fixing these issues, I'd expect the pages to be used as reference material by the web extension

**Comment by v-viyada** [comment]
This is released in version 2.42.0
