### ISSUE TITLE
Can't run accessibility insight-FastPass on React blade. Error: There are iframes in the target page that are non-responsive

### ISSUE THREAD

**Issue by TaliHausner** [microsoft/accessibility-insights-web#7097]
Hi,

We have new react blade in the portal and we couldn't run the FastPass check (accessibility insight) for it.
There is an issue probably with running this tool on react blades and our blades is one of the first ones created in react.
Same behavior occurred in Chrome and Edge browsers.

**The warning we receive in the tool is:**
_There are iframes in the target page that are non-responsive. These frames have been skipped and are not included in results. If you get this warning unexpectedly in a page where you expect the iframes to be responsive, please[let us know.](https://github.com/microsoft/accessibility-insights-web/issues/6347)_

**blade url:** 
https://ms.portal.azure.com/?feature.securityGraphDebug=true%2F#view/Microsoft_Azure_Security/SecurityMenuBlade/~/AscInformationProtection

**relevant screenshots:**
![dsdsdsdsdsdsd](https://github.com/microsoft/accessibility-insights-web/assets/45973331/38e8f9ca-2aff-4b1e-842f-394a14c8b51a)

![Screenshot 2023-11-15 125334](https://github.com/microsoft/accessibility-insights-web/assets/45973331/91865caa-1f56-45d7-8bf1-77ce6b0df18b)

Would like to get your help with this.

Thanks,
Tali

**Comment by v-viyada** [comment]
This is being tracked and followed up internally.

**Comment by DaveTryon** [comment]
@TaliHausner, @v-viyada, please continue this with #6347. We've looked at this and are unable to repro the problem, but if you can successfully get a repro case, it should definitely be captured in #6347.
