### ISSUE TITLE
Snippet is not formatted for automated check issues in details view

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#715]
![image](https://user-images.githubusercontent.com/29855291/58653265-2d81d980-82ca-11e9-9660-175994bc9f2b.png)

Can we do some formatting for the snippet displayed.
Also, we could highlight based on html syntax.

**Comment by ferBonnin** [comment]
Closing this issue as out of scope since this will get address with other feature.
