### ISSUE TITLE
Accessibility Insights report still shows "..tests that cover all the WCAG 2.1 AA success criteria" instead of WCAG 2.2

### ISSUE THREAD

**Issue by jasvindargillQA** [microsoft/accessibility-insights-web#7209]
Latest version of A11y Insights have WCAG 2.2 criteria tests listed in full assessment. However when we generate the report it still says WCAG 2.1.

Sample heading from report:
"This report shows the overall accessibility of the website or web app through a combination of automated and manual tests that cover all the WCAG 2.1 AA success criteria."

**Comment by v-viyada** [comment]
This is released in version 2.42.0
