### ISSUE TITLE
The Visual Helper is not working on the Screen for Chrome - version -122.0.6261.69

### ISSUE THREAD

**Issue by abinashshibol** [microsoft/accessibility-insights-web#7259]
## Describe the bug
**We usually use Visual Helper on the screen to validate Keyboard navigation cases or other cases that have a visual helper. 
Now, when we are trying to enable the visual helper then it is not navigating to the screen nor navigating between widgets while doing tab in our tab out.**

**The Visual helper is not working for many web pages , Chrome - version -122.0.6261.69**
**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Assessment for a page
2. Click on Key board navigation 
3. Enable the visual helper
4. The page navigation are not possible. Do the tab in or tab out , still no navigation 

## Context (please complete the following information)

- OS Name & Version: 
- Target Page:

**Comment by v-viyada** [comment]
@abinashshibol We are not able to reproduce the issue using the latest version of chrome. If it is ok, could you please share the page details which you are trying to scan for reproducing the issue.

**Comment by abinashshibol** [comment]
try this page 

https://www.vonage.com/unified-communications/campaigns/vbc-brand/

**Comment by abinashshibol** [comment]
@v-viyada  here you can test-  https://www.vonage.com/unified-communications/campaigns/vbc-brand/
