### ISSUE TITLE
the aria-required-children rule flags child elements that are not in the accessibility tree as needing to be removed

### ISSUE THREAD

**Issue by stmillMSFT** [microsoft/accessibility-insights-web#7273]
## Describe the bug

When evaluating the `aria-required-children` rule, the tool reports elements that are not in the accessibility tree (via aria-hidden=true) as needing to be removed. 
![image](https://github.com/microsoft/accessibility-insights-web/assets/42849800/c768c5b6-5082-44f2-bd83-ebb7509dddbd)

Your own docs even list removal from the accessibility tree as a valid way to pass the rule. 
![image](https://github.com/microsoft/accessibility-insights-web/assets/42849800/26dbd405-babb-4b0f-bac2-3a94b2eb7f57)

But setting aria-hidden="true" on the element (which removes it from the accessibility tree), does not prevent the element from being flagged as needing to be removed.

**To Reproduce**

Run fastpass on the codepen below. Two false-positives get reported.

## CodePen repro example

https://codepen.io/stmill/pen/VwNKLKQ
(this is not quite a minimal repro, since I'm trying to reuse it to repro a related bug as well)

This is also present on this page: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped

## Expected behavior

Elements that are not in the accessibility tree should not be included for this rule. The current behavior does not match the aria spec or your own documentation.

## Screenshots

Included above.

## Context (please complete the following information)

- OS Name & Version: Windows 11 Enterprise 22H2 Build 22621.3296
- AI-Web Version & Environment:  2.41.0
- Browser Version: Edge 122.0.2365.80
- Target Page: Cannot be shared here. If you're a Microsoft FTE, ping me (stmill), and I can share more.

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by DaveTryon** [comment]
Let's try to understand what is happening here

**Comment by v-sharmachir** [comment]
This is released in version 2.43.0
