### ISSUE TITLE
Download report gives an error on pages

### ISSUE THREAD

**Issue by virav** [microsoft/accessibility-insights-web#730]
While doing the assessment of a specific page, we get download error on "export result". I had discussed this issue with @smoralesd with screen share and as per discussion, it is an HTML file size issue. Please help me to overcome this issue for our portal to be accessibility compliant.

Thank you!

**Comment by smoralesd** [comment]
hi @virav We have a fix for this issue now on [insider](https://chrome.google.com/webstore/detail/accessibility-insights-fo/nnmjfbmebeckhpejobgjjjnchlljiagp). It should go to [production](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) presently (probably next week).

Please let us know if you have any  question about this bug fix.

**Comment by virav** [comment]
It's working as expected. Thank you, Team!
