### ISSUE TITLE
yarn precheckin fails in copyright check after yarn build

### ISSUE THREAD

**Issue by peterdur** [microsoft/accessibility-insights-web#735]
## Describe the bug

Running `yarn precheckin` after doing a `yarn build` fails. If the file tree is clean, `yarn precheckin` succeeds.

**To Reproduce**

1. `yarn build`
2. `yarn precheckin`
3. See errors like this:
`License not found in \src\common\components\guidance-tags.scss.d.ts`

## Expected behavior

`yarn precheckin` should succeed

## Additional context

Looks to be related to #688. When all scss.d.ts files are removed, the license check passes.

**Comment by ferBonnin** [comment]
needs engineering investigation. The fix is not obvious because of the tools.

**Comment by Shobhit1** [comment]
PR #834 created for the fix.

**Comment by Shobhit1** [comment]
Fixed. `Precheckin` works fine on local build now.
Tagging @peterdur
