### ISSUE TITLE
<hx role="none"> is reported as heading.

### ISSUE THREAD

**Issue by shaminder1** [microsoft/accessibility-insights-web#7362]
## Describe the bug

headings tag with role="none "are tagged as headings,

**To Reproduce**

1. Open Accessibility insights for web
2. Turn on Headings in Adhoc Tools.
3. Check if headings tag with role="none "are tagged as headings,

## Expected behavior

Heading tags with role="none" should not be detected as programmatic headings.

## Screenshots

![image](https://github.com/microsoft/accessibility-insights-web/assets/56667867/0803799e-15e0-4298-8c25-7feadd9092f6)

## Context (please complete the following information)

- OS Name & Version: <NA>
- AI-Web Version & Environment: Accessibility Insights for Web - Version 2.42.0 | Powered by 
[axe-core](https://www.npmjs.com/package/axe-core)
 4.8.4>
- Browser Version: Chrome Version 125.0.6422.142 (Official Build) (32-bit)
- Target Page: <Any>

## Are you willing to submit a PR?

NA

## Did you search for similar existing issues?
No

**Comment by shaminder1** [comment]
By default screen readers treat content contained in <element role="none" > as normal text (without any semantic meaning). But AI tool identifies the same as heading.

**Comment by v-sharmachir** [comment]
This is released in version 2.44.0
