### ISSUE TITLE
Allow manual adding of issues for any test

### ISSUE THREAD

**Issue by anphira** [microsoft/accessibility-insights-web#7397]
## Is your feature request related to a problem? Please describe.
There are regularly items that are not detected by the scanner. For example, a modal dialog can be opened on the page, but none of the modal components are detected by the tool. There are contrast failures on those modal components, but I have no way of adding those failures to Contrast > UI components.

## Describe the desired outcome
I need to manually add failures to any test. The tool can't find everything, so I need to be able to add a manual failure.

## Describe alternatives you've considered
Right now I have to keep a separate file of noted manual failures.

## Additional context
On the Adaptable content > Contrast -- on some sites it detects nothing. But there are failures on color contrast. It just says "Instances No matching instances". Right now I just have to keep a separate document noting these failures. I want to be able to include them in the nice report this tool makes.

**Comment by v-prachin** [comment]
Hello @anphira, could you please provide additional information related to components for which we are getting failures & the tool is not fetching them. If you could provide details, we can reproduce the issue from our end and can investigate on it?

**Comment by anphira** [comment]
[Assessment_20240724_Maryland-tax-connect.json](https://github.com/user-attachments/files/16391659/Assessment_20240724_Maryland-tax-connect.json)
I attached the JSON from an audit on https://mdtaxconnect.gov/

As far as I was able to tell, the tool was not able to find the content in the modal windows. A modal is triggered when clicking "File a form as a guest". Close button is color #000 BUT has an opacity of .2. which is a contrast ratio of 1.6 and therefore fails contrast.

Another example of the automated checker passing an element it shouldn't: The label for username is "<label for="userID"></label>" -- that should be failed as a missing label, but is instead given a pass.

Automated checks will always pass some things that they should not, which is why I'm requesting to be able to add manual failures to all modules. 

HTML files are not supported as uploads, but here's the link to the report as HTML: https://www.dropbox.com/scl/fi/f6amhewvxd306omrn88x4/Assessment_20240724_Maryland-tax-connect.html?rlkey=b8a02nyim9zp4p58rvol1pcti&dl=0

**Comment by joestegman425** [comment]
Hi @anphira,
Thank you for the feedback. We have reviewed this issue and agree it would be a helpful product addition; however, the team is unable to resource this at this time. We will keep this item on the backlog and review for inclusion in a future product release.
