### ISSUE TITLE
Automated checks visualization appearing inconsistently on target page

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-web#743]
## Describe the bug
Details copied from customer email.

When run the tool, it is showing the number of issues (count) that has been identified on the page run, however, the tool is not highlighting the areas on the page where the issue are being identified.
PFA snippet for your reference. In the foreground, it is displayed that the tool has identified 29 failures in total, however, in the background the tool has failed to identify the areas where the issues are reported.

**To Reproduce**
Please refer to email "Need Support in fixing AI Tool issue" or ask @jalkire or @ferBonnin for the URL and credentials to repro this. 

1.	Open Application URL
2.	refer to the email for how to get to page to test
7.	Run AI for Web tool to identify the failures

## Expected behavior

Visualization appears

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac]
- Version [e.g. 1.140.1]
- Browser Version [e.g Chrome 71.0]
- Target Page [e.g www.bing.com]

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes/No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)

**Comment by ferBonnin** [comment]
@dbjorge please take a look at this issue, looks like the other issue with the iframes getting blocked we had in the past.

**Comment by dbjorge** [comment]
This is going to need an independent investigation/fix, it isn't particularly specific to the past investigation. Unassigning myself since I'm not working on it actively; this is ready to be picked up by anyone looking at the ready for work queue.

**Comment by ferBonnin** [comment]
per conversation with Peter and given that we didn't hear back on this issue, closing as out of scope.
