### ISSUE TITLE
High Contrast mode: Info icon on the hidden state banner is not visible

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-web#756]
## Describe the bug

The info icon on the hidden state banner in details view is not having sufficient contrast against its background

**To Reproduce**

1. Run assessment on any page
2. Enable high contrast mode from settings panel
3. Switch to the target page used in step 1
4. Open a new tab in the target page window
5. Go back to details view page
6. Observe that the banner message about the target page being in hidden state is displayed and the info icon at the start of the banner is barely visible (highlighted in red in the screenshot)

## Expected behavior

The info icon should have enough contrast against its background

## Screenshots

![image](https://user-images.githubusercontent.com/22068434/59187890-4c366a80-8b2b-11e9-8124-5f45b41bdc56.png)

## Extension (please complete the following information)

- Accessibility Insights for Web - prod
- Browser Version: Chrome 75.0.3770.80
- Target Page: Any page

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
@peterdur please add more detail and mark ready for work :)

**Comment by peterdur** [comment]
Investigated as per notes above and the fix is simple, so going ahead with fix.

**Comment by peterdur** [comment]
Fix now available in Canary. Assigning to @iamrafan to validate and close.

**Comment by iamrafan** [comment]
Validated the fix in prod v2.7.1
