### ISSUE TITLE
High Contrast mode: "Pass unmarked instances" button does not have enough contrast between 'active' and 'disabled' states

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-web#757]
## Describe the bug

It is tough to tell if the "Pass unmarked instances" button in assisted manual tests is active or disabled when in high contrast mode. The button is not having enough contrast across the states 

**To Reproduce**

1. Run assessment on any page
2. Enable high contrast mode from settings panel
3. Navigate to landmarks assessment -> 1. landmark roles (test step)
4. Click the "Pass unmarked instances" button
5. The button goes into disabled state
6. Observe that there is not much contrast between the active and disabled states

## Expected behavior

Users should be able to visually distinguish between active and disabled states 

## Screenshots

- Active state
![image](https://user-images.githubusercontent.com/22068434/59190573-eac5ca00-8b31-11e9-956b-325975add2a0.png)

- Disabled state
![image](https://user-images.githubusercontent.com/22068434/59190744-6162c780-8b32-11e9-97d4-b6fbcd8c47be.png)

## Extension

- Accessibility Insights for Web - prod
- Browser Version: Chrome 75.0.3770.80
- Target Page: Any page

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
@cheade Peter and I agree this is an issue, could you suggest other color?

**Comment by cheade** [comment]
Hi guys!

![image](https://user-images.githubusercontent.com/40274682/59223675-5d11cb00-8b81-11e9-80b7-b087928ff4b0.png)

This purple should be in our high color contrast palette as a disabled color. 

Something else I've noticed in default windows high contrast apps, the actionable command buttons in high-contrast are outlined in white to further help define that it's an action, in lieu of the subtly that is removed in high contrast. (for active buttons)

**Comment by karanbirsingh** [comment]
It seems to me the ActionButton OfficeFabric component does not support semantic styles yet for its disabled text color. I filed an issue here to validate this: https://github.com/OfficeDev/office-ui-fabric-react/issues/9418

If the button can use the `disabledText` semantic slot instead, then we'll just need to update OF once the fix is in. Otherwise we can look into workarounds on our end.

**Comment by smoralesd** [comment]
@cheade I have a couple of questions:
- should we use #C285FF as the text color? or the background color?
- should the color be applied to all the buttons? That sounds like it'll need proper validation throughout the extension

**Comment by cheade** [comment]
@smoralesd Hi! I'm back from my OOF, so apologies on the delayed response. In the case of the Pass all unmarked instances button, it's just the text that is visible as there is no defined border so we'd change the text to the purple color. 

Any button that does have a defined background, the background color should change.

**Comment by iamrafan** [comment]
Validated the fix in prod version 2.15.0
