### ISSUE TITLE
Add additional visual helpers to the Keyboard and Focus tests

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#758]
## Is your feature request related to a problem? Please describe.
Testing keyboard interaction and focus can be difficult if a page has elements that don't provide visible keyboard focus. 

## Describe the desired outcome
Must have: Ability to see which element currently has the input focus, even if the element doesn't provide its own visible focus indicator. 
Nice to have: (1) Ability to record which elements have received the focus, and (2) ability to see the focus order. Both of these are provided by the visual helper for Focus > Focus order.

## Describe alternatives you've considered
None

## Additional context
None

**Comment by ferBonnin** [comment]
Thanks for the suggestion Lisa Louise! Just to clarify the ask, you would like us to add the same visual helper used in Focus order to the following requirements:
- Revealing content
- Modal dialog
- closing content
- no keyboard traps
- on focus
- on input

correct?
how will the instructions change for each requirement?

**Comment by LiLoDavis** [comment]
> Thanks for the suggestion Lisa Louise! Just to clarify the ask, you would like us to add the same visual helper used in Focus order to the following requirements:
> 
> * Revealing content
> * Modal dialog
> * closing content
> * no keyboard traps
> * on focus
> * on input
> 
> correct?
> how will the instructions change for each requirement?

Yes, those are the requirements that need a visualization. Alternatively, we could also include **Keyboard navigation** and use the same visualization for all of them.
I recommend adding this text to the beginning of each requirement's **How to test** section: "The visual helper for this requirement highlights each element that receives the input focus."

**Comment by DaveTryon** [comment]
We're working on a feature of assessment improvements and will consider this as a candidate for that feature. 

Thanks for using Accessibility Insights!
