### ISSUE TITLE
Target page with placeholder iframe causes visualization enablement to hang

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#786]
## Describe the bug

If a target page contains certain types of placeholder iframe elements (eg, an element like `<iframe src="javascript:false;">`, [apparently a common technique](https://stackoverflow.com/a/4284645)), actions that involve injecting visualizations into the target page will end up spinning forever without making progress:

* enabling any ad-hoc tool
* performing a fast pass scan
* etc

**To Reproduce**

1. Navigate to https://codepen.io/dbjorge/pen/Kjpmja
2. Enable any visualization (eg, by attempting to enable any ad-hoc tool or running a FastPass)
3. Observe that the "enable" action hangs/remains in progress forever.

## Expected behavior

Shouldn't hang

## Screenshots

![image](https://user-images.githubusercontent.com/376284/59394366-3e076a80-8d34-11e9-94c0-41b24c5ad771.png)

## Extension (please complete the following information)

- OS: Windows
- Version: Version 2.4.1
- Browser Version: Chrome Stable Version 75.0.3770.80 (Official Build) (64-bit)
- Target Page: https://codepen.io/dbjorge/pen/Kjpmja

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? Yes

## Did you search for similar existing issues?

Yes

**Comment by devaradhanm** [comment]
I observed that the call to chrome to inject script never completes. 
chrome.tabs.executeScript(587, {code: "console.log('hi');", allFrames: true}, console.log);
i will investigate further if we can do something from our end, or if we need to create a bug on chrome.

**Comment by devaradhanm** [comment]
looks like this command works on document idle by default. for some reason, it is not idle in this case. forcing the injection by setting runAt: 'document_start' fixes this issue
