### ISSUE TITLE
Use native async, await & promise

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/accessibility-insights-web#801]
We don't need 'q' dependency. We could use async, await & promise since the browser we use will have es6 promise & async, await support

**Comment by smoralesd** [comment]
@devaradhanm  We are using `progress` api from Q on the assessment -> automated checks section. We need PM confirmation that it's fine to remove that before actually removing Q. Alternative, we could implement it ourselves.

**Comment by karanbirsingh** [comment]
One usage of `progress` from `q` is here in `tab-stops-analyzer`: https://github.com/microsoft/accessibility-insights-web/blob/a5f230e43006f37185d16bb7df5372b03a11f4ca/src/injected/analyzers/tab-stops-analyzer.ts#L40 

`progress` looks to be deprecated soon ([details](https://devdocs.io/q/index#promise-progress)) so it may be worth visiting its usages in the project. If all usages of `progress` are removed/replaced, it seems the other usages of `q` could be replaced with native calls. @smoralesd can you point to where `progress` is used in assessment -> automated checks? I was unable to find it.

**Comment by ferBonnin** [comment]
@peterdur to create a feature for this.

**Comment by smoralesd** [comment]
@karanbirsingh my bad. We're not actually using `progress` on the assessment -> automated checks. I guess is just the one usage you mention for tab stops.

**Comment by peterdur** [comment]
Created feature 1568193 per note above.

**Comment by peterdur** [comment]
Resolving since will be tracked by feature above.
