### ISSUE TITLE
Long target page is not responsive in new report

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#813]
## Describe the bug

the target page link is not responsive with long links

**To Reproduce**

1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. run automated checks
3. download report and add a comment with line breaks and spaces
4. open report
5. change display to 1920x 1080 and zoom to 400%

## Expected behavior

target page link is fully readable on top and on scan details

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.5.1
- Browser Version [e.g Chrome 71.0] 74
- Target Page [e.g www.bing.com] https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights)
Yes

## Additional context

Found during validation

![screenshot of zoomed in url](https://user-images.githubusercontent.com/7775527/59629802-7f16ca80-90f8-11e9-8e03-e366f668a50d.png)

**Comment by smoralesd** [comment]
@ferBonnin I looked at the figma file. In the case of the target page, it actually shows the url being cut and ellipsis being added. I followed that approach instead of wrapping (which looks better, I tried both)

In the case of the scan details, I added wrapping as you suggested.

**Comment by ferBonnin** [comment]
@smoralesd sounds good :)

**Comment by ferBonnin** [comment]
since this is closed marking it as resolved
