### ISSUE TITLE
Failure instance dialog is missing spacing & icons

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-web#829]
## Describe the bug

In prod version 2.5.4, the failure instance dialog is missing spacing and icons:
![image](https://user-images.githubusercontent.com/7775527/59799198-b58b4b80-9298-11e9-891a-71aa3af518bc.png)

**To Reproduce**
- Run automated checks on bing.com
- select any exclamation point to open the failure instance dialog

## Expected behavior

We expect more spacing between the buttons. Here is a screenshot:

![image](https://user-images.githubusercontent.com/7775527/59799320-f2574280-9298-11e9-8ebe-2708444a0f1e.png)

## Extension (please complete the following information)

- OS: Windows
- Version: 2.5.4
- Browser Version: Chrome 75.0.3770.100 (Official Build) (64-bit)
- Target Page: www.bing.com

**Comment by waabid** [comment]
This seems to be due to an Office Fabric update.
