### ISSUE TITLE
Inconsistency in the implementation of 'standardizeTags'

### ISSUE THREAD

**Issue by haonliu** [microsoft/accessibility-insights-web#850]
## Describe the bug

We have a lot of duplication in src\background\issue-details-text-generator.ts and src\issue-filing\common\issue-filing-url-string-utils.ts. Also the implementation of ``standardizeTags`` are not consistent. 

The one used in issue filing includes more tags (for example, new wcag 2.1 tags) than the other one.

**To Reproduce**
This is more of an code defect. So there is no repro steps.

## Expected behavior

The generated text from copy failure details should be consistent with azure boards issue filing content.

## Extension (please complete the following information)

- OS: Windows
- Version 2.5.5

## Are you willing to submit a PR?

Yes.

## Additional context

Issue #548 is also related.

**Comment by ferBonnin** [comment]
we took a look and the only thing different between copy failure details and azureDevOps is the missing tag for WCAG 2.1.

If we standardize, need to consider that copy failure details is plain text, so you need to specify the links explicitly.
