### ISSUE TITLE
On Automated check report, summary bar shows NaN

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#852]
## Describe the bug

On the automated checks report, the summary section shows 'NaN' instead of the proper count for each, failed, passed and not applicable sub-sections

**To Reproduce**

1. Navigate to any webpage/local html file
2. Open the details view
3. Using the switcher, select FastPass
4. Run automated checks
5. Click the 'Export result' button
6. Open the html file the browser just downloaded
7. On the report, observe the summary section

## CodePen repro example

Not applicable

## Expected behavior

Summary section should show correct counts

## Screenshots

![01 - summary broken](https://user-images.githubusercontent.com/2837582/60117947-1353e380-9730-11e9-9eff-09ad40952b24.png)

## Extension (please complete the following information)

- OS: Windows
- Version 10.0.17763 Build 17763
- Browser Chrome version 75.0.3770.100
- Target Page any

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

No

## Additional context

Found this on master branch, on commit [528529d2](https://github.com/microsoft/accessibility-insights-web/tree/528529d20abdd09bdd813a1d971c9783168def0f). Revert back to previous commit, [7e454efd](https://github.com/microsoft/accessibility-insights-web/tree/7e454efd3238e82f1c10c96f0059fa45e3e7db68), and the summary bar seems to be working fine

**Comment by karanbirsingh** [comment]
@smoralesd this is fixed in canary

**Comment by smoralesd** [comment]
Validated it on canary.
