### ISSUE TITLE
Accessibility Insights for Web crashing in Linux

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#860]
## Describe the bug

Per support comments in Chrome store, Version 2.5.5 is broken in Linux
https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?pli=1 

**To Reproduce**
Use Linux Mint 17

## Expected behavior

Accessibility Insights for Web should work

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows 
- Version [e.g. 1.140.1] 2.5.5 
- Browser Version [e.g Chrome 71.0] 75.0.3770.100
- Target Page [e.g www.bing.com] any

## Additional context

reported in Chrome store

**Comment by Shobhit1** [comment]
Resolved with 2.6.0 release.
