### ISSUE TITLE
Update aria-level accessibility bug 

### ISSUE THREAD

**Issue by ssthegrt** [microsoft/accessibility-insights-web#873]
## Describe the bug

Detecting unnecessary aria-level accessibility bug in **ARIA: heading role**

## Expected behavior

Any tag with role="heading" and with out level mentioned is producing aria-level accessibility bug.
But if no level is present, then aria-level has value of 2 by default. So it shouldn't be reported as bug.
Follow the link to check:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role#Associated_WAI-ARIA_roles_states_and_properties

## Screenshots

![ss1](https://user-images.githubusercontent.com/16956669/60341737-26cfaa80-99cd-11e9-8a8f-877e61299cf1.PNG)
 
This is the bug after using the tool "Accessibilty insights for web".

**Comment by DaveTryon** [comment]
From https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role#Associated_WAI-ARIA_roles_states_and_properties (emphasis added), and dating from September 23, 2018:

The aria-level attribute specifies the heading level in the document structure. **If no level is present, a value of 2 is the default.**

Assigning for triage, although I suspect that this change would be made in axe-core.

**Comment by ferBonnin** [comment]
@iamrafan could you please do AT testing with this and open a bug with Deque in case the behaviour is consistent (i.e. no aria-level means level 2)?

**Comment by iamrafan** [comment]
@ssthegrt: Browsers/ATs do not process the implicit ```aria-level``` value in a consistent manner, hence we are showing this issue.

The ARIA WG is also going to remove the implicit values for required attributes in the ARIA spec. Please find more info form: 
- https://github.com/w3c/aria/issues/787#issuecomment-417070479
- https://github.com/w3c/aria/wiki/Required-Properties-with-Default-Values

Here are a couple of examples depicting the current behavior when using Firefox/NVDA

* ```role=heading``` elements 2 and 4 without ```aria-level``` attribute

    * Example: https://codepen.io/iamrafan/pen/orqpyE

    * ![image](https://user-images.githubusercontent.com/22068434/60461852-9f687e00-9bfc-11e9-8924-7d88914f8059.png)



* All ```role=heading``` elements with ```aria-level``` attribute
    * Example: https://codepen.io/iamrafan/pen/LKdede?editors=1010
    * ![image](https://user-images.githubusercontent.com/22068434/60461997-01c17e80-9bfd-11e9-9f0a-d191ef569bf5.png)
