### ISSUE TITLE
Test case: verify automated checks results from major target pages

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#895]
Verify that automated checks can successfully scan microsoft.com and bing.com.

**Comment by Shobhit1** [comment]
The basic idea is to verify that our automated checks is not broken when we run on complex websites. The website can be anything like cnn etc.

**Comment by dbjorge** [comment]
Suborder here will be:
1. Implement the meat of the test case against a checked in test page
2. Implement `it.skip` versions against key external properties
3. Go do #896 and incorporate the `it.skip`'d cases there

**Comment by dbjorge** [comment]
Cutting subparts 2 and 3 due to feature timebox
