### ISSUE TITLE
Add parallel job to run E2E tests on Ubuntu build agent

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#898]
Right now, our E2E tests only run on MacOS in our CI/PR builds. We'd like them to run in parallel on all of our supported OSes.

As part of this task, investigate limits on parallel build job count and consider making some of the jobs CI-only if necessary

**Comment by Shobhit1** [comment]
According to official [Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#microsoft-hosted-cicd) documentation:

> "Public project: 10 free Microsoft-hosted parallel jobs that can run for up to 360 minutes (6 hours) each time, with no overall time limit per month."
