### ISSUE TITLE
Assessment and Automated checks report is broken in Canary

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#910]
## Describe the bug
Assessment report is not formatted

**To Reproduce**

1. Go to any website
2. mark one requirement as pass, one as fail
3. download report

## Expected behavior

report is correctly formated

## Screenshots

![Screenshot of report](https://user-images.githubusercontent.com/9062104/60741565-c8e81900-9f1e-11e9-9fd1-3176c93a8331.png)

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2019.7.3.2305
- Browser Version [e.g Chrome 71.0] Chrome 75
- Target Page [e.g www.bing.com] any

## Are you willing to submit a PR?

 No

## Did you search for similar existing issues?

Yes
## Additional context

Issue is only in Canary right now.

**Comment by peterdur** [comment]
Resolving bug. Fer, please confirm that Canary works for you now.

**Comment by ferBonnin** [comment]
looks good now :) thanks Peter!
