### ISSUE TITLE
E2E test fails when font fails to load

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#923]
## Describe the bug

When writing/running E2E tests, there is a `requestfailed` error from attempting to load a font, causing a `forceTestFailure` call in `page.ts`. (See sample error message below.) This causes the whole test suite to fail.

```
Test suite failed to run

    expect(received).toBeNull()

    Received: "request failed - net::ERR_ABORTED, https://static2.sharepointonline.com/files/fabric/assets/fonts/segoeui-westeuropean/segoeui-semilight.woff2"

      2 | // Licensed under the MIT License.
      3 | export function forceTestFailure(errorMessage: string): void {
    > 4 |     expect(errorMessage).toBeNull();
        |                          ^
      5 | }
      6 |
```

A similar error is seen in the browser console when running an Assessment: 
```
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://az416426.vo.msecnd.net". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```

**To Reproduce**

For first error message described (test suite failed to run):
1. Go to https://dev.azure.com/ms/accessibility-insights-web/_build/results?buildId=24268
2. Navigate to "e2e_tests_windows" > "run e2e tests"
3. See errors

For second error message described (in browser console):
1. Go to www.bing.com
2. Open extension and run Assessment
3. Inspect the resulting details view page
4. Open the browser console
5. See error message

## Expected behavior

Test suite should not fail when there is a font loading failure.

## Extension (please complete the following information)

- OS: Windows
- Version 10.0.18362
- Browser Version Chrome 75.0.3770.100
- Target Page www.bing.com

## Are you willing to submit a PR?

 Yes

## Did you search for similar existing issues?

Yes

## Additional context

**Note: Temporary fix in #927 where the error handler doesn't do anything if the URL contains 'fonts' or 'icons'. Must update/replace error handler when resolving this issue.**

**Comment by lamaks** [comment]
Please provide the URI to repro the issue

**Comment by ferBonnin** [comment]
Reviewed with Peter, closing since this is old and there is a workaround
