### ISSUE TITLE
Automated checks report: x icons are coded as no value

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#937]
## Describe the bug

Icons on the automated checks report are coded as "no value" under Images -> Image function requirement

**To Reproduce**

1. Go to https://www.washington.edu/accesscomputing/AU/before.html
2. Open FastPass
3. Run Automated checks
4. Export the report by click on the "Export result" button
5. Open the download file
6. Open the assessment (on the automated checks report file)
7. If prompted, start a new assessment
8. Go to Images test
9. Under Image function requirement, look at the Instances list
11. Enable the visual helper
10. Observe
   - On the Instances list: all the listed instances show **Coded as: (no value)** and **Accessible name: (no value)**
   - On the report: the visual helper highlight:
      - On the Summary section, the icons for failed, passed and not applicable status
      - Under Failed instances, each of the failed icons for each one of the failed rules

## Expected behavior

Every image on the report (icon or otherwise) should be properly coded

## Screenshots

![image](https://user-images.githubusercontent.com/2837582/61067865-7e064f80-a3bd-11e9-9484-fb208eab48bb.png)

## Extension (please complete the following information)

- OS: Windows 10.0.17763 Build 17763
- Version: Canary 2019.7.11.26
- Browser Chrome 75.0.3770.100 (Official Build) (64-bit)
- Target Page https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

No

## Additional context

- Interesting enough, the icons on each result section (Failed instances, Passed checks, Not applicable checks) are not highlighted by the visual helper (and thus, don't show up on the Instance list)
- This may be a false positive as the svg icons are place under a `<div aria-hidden="true">` container (although, is not a direct child of said `<div>`)

**Comment by ferBonnin** [comment]
@iamrafan can you take a look at this and see if its a false-positive?

**Comment by iamrafan** [comment]
@smoralesd hey Sebastian, did you mean to say its a false positive on the there icons under summary?

But looks like non of their parents are having ```aria-hidden="true"``` and hence are being exposed to ATs, but are lacking an accessible name

**Comment by smoralesd** [comment]
@iamrafan On my first review of the issue, I though I found an element with `aria-hidden="true"` containing the icons but you're right, there is none. So good news is this is not a false positive and the fix is actually quite simple! PR #959 is waiting for review to fix this issue.

Thanks for double checking on this!
