### ISSUE TITLE
Refreshing details page causes state change in target page

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#946]
## Describe the bug

After running Fast Pass, refreshing the details page does not maintain the state in the details and target pages.

**To Reproduce**

1. Go to www.bing.com
2. Open extension popup and run Fast Pass (target page should show injected UI boxes around failure instances)
3. Uncheck all failure instances on details page (target page should no longer show any injected UI boxes)
4. Refresh details page
5. Observe state change: failure instances on details page are all checked (should remain unchecked) and injected UI components reappear on target page (components should not be present)

## Expected behavior

The state should not change on details and target pages.

## Extension (please complete the following information)

- OS: Windows
- Version 10.0.18362
- Browser Version Chrome 75.0.3770.100
- Target Page www.bing.com

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
If I remember correctly we already talked about this bug and decided it was by design. Most users in any application use refresh as a way to restart the app in the state it was when they first started. In this case, everything selected is the default behaviour.

**Comment by lisli1** [comment]
This was found during Insider validation. Since this behavior is by design, I'll remove it from our validation steps and close the issue.
