### ISSUE TITLE
Nested Lists

### ISSUE THREAD

**Issue by brianteeman** [microsoft/accessibility-insights-web#987]
## Describe the bug

The AXE rule says "`<ul> and <ol> must only directly contain <li>, <script> or <template> elements"` but it is perfectly valid to have a nested list`

**To Reproduce**

1. Go to https://www.w3.org/WAI/tutorials/page-structure/content/
2. Run FastPass automated checks

## Expected behavior
No failures for links 

## Extension (please complete the following information)

- OS: Windows
- Version : 2.7.1
- Browser Version: Version 75.0.3770.142

## Are you willing to submit a PR?

Willing but not sure if I am able

## Did you search for similar existing issues?
Nothing found

**Comment by iamrafan** [comment]
Hi @brianteeman , I do not see any ```list``` rule failures for links. I see ```list``` failures only on the examples due to the presence of ```...``` outside ```<li>``` tags.

![image](https://user-images.githubusercontent.com/22068434/62139832-d5059300-b29e-11e9-8e3f-bf1e2fa8a30a.png)

**Comment by brianteeman** [comment]
Seems to be related to https://github.com/dequelabs/axe-core/issues/1171

**Comment by iamrafan** [comment]
@brianteeman can you please share the code snippet of the specific failure you are seeing?

**Comment by CorgiDev** [comment]
I believe the following is what the original author's issue was about. The Accessibility Insights tool is counting nested lists as invalid even though W3 standards say that nested lists are okay. For example, if I have a list like so:
```html
<ul>
    <li>A</li>
        <ul>
               <li>1</li>
               <li>2</li>
        </ul>
    <li>B</li>
</ul>
```

Accessibility Insights marks that as invalid, saying that "List element has direct children that are not allowed inside <li> elements". Blanket marking these items as invalid ignores the fact that nested lists are acceptable to WCAG and W3 standards.

The error in question, links to a Deque article entitled "[<ul> and <ol> must only directly contain <li>, <script> or <template> elements](https://dequeuniversity.com/rules/axe/3.5/list?application=msftAI)" . The article appears to be talking about nesting things other than <li>, <script>, or <template> elements within a <ol> or <ul> list. However, that article fails to mention that the W3 actually includes Nested Lists in its Web Accessibility Tutorials section where it specifically states that "Every list can be nested into another list."

The error also links to [WCAG Success Criterion 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships) that just deals with ensuring that intent/relationship is understood. As you dig into it, this section of the WCAG actually links to several other W3 pages that specifically mention nested lists as being okay further emphasizing the fact that nested lists are okay as long as the intent and relationship is understandable. Though they have recently added additional details for maintaining item numbering order when you have nested items within an ordered list.

**Additional References:**
- [W3 - WAI Tutorials - Page Structure - Nested Lists](https://www.w3.org/WAI/tutorials/page-structure/content/#nested-lists)
- [W3 - Section 10 - Lists](https://www.w3.org/TR/html4/struct/lists.html)

**Comment by CorgiDev** [comment]
In case anyone else looks at this issue, I believe I figured out the cause. I had a similar issue with my resume page on my personal site. I had nested lists formatted in a format similar to the example shown below:

```html
<ul>
   <li>Item 1</li>
   <li>Item 2</li>
   <ul>
      <li>Nest List Item 1</li>
      <li>Nest List Item 2</li>
      <li>Nest List Item 3</li>
   </ul>
   <li>Item 3</li>
</ul>
```

This seemed like it should count as passing based on the information listed in my previous comment. Additionally, a practice question in a Deque CPACC/WAS prep course made it seem more likely. However, after reviewing several WCAG pages that had nested lists within them, I realized that they place the nested lists within a list item as shown in the additional example below:

```html
<ul>
   <li>Item 1</li>
   <li>Item 2 (Related to the nested list)
      <ul>
         <li>Nest List Item 1</li>
         <li>Nest List Item 2</li>
         <li>Nest List Item 3</li>
      </ul>
   </li>
   <li>Item 3</li>
</ul>
```
